import Link from 'next/link';
import {supportArticles,supportGroups} from '@askadia/contracts';
import {ArrowRight,BookOpen,Mail,MessageCircle,ShieldCheck} from 'lucide-react';
import {MarketingShell,marketingMetadata} from '../../components/marketing-site';
import {publicContact} from '../../lib/public-contact';
import s from '../home.module.css';
export const dynamic='force-dynamic';
export const metadata=marketingMetadata('Central de suporte','Orientações para usar a MedSI: acesso à conta, perfil da clínica, estratégia, calendário, atendimento e publicação do site.','/suporte');
const groups=supportGroups.map(group=>({...group,items:supportArticles.filter(article=>article.group===group.id)}));
export default function Support(){const contact=publicContact();return <MarketingShell><section className={s.pageHero}><span className={s.eyebrow}>CENTRAL DE SUPORTE</span><h1>Vamos encontrar seu próximo passo.</h1><p>Respostas para as dúvidas mais comuns e orientações para continuar usando a MedSI.</p><div className={s.actions}><Link href="/login" className={s.primary}>Acessar minha conta <ArrowRight size={17}/></Link><a className={s.textLink} href="#acesso">Ver orientações <ArrowRight size={16}/></a></div></section><div className={s.contentNarrow}><nav className={s.supportLinks} aria-label="Tópicos de suporte">{groups.map(group=><a key={group.id} href={'#'+group.id}><BookOpen size={18}/>{group.title}<ArrowRight size={16}/></a>)}</nav>{groups.map(group=><section key={group.id} id={group.id} className={s.helpGroup}><h2>{group.title}</h2><div className={s.questions}>{group.items.map(article=><details key={article.id} id={article.id}><summary>{article.title}</summary><p>{article.answer}</p></details>)}</div></section>)}<section className={s.infoCard}><ShieldCheck size={26}/><h2>Precisa de ajuda com o seu caso?</h2><p>Informe a empresa, a tela em que ocorreu o problema e os passos para reproduzi-lo. Se enviar uma captura de tela, oculte dados de pacientes e informações privadas. Nunca envie senhas, tokens ou chaves de API.</p>{contact.supportWhatsapp?<a className={s.primary} href={'https://wa.me/'+contact.supportWhatsapp} target="_blank" rel="noopener noreferrer"><MessageCircle size={17}/>Falar com um especialista</a>:contact.supportEmail?<a className={s.primary} href={'mailto:'+contact.supportEmail+'?subject=Ajuda%20com%20a%20MedSI'}><Mail size={17}/>Falar com o suporte</a>:<><p className={s.note}>O canal direto de suporte está em preparação. As orientações desta central continuam disponíveis.</p><Link href="/contato" className={s.secondary}>Ver opções de contato <ArrowRight size={17}/></Link></>}</section></div></MarketingShell>;}
