import {randomUUID} from 'node:crypto';
import {beforeEach,describe,expect,it} from 'vitest';
import {MemoryStore} from './helpers/firestore-memory';
import {AsaasBillingService,AsaasSandboxAdapter} from '../apps/api/src/billing/asaas';
import type {Row} from '../apps/api/src/platform/firestore/store';

describe('Asaas sandbox HTTP adapter and orchestration fixtures (no remote calls)',()=>{
 let store:MemoryStore,company:string,owner:string,id:string,calls:{path:string;method:string;body:Row|null}[],status:string,deleted:boolean,failCreate:boolean,created:boolean;
 beforeEach(async()=>{store=new MemoryStore();company=randomUUID();owner=randomUUID();id=randomUUID();calls=[];status='PENDING';deleted=false;failCreate=false;created=false;await store.run(async tx=>{tx.put('companies',company,{id:company,workspace_id:'w',archived_at:null});tx.put('workspace_members','w_'+owner,{role:'owner'});tx.put('company_onboarding',company,{profile_version:1,revision:1,confirmed_revision:1});tx.put('company_billing_customers',company,{company_id:company,customer_id:'cus_fixture',provider:'asaas',environment:'sandbox'});});});
 const subscription=()=>({id:'sub_fixture',customer:'cus_fixture',externalReference:id,status:'ACTIVE',value:1597,cycle:'MONTHLY',deleted});
 const transport:typeof fetch=async(url,options)=>{const path=new URL(String(url)).pathname+new URL(String(url)).search,method=options?.method??'GET';calls.push({path,method,body:options?.body?JSON.parse(String(options.body)):null});expect(new URL(String(url)).origin).toBe('https://api-sandbox.asaas.com');expect(new Headers(options?.headers).get('access_token')).toBe('sandbox-key');if(method==='POST'){created=true;if(failCreate)throw new Error('network timeout');return Response.json(subscription());}if(method==='DELETE'){deleted=true;return Response.json({deleted:true,id:'sub_fixture'});}if(path.includes('/payments'))return Response.json({data:[{id:'pay_fixture',customer:'cus_fixture',subscription:'sub_fixture',value:1597,status,dueDate:new Date().toISOString().slice(0,10),invoiceUrl:'https://sandbox.asaas.com/i/fixture'}],hasMore:false});if(path.includes('?externalReference='))return Response.json({data:created?[subscription()]:[],hasMore:false});return Response.json(subscription());};
 const service=()=>new AsaasBillingService(store,new AsaasSandboxAdapter('sandbox-key',transport));
 const actor=()=>({role:'authenticated' as const,id:owner});
 it('creates one subscription with server terms and reconciles browser retries without granting unpaid access',async()=>{await service().checkout(actor(),company,id,'askadia_monthly');await service().checkout(actor(),company,id,'askadia_monthly');expect(calls.filter(c=>c.method==='POST')).toHaveLength(1);expect(calls.find(c=>c.method==='POST')?.body).toMatchObject({customer:'cus_fixture',value:1597,externalReference:id,cycle:'MONTHLY',billingType:'UNDEFINED'});expect(await store.run(tx=>tx.get('company_subscriptions',company))).toMatchObject({status:'pending'});});
 it('recovers uncertain creation without a second POST',async()=>{failCreate=true;await expect(service().checkout(actor(),company,id,'askadia_monthly')).rejects.toThrow();expect(await store.run(tx=>tx.get('company_billing_checkouts',id))).toMatchObject({status:'uncertain'});await service().checkout(actor(),company,id,'askadia_monthly');expect(calls.filter(c=>c.method==='POST')).toHaveLength(1);expect(await store.run(tx=>tx.get('company_subscriptions',company))).toMatchObject({provider_subscription_id:'sub_fixture'});});
 it('verifies webhook token before network calls, fetches current provider state, and ignores stale event payload',async()=>{await service().checkout(actor(),company,id,'askadia_monthly');calls=[];const event={id:'evt_paid',event:'PAYMENT_CONFIRMED',payment:{subscription:'sub_fixture',status:'CONFIRMED'}};await expect(service().webhook('wrong',event,'secret')).rejects.toThrow();expect(calls).toEqual([]);status='REFUNDED';await service().webhook('secret',event,'secret');expect(await store.run(tx=>tx.get('company_subscriptions',company))).toMatchObject({status:'pending'});const count=calls.length;await service().webhook('secret',event,'secret');expect(calls).toHaveLength(count);});
 it('cancels only the actor authorized subscription and persists provider deletion',async()=>{await service().checkout(actor(),company,id,'askadia_monthly');await expect(service().cancel({role:'authenticated',id:randomUUID()},company)).rejects.toThrow('Access denied');expect(calls.filter(c=>c.method==='DELETE')).toHaveLength(0);await service().cancel(actor(),company);expect(await store.run(tx=>tx.get('company_subscriptions',company))).toMatchObject({status:'cancelled',cancellation_requested:true});});
 it('accepts authenticated irreversible provider deletion without relying on a removed resource GET',async()=>{await service().checkout(actor(),company,id,'askadia_monthly');calls=[];const billing=new AsaasBillingService(store,new AsaasSandboxAdapter('sandbox-key',async()=>new Response('',{status:404})));await billing.webhook('secret',{id:'evt_delete',event:'SUBSCRIPTION_DELETED',subscription:{id:'sub_fixture'}},'secret');expect(await store.run(tx=>tx.get('company_subscriptions',company))).toMatchObject({status:'cancelled'});await billing.webhook('secret',{id:'evt_old_payment',event:'PAYMENT_CONFIRMED',payment:{subscription:'sub_fixture'}},'secret');expect(await store.run(tx=>tx.get('company_subscriptions',company))).toMatchObject({status:'cancelled'});});
 it('persists verified deletion even when a removed subscription GET returns 404',async()=>{await service().checkout(actor(),company,id,'askadia_monthly');const billing=new AsaasBillingService(store,new AsaasSandboxAdapter('sandbox-key',async(_url,options)=>options?.method==='DELETE'?Response.json({deleted:true,id:'sub_fixture'}):new Response('',{status:404})));expect(await billing.cancel(actor(),company)).toMatchObject({status:'cancelled',provider_confirmed:true});});
 it.each([401,403,429,500])('reports provider %s without leaking response bodies or access token',async code=>{const adapter=new AsaasSandboxAdapter('sandbox-key',async()=>new Response('secret diagnostic',{status:code}));await expect(adapter.subscription('sub_fixture')).rejects.toThrow('Asaas request failed ('+code+')');});
 it('rejects pagination overflow and never silently truncates paid evidence',async()=>{const adapter=new AsaasSandboxAdapter('sandbox-key',async()=>Response.json({data:Array.from({length:100},(_,i)=>({id:'pay_'+i})),hasMore:true}));await expect(adapter.payments('sub_fixture')).rejects.toThrow('Asaas pagination limit');});
});
