import {randomUUID} from 'node:crypto';
import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {MemoryStore} from './helpers/firestore-memory';
import {billingRpc,verifyAsaasWebhookToken,subscriptionEntitlement} from '../apps/api/src/platform/firestore/billing';
import type {FirestoreActor} from '../apps/api/src/platform/firestore/access';
import type {Row} from '../apps/api/src/platform/firestore/store';

describe('Asaas billing lifecycle — isolated sandbox fixtures',()=>{
 let store:MemoryStore,company:string,other:string,owner:string,request:string;
 const server:FirestoreActor={role:'service_role',id:null};
 const call=(actor:FirestoreActor,name:string,args:Row)=>store.run(tx=>billingRpc(tx,actor,name,args));
 const user=():FirestoreActor=>({role:'authenticated',id:owner});
 beforeEach(async()=>{vi.useFakeTimers({toFake:['Date']});vi.setSystemTime(new Date('2026-10-07T12:00:00Z'));store=new MemoryStore();company=randomUUID();other=randomUUID();owner=randomUUID();request=randomUUID();await store.run(async tx=>{tx.put('companies',company,{id:company,workspace_id:'w',archived_at:null});tx.put('companies',other,{id:other,workspace_id:'x',archived_at:null});tx.put('workspace_members','w_'+owner,{role:'owner'});tx.put('company_onboarding',company,{profile_version:1,revision:2,confirmed_revision:2});tx.put('company_billing_customers',company,{company_id:company,provider:'asaas',environment:'sandbox',customer_id:'cus_fixture'});});});
 afterEach(()=>{vi.useRealTimers();vi.unstubAllEnvs();});
 async function begin(){return call(user(),'begin_asaas_checkout',{p_company_id:company,p_id:request,p_plan:'askadia_monthly'});}
 async function attach(){await begin();return call(server,'attach_asaas_subscription_server',{p_company_id:company,p_id:request,p_subscription:{id:'sub_fixture',customer:'cus_fixture',externalReference:request,status:'ACTIVE',value:1597,cycle:'MONTHLY'},p_environment:'sandbox'});}
 async function reserve(event='evt_fixture'){return call(server,'reserve_asaas_reconciliation_server',{p_subscription_id:'sub_fixture',p_event_id:event,p_payload_hash:event});}
 const payment=(status='CONFIRMED'):Row=>({id:'pay_fixture',subscription:'sub_fixture',customer:'cus_fixture',status,value:1597,dueDate:'2026-10-07',invoiceUrl:'https://sandbox.asaas.com/i/fixture'});
 async function apply(generation:number,payments:Row[]=[payment()],status='ACTIVE'){return call(server,'apply_asaas_snapshot_server',{p_subscription_id:'sub_fixture',p_generation:generation,p_subscription:{id:'sub_fixture',customer:'cus_fixture',externalReference:request,status,value:1597,cycle:'MONTHLY'},p_payments:payments,p_environment:'sandbox'});}
 it('persists pending checkout idempotently with server pricing and no entitlement',async()=>{const first=await begin();expect(first).toMatchObject({status:'prepared',total_cents:159700,customer_id:'cus_fixture'});expect(await begin()).toEqual(first);expect(await store.run(tx=>tx.get('company_subscriptions',company))).toBeNull();await expect(call(user(),'begin_asaas_checkout',{p_company_id:company,p_id:request,p_plan:'askadia_semiannual'})).rejects.toThrow('Checkout conflict');});
 it('denies cross-tenant checkout and authenticated snapshot writes',async()=>{await expect(call(user(),'begin_asaas_checkout',{p_company_id:other,p_id:request,p_plan:'askadia_monthly'})).rejects.toThrow('Access denied');await expect(call(user(),'attach_asaas_subscription_server',{})).rejects.toThrow('Access denied');});
 it('does not grant access when the provider creates an active subscription with unpaid charges',async()=>{await attach();const r=await reserve();await apply(r.generation,[payment('PENDING')]);expect(await store.run(tx=>tx.get('company_subscriptions',company))).toMatchObject({status:'pending',current_period_end:null});});
 it('grants only a provider confirmed paid period and journals duplicate events once',async()=>{await attach();const r=await reserve();await apply(r.generation);expect(await store.run(tx=>tx.get('company_subscriptions',company))).toMatchObject({status:'active',current_period_end:'2026-11-07T00:00:00.000Z',provider:'asaas',provider_confirmed:true});expect(await reserve()).toMatchObject({duplicate:true});expect(await store.run(tx=>tx.list('billing_provider_events'))).toHaveLength(1);});
 it('rejects forged customer, amount, subscription and malformed paid dates atomically',async()=>{await attach();const r=await reserve();for(const patch of [{customer:'cus_other'},{value:1},{subscription:'sub_other'},{dueDate:'2026-02-31'}])await expect(apply(r.generation,[{...payment(),...patch}])).rejects.toThrow();expect(await store.run(tx=>tx.get('company_subscriptions',company))).toMatchObject({status:'pending'});});
 it('ignores a stale reconciliation finishing after a newer refund',async()=>{await attach();const first=await reserve('evt_paid'),second=await reserve('evt_refund');await apply(second.generation,[payment('REFUNDED')]);expect(await apply(first.generation)).toMatchObject({stale:true});expect(await store.run(tx=>tx.get('company_subscriptions',company))).toMatchObject({status:'pending'});});
 it('keeps paid access for the paid period when the next charge is overdue, and expires it',async()=>{await attach();const r=await reserve();await apply(r.generation,[payment(),{...payment('OVERDUE'),id:'pay_next',dueDate:'2026-11-07'}]);expect(await store.run(tx=>tx.get('company_subscriptions',company))).toMatchObject({status:'active'});vi.setSystemTime(new Date('2026-11-07T00:00:00Z'));const next=await reserve('evt_later');await apply(next.generation,[payment()]);expect(await store.run(tx=>tx.get('company_subscriptions',company))).toMatchObject({status:'expired'});});
 it('cancels immediately on confirmed provider cancellation and denies old charge activation',async()=>{await attach();const r=await reserve();await apply(r.generation,[],'INACTIVE');const next=await reserve('evt_old');await apply(next.generation,[payment()],'INACTIVE');expect(await store.run(tx=>tx.get('company_subscriptions',company))).toMatchObject({status:'cancelled'});});
 it('allows a new provider checkout after a confirmed expired subscription',async()=>{await attach();const r=await reserve();await apply(r.generation,[],'EXPIRED');expect(await call(user(),'begin_asaas_checkout',{p_company_id:company,p_id:randomUUID(),p_plan:'askadia_monthly'})).toMatchObject({status:'prepared'});});
 it('requires cancellation before replacing an expired paid period with a still-active provider recurrence',async()=>{await attach();const r=await reserve();await apply(r.generation,[{...payment(),dueDate:'2026-08-01'}]);await expect(call(user(),'begin_asaas_checkout',{p_company_id:company,p_id:randomUUID(),p_plan:'askadia_monthly'})).rejects.toThrow('Cancel current recurrence first');});
 it('prevents a prior subscription event from overwriting a replacement subscription',async()=>{await attach();const r=await reserve();await apply(r.generation,[],'EXPIRED');const replacement=randomUUID();await call(user(),'begin_asaas_checkout',{p_company_id:company,p_id:replacement,p_plan:'askadia_monthly'});await call(server,'attach_asaas_subscription_server',{p_company_id:company,p_id:replacement,p_environment:'sandbox',p_subscription:{id:'sub_replacement',customer:'cus_fixture',externalReference:replacement,status:'ACTIVE',value:1597,cycle:'MONTHLY'}});const late=await reserve('evt_old_cycle');expect(late).toMatchObject({duplicate:true});expect(await store.run(tx=>tx.get('company_subscriptions',company))).toMatchObject({provider_subscription_id:'sub_replacement',status:'pending'});});
 it('marks cancellation requested without claiming provider cancellation',async()=>{await attach();expect(await call(user(),'request_asaas_cancellation',{p_company_id:company})).toMatchObject({cancellation_requested:true,status:'pending'});});
 it('keeps sandbox payments out of live access and requires provider confirmation',()=>{const sub={provider:'asaas',status:'active',environment:'sandbox',provider_confirmed:true,current_period_end:'2026-11-07T00:00:00Z'};expect(subscriptionEntitlement(sub)).toEqual({live:false,sandbox:false});vi.stubEnv('CHECKOUT_MODE','asaas_sandbox');vi.stubEnv('NODE_ENV','test');expect(subscriptionEntitlement(sub)).toEqual({live:false,sandbox:true});expect(subscriptionEntitlement({...sub,provider_confirmed:false})).toEqual({live:false,sandbox:false});vi.stubEnv('NODE_ENV','production');expect(subscriptionEntitlement(sub)).toEqual({live:false,sandbox:false});expect(subscriptionEntitlement({...sub,environment:'production'})).toEqual({live:true,sandbox:false});});
 it('rejects missing/mismatching webhook authentication and accepts the exact configured token',()=>{expect(()=>verifyAsaasWebhookToken(undefined,'configured-token')).toThrow();expect(()=>verifyAsaasWebhookToken('wrong','configured-token')).toThrow();expect(()=>verifyAsaasWebhookToken('token',undefined)).toThrow();expect(()=>verifyAsaasWebhookToken('configured-token','configured-token')).not.toThrow();});
});
