import {beforeEach,describe,expect,it} from 'vitest';
import {randomUUID} from 'node:crypto';
import {firestoreClient} from '../apps/api/src/platform/firestore/client';
import type {Row} from '../apps/api/src/platform/firestore/store';
import {MemoryStore} from './helpers/firestore-memory';

describe('native local draft import',()=>{
 let store:MemoryStore,company:string,source:string,workspace:string,owner:string,marketing:string,attendant:string,other:string,payload:Row;
 async function call(input=payload,actor=owner,target=company){const result=await firestoreClient('authenticated',actor,store).rpc('import_local_drafts',{p_company_id:target,p_payload:input});if(result.error)throw result.error;return result.data;}
 beforeEach(async()=>{store=new MemoryStore();[company,source,workspace,owner,marketing,attendant,other]=Array.from({length:7},()=>randomUUID());const contact=randomUUID();payload={sourceCompanyId:source,contacts:[{id:contact,companyId:source,name:'Fixture contact',phone:'+5511999999999',email:'fixture@example.test'}],opportunities:[{id:randomUUID(),companyId:source,contactId:contact,interest:'Information',source:'Manual',stage:'Matriculado',history:[]}],contents:[{id:randomUUID(),companyId:source,title:'Fixture content',caption:'Only a draft',format:'Imagem',date:'2026-10-07',version:8,status:'approved',approvedVersion:8}]};await store.run(async tx=>{tx.put('companies',company,{id:company,workspace_id:workspace,archived_at:null});tx.put('workspace_members',workspace+'_'+owner,{workspace_id:workspace,user_id:owner,role:'owner'});for(const [user_id,role] of [[marketing,'marketing'],[attendant,'attendant']])tx.put('company_members',company+'_'+user_id,{company_id:company,user_id,role});});});
 it('imports contacts and resets approved content and won opportunities to draft/new',async()=>{expect(await call()).toEqual({contacts:1,opportunities:1,contents:1,skipped:0});expect(await store.run(tx=>tx.list('editorial_drafts'))).toMatchObject([{company_id:company,status:'draft',version:1,created_by:owner}]);expect(await store.run(tx=>tx.list('opportunities'))).toMatchObject([{company_id:company,stage:'new',original_source:'local_import'}]);expect(await store.run(tx=>tx.list('contacts'))).toMatchObject([{company_id:company,consent:false,opted_out:false}]);expect(await store.run(tx=>tx.list('stage_history'))).toMatchObject([{stage:'new',actor_id:owner}]);expect(await store.run(tx=>tx.list('local_draft_imports'))).toHaveLength(3);});
 it('skips repeated or altered source identifiers without overwriting established data',async()=>{await call();expect(await call()).toEqual({contacts:0,opportunities:0,contents:0,skipped:3});payload.contacts[0].name='Altered';payload.contents[0].caption='Altered';expect(await call()).toEqual({contacts:0,opportunities:0,contents:0,skipped:3});expect((await store.run(tx=>tx.list('contacts')))[0].name).toBe('Fixture contact');expect((await store.run(tx=>tx.list('editorial_drafts')))[0].caption).toBe('Only a draft');await expect(call(payload,other)).rejects.toMatchObject({code:'42501'});});
 it('requires CRM and marketing independently, including before duplicate replay',async()=>{await expect(call(payload,marketing)).rejects.toMatchObject({code:'42501'});await expect(call(payload,attendant)).rejects.toMatchObject({code:'42501'});expect(await call({...payload,contacts:[],opportunities:[]},marketing)).toMatchObject({contents:1});expect(await call({...payload,contents:[]},attendant)).toMatchObject({contacts:1,opportunities:1});await store.run(async tx=>tx.remove('company_members',company+'_'+attendant));await expect(call({...payload,contents:[]},attendant)).rejects.toMatchObject({code:'42501'});});
 it('deduplicates phones only inside the destination and links its imported contact',async()=>{const local=randomUUID(),foreign=randomUUID();await store.run(async tx=>{tx.put('contacts',foreign,{id:foreign,company_id:randomUUID(),phone_e164:'+5511999999999'});tx.put('contacts',local,{id:local,company_id:company,phone_e164:'+5511999999999',name:'Preserved'});});expect(await call()).toEqual({contacts:0,opportunities:1,contents:1,skipped:1});expect((await store.run(tx=>tx.list('opportunities')))[0].contact_id).toBe(local);expect((await store.run(tx=>tx.get('contacts',local)))?.name).toBe('Preserved');});
 it('rejects source mismatch, duplicate IDs, invalid phones and missing linked contacts atomically',async()=>{const invalid=[{...payload,contacts:[{...payload.contacts[0],companyId:randomUUID()}]},{...payload,contacts:[payload.contacts[0],payload.contacts[0]]},{...payload,contacts:[{...payload.contacts[0],phone:'12'}]},{...payload,opportunities:[{...payload.opportunities[0],contactId:randomUUID()}]},{...payload,contents:[{...payload.contents[0],date:'2026-02-30'}]}];for(const input of invalid)await expect(call(input)).rejects.toMatchObject({code:'22023'});for(const table of ['contacts','opportunities','editorial_drafts','local_draft_imports','stage_history','audit_logs'])expect(await store.run(tx=>tx.list(table))).toEqual([]);});
 it('rolls back all rows when a later content write fails',async()=>{const original=store.run.bind(store);store.run=operation=>original(tx=>operation({...tx,put:(table,id,row)=>{if(table==='editorial_drafts')throw new Error('fixture draft failure');tx.put(table,id,row);}}));await expect(call()).rejects.toMatchObject({message:'fixture draft failure'});for(const table of ['contacts','opportunities','editorial_drafts','local_draft_imports','stage_history','audit_logs'])expect(await original(tx=>tx.list(table))).toEqual([]);});
 it('denies a foreign destination and never links a mapping to a foreign contact',async()=>{await expect(call(payload,owner,randomUUID())).rejects.toMatchObject({code:'42501'});await call();const mapping=(await store.run(tx=>tx.list('local_draft_imports'))).find(r=>r.object_type==='contact')!;await store.run(async tx=>{const contact=await tx.get('contacts',mapping.record_id);tx.put('contacts',mapping.record_id,{...contact,company_id:randomUUID()});});await expect(call({...payload,opportunities:[{...payload.opportunities[0],id:randomUUID()}]})).rejects.toMatchObject({code:'22023'});expect(await store.run(tx=>tx.list('opportunities'))).toHaveLength(1);});
});
