import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {firestoreClient} from '../apps/api/src/platform/firestore/client';
import {CompanySiteController} from '../apps/api/src/sites/controller';
import {randomUUID} from 'node:crypto';
import {MemoryStore} from './helpers/firestore-memory';
import {siteRpc} from '../apps/api/src/platform/firestore/sites';
import type {FirestoreActor} from '../apps/api/src/platform/firestore/access';
import type {Row} from '../apps/api/src/platform/firestore/store';
import {context,stages} from '../apps/api/src/platform/firestore/journey-state';
import {renderSite} from '../packages/contracts/src/site';
const company=randomUUID(),otherCompany=randomUUID(),workspace=randomUUID(),owner=randomUUID(),other=randomUUID();
const actor:FirestoreActor={role:'authenticated',id:owner},server:FirestoreActor={role:'service_role',id:null};
const content={name:'Clínica Fixture',headline:'Atendimento administrativo',intro:'Serviços da clínica',about:'Equipe',services:[{title:'Cardiologia',description:'Consultas'}],address:'Rua Exemplo',hours:'',offer:'',whatsapp:'5511999999999',cta:'Falar com a equipe',color:'#27292e',background:'light',images:[],logo:null};
let store:MemoryStore;
const call=(name:string,args:Row={},a=actor)=>store.run(tx=>siteRpc(tx,a,name,{p_company_id:company,...args}));
const save=(revision=0,values=content)=>call('save_company_site',{p_revision:revision,p_profile_version:1,p_content:values});
const publish=(revision=1)=>call('publish_company_site',{p_revision:revision,p_publish:true});
async function paid(){await store.run(async tx=>tx.put('company_subscriptions',company,{status:'active',current_period_end:new Date(Date.now()+86400000).toISOString()}));}

async function completedSetup(preference='create'){
 await paid();await store.run(async tx=>{const p=await tx.get('company_profile_versions',company+'_1');tx.put('company_profile_versions',company+'_1',{...p,facts:{websitePreference:{value:preference,status:'provided'}}});});
 for(let stage=1;stage<=5;stage++)await store.run(async tx=>{const ctx=await context(tx,company),current=stages(ctx)[stage-1],id=randomUUID();tx.put('company_marketing_approvals',id,{id,company_id:company,profile_version:1,stage,basis:current.basis,token:randomUUID(),approved_at:new Date().toISOString(),invalidated_at:null});});
 await store.run(async tx=>{const ctx=await context(tx,company);tx.put('company_setup',company,{company_id:company,profile_version:1,bases:stages(ctx).map(s=>s.basis),approved_by:owner,invalidated_at:null});});
}
describe('Firestore sites: private versioned clinic preview',()=>{
 afterEach(()=>vi.unstubAllEnvs());
 beforeEach(async()=>{store=new MemoryStore();await store.run(async tx=>{tx.put('companies',company,{id:company,workspace_id:workspace});tx.put('companies',otherCompany,{id:otherCompany,workspace_id:randomUUID()});tx.put('workspace_members',workspace+'_'+owner,{role:'owner'});tx.put('company_onboarding',company,{revision:3,confirmed_revision:3,profile_version:1});tx.put('company_profile_versions',company+'_1',{company_id:company,version:1,facts:{}});});});
 it('automatically seeds the requested site once after valid setup and preserves published content',async()=>{await completedSetup();await store.run(async tx=>tx.put('company_sites',company,{company_id:company,revision:2,profile_version:0,draft:content,published:content,published_revision:2,approval:{revision:2}}));const job=await call('claim_company_site_server',{},server);expect(job).toMatchObject({kind:'site',companyId:company});expect(await call('claim_company_site_server',{},server)).toBeNull();expect(await store.run(tx=>tx.list('company_site_auto_seeds'))).toHaveLength(1);expect(await call('finish_company_site_server',{p_id:job.id,p_token:job.token,p_output:{...content,headline:'Private automatic preview'}},server)).toBe(true);expect(await call('claim_company_site_server',{},server)).toBeNull();expect(await store.run(tx=>tx.get('company_sites',company))).toMatchObject({revision:3,published:content,draft:{headline:'Private automatic preview'}});expect(await store.run(tx=>tx.list('site_generation_runs'))).toHaveLength(1);});
 it('does not auto seed existing websites, invalidated setup or exhausted quota',async()=>{await completedSetup('existing');expect(await call('claim_company_site_server',{},server)).toBeNull();await completedSetup();await store.run(async tx=>tx.put('onboarding_provider_limits',company+'_site',{daily_calls:0}));expect(await call('claim_company_site_server',{},server)).toBeNull();expect(await store.run(tx=>tx.list('company_site_auto_seeds'))).toEqual([]);await store.run(async tx=>{tx.put('onboarding_provider_limits',company+'_site',{daily_calls:5});const setup=await tx.get('company_setup',company);tx.put('company_setup',company,{...setup,invalidated_at:new Date().toISOString()});});expect(await call('claim_company_site_server',{},server)).toBeNull();});
 it('rechecks automatic setup approval on completion and recovers the same seed after lease expiry',async()=>{await completedSetup();const first=await call('claim_company_site_server',{},server);await store.run(async tx=>{const row=await tx.get('company_site_jobs',first.id);tx.put('company_site_jobs',first.id,{...row,lease_until:new Date(0).toISOString()});});const resumed=await call('claim_company_site_server',{},server);expect(resumed.id).toBe(first.id);expect(resumed.token).not.toBe(first.token);await store.run(async tx=>{const approval=(await tx.list('company_marketing_approvals',[{field:'company_id',value:company}])).find(a=>a.stage===5)!;tx.put('company_marketing_approvals',approval.id,{...approval,invalidated_at:new Date().toISOString()});});expect(await call('finish_company_site_server',{p_id:resumed.id,p_token:resumed.token,p_output:content},server)).toBe(false);expect(await store.run(tx=>tx.get('company_site_jobs',resumed.id))).toMatchObject({status:'stale'});expect(await store.run(tx=>tx.list('site_generation_runs'))).toHaveLength(1);});
 it('serves the real private editor read/save flow through the Firestore client with tenant authorization',async()=>{vi.stubEnv('DATABASE_PROVIDER','firestore');vi.stubEnv('WEB_ORIGIN','https://medsi.example.test');const client=firestoreClient('authenticated',owner,store),r={headers:{},actor:{id:owner,email:'fixture@example.test',client}},controller=new CompanySiteController();await controller.save(r,company,{revision:0,profileVersion:1,content});expect(await controller.read(r,company)).toMatchObject({site:{revision:1,draft:content},canEdit:true,canPublish:true});const unauthorized={headers:{},actor:{id:other,email:'other@example.test',client:firestoreClient('authenticated',other,store)}};await expect(controller.read(unauthorized,company)).rejects.toThrow();});
 it('persists editable private snapshots, renders actual branding/services and preserves history on reload',async()=>{await save();expect(await call('read_published_site_server',{},server)).toBeNull();const reloaded=await store.run(tx=>tx.get('company_sites',company));expect(renderSite(reloaded!.draft,()=>'' )).toContain('Cardiologia');await save(1,{...content,headline:'Versão editada'});expect(await store.run(tx=>tx.get('company_site_versions',company+'_1'))).toMatchObject({content:{headline:content.headline}});expect(await store.run(tx=>tx.get('company_sites',company))).toMatchObject({revision:2,draft:{headline:'Versão editada'}});});
 it('rejects cross tenant access, stale edits and foreign images without writes',async()=>{await expect(call('save_company_site',{p_revision:0,p_profile_version:1,p_content:content},{role:'authenticated',id:other})).rejects.toMatchObject({code:'42501'});await save();await expect(save()).rejects.toMatchObject({code:'40001'});const image=randomUUID();await store.run(async tx=>tx.put('onboarding_attachments',image,{company_id:otherCompany,mime:'image/png'}));await expect(save(1,{...content,images:[image]} as typeof content)).rejects.toMatchObject({code:'42501'});expect(await store.run(tx=>tx.get('company_sites',company))).toMatchObject({revision:1});});
 it('requires site permission and approval of exact version; editing invalidates approval and preserves public snapshot',async()=>{await save();await expect(publish()).rejects.toMatchObject({code:'42501'});await call('approve_company_site',{p_revision:1});await publish();await save(1,{...content,headline:'Private edit'});expect(await call('read_published_site_server',{},server)).toMatchObject({revision:1,content:{headline:content.headline}});await expect(publish(2)).rejects.toMatchObject({code:'42501'});await call('publish_company_site',{p_revision:2,p_publish:false});expect(await call('read_published_site_server',{},server)).toBeNull();await expect(publish(2)).rejects.toMatchObject({code:'42501'});});
 it('simulation: refuses unapproved or altered public snapshots',async()=>{
  await save();await store.run(async tx=>{const site=await tx.get('company_sites',company);tx.put('company_sites',company,{...site,published:content,published_revision:1});});
  expect(await call('read_published_site_server',{},server)).toBeNull();
  await call('approve_company_site',{p_revision:1});await publish();
  await store.run(async tx=>{const site=await tx.get('company_sites',company);tx.put('company_sites',company,{...site,published:{...content,headline:'Unapproved replacement'}});});
  expect(await call('read_published_site_server',{},server)).toBeNull();
 });
 it('simulation: routes the approved published version after a private edit',async()=>{
  await save();await call('approve_company_site',{p_revision:1});await publish();await call('set_site_domain',{p_hostname:'www.fixture.com.br'});await save(1,{...content,headline:'Private next version'});
  const d=await store.run(tx=>tx.get('company_site_domains',company));
  expect(await call('verify_site_domain_server',{p_actor:owner,p_hostname:d!.hostname,p_token:d!.verification_token,p_routed:true},server)).toBe(true);
  expect(await call('read_published_site_server',{p_company_id:null,p_hostname:d!.hostname},server)).toMatchObject({revision:1,content:{headline:content.headline}});
  const site=await store.run(tx=>tx.get('company_sites',company));expect(site!.approval).toBeNull();expect(site!.published_approval).toMatchObject({revision:1,revoked_at:null});
 });
 it('simulation: blocks revoked publication, archived companies and routing after profile changes',async()=>{
  await save();await call('approve_company_site',{p_revision:1});await publish();await call('set_site_domain',{p_hostname:'www.fixture.com.br'});
  const d=await store.run(tx=>tx.get('company_site_domains',company));
  await store.run(async tx=>tx.put('company_onboarding',company,{revision:4,confirmed_revision:3,profile_version:1}));
  await expect(call('verify_site_domain_server',{p_actor:owner,p_hostname:d!.hostname,p_token:d!.verification_token,p_routed:true},server)).rejects.toMatchObject({code:'40001'});
  // A profile edit does not silently replace or withdraw the already published snapshot.
  expect(await call('read_published_site_server',{},server)).toMatchObject({revision:1});
  await store.run(async tx=>{const site=await tx.get('company_sites',company);tx.put('company_sites',company,{...site,published_approval:{...site!.published_approval,revoked_at:new Date().toISOString()}});});
  expect(await call('read_published_site_server',{},server)).toBeNull();
  await store.run(async tx=>{const site=await tx.get('company_sites',company);tx.put('company_sites',company,{...site,published_approval:{...site!.published_approval,revoked_at:null}});tx.put('companies',company,{id:company,workspace_id:workspace,archived_at:new Date().toISOString()});});
  expect(await call('read_published_site_server',{},server)).toBeNull();
 });
 it('simulation: rejects same-company attachment metadata pointing at another clinic storage path',async()=>{
  const image=randomUUID();await store.run(async tx=>tx.put('onboarding_attachments',image,{id:image,company_id:company,mime:'image/png',object_path:otherCompany+'/onboarding/'+image+'.png'}));
  await expect(save(0,{...content,images:[image]} as typeof content)).rejects.toMatchObject({code:'42501'});
  expect(await store.run(tx=>tx.get('company_sites',company))).toBeNull();
 });
 it('does not grant publication to marketing editors and serializes two edits of the same revision',async()=>{const editor=randomUUID();await store.run(async tx=>tx.put('company_members',company+'_'+editor,{company_id:company,user_id:editor,role:'marketing'}));await save();await expect(call('approve_company_site',{p_revision:1},{role:'authenticated',id:editor})).rejects.toMatchObject({code:'42501'});const results=await Promise.allSettled([save(1,{...content,headline:'Edit A'}),save(1,{...content,headline:'Edit B'})]);expect(results.filter(r=>r.status==='fulfilled')).toHaveLength(1);expect(results.filter(r=>r.status==='rejected')).toHaveLength(1);});
 it('reserves each domain and slug for one clinic and releases them when replaced',async()=>{const secondWorkspace=randomUUID();await store.run(async tx=>{tx.put('companies',otherCompany,{id:otherCompany,workspace_id:secondWorkspace});tx.put('workspace_members',secondWorkspace+'_'+owner,{role:'owner'});});await call('set_site_slug',{p_slug:'clinica-one'});await expect(call('set_site_slug',{p_company_id:otherCompany,p_slug:'clinica-one'})).rejects.toMatchObject({code:'23505'});await call('set_site_slug',{p_slug:'clinica-two'});expect(await call('set_site_slug',{p_company_id:otherCompany,p_slug:'clinica-one'})).toBe(true);await call('set_site_domain',{p_hostname:'www.clinica.com.br'});await expect(call('set_site_domain',{p_company_id:otherCompany,p_hostname:'www.clinica.com.br'})).rejects.toMatchObject({code:'23505'});await call('set_site_domain',{p_hostname:null});expect(await call('set_site_domain',{p_company_id:otherCompany,p_hostname:'www.clinica.com.br'})).toBe(true);});
 it('rejects profile changes and rechecks permission revocation',async()=>{await save();await call('approve_company_site',{p_revision:1});await store.run(async tx=>tx.put('company_onboarding',company,{revision:4,confirmed_revision:3,profile_version:1}));await expect(publish()).rejects.toMatchObject({code:'40001'});await store.run(async tx=>tx.remove('workspace_members',workspace+'_'+owner));await expect(call('approve_company_site',{p_revision:1})).rejects.toMatchObject({code:'42501'});});
 it('reserves addresses atomically and cannot route an unpublished site; only trusted service verifies',async()=>{await call('set_site_domain',{p_hostname:'www.clinica.com.br'});const d=await store.run(tx=>tx.get('company_site_domains',company));const args={p_actor:owner,p_hostname:d!.hostname,p_token:d!.verification_token};await expect(call('verify_site_domain_server',args)).rejects.toMatchObject({code:'42501'});await expect(call('verify_site_domain_server',{...args,p_routed:true},server)).rejects.toMatchObject({code:'42501'});await call('verify_site_domain_server',args,server);expect(await call('read_published_site_server',{p_company_id:null,p_hostname:d!.hostname},server)).toBeNull();await call('set_site_domain',{p_hostname:'www.nova.com.br'});await expect(call('verify_site_domain_server',args,server)).rejects.toMatchObject({code:'40001'});await call('set_site_slug',{p_slug:'clinica-fixture'});await expect(call('read_published_site_server',{p_company_id:null,p_slug:'clinica-fixture'})).rejects.toMatchObject({code:'42501'});});
 it('deduplicates generation and enforces paid access and daily budget',async()=>{await expect(call('reserve_site_generation',{p_id:randomUUID()})).rejects.toMatchObject({code:'P0402'});await paid();const id=randomUUID();expect(await call('reserve_site_generation',{p_id:id})).toBe(true);expect(await call('reserve_site_generation',{p_id:id})).toBe(false);await store.run(async tx=>tx.put('onboarding_provider_limits',company+'_site',{daily_calls:1}));await expect(call('reserve_site_generation',{p_id:randomUUID()})).rejects.toMatchObject({code:'22023'});});
 it('leases each task once and persists generated preview without publishing',async()=>{await paid();const id=randomUUID(),args={p_id:id,p_revision:0,p_profile_version:1,p_feedback:'Priorize contato'};expect(await call('enqueue_company_site',args)).toMatchObject({id,status:'pending'});expect(await call('enqueue_company_site',args)).toMatchObject({id});await expect(call('claim_company_site_server')).rejects.toMatchObject({code:'42501'});const claimed=await call('claim_company_site_server',{},server);expect(claimed).toMatchObject({id,kind:'site',feedback:'Priorize contato'});expect(await call('claim_company_site_server',{},server)).toBeNull();expect(await call('finish_company_site_server',{p_id:id,p_token:randomUUID(),p_output:content},server)).toBe(false);expect(await call('finish_company_site_server',{p_id:id,p_token:claimed.token,p_output:content},server)).toBe(true);expect(await call('finish_company_site_server',{p_id:id,p_token:claimed.token,p_output:content},server)).toBe(false);expect(await store.run(tx=>tx.get('company_sites',company))).toMatchObject({revision:1,published:null});});
 it('recovers an expired lease after restart and rejects obsolete generation after an edit',async()=>{await paid();const id=randomUUID();await call('enqueue_company_site',{p_id:id,p_revision:0,p_profile_version:1,p_feedback:''});const first=await call('claim_company_site_server',{},server);await store.run(async tx=>{const row=await tx.get('company_site_jobs',id);tx.put('company_site_jobs',id,{...row,lease_until:new Date(0).toISOString()});});const resumed=await call('claim_company_site_server',{},server);expect(resumed.token).not.toBe(first.token);await save();expect(await call('finish_company_site_server',{p_id:id,p_token:resumed.token,p_output:content},server)).toBe(false);expect(await store.run(tx=>tx.get('company_site_jobs',id))).toMatchObject({status:'stale'});});
 it('backs off failures, preserves the draft and stops after three attempts',async()=>{await paid();await save();const id=randomUUID();await call('enqueue_company_site',{p_id:id,p_revision:1,p_profile_version:1,p_feedback:''});for(let n=0;n<3;n++){const job=await call('claim_company_site_server',{},server);await call('finish_company_site_server',{p_id:id,p_token:job.token,p_output:null},server);if(n<2){expect(await call('claim_company_site_server',{},server)).toBeNull();await store.run(async tx=>{const row=await tx.get('company_site_jobs',id);tx.put('company_site_jobs',id,{...row,next_attempt_at:new Date(0).toISOString()});});}}expect(await store.run(tx=>tx.get('company_site_jobs',id))).toMatchObject({status:'failed',attempts:3});expect(await store.run(tx=>tx.get('company_sites',company))).toMatchObject({revision:1,draft:content});});
});
