import {beforeEach,afterEach,describe,it,expect,vi} from 'vitest';
import {randomUUID} from 'node:crypto';
import {MemoryStore} from './helpers/firestore-memory';
import {draftServiceReply} from '../apps/api/src/inbox/assistant';
import {inboxRpc} from '../apps/api/src/platform/firestore/inbox';
import {crmRpc} from '../apps/api/src/platform/firestore/crm';
import {channelOperations,channelRpc} from '../apps/api/src/platform/firestore/channels';
import {sealChannel,openChannel} from '../apps/api/src/onboarding/channels';
import type {FirestoreActor} from '../apps/api/src/platform/firestore/access';
import type {Row} from '../apps/api/src/platform/firestore/store';

describe('native Firestore administrative attendance (local transaction fixtures)',()=>{
 let store:MemoryStore,company:string,workspace:string,actor:FirestoreActor,other:FirestoreActor,contact:string,channel:string;
 const service:FirestoreActor={role:'service_role',id:null},thread='5511999999999@s.whatsapp.net';
 const call=(name:string,args:Row={},who=actor)=>store.run(tx=>(channelOperations.includes(name)?channelRpc:name.includes('crm')||['open_company_conversation','set_conversation_mode','add_conversation_note','claim_company_reply'].includes(name)?crmRpc:inboxRpc)(tx,who,name,{p_company_id:company,...args}));
 const settings=(revision=0,automatic=false)=>({channel:'whatsapp',revision,mode:'ai',prompt:'Respostas administrativas. Encaminhe dúvidas clínicas.',rules:[],fallback:'Nossa equipe responderá.',automatic});
 async function activate(){const saved=await call('save_service_settings',{p_settings:settings(0,true)}) as Row;await call('save_service_policy',{p_policy:{revision:saved.revision,profileVersion:1,timezone:'UTC',hours:Array.from({length:7},(_,day)=>({day,start:0,end:1440})),reviewed:true}});await call('save_contact_consent',{p_contact_id:contact,p_consent:true,p_opt_out:false,p_evidence:'Consentimento registrado pela equipe fictícia'});await store.run(async tx=>{const s=await tx.get('company_service_settings',company+'_whatsapp');tx.put('company_service_settings',company+'_whatsapp',{...s,enabled_since:new Date(Date.now()-60000).toISOString()});});}
 const claim=(id=randomUUID())=>call('inbox_auto_claim',{p_thread:thread,p_message_id:id,p_time:new Date().toISOString()},service);
 afterEach(()=>vi.unstubAllEnvs());
 beforeEach(async()=>{store=new MemoryStore();company=randomUUID();workspace=randomUUID();actor={role:'authenticated',id:randomUUID()};other={role:'authenticated',id:randomUUID()};contact=randomUUID();channel=randomUUID();
  await store.run(async tx=>{tx.put('companies',company,{id:company,workspace_id:workspace});tx.put('workspace_members',workspace+'_'+actor.id,{workspace_id:workspace,user_id:actor.id,role:'owner'});tx.put('company_onboarding',company,{company_id:company,revision:1,confirmed_revision:1,profile_version:1});tx.put('company_profile_versions',company+'_1',{company_id:company,version:1,facts:{name:{value:'Clínica fictícia',status:'provided'},history:{value:'PRIVATE CURRICULUM'},services:{value:'Atendimento administrativo',status:'provided'}}});tx.put('company_subscriptions',company,{company_id:company,status:'active',current_period_end:new Date(Date.now()+86400000).toISOString()});tx.put('company_channels',channel,{id:channel,company_id:company,provider:'evolution',status:'connected',remote_id:'askadia-'+company});tx.put('contacts',contact,{id:contact,company_id:company,name:'Contato fictício',phone_e164:'+5511999999999',consent:false,opted_out:false});});
 });
 it('denies cross-tenant calls before reads and writes',async()=>{await expect(call('save_service_settings',{p_settings:settings()},other)).rejects.toMatchObject({code:'42501'});await expect(call('save_crm_contact',{p_request_id:randomUUID(),p_name:'Outro'},other)).rejects.toMatchObject({code:'42501'});});
 it('requires configuration permissions and invalidates stale revisions',async()=>{await store.run(async tx=>tx.put('company_members',company+'_'+other.id,{company_id:company,user_id:other.id,role:'attendant'}));await expect(call('save_service_settings',{p_settings:settings()},other)).rejects.toMatchObject({code:'42501'});const saved=await call('save_service_settings',{p_settings:settings()}) as Row;expect(saved.revision).toBe(1);await expect(call('save_service_settings',{p_settings:settings()})).rejects.toMatchObject({code:'40001'});});
 it('does not activate on disconnected channels or an unconfirmed profile',async()=>{await store.run(async tx=>tx.put('company_channels',channel,{id:channel,company_id:company,provider:'evolution',status:'disconnected',remote_id:'askadia-'+company}));await expect(call('save_service_settings',{p_settings:settings(0,true)})).rejects.toMatchObject({code:'22023'});});
 it('atomically reserves once, locks uncertain content against fresh request IDs',async()=>{await call('take_inbox_conversation',{p_channel:'whatsapp',p_thread:thread});const id=randomUUID(),args={p_thread:thread,p_id:id,p_body:'Resposta administrativa'};const results=await Promise.all([call('reserve_inbox_dispatch',args),call('reserve_inbox_dispatch',args)]);expect(results).toEqual([true,false]);await call('finish_inbox_dispatch',{p_id:id,p_state:'uncertain',p_provider_id:null});expect(await call('reserve_inbox_dispatch',{...args,p_id:randomUUID()})).toBe(false);await call('finish_inbox_dispatch',{p_id:id,p_state:'sent',p_provider_id:'late'});expect((await store.run(tx=>tx.get('inbox_dispatches',id)))?.state).toBe('uncertain');});
 it('rejects forged finish and conflicting request reuse',async()=>{await call('take_inbox_conversation',{p_channel:'whatsapp',p_thread:thread});const id=randomUUID();await call('reserve_inbox_dispatch',{p_thread:thread,p_id:id,p_body:'Resposta'});await expect(call('reserve_inbox_dispatch',{p_thread:thread,p_id:id,p_body:'Mudou'})).rejects.toMatchObject({code:'40001'});await expect(call('finish_inbox_dispatch',{p_id:id,p_state:'sent',p_provider_id:null})).rejects.toMatchObject({code:'22023'});});
 it('blocks manual outbound messages after explicit contact opt-out',async()=>{await call('take_inbox_conversation',{p_channel:'whatsapp',p_thread:thread});await call('save_contact_consent',{p_contact_id:contact,p_consent:false,p_opt_out:true,p_evidence:'Pedido explícito do contato fictício'});await expect(call('reserve_inbox_dispatch',{p_thread:thread,p_id:randomUUID(),p_body:'Olá'})).rejects.toMatchObject({code:'42501'});});
 it('requires takeover and blocks dispatch after release',async()=>{await expect(call('reserve_inbox_dispatch',{p_thread:thread,p_id:randomUUID(),p_body:'Olá'})).rejects.toMatchObject({code:'42501'});await call('take_inbox_conversation',{p_channel:'whatsapp',p_thread:thread});await call('release_inbox_conversation',{p_thread:thread});await expect(call('reserve_inbox_dispatch',{p_thread:thread,p_id:randomUUID(),p_body:'Olá'})).rejects.toMatchObject({code:'42501'});});
 it('deduplicates contacts and notes, keeps conversations human, rejects foreign IDs',async()=>{const id=randomUUID(),args={p_request_id:id,p_name:'Pessoa Fictícia',p_phone:'+5511888888888',p_email:'',p_interest:'Administrativo'};const result=await call('save_crm_contact',args) as Row;expect(await call('save_crm_contact',args)).toEqual(result);await expect(call('save_crm_contact',{...args,p_name:'Outro nome'})).rejects.toMatchObject({code:'40001'});const conversation=await call('open_company_conversation',{p_contact_id:result.contact.id}) as Row;expect(conversation.mode).toBe('human');const note={p_id:conversation.id,p_request_id:randomUUID(),p_body:'Observação administrativa'};expect(await call('add_conversation_note',note)).toEqual(await call('add_conversation_note',note));await expect(call('set_conversation_mode',{p_id:conversation.id,p_revision:0,p_mode:'closed'})).rejects.toMatchObject({code:'40001'});await expect(call('set_conversation_mode',{p_id:randomUUID(),p_revision:1,p_mode:'human'})).rejects.toMatchObject({code:'42501'});});
 it('syncs WhatsApp without inventing consent, including opaque LID contacts',async()=>{const input={p_contacts:[{jid:thread,name:'Contato',preview:'Informações',time:null},{jid:'123456789@lid',name:'Outro',preview:'',time:null}]};const first=await call('sync_whatsapp_crm',input);expect(first).toEqual({added:1,linked:2});expect(await call('sync_whatsapp_crm',input)).toEqual({added:0,linked:2});const rows=await store.run(tx=>tx.list('contacts',[{field:'company_id',value:company}]));expect(rows.every(r=>r.consent===false)).toBe(true);});
 it('keeps credential bridge service-only, actor-authorized and tenant-bound',async()=>{const meta=randomUUID();await store.run(async tx=>{tx.put('company_channels',meta,{id:meta,company_id:company,provider:'meta',status:'connected',remote_id:'123',metadata:{instagramId:'456'}});tx.put('channel_secrets',meta,{channel_id:meta,company_id:company,cipher:'encrypted-fixture-only'});});const args={p_actor:actor.id,p_action:'crm.read'};await expect(call('read_company_meta_server',args)).rejects.toMatchObject({code:'42501'});await expect(call('read_company_meta_server',{...args,p_actor:other.id},service)).rejects.toMatchObject({code:'42501'});expect(await call('read_company_meta_server',args,service)).toMatchObject({remote_id:'123',cipher:'encrypted-fixture-only'});await store.run(async tx=>tx.put('channel_secrets',meta,{channel_id:meta,company_id:randomUUID(),cipher:'foreign'}));expect(await call('read_company_meta_server',args,service)).toBeNull();});
 it('minimizes AI context and requires paid access',async()=>{await call('save_service_settings',{p_settings:settings()});const context=await call('inbox_ai_context',{p_channel:'whatsapp'}) as Row;expect(context.profile.name).toBeTruthy();expect(context.profile.history).toBeUndefined();await store.run(async tx=>tx.remove('company_subscriptions',company));await expect(call('inbox_ai_context',{p_channel:'whatsapp'})).rejects.toMatchObject({code:'P0402'});});
 it('requires consent, reviewed policy and server role before claiming',async()=>{await call('save_service_settings',{p_settings:settings(0,true)});expect(await claim()).toBeNull();await expect(call('inbox_auto_targets')).rejects.toMatchObject({code:'42501'});});
 it('rechecks consent and hours immediately before dispatch',async()=>{await activate();const id=randomUUID(),job=await claim(id) as Row;expect(job.token).toBeTruthy();await call('save_contact_consent',{p_contact_id:contact,p_consent:false,p_opt_out:true,p_evidence:'Solicitação do contato fictício'});expect(await call('inbox_auto_prepare',{p_message_id:id,p_token:job.token,p_body:'Resposta',p_handoff:false},service)).toBe(false);expect(await claim()).toBeNull();});
 it('cancels generation on human takeover and blocks takeover during dispatch',async()=>{await activate();const id=randomUUID(),job=await claim(id) as Row;await call('take_inbox_conversation',{p_channel:'whatsapp',p_thread:thread});expect(await call('inbox_auto_prepare',{p_message_id:id,p_token:job.token,p_body:'Resposta',p_handoff:false},service)).toBe(false);await call('release_inbox_conversation',{p_thread:thread});const second=randomUUID(),job2=await call('inbox_auto_claim',{p_thread:thread,p_message_id:second,p_time:new Date(Date.now()+1000).toISOString()},service) as Row;expect(await call('inbox_auto_prepare',{p_message_id:second,p_token:job2.token,p_body:'Resposta',p_handoff:false},service)).toBe(true);await expect(call('take_inbox_conversation',{p_channel:'whatsapp',p_thread:thread})).rejects.toMatchObject({code:'40001'});});
 it('recovers stale dispatch as uncertain and never claims a second send',async()=>{await activate();const id=randomUUID(),job=await claim(id) as Row;await call('inbox_auto_prepare',{p_message_id:id,p_token:job.token,p_body:'Resposta',p_handoff:false},service);await store.run(async tx=>{const row=(await tx.list('inbox_auto_jobs'))[0];tx.put('inbox_auto_jobs',row.id,{...row,updated_at:new Date(Date.now()-180000).toISOString()});});await call('inbox_auto_targets',{},service);expect((await store.run(tx=>tx.list('inbox_auto_jobs')))[0].state).toBe('uncertain');expect(await claim()).toBeNull();});
 it('invalidates automation on profile revision, policy hours or actor revocation',async()=>{await activate();expect((await call('inbox_auto_targets',{},service)) as Row[]).toHaveLength(1);await store.run(async tx=>{const policy=await tx.get('company_service_policies',company);tx.put('company_service_policies',company,{...policy,hours:[]});});expect(await claim()).toBeNull();await store.run(async tx=>tx.remove('workspace_members',workspace+'_'+actor.id));expect(await call('inbox_auto_targets',{},service)).toEqual([]);});
 it('persists OAuth state and cipher privately, checks tenant AAD and consumes once',async()=>{
  vi.stubEnv('SECRETS_ENCRYPTION_KEY','a'.repeat(64));const id=randomUUID(),stateHash='b'.repeat(64),args={p_id:id,p_hash:stateHash};await call('begin_meta_session',args);await expect(call('consume_meta_session',args,other)).rejects.toMatchObject({code:'42501'});expect(await call('consume_meta_session',args)).toBe(company);await expect(call('consume_meta_session',args)).rejects.toMatchObject({code:'42501'});
  const selection={pages:[{id:'123',name:'Página fictícia',access_token:'fixture-page-secret',tasks:['MESSAGING'],instagram_business_account:{id:'456'}}],scopes:['instagram_basic'],userToken:'fixture-user-secret',expiresAt:null};await call('save_meta_selection',{p_id:id,p_cipher:sealChannel(company,selection)});
  const cipher=await call('read_meta_selection',{p_id:id}) as string;expect(openChannel<Row>(company,cipher)).toEqual(selection);expect(()=>openChannel(randomUUID(),cipher)).toThrow();
  const channelArgs={p_provider:'meta',p_remote:'123',p_name:'Página fictícia',p_status:'connected',p_metadata:{scopes:selection.scopes,instagramId:'456',expiresAt:null},p_cipher:sealChannel(company,{token:'fixture-page-secret',userToken:'fixture-user-secret'}),p_session:id};const saved=await call('save_company_channel',channelArgs) as Row;expect(JSON.stringify(saved)).not.toContain('secret');expect(saved.cipher).toBeUndefined();expect(await store.run(tx=>tx.get('meta_sessions',id))).toBeNull();await expect(call('read_meta_selection',{p_id:id})).rejects.toMatchObject({code:'42501'});
  await call('disconnect_company_channel',{p_provider:'meta'});expect(await store.run(tx=>tx.get('channel_secrets',saved.id))).toBeNull();
 });
 it('rejects made-up connection states and token metadata',async()=>{
  vi.stubEnv('SECRETS_ENCRYPTION_KEY','a'.repeat(64));const args={p_provider:'evolution',p_remote:'askadia-'+company,p_name:'WhatsApp',p_status:'connected',p_metadata:{connectionState:'closed'},p_cipher:sealChannel(company,{instance:'askadia-'+company})};await expect(call('save_company_channel',args)).rejects.toMatchObject({code:'22023'});await expect(call('save_company_channel',{...args,p_metadata:{connectionState:'open',token:'secret'}})).rejects.toMatchObject({code:'22023'});await expect(call('save_company_channel',{...args,p_metadata:{connectionState:'open'},p_cipher:sealChannel(randomUUID(),{instance:'askadia-'+company})})).rejects.toMatchObject({code:'22023'});
 });
 it('escalates clinical questions before using AI or a rule-based response',async()=>{expect(await draftServiceReply({...settings(),mode:'flow',rules:[{match:'dose',reply:'Unsafe fixture must not be used',handoff:false}]},{},[{id:'fixture',body:'Qual dose de medicamento devo tomar?',fromMe:false,time:null,kind:'text',status:'received'}])).toMatchObject({handoff:true,model:null});});
 it('observes opt-out without granting consent or invoking a provider',async()=>{await activate();await call('inbox_record_opt_out',{p_thread:thread},service);expect((await store.run(tx=>tx.get('contacts',contact)))?.opted_out).toBe(true);expect(await claim()).toBeNull();});
});
