import {randomUUID} from 'node:crypto';
import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {firestoreClient} from '../apps/api/src/platform/firestore/client';
import {hash} from '../apps/api/src/platform/firestore/access';
import type {Row} from '../apps/api/src/platform/firestore/store';
import {MemoryStore} from './helpers/firestore-memory';
import {CalendarController} from '../apps/api/src/onboarding/calendar-controller';
import {CompanySiteController} from '../apps/api/src/sites/controller';
import type {AuthRequest} from '../apps/api/src/identity/auth';
import {draftServiceReply} from '../apps/api/src/inbox/assistant';
import {renderSite} from '../packages/contracts/src/site';

type Client=ReturnType<typeof firestoreClient>;
type Clinic={company:string;owner:string;name:string;specialty:string;client:Client;checkout:Row};
async function value<T=Row>(request:PromiseLike<{data:unknown;error:unknown}>):Promise<T>{const response=await request;if(response.error)throw response.error;return response.data as T;}
const instant=new Date('2026-10-07T12:00:00Z');
const limits='Fixture isolada: fontes sem homologação; sem dados de pacientes ou conclusão clínica.';
const recommendation={title:'Revisão administrativa fixture',objective:'Organizar atendimento',audience:'Público agregado',steps:['Revisar regras e informações'],message:'Nossa equipe pode ajudar com horários.',requirements:['Consentimento','Revisão humana'],successMetric:'A definir'};
const recommendations={summary:'Propostas fictícias para revisão',whatsapp:[recommendation],messages:[recommendation],traffic:[recommendation],unknowns:['Nenhum canal conectado ou gasto autorizado nesta fixture']};
function research(clinic:Clinic){return {city:'São Paulo',uf:'SP',collectedAt:instant.toISOString(),ibge:{state:'unavailable',data:null,sex:[],ages:[],sourceUrl:'https://servicodados.ibge.gov.br',message:'Fixture: indisponível'},trends:{state:'unconfigured',query:clinic.specialty,geo:'BR-SP',region:'São Paulo',period:'today 3-m',rows:[],sourceUrl:'https://trends.google.com',message:'Fixture: chave não configurada'}};}
function strategy(clinic:Clinic){return {diagnosis:'Análise de marketing fixture; fontes indisponíveis reconhecidas.',positioning:clinic.name+' — comunicação administrativa de '+clinic.specialty,objectives:[{goal:'Informar serviços',metric:'Contatos administrativos',suggestedTarget:'Definir após mensuração'}],planningMonth:'2026-10',calendar:['imagem','carrossel','video'].map((format,i)=>({week:1,format,theme:clinic.specialty+' · tema '+i,brief:'Orientação administrativa fixture',needsClientVideo:format==='video'})),ads:[],keywords:Array.from({length:20},(_,i)=>clinic.specialty+' termo '+i),unknowns:['Métricas e concorrentes sem dados disponíveis na fixture']};}
function details(item:Row,clinic:Clinic){return {title:clinic.specialty+' · '+item.idea,caption:'Rascunho administrativo de '+clinic.name,cta:'Fale com a equipe',hashtags:[],designBrief:'Usar identidade confirmada da clínica fictícia.',slides:item.format==='carrossel'?[{text:'Capa',visual:'Sistema visual fixture'},{text:'Contate a equipe',visual:'Mesmo sistema visual'}]:[],videoScript:item.format==='video'?'Cliente grava vídeo sobre horários e serviços administrativos.':'',clientMaterials:item.format==='video'?['MP4 gravado pelo cliente']:[],unknowns:['Revisão responsável ainda necessária']};}

describe('complete native journey — two isolated fictitious clinics, no external APIs',()=>{
 let store:MemoryStore,server:Client,clinics:Clinic[];
 const call=(clinic:Clinic,name:string,args:Row={})=>value(clinic.client.rpc(name,{p_company_id:clinic.company,...args}));
 const journey=(clinic:Clinic)=>call(clinic,'read_marketing_journey');
 const approve=async(clinic:Clinic,stage:number)=>{const current=await journey(clinic);return call(clinic,'approve_marketing_stage',{p_stage:stage,p_basis:current.stages[stage-1].basis,p_limitations:limits});};
 const reload=(clinic:Clinic)=>{clinic.client=firestoreClient('authenticated',clinic.owner,store);return clinic;};
 const ownerRequest=(clinic:Clinic)=>({actor:{id:clinic.owner,client:clinic.client}} as unknown as AuthRequest);
 const identify=(company:string)=>{const clinic=clinics.find(c=>c.company===company);expect(clinic).toBeTruthy();return clinic!;};
 async function stored(company:string,path:string,mime:string,size=24){await store.run(async tx=>tx.put('storage_objects',hash('company-assets/'+path),{company_id:company,bucket:'company-assets',path,status:'ready',mime,size,sha256:hash('SYNTHETIC FIXTURE ONLY '+path),fixture:true}));}
 async function register(name:string,specialty:string){
  const owner=await value<string>(server.rpc('ensure_firebase_identity_server',{p_uid:'fixture-'+randomUUID(),p_email:randomUUID()+'@example.test',p_name:name}));let client=firestoreClient('authenticated',owner,store);
  const creation=await value(client.rpc('begin_company_onboarding',{p_request_id:randomUUID()})),company=creation.companyId;
  const steps:[string,Row][]=[['businessType',{value:'clinic'}],['cnpj',{value:'11222333000181'}],['address',{name,addressLine:'Rua Exemplo fictício, 10',city:'São Paulo',uf:'SP',postalCode:'01001000',businessType:'clinic'}],['specialty',{values:[specialty]}],['history',{mode:'text',text:'História administrativa fictícia; sem informações de pacientes.'}],['logo',{mode:'create',style:'Minimalista'}],['photos',{mode:'skip',attachmentIds:[]}],['website',{mode:'create'}],['confirm',{}]];
  for(const [index,[step,answer]] of steps.entries()){
   const before=await value(client.rpc('company_onboarding_read',{p_company_id:company}));await value(client.rpc('save_medical_intake',{p_company_id:company,p_request_id:randomUUID(),p_revision:before.state.revision,p_step:step,p_answer:answer}));
   if(index===1){client=firestoreClient('authenticated',owner,store);const resumed=await value(client.rpc('begin_company_onboarding',{p_request_id:randomUUID()}));expect(resumed).toMatchObject({companyId:company,resumed:true});expect((await value(client.rpc('company_onboarding_read',{p_company_id:company}))).state.revision).toBe(2);}
  }
  const clinic:Clinic={owner,company,name,specialty,client,checkout:{}};expect(await call(clinic,'company_purchase_state')).toMatchObject({aiAllowed:false,onboardingComplete:true,accessMode:'none'});
  expect((await client.rpc('request_regional_research',{p_company_id:company})).error?.code).toBe('P0402');clinic.checkout=await call(clinic,'begin_test_checkout',{p_id:randomUUID(),p_plan:'askadia_monthly'});
  expect((await client.rpc('complete_test_checkout_server',{p_company_id:company,p_id:clinic.checkout.id,p_actor:owner,p_outcome:'approved',p_accepted:true})).error?.code).toBe('42501');
  await value(server.rpc('complete_test_checkout_server',{p_company_id:company,p_id:clinic.checkout.id,p_actor:owner,p_outcome:'approved',p_accepted:true}));expect(await call(clinic,'company_purchase_state')).toMatchObject({aiAllowed:true,accessMode:'test'});return clinic;
 }
 async function prepare(clinic:Clinic){
  await call(clinic,'set_planning_preferences',{p_settings:{postsPerMonth:3,maxPostsPerWeek:3}});await call(clinic,'request_regional_research');const regional=await value(server.rpc('claim_regional_research_server'));expect(regional.companyId).toBe(clinic.company);await value(server.rpc('finish_regional_research_server',{p_id:regional.id,p_token:regional.token,p_snapshot:research(clinic)}));await approve(clinic,1);
  const job=await value(server.rpc('claim_content_preparation_server'));expect(job).toMatchObject({companyId:clinic.company,kind:'strategy'});expect(job.context.facts.name.value).toBe(clinic.name);await value(server.rpc('finish_content_preparation_server',{p_id:job.id,p_token:job.token,p_result:{output:strategy(clinic),model:'fixture-no-model-called',responseId:null,usage:null}}));await approve(clinic,2);await approve(clinic,3);
  const launch=await value(server.rpc('claim_company_launch_server'));expect(launch.companyId).toBe(clinic.company);await value(server.rpc('finish_company_launch_server',{p_id:launch.id,p_token:launch.token,p_output:recommendations}));await approve(clinic,4);
  await call(clinic,'set_traffic_preference',{p_mode:'skipped',p_basis:(await journey(clinic)).stages[4].basis});expect((await journey(clinic)).stages[4]).toMatchObject({status:'skipped',approved:true});expect(await call(clinic,'finish_company_setup')).toMatchObject({setupComplete:true});
  const saved=await call(clinic,'save_service_settings',{p_settings:{channel:'whatsapp',revision:0,mode:'ai',prompt:'Atendimento administrativo de '+clinic.name+'. Perguntas clínicas seguem para equipe.',rules:[],fallback:'A equipe responderá.',automatic:false}});
  await call(clinic,'save_service_policy',{p_policy:{revision:saved.revision,profileVersion:1,timezone:'America/Sao_Paulo',hours:[{day:3,start:480,end:1080}],reviewed:true}});expect(await call(clinic,'read_service_policy')).toMatchObject({valid:true,profileVersion:1});
 }
 async function produce(){
  let count=0;for(;count<20;count++){const job=await value<Row|null>(server.rpc('claim_content_production_server'));if(!job)break;const clinic=identify(job.companyId);let result:Row;
   if(job.kind==='details')result={items:job.context.items.map((item:Row)=>({id:item.id,details:details(item,clinic)})),model:'fixture-copy'};
   else {expect(job.context.item.company_id).toBe(clinic.company);await stored(clinic.company,clinic.company+'/generated/'+job.runId+'.png','image/png');result={mime:'image/png',model:'fixture-image'};}
   expect(await value(server.rpc('finish_content_production_server',{p_id:job.id,p_token:job.token,p_result:result}))).toMatchObject({status:'completed'});
  }expect(count).toBeLessThan(20);expect(count).toBe(8); // 2 text batches, 2 images and 4 carousel frames.
  for(const clinic of clinics){const items=await value<Row[]>(clinic.client.from('company_calendar_items').select('*').eq('company_id',clinic.company));for(const item of items){if(item.format==='video'){const upload=randomUUID(),path=clinic.company+'/final-video/'+upload+'.mp4';await stored(clinic.company,path,'video/mp4');await call(clinic,'finish_calendar_video',{p_item:item.id,p_revision:item.revision,p_upload:upload,p_size:24,p_name:'fixture-client-recorded.mp4'});}await call(clinic,'approve_calendar_item',{p_id:item.id,p_revision:item.revision});}}
 }
 async function sitesAndLogos(){
  const logos=new Map<string,string>();for(let n=0;n<3;n++){const job=await value<Row|null>(server.rpc('claim_visual_job_server'));if(!job)break;expect(job.request.kind).toBe('brand_logo');const asset=randomUUID(),path=job.companyId+'/onboarding/'+asset+'.png';await stored(job.companyId,path,'image/png');expect(await value(server.rpc('finish_visual_job_server',{p_id:job.id,p_token:job.token,p_result:{attachmentId:asset,mime:'image/png',size:24,model:'fixture-image'}}))).toBe(true);logos.set(job.companyId,asset);}expect(logos.size).toBe(2);
  for(let n=0;n<3;n++){const job=await value<Row|null>(server.rpc('claim_company_site_server'));if(!job)break;const clinic=identify(job.companyId);const content={name:clinic.name,headline:'Serviços de '+clinic.specialty,intro:'Preview privado fictício',about:'Somente informações administrativas declaradas.',services:[{title:clinic.specialty,description:'Serviço confirmado no cadastro fictício'}],address:'Rua Exemplo fictício, 10',hours:'Consultar a equipe',offer:'',whatsapp:'',cta:'Falar com a equipe',color:'#234567',background:'light',images:[],logo:logos.get(clinic.company)!};expect(await value(server.rpc('finish_company_site_server',{p_id:job.id,p_token:job.token,p_output:content}))).toBe(true);}
  expect(await value(server.rpc('claim_visual_job_server'))).toBeNull();expect(await value(server.rpc('claim_company_site_server'))).toBeNull();
 }
 beforeEach(async()=>{vi.useFakeTimers({toFake:['Date']});vi.setSystemTime(instant);vi.stubEnv('NODE_ENV','test');vi.stubEnv('DATABASE_PROVIDER','firestore');vi.stubEnv('CHECKOUT_MODE','test');vi.stubEnv('WEB_ORIGIN','https://fixture.example.test');vi.stubEnv('OPENAI_API_KEY','');vi.stubEnv('SERPAPI_API_KEY','');vi.stubGlobal('fetch',vi.fn().mockRejectedValue(new Error('External network forbidden in complete-journey fixtures')));store=new MemoryStore();server=firestoreClient('service_role',null,store);clinics=[await register('Clínica Alfa fictícia','Cardiologia'),await register('Clínica Beta fictícia','Dermatologia')];for(const clinic of clinics)await prepare(clinic);});
 afterEach(()=>{vi.useRealTimers();vi.unstubAllEnvs();vi.unstubAllGlobals();});

 it('resumes both clinics through persistent drafts, reviewed media, attendance and private site without external activation',async()=>{
  await produce();await sitesAndLogos();const calendar=new CalendarController(),sites=new CompanySiteController();for(const clinic of clinics){reload(clinic);const resumed=await value(clinic.client.rpc('begin_company_onboarding',{p_request_id:randomUUID()}));expect(resumed.companyId).toBe(clinic.company);expect(await call(clinic,'company_purchase_state')).toMatchObject({accessMode:'test',setupComplete:true});const result=await calendar.read(ownerRequest(clinic),clinic.company);expect(result.items).toHaveLength(3);expect(result.assets).toHaveLength(3);expect(result.videos).toHaveLength(1);expect(result.items.every(i=>i.status==='approved'&&i.revision===i.approved_revision)).toBe(true);expect(result.items.every(i=>i.details?.caption.includes(clinic.name))).toBe(true);expect(result.providerValidation).toBe('pending');const attendance=await call(clinic,'inbox_ai_context',{p_channel:'whatsapp'});expect(attendance.profile.history).toBeUndefined();expect(attendance.profile.name.value).toBe(clinic.name);const escalation=await draftServiceReply(attendance.settings,attendance.profile,[{id:'fixture-clinical-question',body:'Qual dose de medicamento devo tomar?',fromMe:false,time:instant.toISOString(),kind:'text',status:'received'}]);expect(escalation).toMatchObject({handoff:true,model:null});const handoff=await call(clinic,'take_inbox_conversation',{p_channel:'whatsapp',p_thread:'5511999999999@s.whatsapp.net'});expect(handoff).toMatchObject({company_id:clinic.company,actor_id:clinic.owner,released_at:null});expect((await clinic.client.rpc('reserve_inbox_dispatch',{p_company_id:clinic.company,p_thread:handoff.thread,p_id:randomUUID(),p_body:escalation.text})).error?.code).toBe('42501');const preview=await sites.read(ownerRequest(clinic),clinic.company);expect(preview.site).toMatchObject({published:null,revision:1,draft:{name:clinic.name}});expect(renderSite(preview.site!.draft!,id=>'/private-fixture/'+id)).toContain(clinic.name);expect(await value(server.rpc('read_published_site_server',{p_company_id:clinic.company}))).toBeNull();expect((await clinic.client.rpc('publish_company_site',{p_company_id:clinic.company,p_revision:1,p_publish:true})).error?.code).toBe('42501');expect((await clinic.client.rpc('save_service_settings',{p_company_id:clinic.company,p_settings:{channel:'whatsapp',revision:1,mode:'ai',prompt:'Administrativo',rules:[],fallback:'Equipe',automatic:true}})).error?.code).toBe('22023');}
  for(const table of ['company_paid_plans','company_ad_executions','company_social_publications','message_campaign_deliveries'])expect(await store.run(tx=>tx.list(table))).toEqual([]);expect(await value(server.rpc('inbox_auto_targets'))).toEqual([]);expect(fetch).not.toHaveBeenCalled();
 });

 it('denies crossed calendar/site/profile/file references and checkout resolution while preserving the other clinic',async()=>{
  await produce();await sitesAndLogos();const [a,b]=clinics,foreignCalendar=await value<Row[]>(b.client.from('company_calendar_items').select('*').eq('company_id',b.company)),foreignSite=await value<Row>(b.client.from('company_sites').select('*').eq('company_id',b.company).single());
  for(const table of ['company_calendar_items','company_creatives','onboarding_attachments','company_sites'])expect((await a.client.from(table).select('*').eq('company_id',b.company)).error?.code).toBe('42501');expect((await a.client.rpc('company_onboarding_read',{p_company_id:b.company})).error?.code).toBe('42501');expect((await a.client.rpc('approve_calendar_item',{p_company_id:a.company,p_id:foreignCalendar[0].id,p_revision:foreignCalendar[0].revision})).error?.code).toBe('40001');
  const ownSite=await value<Row>(a.client.from('company_sites').select('*').eq('company_id',a.company).single());expect((await a.client.rpc('save_company_site',{p_company_id:a.company,p_revision:1,p_profile_version:1,p_content:{...ownSite.draft,logo:foreignSite.draft.logo}})).error?.code).toBe('42501');expect(await value(a.client.from('company_sites').select('*').eq('company_id',a.company).single())).toEqual(ownSite);
  expect((await server.rpc('complete_test_checkout_server',{p_company_id:a.company,p_id:b.checkout.id,p_actor:a.owner,p_outcome:'approved',p_accepted:true})).error?.code).toBe('22023');expect(await call(b,'company_purchase_state')).toMatchObject({aiAllowed:true,setupComplete:true});expect(fetch).not.toHaveBeenCalled();
 });

 it('invalidates in-flight art/site and reviewed attendance after a progressive profile change without destroying approved history',async()=>{
  await produce();await sitesAndLogos();const [a,b]=clinics,items=await value<Row[]>(a.client.from('company_calendar_items').select('*').eq('company_id',a.company)),image=items.find(i=>i.format==='imagem')!,run=randomUUID();await call(a,'start_content_run',{p_request_id:run,p_kind:'design',p_item_id:image.id,p_frame:0});const siteJob=await call(a,'enqueue_company_site',{p_id:randomUUID(),p_revision:1,p_profile_version:1,p_feedback:'Atualizar apenas preview privado'}),claimed=await value(server.rpc('claim_company_site_server'));expect(claimed.id).toBe(siteJob.id);
  const baseline=await value<Row[]>(a.client.from('company_calendar_approvals').select('*').eq('company_id',a.company)),before=await call(a,'company_onboarding_read');await call(a,'save_company_marketing_facts',{p_request_id:randomUUID(),p_revision:before.state.revision,p_facts:{hours:{status:'provided',value:'Segunda a sexta, 08h às 18h'}}});
  expect(await call(a,'company_purchase_state')).toMatchObject({aiAllowed:true,setupComplete:false});expect((await journey(a)).stages.every((stage:Row)=>!stage.approved)).toBe(true);expect(await call(a,'read_service_policy')).toMatchObject({valid:false,profileVersion:2});expect(await call(a,'finish_content_design',{p_request_id:run,p_mime:'image/png',p_model:'late-fixture'})).toEqual({status:'stale'});expect(await value(server.rpc('finish_company_site_server',{p_id:claimed.id,p_token:claimed.token,p_output:{}}))).toBe(false);expect(await value(a.client.from('company_calendar_approvals').select('*').eq('company_id',a.company))).toEqual(baseline);expect(await value(a.client.from('company_calendar_items').select('*').eq('company_id',a.company))).toEqual(items);expect(await call(b,'company_purchase_state')).toMatchObject({setupComplete:true});expect(await call(b,'read_service_policy')).toMatchObject({valid:true});expect(fetch).not.toHaveBeenCalled();
 });

 it('keeps checkout retries from extending access or restarting another clinic’s approved work',async()=>{
  const [a,b]=clinics,grant=await store.run(tx=>tx.get('company_test_access',a.company)),approved=await journey(b);vi.setSystemTime(new Date(Date.now()+61000));const args={p_company_id:a.company,p_id:a.checkout.id,p_actor:a.owner,p_outcome:'approved',p_accepted:true};const first=await value(server.rpc('complete_test_checkout_server',args)),again=await value(server.rpc('complete_test_checkout_server',args));expect(again).toEqual(first);expect(await store.run(tx=>tx.get('company_test_access',a.company))).toEqual(grant);
  for(const outcome of ['declined','cancelled'])expect((await server.rpc('complete_test_checkout_server',{...args,p_outcome:outcome})).error?.code).toBe('22023');expect(await call(a,'company_purchase_state')).toMatchObject({accessMode:'test',setupComplete:true});expect(await journey(b)).toEqual(approved);
  server=firestoreClient('service_role',null,store);const jobs=await Promise.all([value<Row|null>(server.rpc('claim_content_production_server')),value<Row|null>(server.rpc('claim_content_production_server'))]);expect(jobs.every(Boolean)).toBe(true);expect(new Set(jobs.map(j=>j!.companyId))).toEqual(new Set(clinics.map(c=>c.company)));expect(new Set(jobs.map(j=>j!.runId)).size).toBe(2);expect(await value(server.rpc('claim_content_production_server'))).toBeNull();expect(fetch).not.toHaveBeenCalled();
 });

 it('drops unpaid production and site results for one clinic while completing independent work for the other',async()=>{
  const art=await value(server.rpc('claim_content_production_server')),site=await value(server.rpc('claim_company_site_server')),a=identify(art.companyId),other=clinics.find(c=>c.company!==a.company)!;expect(site.companyId).toBe(a.company);await store.run(async tx=>{const grant=await tx.get('company_test_access',a.company);tx.put('company_test_access',a.company,{...grant,valid_until:new Date(0).toISOString()});});expect(await call(a,'company_purchase_state')).toMatchObject({aiAllowed:false,accessMode:'none'});
  expect(await value(server.rpc('finish_content_production_server',{p_id:art.id,p_token:art.token,p_result:{items:art.context.items.map((item:Row)=>({id:item.id,details:details(item,a)})),model:'late-fixture'}}))).toBe(false);expect(await value(server.rpc('finish_company_site_server',{p_id:site.id,p_token:site.token,p_output:{}}))).toBe(false);
  const independent=await value(server.rpc('claim_content_production_server'));expect(independent.companyId).toBe(other.company);expect(await value(server.rpc('finish_content_production_server',{p_id:independent.id,p_token:independent.token,p_result:{items:independent.context.items.map((item:Row)=>({id:item.id,details:details(item,other)})),model:'fixture-copy'}}))).toEqual({status:'completed'});expect(await call(other,'company_purchase_state')).toMatchObject({aiAllowed:true,setupComplete:true});expect((await value<Row[]>(a.client.from('company_calendar_items').select('*').eq('company_id',a.company))).every(i=>i.details===null)).toBe(true);expect(fetch).not.toHaveBeenCalled();
 });
});
