import {beforeEach,describe,expect,it} from 'vitest';
import {randomUUID} from 'node:crypto';
import {firestoreClient} from '../apps/api/src/platform/firestore/client';
import {DashboardController} from '../apps/api/src/dashboard/controller';
import type {AuthRequest} from '../apps/api/src/identity/auth';
import type {Row} from '../apps/api/src/platform/firestore/store';
import {MemoryStore} from './helpers/firestore-memory';

describe('native Firestore dashboard',()=>{
 let store:MemoryStore,company:string,workspace:string,owner:string,marketing:string,admin:string,attendant:string,other:string;
 const web=(id='web-1')=>({kind:'web',id,date:'2026-10-01',provider:'ga4',resource:'site',metric:'sessions',value:7,timezone:'America/Sao_Paulo',coverage:'complete'});
 const payment=()=>({kind:'payment',id:'payment-1',date:'2026-10-01',customerId:'anonymous-source-key',netCents:10000,variableCostCents:null,acquisitionDate:'2026-10-01',customerHistoryKnown:true,customerPreexisting:false,channel:'organic',campaignId:'',evidence:'Manual source',classification:'acquisition'});
 const document=(records:Row[]=[web()],domain='digital')=>({source:'Fixture CSV',domain,coverageStart:'2026-10-01',coverageEnd:'2026-10-07',coverage:'complete',note:'Declared fixture coverage',records});
 async function call(name:string,args:Row={},actor=owner){const r=await firestoreClient('authenticated',actor,store).rpc(name,{p_company_id:company,...args});if(r.error)throw r.error;return r.data as Row;}
 beforeEach(async()=>{store=new MemoryStore();[company,workspace,owner,marketing,admin,attendant,other]=Array.from({length:7},()=>randomUUID());await store.run(async tx=>{tx.put('companies',company,{id:company,workspace_id:workspace,name:'Fixture clinic',city:'São Paulo',segment:'Clínica',timezone:'America/Sao_Paulo',archived_at:null,private_secret:'hidden'});tx.put('workspace_members',workspace+'_'+owner,{workspace_id:workspace,user_id:owner,role:'owner'});for(const [user_id,role] of [[marketing,'marketing'],[admin,'admin'],[attendant,'attendant']])tx.put('company_members',company+'_'+user_id,{company_id:company,user_id,role});});});
 it('returns exact empty sources and lets the actual controller keep financial metrics unavailable',async()=>{const raw=await call('dashboard_read');expect(raw).toEqual({company:{id:company,name:'Fixture clinic',city:'São Paulo',segment:'Clínica',timezone:'America/Sao_Paulo'},keywordProfile:null,facts:[],coverage:[],crm:[],permissions:{digital:true,finance:true,writeDigital:true,writeFinance:true}});const req={actor:{client:firestoreClient('authenticated',owner,store)}} as AuthRequest;const snapshot=await new DashboardController().read(req,{companyId:company,start:'2026-10-01',end:'2026-10-07',timezone:'America/Sao_Paulo',comparison:'none'});expect(snapshot.metrics.find(m=>m.id==='cac')?.value).toBeNull();expect(snapshot.series).toEqual([]);});
 it('keeps marketing and manager financial access separate, and redacts CRM identity fields',async()=>{await call('dashboard_import',{p_document:document()});await call('dashboard_import',{p_document:document([payment()],'finance')});await store.run(async tx=>{tx.put('opportunities','opp',{id:'opp',company_id:company,contact_id:'contact',created_at:'2026-10-01T12:00:00Z',stage:'new',original_source:'manual',name:'PRIVATE',phone:'PRIVATE',email:'PRIVATE',interest:'PRIVATE'});});const m=await call('dashboard_read',{},marketing);expect(m.facts).toHaveLength(1);expect(m.coverage).toHaveLength(1);expect(m.crm).toBeNull();expect(m.permissions).toEqual({digital:true,finance:false,writeDigital:true,writeFinance:false});expect((await call('dashboard_read',{},admin)).permissions.finance).toBe(false);expect(JSON.stringify((await call('dashboard_read')).crm)).not.toContain('PRIVATE');await expect(call('dashboard_import',{p_document:document([payment()],'finance')},marketing)).rejects.toMatchObject({code:'42501'});await expect(call('dashboard_read',{},attendant)).rejects.toMatchObject({code:'42501'});await expect(call('dashboard_read',{},other)).rejects.toMatchObject({code:'42501'});});
 it('revalidates membership before using retained finance and delegated marketing grants',async()=>{await store.run(async tx=>{tx.put('dashboard_permissions',company+'_'+marketing,{company_id:company,user_id:marketing,financial_details:true,manage_costs:true});});expect((await call('dashboard_read',{},marketing)).permissions.writeFinance).toBe(true);await store.run(async tx=>tx.remove('company_members',company+'_'+marketing));await expect(call('dashboard_read',{},marketing)).rejects.toMatchObject({code:'42501'});});
 it('deduplicates canonical imports and versions altered facts without duplicating unchanged records',async()=>{const first=await call('dashboard_import',{p_document:document()});expect(first).toMatchObject({id:expect.any(String),written:1,duplicate:false});expect(await call('dashboard_import',{p_document:document()})).toEqual({...first,written:0,duplicate:true});expect(await call('dashboard_import',{p_document:document([{...web(),value:9}])})).toMatchObject({written:1,duplicate:false});expect((await call('dashboard_read')).facts).toMatchObject([{revision:2,payload:{value:9}}]);expect(await store.run(tx=>tx.list('dashboard_fact_revisions'))).toHaveLength(2);await expect(call('dashboard_import',{p_document:document()},other)).rejects.toMatchObject({code:'42501'});});
 it('validates every record atomically and rejects duplicate keys, unknown fields and mixed domains',async()=>{for(const records of [[web(),{...web('bad'),value:-1}],[web(),web()],[{...web(),phone:'secret'}],[web(),payment()]])await expect(call('dashboard_import',{p_document:document(records)})).rejects.toMatchObject({code:'22023'});for(const table of ['dashboard_imports','dashboard_facts','dashboard_fact_revisions','audit_logs'])expect(await store.run(tx=>tx.list(table))).toEqual([]);});
 it('rolls back staged facts, revisions, batch and audit on a storage write failure',async()=>{const original=store.run.bind(store);store.run=operation=>original(tx=>operation({...tx,put:(table,id,row)=>{if(table==='dashboard_fact_revisions')throw new Error('fixture write failure');tx.put(table,id,row);}}));await expect(call('dashboard_import',{p_document:document()})).rejects.toMatchObject({message:'fixture write failure'});for(const table of ['dashboard_imports','dashboard_facts','dashboard_fact_revisions','audit_logs'])expect(await original(tx=>tx.list(table))).toEqual([]);});
 it('preserves the contract limit for large valid fact batches',async()=>{expect(await call('dashboard_import',{p_document:document(Array.from({length:1000},(_,i)=>web('key-'+i)))})).toMatchObject({written:1000});expect(await store.run(tx=>tx.list('dashboard_facts'))).toHaveLength(1000);});
 it('versions confirmed keywords without synthesizing measured trends',async()=>{expect(await call('dashboard_set_keywords',{p_services:['pilates'],p_neighborhood:'Centro'},marketing)).toBeNull();await call('dashboard_set_keywords',{p_services:['pilates','funcional'],p_neighborhood:'Centro'},marketing);const raw=await call('dashboard_read',{},marketing);expect(raw.keywordProfile).toMatchObject({services:['pilates','funcional'],revision:2});expect(raw.facts).toEqual([]);await expect(call('dashboard_set_keywords',{p_services:['invented'],p_neighborhood:''})).rejects.toMatchObject({code:'22023'});});
 it('records financial exports only in the authorized company',async()=>{const args={p_filters:{companyId:company},p_snapshot:{company:{id:company},metrics:[]},p_method:'fixture-method'};const id=await call('dashboard_record_export',args);expect(await store.run(tx=>tx.get('dashboard_exports',String(id)))).toMatchObject({company_id:company,actor_id:owner,method_version:'fixture-method',snapshot:args.p_snapshot});await expect(call('dashboard_record_export',args,marketing)).rejects.toMatchObject({code:'42501'});await expect(call('dashboard_record_export',{...args,p_snapshot:{company:{id:randomUUID()}}})).rejects.toMatchObject({code:'22023'});expect(await store.run(tx=>tx.list('dashboard_exports'))).toHaveLength(1);});
 it('isolates source keys and coverage by destination company',async()=>{const second=randomUUID();await store.run(async tx=>tx.put('companies',second,{id:second,workspace_id:workspace,archived_at:null}));await call('dashboard_import',{p_document:document()});await call('dashboard_import',{p_company_id:second,p_document:document()});expect(await store.run(tx=>tx.list('dashboard_facts'))).toHaveLength(2);expect((await call('dashboard_read')).facts).toHaveLength(1);});
 it('grants internal read scopes only and revalidates staff, session and assignment',async()=>{const staff=randomUUID(),session=randomUUID(),assignment=randomUUID();await call('dashboard_import',{p_document:document([payment()],'finance')});await store.run(async tx=>{tx.put('platform_staff',staff,{user_id:staff,active:true,role:'support'});tx.put('company_assignments',assignment,{company_id:company,staff_id:staff});tx.put('internal_access_sessions',session,{id:session,company_id:company,operator_id:staff,ended_at:null,expires_at:new Date(Date.now()+60000).toISOString()});});const args={p_internal_session:session};const support=await call('dashboard_read',args,staff);expect(support.permissions).toEqual({digital:true,finance:false,writeDigital:false,writeFinance:false});expect(support.crm).toBeNull();expect(support.facts).toEqual([]);await expect(call('dashboard_import',{...args,p_document:document()},staff)).rejects.toMatchObject({code:'42501'});await expect(call('dashboard_read',args,other)).rejects.toMatchObject({code:'42501'});await store.run(async tx=>tx.remove('company_assignments',assignment));await expect(call('dashboard_read',args,staff)).rejects.toMatchObject({code:'42501'});await store.run(async tx=>tx.put('platform_staff',staff,{user_id:staff,active:true,role:'platform_admin'}));expect((await call('dashboard_read',args,staff)).permissions).toEqual({digital:true,finance:true,writeDigital:false,writeFinance:false});expect((await call('dashboard_read',args,staff)).facts).toHaveLength(1);await call('dashboard_record_export',{...args,p_filters:{companyId:company},p_snapshot:{company:{id:company}},p_method:'fixture'},staff);await store.run(async tx=>{const row=await tx.get('internal_access_sessions',session);tx.put('internal_access_sessions',session,{...row,company_id:randomUUID()});});await expect(call('dashboard_read',args,staff)).rejects.toMatchObject({code:'42501'});await store.run(async tx=>{const row=await tx.get('internal_access_sessions',session);tx.put('internal_access_sessions',session,{...row,company_id:company,expires_at:new Date(Date.now()-1000).toISOString()});});await expect(call('dashboard_read',args,staff)).rejects.toMatchObject({code:'42501'});await store.run(async tx=>{const row=await tx.get('internal_access_sessions',session);tx.put('internal_access_sessions',session,{...row,expires_at:new Date(Date.now()+60000).toISOString(),ended_at:new Date().toISOString()});});await expect(call('dashboard_read',args,staff)).rejects.toMatchObject({code:'42501'});await store.run(async tx=>{const row=await tx.get('internal_access_sessions',session);tx.put('internal_access_sessions',session,{...row,ended_at:null});tx.put('platform_staff',staff,{user_id:staff,active:false,role:'platform_admin'});});await expect(call('dashboard_read',args,staff)).rejects.toMatchObject({code:'42501'});expect(await store.run(tx=>tx.get('company_members',company+'_'+staff))).toBeNull();});

 it('does not let an owner attribute an export to another operator or expired internal session',async()=>{const session=randomUUID();await store.run(async tx=>tx.put('internal_access_sessions',session,{id:session,company_id:company,operator_id:other,expires_at:new Date(Date.now()+60000).toISOString(),ended_at:null}));const args={p_filters:{companyId:company},p_snapshot:{company:{id:company}},p_method:'fixture',p_internal_session:session};await expect(call('dashboard_record_export',args)).rejects.toMatchObject({code:'42501'});await store.run(async tx=>{tx.put('platform_staff',owner,{user_id:owner,role:'platform_admin',active:true});const row=await tx.get('internal_access_sessions',session);tx.put('internal_access_sessions',session,{...row,operator_id:owner,expires_at:new Date(Date.now()-1000).toISOString()});});await expect(call('dashboard_record_export',args)).rejects.toMatchObject({code:'42501'});expect(await store.run(tx=>tx.list('dashboard_exports'))).toEqual([]);});

});
