import {randomUUID} from 'node:crypto';
import {beforeEach,describe,it,expect,vi} from 'vitest';
import {MemoryStore} from './helpers/firestore-memory';
import type {Row} from '../apps/api/src/platform/firestore/store';
import type {FirestoreActor} from '../apps/api/src/platform/firestore/access';
import {hash} from '../apps/api/src/platform/firestore/access';
const fixture=vi.hoisted(()=>({valid:true,skipped:false}));
vi.mock('../apps/api/src/platform/firestore/journey-state',async()=>{const original=await vi.importActual<typeof import('../apps/api/src/platform/firestore/journey-state')>('../apps/api/src/platform/firestore/journey-state');return {...original,context:async()=>({confirmed:true,version:1,traffic:{mode:fixture.skipped?'skipped':'planned'},approvals:[{stage:5,token:'fixture'}],facts:{},recommendations:null}),stages:()=>Array.from({length:5},()=>({approved:fixture.valid}))};});
import {advertisingRpc} from '../apps/api/src/platform/firestore/advertising';
// Local fixtures only: neither AI nor advertising providers are called.
describe('native advertising transaction lifecycle',()=>{
 let store:MemoryStore,company:string,owner:string,outsider:string,plan:string,execution:string;
 const service:FirestoreActor={role:'service_role',id:null};
 const call=(name:string,args:Row={},actor:FirestoreActor=service)=>store.run(tx=>advertisingRpc(tx,actor,name,args));
 const customer=()=>({role:'authenticated' as const,id:owner});
 const spec=()=>({name:'Fixture campaign',format:'google_search',accountId:'1234567890',accountName:'Fixture account',pageId:null,currency:'BRL',budgetCents:10000,startsAt:new Date(Date.now()+86400000).toISOString(),endsAt:new Date(Date.now()+5*86400000).toISOString(),timezone:'America/Sao_Paulo',destination:'https://fixture.example.com',location:{latitude:-23,longitude:-46,label:'Fixture city',placeId:'fixture'},copy:{headline:'Fixture headline',text:'Fixture administrative text',headlines:['Fixture one','Fixture two','Fixture three'],descriptions:['Fixture description one','Fixture description two'],keywords:['fixture one','fixture two','fixture three'],radiusKm:5,maxCpcCents:100},imageId:null,imageSha256:null,siteRevision:null});
 beforeEach(async()=>{fixture.valid=true;fixture.skipped=false;store=new MemoryStore();company=randomUUID();owner=randomUUID();outsider=randomUUID();plan=randomUUID();execution=randomUUID();await store.run(async tx=>{const workspace=randomUUID();tx.put('companies',company,{id:company,workspace_id:workspace});tx.put('workspace_members',workspace+'_'+owner,{role:'owner'});tx.put('company_subscriptions',company,{company_id:company,status:'active',plan_id:'fixture',current_period_end:new Date(Date.now()+86400000).toISOString()});tx.put('company_paid_plans',plan,{id:plan,company_id:company,profile_version:1,actor_id:owner,budget:100,days:4,status:'ready',output:{campaigns:[{provider:'google',investment:100}]}});tx.put('company_ad_connections',company+'_google',{company_id:company,provider:'google',account_id:'1234567890',name:'Fixture',status:'connected'});tx.put('company_ad_executions',execution,{id:execution,company_id:company,plan_id:plan,campaign_index:0,provider:'google',actor_id:owner,profile_version:1,revision:1,spec:spec(),status:'draft',desired:'run',remote:{},approved_revision:null,lease_token:null,lease_until:null,attempts:0,copy_attempts:0,next_attempt_at:new Date().toISOString()});});});
 const approve=()=>call('approve_ad_execution',{p_company_id:company,p_id:execution,p_revision:1},customer());
 it('denies cross tenant access and service RPC impersonation',async()=>{await expect(call('approve_ad_execution',{p_company_id:company,p_id:execution,p_revision:1},{role:'authenticated',id:outsider})).rejects.toMatchObject({code:'42501'});await expect(call('claim_ad_execution_server',{},customer())).rejects.toMatchObject({code:'42501'});});
 it('skipping traffic produces no seed, proposal, or execution lease',async()=>{fixture.skipped=true;expect(await call('claim_ad_plan_seed_server')).toBeNull();await expect(call('begin_paid_plan',{p_company_id:company,p_id:randomUUID(),p_budget:100,p_days:30},customer())).rejects.toMatchObject({code:'40001'});await expect(approve()).rejects.toMatchObject({code:'40001'});expect(await call('claim_ad_execution_server')).toBeNull();});
 it('approval requires campaign ceiling, matching account, and current strategy',async()=>{await store.run(async tx=>{const e=(await tx.get('company_ad_executions',execution))!;tx.put('company_ad_executions',execution,{...e,spec:{...e.spec,budgetCents:10001}});});await expect(approve()).rejects.toMatchObject({code:'22023'});});
 it('serializes leases and reconciles an interrupted provider step without duplication',async()=>{await approve();const [first,second]=await Promise.all([call('claim_ad_execution_server'),call('claim_ad_execution_server')]) as [Row,Row|null];expect(first.action).toBe('provision');expect(second).toBeNull();const args={p_id:execution,p_token:first.lease_token,p_step:'google',p_hash:hash({fixture:true})};expect(await call('ad_step_server',args)).toEqual({status:'execute'});expect(await call('ad_step_server',args)).toEqual({status:'reconcile'});await expect(call('ad_step_server',{...args,p_hash:hash({fixture:false})})).rejects.toMatchObject({code:'40001'});expect(await call('ad_step_server',{...args,p_result:'customers/123/campaigns/456'})).toEqual({status:'saved'});expect(await call('ad_step_server',args)).toEqual({status:'done',id:'customers/123/campaigns/456'});});
 it('revocation during execution queues compensating pause and rejects activation',async()=>{await approve();const job=await call('claim_ad_execution_server') as Row;await call('control_ad_execution',{p_company_id:company,p_id:execution,p_revision:1,p_action:'pause'},customer());expect(await call('ad_execution_guard_server',{p_id:execution,p_token:job.lease_token})).toBe(false);expect(await call('finish_ad_execution_server',{p_id:execution,p_token:job.lease_token,p_result:{status:'scheduled',complete:true}})).toBe(false);const stop=await call('claim_ad_execution_server') as Row;expect(stop.action).toBe('stop');await call('finish_ad_execution_server',{p_id:execution,p_token:stop.lease_token,p_result:{status:'paused'}});expect(await call('claim_ad_execution_server')).toBeNull();});
 it('expired leases cannot persist external effects and are recoverable',async()=>{await approve();const job=await call('claim_ad_execution_server') as Row;await store.run(async tx=>{const e=(await tx.get('company_ad_executions',execution))!;tx.put('company_ad_executions',execution,{...e,lease_until:new Date(Date.now()-1).toISOString()});});expect(await call('ad_execution_guard_server',{p_id:execution,p_token:job.lease_token})).toBe(false);const recovered=await call('claim_ad_execution_server') as Row;expect(recovered.lease_token).not.toBe(job.lease_token);await expect(call('ad_step_server',{p_id:execution,p_token:job.lease_token,p_step:'google',p_hash:hash({})})).rejects.toMatchObject({code:'40001'});});
 it('edits invalidate approval and retain server owned references',async()=>{await approve();const e=await store.run(tx=>tx.get('company_ad_executions',execution));await expect(call('edit_ad_execution',{p_company_id:company,p_id:execution,p_revision:1,p_spec:{...e!.spec,location:{...e!.spec.location,latitude:0}}},customer())).rejects.toMatchObject({code:'22023'});await call('edit_ad_execution',{p_company_id:company,p_id:execution,p_revision:1,p_spec:{...e!.spec,name:'Revised fixture'}},customer());const edited=await store.run(tx=>tx.get('company_ad_executions',execution));expect(edited).toMatchObject({revision:2,status:'draft',approved_revision:null});});
 it('stores advertising secrets outside client readable connection rows',async()=>{await call('ad_credentials_server',{p_company_id:company,p_actor:owner,p_provider:'google',p_write:{status:'connected',accountId:'1234567890',cipher:'encrypted-fixture'}});const connection=await store.run(tx=>tx.get('company_ad_connections',company+'_google'));expect(connection).not.toHaveProperty('cipher');const returned=await call('ad_credentials_server',{p_company_id:company,p_actor:owner,p_provider:'google'}) as Row;expect(returned.cipher).toBe('encrypted-fixture');await call('ad_credentials_server',{p_company_id:company,p_actor:owner,p_provider:'google',p_write:{status:'disconnected'}});expect(await store.run(tx=>tx.get('ad_credentials',company+'_google'))).toBeNull();});
 it('queues review drafts only once after a validated proposal completes',async()=>{const id=randomUUID(),args={p_company_id:company,p_id:id,p_budget:100,p_days:30};await call('begin_paid_plan',args,customer());const output={summary:'Fixture',campaigns:[{name:'Fixture',provider:'google',objective:'Traffic',investment:100,audience:'Adults',region:'Fixture city',media:['search'],creativeBrief:'Fixture',copy:'Fixture',rationale:'Fixture'}],unknowns:[]};const finish={p_company_id:company,p_actor:owner,p_id:id,p_output:output,p_model:'fixture'};await call('finish_paid_plan_server',finish);await call('finish_paid_plan_server',finish);const rows=await store.run(tx=>tx.list('company_ad_executions',[{field:'plan_id',value:id}]));expect(rows).toHaveLength(1);expect(rows[0]).toMatchObject({status:'preparing',approved_revision:null,spec:null});});
 it('requires a tenant owned Meta asset and rejects changed asset hashes',async()=>{const image=randomUUID(),imageHash='a'.repeat(64);await store.run(async tx=>{const e=(await tx.get('company_ad_executions',execution))!;tx.put('company_ad_connections',company+'_meta',{company_id:company,provider:'meta',account_id:'act_1234567890',source_page:'12345',status:'connected'});tx.put('company_ad_executions',execution,{...e,provider:'meta',spec:{...e.spec,format:'meta_traffic_image',accountId:'act_1234567890',pageId:'12345',imageId:image,imageSha256:imageHash}});tx.put('onboarding_attachments',image,{id:image,company_id:outsider,mime:'image/png',object_path:outsider+'/image.png',sha256:imageHash});});await expect(approve()).rejects.toMatchObject({code:'22023'});await store.run(async tx=>tx.put('onboarding_attachments',image,{id:image,company_id:company,mime:'image/png',object_path:company+'/image.png',sha256:'b'.repeat(64)}));await expect(approve()).rejects.toMatchObject({code:'40001'});});
 it('invalidates approved work after strategy revocation instead of provisioning',async()=>{await approve();fixture.valid=false;const job=await call('claim_ad_execution_server') as Row;expect(job.action).toBe('invalidate');expect(await call('ad_execution_guard_server',{p_id:execution,p_token:job.lease_token})).toBe(false);});

 it('requires delegated approval limits for the total plan budget',async()=>{const approver=randomUUID();await store.run(async tx=>{tx.put('company_members',company+'_'+approver,{company_id:company,user_id:approver,role:'reader'});tx.put('company_permission_grants','fixture',{company_id:company,user_id:approver,action:'ads.approve',budget_limit_cents:9999});});const args={p_company_id:company,p_id:execution,p_revision:1},actor:FirestoreActor={role:'authenticated',id:approver};await expect(call('approve_ad_execution',args,actor)).rejects.toMatchObject({code:'42501'});await store.run(async tx=>tx.put('company_permission_grants','fixture',{company_id:company,user_id:approver,action:'ads.approve',budget_limit_cents:10000}));await call('approve_ad_execution',args,actor);await store.run(async tx=>tx.remove('company_members',company+'_'+approver));expect((await call('claim_ad_execution_server') as Row).action).toBe('invalidate');});
 it('rejects an unpublished destination revision and unsubscribed proposal generation',async()=>{await store.run(async tx=>{const e=(await tx.get('company_ad_executions',execution))!;tx.put('company_ad_executions',execution,{...e,spec:{...e.spec,siteRevision:1}});});await expect(approve()).rejects.toMatchObject({code:'40001'});await store.run(async tx=>tx.remove('company_subscriptions',company));await expect(call('begin_paid_plan',{p_company_id:company,p_id:randomUUID(),p_budget:100,p_days:30},customer())).rejects.toMatchObject({code:'42501'});});

});
