import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
vi.mock('../apps/api/src/platform/firebase-auth',()=>({verifyFirebaseActor:vi.fn()}));
const fixture=vi.hoisted(()=>({rpc:vi.fn(),from:vi.fn(),select:vi.fn(),eq:vi.fn(),in:vi.fn(),generate:vi.fn()}));
vi.mock('../apps/api/src/campaigns/ads',()=>({serviceDb:()=>({rpc:fixture.rpc,from:fixture.from}),adsAccess:vi.fn()}));
vi.mock('../apps/api/src/sites/generation',()=>({generateSite:fixture.generate}));
import {LaunchPreparation} from '../apps/api/src/onboarding/launch';
const materials=[{id:'fixture-image',mime:'image/png',name:'Foto fixture'}],output={name:'Fixture clinic'},previous={name:'Previous draft'};
const job={id:'fixture-job',companyId:'fixture-company',token:'fixture-token',kind:'site',facts:{name:'Fixture clinic'},previous,feedback:'Revisar contato'};
const run=async()=>{const worker=new LaunchPreparation();worker.onModuleDestroy();await (worker as unknown as {tick():Promise<void>}).tick();};
beforeEach(()=>{vi.clearAllMocks();for(const [key,value] of Object.entries({DATABASE_PROVIDER:'firestore',FIREBASE_PROJECT_ID:'fixture-project',OPENAI_API_KEY:'fixture-key',OPENAI_MODEL_ORCHESTRATOR:'fixture-orchestrator',OPENAI_MODEL_SITE:'fixture-site',CONTENT_AUTOPREP_ENABLED:'true',SUPABASE_URL:'https://fixture.test',SUPABASE_SERVICE_ROLE_KEY:'fixture-key'}))vi.stubEnv(key,value);fixture.rpc.mockImplementation(async(name:string)=>({data:name==='claim_company_site_server'?job:null,error:null}));fixture.from.mockReturnValue({select:fixture.select});fixture.select.mockReturnValue({eq:fixture.eq});fixture.eq.mockReturnValue({in:fixture.in});fixture.in.mockResolvedValue({data:materials,error:null});fixture.generate.mockResolvedValue(output);});
afterEach(()=>vi.unstubAllEnvs());
describe('native site executor — generation fixtures only',()=>{
 it('claims the dedicated site queue, scopes materials and saves through its dedicated finish operation',async()=>{await run();expect(fixture.rpc.mock.calls.slice(0,2).map(([name])=>name)).toEqual(['claim_company_launch_server','claim_company_site_server']);expect(fixture.from).toHaveBeenCalledWith('onboarding_attachments');expect(fixture.eq).toHaveBeenCalledWith('company_id',job.companyId);expect(fixture.generate).toHaveBeenCalledWith(job.facts,materials,previous,job.feedback);expect(fixture.rpc).toHaveBeenLastCalledWith('finish_company_site_server',{p_id:job.id,p_token:job.token,p_output:output});expect(fixture.rpc.mock.calls.some(([name])=>name==='finish_company_launch_server')).toBe(false);});
 it('routes provider failures to the dedicated site failure operation for retry and draft preservation',async()=>{fixture.generate.mockRejectedValue(new Error('Fixture provider timeout'));await run();expect(fixture.rpc).toHaveBeenLastCalledWith('finish_company_site_server',{p_id:job.id,p_token:job.token,p_output:null});});
 it('routes scoped material-read failures to the site operation without invoking the provider',async()=>{fixture.in.mockResolvedValue({data:null,error:{code:'42501',message:'Access revoked'}});await run();expect(fixture.generate).not.toHaveBeenCalled();expect(fixture.rpc).toHaveBeenLastCalledWith('finish_company_site_server',{p_id:job.id,p_token:job.token,p_output:null});});
 it('retains the legacy site queue and its finish operation without claiming the native fallback',async()=>{vi.stubEnv('DATABASE_PROVIDER','supabase');fixture.rpc.mockImplementation(async(name:string)=>({data:name==='claim_company_launch_server'?job:null,error:null}));await run();expect(fixture.rpc).toHaveBeenLastCalledWith('finish_company_launch_server',{p_id:job.id,p_token:job.token,p_output:output});expect(fixture.rpc.mock.calls.some(([name])=>name==='claim_company_site_server')).toBe(false);});
 it('does not double claim native sites while an existing launch task owns the executor',async()=>{fixture.rpc.mockImplementation(async(name:string)=>({data:name==='claim_company_launch_server'?job:null,error:null}));await run();expect(fixture.rpc.mock.calls.some(([name])=>name==='claim_company_site_server')).toBe(false);expect(fixture.rpc).toHaveBeenLastCalledWith('finish_company_launch_server',expect.objectContaining({p_output:output}));});
 it('does no provider work when both native queues are empty',async()=>{fixture.rpc.mockResolvedValue({data:null,error:null});await run();expect(fixture.rpc).toHaveBeenCalledTimes(2);expect(fixture.from).not.toHaveBeenCalled();expect(fixture.generate).not.toHaveBeenCalled();});
});
