import {randomUUID} from 'node:crypto';
import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {MemoryStore} from './helpers/firestore-memory';
import {firestoreClient} from '../apps/api/src/platform/firestore/client';
import {hash} from '../apps/api/src/platform/firestore/access';
import type {DocumentStore,Row} from '../apps/api/src/platform/firestore/store';

const description={description:'Imagem de referência para a clínica.',category:'space',orientation:'landscape',colors:[],visibleText:'',recommendedUse:'Referência visual',alt:'Sala de referência'};
describe('Firestore image descriptions — MemoryStore simulation, no providers',()=>{
 let store:MemoryStore,company:string,owner:string,id:string,path:string;
 const call=async(name:string,args:Row={})=>{const result=await firestoreClient('service_role',null,store).rpc(name,args);if(result.error)throw result.error;return result.data;};
 const finish=(token:string,args:Row={})=>call('finish_image_description_server',{p_company_id:company,p_id:id,p_token:token,p_description:description,p_model:'fixture',...args});
 const attachment=()=>store.run(tx=>tx.get('onboarding_attachments',id));
 beforeEach(async()=>{vi.useFakeTimers({toFake:['Date']});vi.setSystemTime(new Date('2026-10-07T12:00:00Z'));store=new MemoryStore();company=randomUUID();owner=randomUUID();id=randomUUID();path=company+'/onboarding/'+id+'.png';const workspace=randomUUID();await store.run(async tx=>{tx.put('companies',company,{id:company,workspace_id:workspace});tx.put('workspace_members',workspace+'_'+owner,{role:'owner'});tx.put('onboarding_attachments',id,{id,company_id:company,mime:'image/png',size:8,object_path:path,uploaded_by:owner,description_status:'pending',description_attempts:0,created_at:new Date().toISOString()});tx.put('storage_objects',hash('company-assets/'+path),{company_id:company,mime:'image/png',size:8,status:'ready',sha256:'fixture-digest'});});});
 afterEach(()=>vi.useRealTimers());
 it.each(['ready','failed'])('claims pending work past 1001 terminal %s images without scanning completed history',async(status)=>{
  await store.run(async tx=>{for(let n=0;n<1001;n++){const ready=randomUUID();tx.put('onboarding_attachments',ready,{id:ready,company_id:company,mime:'image/png',description_status:status,description_attempts:3,created_at:new Date().toISOString()});}});
  // Simulate the native store's query bound while preserving real domain code.
  const bounded:DocumentStore={run:operation=>store.run(tx=>operation({...tx,list:async(collection,filters)=>{const rows=await tx.list(collection,filters);if(rows.length>1000)throw new Error('Use a narrower Firestore query');return rows;}}))};
  const client=firestoreClient('service_role',null,bounded),claimed=await client.rpc('claim_image_description_server');
  expect(claimed.error).toBeNull();expect(claimed.data).toMatchObject({id,companyId:company});
  await finish(claimed.data.token);
  const idle=await client.rpc('claim_image_description_server');expect(idle.error).toBeNull();expect(idle.data).toBeNull();
 });
 it('leaves legacy attachments without queue status for explicit backfill',async()=>{await store.run(async tx=>{const row=await tx.get('onboarding_attachments',id);delete row!.description_status;tx.put('onboarding_attachments',id,row!);});expect(await call('claim_image_description_server')).toBeNull();expect((await attachment())?.description_status).toBeUndefined();});

 it('registers both service RPCs and denies user or anonymous workers',async()=>{for(const role of ['authenticated','anon'] as const)for(const name of ['claim_image_description_server','finish_image_description_server'])expect((await firestoreClient(role,owner,store).rpc(name)).error?.code).toBe('42501');expect(await call('claim_image_description_server')).toMatchObject({id,companyId:company,path,mime:'image/png'});});
 it('serializes claims, recovers an expired lease and rejects late or cross-tenant results',async()=>{const jobs=await Promise.all([call('claim_image_description_server'),call('claim_image_description_server')]);expect(jobs.filter(Boolean)).toHaveLength(1);const first=jobs.find(Boolean);expect(await finish(first.token,{p_company_id:randomUUID()})).toBe(false);vi.setSystemTime(new Date(Date.now()+300001));expect(await finish(first.token)).toBe(false);const second=await call('claim_image_description_server');expect(second.token).not.toBe(first.token);expect(await finish(first.token)).toBe(false);expect(await finish(second.token)).toBe(true);expect(await attachment()).toMatchObject({description_status:'ready',description_attempts:2,description_token:null,visual_description:description,description_model:'fixture'});expect(await finish(second.token)).toBe(false);expect(await call('claim_image_description_server')).toBeNull();});
 it('backs off failed work for five minutes and stops after three attempts',async()=>{for(let attempt=1;attempt<=3;attempt++){const job=await call('claim_image_description_server');expect(job).toBeTruthy();expect(await finish(job.token,{p_description:null,p_model:null})).toBe(true);expect(await attachment()).toMatchObject({description_status:'failed',description_attempts:attempt});expect(await call('claim_image_description_server')).toBeNull();vi.setSystemTime(new Date(Date.now()+300001));}expect(await call('claim_image_description_server')).toBeNull();});
 it('marks the final expired lease failed instead of leaving a crashed worker processing forever',async()=>{for(let attempt=1;attempt<=3;attempt++){expect(await call('claim_image_description_server')).toBeTruthy();vi.setSystemTime(new Date(Date.now()+300001));}expect(await call('claim_image_description_server')).toBeNull();expect(await attachment()).toMatchObject({description_status:'failed',description_attempts:3,description_token:null});});
 it.each(['missing','tenant','mime','size','path','archived'])('does not claim %s storage or company metadata',async(change)=>{await store.run(async tx=>{const object=await tx.get('storage_objects',hash('company-assets/'+path));if(change==='missing')tx.remove('storage_objects',hash('company-assets/'+path));if(change==='tenant')tx.put('storage_objects',hash('company-assets/'+path),{...object,company_id:randomUUID()});if(change==='mime')tx.put('storage_objects',hash('company-assets/'+path),{...object,mime:'image/jpeg'});if(change==='size')tx.put('storage_objects',hash('company-assets/'+path),{...object,size:9});if(change==='path'){const row=await tx.get('onboarding_attachments',id);tx.put('onboarding_attachments',id,{...row,object_path:randomUUID()+'/onboarding/'+id+'.png'});}if(change==='archived')tx.put('companies',company,{id:company,archived_at:new Date().toISOString()});});expect(await call('claim_image_description_server')).toBeNull();});
 it.each(['object','attachment','archive','access'])('rejects completion when %s changes during processing',async(change)=>{const job=await call('claim_image_description_server');await store.run(async tx=>{if(change==='object'){const object=await tx.get('storage_objects',hash('company-assets/'+path));tx.put('storage_objects',hash('company-assets/'+path),{...object,sha256:'changed'});}if(change==='attachment'){const row=await tx.get('onboarding_attachments',id);tx.put('onboarding_attachments',id,{...row,size:9});}if(change==='archive'){const row=await tx.get('companies',company);tx.put('companies',company,{...row,archived_at:new Date().toISOString()});}if(change==='access'){const row=await tx.get('companies',company);tx.remove('workspace_members',row!.workspace_id+'_'+owner);}});expect(await finish(job.token)).toBe(false);expect((await attachment())?.visual_description).toBeUndefined();});
 it('validates output schema atomically and does not describe PDFs',async()=>{const job=await call('claim_image_description_server');await expect(finish(job.token,{p_description:{description:'invented'},p_model:'fixture'})).rejects.toMatchObject({code:'22023'});expect(await attachment()).toMatchObject({description_status:'processing',description_token:job.token});await finish(job.token);await store.run(async tx=>{const pdf=randomUUID();tx.put('onboarding_attachments',pdf,{id:pdf,company_id:company,mime:'application/pdf',created_at:new Date().toISOString()});});expect(await call('claim_image_description_server')).toBeNull();});
 it('initializes SQL-equivalent queue metadata when recording attachments',async()=>{await store.run(async tx=>tx.remove('onboarding_attachments',id));const result=await firestoreClient('authenticated',owner,store).rpc('record_onboarding_attachment',{p_company_id:company,p_id:id,p_path:path,p_name:'Fixture',p_mime:'image/png',p_size:8});expect(result.error).toBeNull();expect(result.data).toMatchObject({description_status:'pending',description_attempts:0,description_token:null,visual_description:null});});
});
