import {randomUUID} from 'node:crypto';
import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {MemoryStore} from './helpers/firestore-memory';
import {digitalRpc} from '../apps/api/src/platform/firestore/digital';
import type {Row} from '../apps/api/src/platform/firestore/store';
import {hash,type FirestoreActor} from '../apps/api/src/platform/firestore/access';

describe('Firestore digital opt-in (isolated fixtures)',()=>{
 let store:MemoryStore,company:string,owner:string,workspace:string;
 const service:FirestoreActor={role:'service_role',id:null};
 const call=(name:string,args:Row={},actor:FirestoreActor={role:'authenticated',id:owner})=>store.run(tx=>digitalRpc(tx,actor,name,{p_company_id:company,...args}));
 afterEach(()=>vi.unstubAllEnvs());
 beforeEach(async()=>{vi.stubEnv('CHECKOUT_MODE','test');vi.stubEnv('NODE_ENV','test');store=new MemoryStore();company=randomUUID();owner=randomUUID();workspace=randomUUID();await store.run(async tx=>{
  tx.put('companies',company,{id:company,workspace_id:workspace});tx.put('workspace_members',workspace+'_'+owner,{role:'owner'});
  tx.put('company_test_access',company,{company_id:company,checkout_id:'fixture',valid_until:new Date(Date.now()+86400000).toISOString()});tx.put('company_test_checkouts','fixture',{company_id:company,mode:'test',status:'test_approved'});tx.put('onboarding_provider_limits',company+'_interpretation',{daily_calls:20});
  tx.put('company_onboarding',company,{profile_version:1,revision:1,confirmed_revision:1});tx.put('company_profile_versions',company+'_1',{facts:{city:{value:'São Paulo - SP'}}});
 });});
 async function connect(){await store.run(async tx=>{tx.put('company_channels','channel',{id:'channel',company_id:company,provider:'meta',status:'connected',metadata:{instagramId:'123',scopes:['instagram_basic','pages_read_engagement']}});tx.put('channel_secrets','channel',{company_id:company,channel_id:'channel',cipher:'encrypted-fixture'});});}
 async function watch(){await call('save_instagram_watch',{p_username:'@clinic.fixture',p_label:'Clinic fixture',p_kind:'local'});return (await store.run(tx=>tx.list('company_instagram_watches')))[0]!;}
 const snapshot={username:'clinic.fixture',name:'Fixture',followers:100,mediaCount:2,collectedAt:new Date().toISOString(),posts:[]};
 it('denies cross-tenant writes and service-only claims',async()=>{await expect(call('save_instagram_watch',{p_username:'clinic.fixture',p_label:'Fixture',p_kind:'local'},{role:'authenticated',id:randomUUID()})).rejects.toMatchObject({code:'42501'});await expect(call('claim_instagram_watch_server')).rejects.toMatchObject({code:'42501'});});
 it('never calls discovery without explicit selection and authorized channel',async()=>{await connect();expect(await call('claim_instagram_watch_server',{},service)).toBeNull();await watch();await store.run(async tx=>tx.remove('channel_secrets','channel'));expect(await call('claim_instagram_watch_server',{},service)).toBeNull();expect((await store.run(tx=>tx.list('company_instagram_watches')))[0]?.status).toBe('unavailable');});
 it('leases once, rejects wrong target/token, preserves earlier evidence on failure',async()=>{await connect();const w=await watch(),job=await call('claim_instagram_watch_server',{},service);expect(job.channel.cipher).toBe('encrypted-fixture');expect(await call('claim_instagram_watch_server',{},service)).toBeNull();expect(await call('finish_instagram_watch_server',{p_id:w.id,p_token:randomUUID(),p_snapshot:snapshot},service)).toBe(false);
  await expect(call('finish_instagram_watch_server',{p_id:w.id,p_token:job.token,p_snapshot:{...snapshot,username:'other'}},service)).rejects.toMatchObject({code:'22023'});expect(await call('finish_instagram_watch_server',{p_id:w.id,p_token:job.token,p_snapshot:snapshot},service)).toBe(true);
  await store.run(async tx=>{const row=await tx.get('company_instagram_watches',w.id);tx.put('company_instagram_watches',w.id,{...row,next_attempt_at:new Date(0).toISOString()});});const second=await call('claim_instagram_watch_server',{},service);await call('finish_instagram_watch_server',{p_id:w.id,p_token:second.token,p_snapshot:null},service);const persisted=await store.run(tx=>tx.get('company_instagram_watches',w.id));expect(persisted?.snapshot).toEqual(snapshot);expect(persisted?.status).toBe('unavailable');
 });
 it('drops an in-flight result after connection revocation and rejects unconfirmed competitor',async()=>{await connect();const w=await watch(),job=await call('claim_instagram_watch_server',{},service);await store.run(async tx=>tx.remove('channel_secrets','channel'));expect(await call('finish_instagram_watch_server',{p_id:w.id,p_token:job.token,p_snapshot:snapshot},service)).toBe(false);expect((await store.run(tx=>tx.get('company_instagram_watches',w.id)))?.snapshot).toBeNull();await expect(call('request_competitor_research',{p_place_id:'node/1'})).rejects.toMatchObject({code:'40001'});});
 it('research requires paid confirmed scope, quota and explicit profile selection',async()=>{
  const regional=randomUUID();await store.run(async tx=>{tx.put('company_journey_state',company+'_1',{regional_id:regional});tx.put('company_regional_research',regional,{id:regional,status:'ready',revision:1,snapshot:{map:{selectionConfirmed:true,selectedIds:['node/1'],competitors:[{id:'node/1',name:'Clinic neighbor fixture'}]}}});tx.put('company_test_access',company,{company_id:company,checkout_id:'fixture',valid_until:new Date(Date.now()+86400000).toISOString()});tx.put('company_test_checkouts','fixture',{company_id:company,mode:'test',status:'test_approved'});tx.put('onboarding_provider_limits',company+'_interpretation',{daily_calls:2});});
  const requested=await call('request_competitor_research',{p_place_id:'node/1'});expect(await call('request_competitor_research',{p_place_id:'node/1'})).toEqual(requested);
  const job=await call('claim_competitor_research_server',{},service);expect(job.query).toBe('Clinic neighbor fixture');expect(await call('claim_competitor_research_server',{},service)).toBeNull();
  const found={username:'neighbor.fixture',name:'Fixture',url:'https://www.instagram.com/neighbor.fixture/',context:'Public source fixture'};
  await expect(call('finish_competitor_research_server',{p_id:job.id,p_token:job.token,p_candidates:[{...found,url:'https://attacker.example'}]},service)).rejects.toMatchObject({code:'22023'});
  expect(await call('finish_competitor_research_server',{p_id:job.id,p_token:job.token,p_candidates:[found]},service)).toBe(true);expect(await store.run(tx=>tx.list('company_instagram_watches'))).toHaveLength(0);
  await call('select_competitor_instagram',{p_place_id:'node/1',p_username:found.username});expect((await store.run(tx=>tx.list('company_instagram_watches')))[0]?.place_id).toBe('node/1');
  await store.run(async tx=>{const r=await tx.get('company_regional_research',regional);tx.put('company_regional_research',regional,{...r,revision:2});});await expect(call('select_competitor_instagram',{p_place_id:'node/1',p_username:found.username})).rejects.toMatchObject({code:'40001'});
 });
 it('stops recurring discovery without paid access and rejects in-flight expired access',async()=>{
  await connect();const w=await watch();await store.run(async tx=>tx.remove('company_test_access',company));expect(await call('claim_instagram_watch_server',{},service)).toBeNull();expect(await store.run(tx=>tx.list('onboarding_provider_attempts'))).toHaveLength(0);
  await store.run(async tx=>{tx.put('company_test_access',company,{company_id:company,checkout_id:'fixture',valid_until:new Date(Date.now()+86400000).toISOString()});const row=await tx.get('company_instagram_watches',w.id);tx.put('company_instagram_watches',w.id,{...row,next_attempt_at:new Date(0).toISOString()});});const job=await call('claim_instagram_watch_server',{},service);expect(job).not.toBeNull();await store.run(async tx=>tx.remove('company_test_access',company));expect(await call('finish_instagram_watch_server',{p_id:w.id,p_token:job.token,p_snapshot:snapshot},service)).toBe(false);expect((await store.run(tx=>tx.get('company_instagram_watches',w.id)))?.snapshot).toBeNull();
 });
 it('uses a tenant daily quota for discovery and records provider failure outcome',async()=>{
  await connect();await watch();await store.run(async tx=>tx.put('onboarding_provider_limits',company+'_interpretation',{daily_calls:1}));const job=await call('claim_instagram_watch_server',{},service);await call('finish_instagram_watch_server',{p_id:job.id,p_token:job.token,p_snapshot:null},service);const attempts=await store.run(tx=>tx.list('onboarding_provider_attempts'));expect(attempts).toHaveLength(1);expect(attempts[0]?.outcome).toBe('failed');await store.run(async tx=>{const row=await tx.get('company_instagram_watches',job.id);tx.put('company_instagram_watches',job.id,{...row,next_attempt_at:new Date(0).toISOString()});});expect(await call('claim_instagram_watch_server',{},service)).toBeNull();expect(await store.run(tx=>tx.list('onboarding_provider_attempts'))).toHaveLength(1);
 });
 it('rejects a result after credential replacement even when the connected account is unchanged',async()=>{
  await connect();const w=await watch(),job=await call('claim_instagram_watch_server',{},service);await store.run(async tx=>tx.put('channel_secrets','channel',{company_id:company,channel_id:'channel',cipher:'replaced-encrypted-fixture'}));expect(await call('finish_instagram_watch_server',{p_id:w.id,p_token:job.token,p_snapshot:snapshot},service)).toBe(false);expect((await store.run(tx=>tx.get('company_instagram_watches',w.id)))?.snapshot).toBeNull();
 });
 it('does not queue confirmed Places selections before explicit Instagram research opt-in',async()=>{
  const place='selected_place_fixture',id=hash({company,place});await store.run(async tx=>{const state=await tx.get('company_onboarding',company);tx.put('company_onboarding',company,{...state,location_confirmed:true});tx.put('company_profile_versions',company+'_1',{facts:{city:{value:'São Paulo - SP'},competitorPlaceIds:{value:place}}});tx.put('company_competitor_research',id,{id,company_id:company,place_id:place,label:'Client confirmed fixture',city:'São Paulo - SP',actor_id:owner,origin:'user_confirmed_places_selection',label_source:'user_confirmed',status:'selected',next_attempt_at:new Date().toISOString()});});
  expect(await call('claim_competitor_research_server',{},service)).toBeNull();expect(await store.run(tx=>tx.list('onboarding_provider_attempts'))).toHaveLength(0);
  const requested=await call('request_competitor_research',{p_place_id:place});expect(requested).toMatchObject({id,profile_version:1,regional_revision:null,origin:'user_confirmed_places_selection',status:'pending'});const job=await call('claim_competitor_research_server',{},service);expect(job.query).toBe('Client confirmed fixture');
  await store.run(async tx=>tx.put('company_profile_versions',company+'_1',{facts:{city:{value:'São Paulo - SP'},competitorPlaceIds:{value:'another_place'}}}));expect(await call('finish_competitor_research_server',{p_id:job.id,p_token:job.token,p_candidates:[]},service)).toBe(false);expect((await store.run(tx=>tx.get('company_competitor_research',id)))?.status).toBe('stale');
 });
 it('bounds selected watches and atomically deduplicates normalized usernames',async()=>{await Promise.all([watch(),watch()]);expect(await store.run(tx=>tx.list('company_instagram_watches'))).toHaveLength(1);for(let i=1;i<10;i++)await call('save_instagram_watch',{p_username:'fixture'+i,p_label:'Fixture',p_kind:'inspiration'});await expect(call('save_instagram_watch',{p_username:'overflow',p_label:'Fixture',p_kind:'local'})).rejects.toMatchObject({code:'22023'});await call('save_instagram_watch',{p_username:'clinic.fixture',p_label:'Fixture',p_kind:'local',p_remove:true});expect(await store.run(tx=>tx.list('company_instagram_watches'))).toHaveLength(9);});
});
