import {afterEach,describe,expect,it,vi} from 'vitest';
import {imageSizes,renderImage} from '../apps/api/src/ai/image-provider';
import {designCreative} from '../apps/api/src/onboarding/content';
import type {CalendarItem} from '@askadia/contracts';
const png='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl6dRkAAAAASUVORK5CYII=';
afterEach(()=>{vi.unstubAllGlobals();vi.unstubAllEnvs();});
describe('OpenAI images and bounded output',()=>{
 it('generates without references and preserves reported usage without inventing absent tokens',async()=>{vi.stubEnv('OPENAI_API_KEY','fixture');vi.stubEnv('OPENAI_MODEL_IMAGE','gpt-image-2.5-sunburst');vi.stubEnv('OPENAI_MODEL_IMAGE','gpt-image-2.5-sunburst');vi.stubEnv('OPENAI_IMAGE_QUALITY','high');const usage={input_tokens:100,output_tokens:200,total_tokens:300,input_tokens_details:{text_tokens:70,image_tokens:30}};const fetcher=vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({data:[{b64_json:png}],usage}))).mockResolvedValueOnce(new Response(JSON.stringify({data:[{b64_json:png}]})));vi.stubGlobal('fetch',fetcher);const result=await renderImage('Arte autorizada','1:1');expect(fetcher.mock.calls[0]![0]).toBe('https://api.openai.com/v1/images/generations');expect(JSON.parse(fetcher.mock.calls[0]![1].body)).toMatchObject({model:'gpt-image-2.5-sunburst',size:'1792x1792',quality:'high',output_format:'png',n:1});expect(result.usage).toEqual(usage);expect((await renderImage('Arte','4:5')).usage).toBeNull();});
 it('never falls back after missing model access and rejects invalid image bytes',async()=>{vi.stubEnv('OPENAI_API_KEY','fixture');vi.stubEnv('OPENAI_MODEL_IMAGE','gpt-image-2.5-sunburst');const fetcher=vi.fn().mockResolvedValueOnce(new Response('{}',{status:403})).mockResolvedValueOnce(new Response(JSON.stringify({data:[{b64_json:Buffer.from('not an image').toString('base64')}]})));vi.stubGlobal('fetch',fetcher);await expect(renderImage('Arte','4:5')).rejects.toThrow('não autorizou');expect(fetcher).toHaveBeenCalledTimes(1);await expect(renderImage('Arte','4:5')).rejects.toThrow('PNG válido');expect(fetcher.mock.calls.every(c=>c[0].startsWith('https://api.openai.com/'))).toBe(true);});
 it('puts the approved carousel style before brand references and preserves actual bytes',async()=>{vi.stubEnv('OPENAI_API_KEY','fixture');vi.stubEnv('OPENAI_MODEL_IMAGE','gpt-image-2.5-sunburst');const fetcher=vi.fn().mockResolvedValue(new Response(JSON.stringify({data:[{b64_json:png}]})));vi.stubGlobal('fetch',fetcher);const item={format:'carrossel',idea:'Ideia',details:{title:'Título',designBrief:'Grid de marca',slides:[{text:'Capa'},{text:'Segunda página'}]}} as unknown as CalendarItem;await designCreative({facts:{},item},1,[{name:'Logo',mime:'image/png',data:Buffer.from('logo').toString('base64')},{name:'Capa da mesma revisão',role:'style',mime:'image/png',data:Buffer.from('style').toString('base64')}]);const body=fetcher.mock.calls[0]![1].body as FormData;expect(await (body.getAll('image[]')[0] as File).text()).toBe('style');expect(await (body.getAll('image[]')[1] as File).text()).toBe('logo');expect(body.get('prompt')).toContain('REFERÊNCIA DE ESTILO');expect(body.get('prompt')).toContain('Segunda página');});
 it('uses supported dimensions and refuses oversized input before provider calls',async()=>{for(const dimensions of Object.values(imageSizes)){const [w,h]=dimensions.split('x').map(Number);expect(w!%16).toBe(0);expect(h!%16).toBe(0);expect(w!*h!).toBeLessThanOrEqual(2560*1440);}vi.stubEnv('OPENAI_API_KEY','fixture');vi.stubEnv('OPENAI_MODEL_IMAGE','gpt-image-2.5-sunburst');const fetcher=vi.fn();vi.stubGlobal('fetch',fetcher);await expect(renderImage('Arte','4:5',[{name:'Grande',mime:'image/png',bytes:Buffer.alloc(10*1024*1024+1)}])).rejects.toThrow('limite');expect(fetcher).not.toHaveBeenCalled();});
});
