import {afterEach,describe,expect,it,vi} from 'vitest';
import {agentModel,agentModelDefaults,agentModelsConfigured,preflightOpenAIModels} from '../apps/api/src/ai/models';
describe('Explicit model configuration and read-only account preflight',()=>{
 afterEach(()=>vi.unstubAllEnvs());
 it('does not infer historical model availability from a key or marketing name',()=>{vi.stubEnv('OPENAI_API_KEY','fixture-key');vi.stubEnv('OPENAI_MODEL_STRATEGY','');vi.stubEnv('OPENAI_MODEL_ANALYSIS','');expect(agentModelsConfigured('strategy')).toBe(false);expect(()=>agentModel('strategy')).toThrow('OPENAI_MODEL_STRATEGY');expect(agentModelDefaults.strategy).toBe('gpt-6-astra');vi.stubEnv('OPENAI_MODEL_ANALYSIS','SOL 6.0');expect(agentModelsConfigured('strategy')).toBe(false);});
 it('resolves configured analysis preference and legacy strategy alias at call time',()=>{vi.stubEnv('OPENAI_MODEL_ANALYSIS','');vi.stubEnv('OPENAI_MODEL_STRATEGY','account-model-fixture');expect(agentModel('strategy')).toBe('account-model-fixture');vi.stubEnv('OPENAI_MODEL_ANALYSIS','analysis-model-fixture');expect(agentModel('strategy')).toBe('analysis-model-fixture');vi.stubEnv('OPENAI_API_KEY','fixture');expect(agentModelsConfigured('strategy')).toBe(true);vi.stubEnv('OPENAI_MODEL_SEARCH','');expect(agentModelsConfigured('strategy','search')).toBe(false);});
 it('never calls a provider without credentials or explicitly configured IDs',async()=>{const fetcher=vi.fn();expect((await preflightOpenAIModels({env:{OPENAI_MODEL_SEARCH:'fixture-model'},roles:['search'],fetcher})).state).toBe('unconfigured');expect((await preflightOpenAIModels({env:{OPENAI_API_KEY:'fixture'},fetcher})).state).toBe('unconfigured');expect(fetcher).not.toHaveBeenCalled();});
 it('lists exact account IDs and distinguishes missing/unconfigured roles',async()=>{const fetcher=vi.fn().mockResolvedValue(new Response(JSON.stringify({data:[{id:'analysis-fixture'}]})));const result=await preflightOpenAIModels({env:{OPENAI_API_KEY:'fixture-secret',OPENAI_PROJECT_ID:'project-fixture',OPENAI_ORG_ID:'org-fixture',OPENAI_MODEL_ANALYSIS:'analysis-fixture',OPENAI_MODEL_COPY:'copy-fixture'},roles:['strategy','copy','search'],fetcher});expect(result.state).toBe('completed');expect(result.roles).toEqual({strategy:{model:'analysis-fixture',state:'listed'},copy:{model:'copy-fixture',state:'missing'},search:{model:null,state:'unconfigured'}});expect(JSON.stringify(result)).not.toContain('fixture-secret');expect(fetcher).toHaveBeenCalledTimes(1);expect(fetcher.mock.calls[0]?.[0]).toBe('https://api.openai.com/v1/models');expect(fetcher.mock.calls[0]?.[1]).toMatchObject({method:'GET',redirect:'error',headers:{'OpenAI-Project':'project-fixture','OpenAI-Organization':'org-fixture'}});});
 it.each([[401,'unauthorized'],[403,'unauthorized'],[429,'rate_limited'],[500,'provider_unavailable']])('sanitizes HTTP %s failures',async(status,failure)=>{const fetcher=vi.fn().mockResolvedValue(new Response('fixture-sensitive-provider-body',{status:Number(status)}));const result=await preflightOpenAIModels({env:{OPENAI_API_KEY:'fixture-secret',OPENAI_MODEL_SEARCH:'fixture'},roles:['search'],fetcher});expect(result.failure).toBe(failure);expect(result.roles.search?.state).toBe('unverified');expect(JSON.stringify(result)).not.toMatch(/fixture-secret|fixture-sensitive-provider-body/);});
 it('rejects malformed listing and catches timeout without returning exception details',async()=>{const env={OPENAI_API_KEY:'fixture',OPENAI_MODEL_SEARCH:'fixture'},roles=['search'] as const;expect((await preflightOpenAIModels({env,roles:[...roles],fetcher:vi.fn().mockResolvedValue(new Response('{"data":[{}]}'))})).failure).toBe('invalid_response');expect((await preflightOpenAIModels({env,roles:[...roles],fetcher:vi.fn().mockRejectedValue(new Error('private-provider-detail'))})).failure).toBe('provider_unavailable');});
});
