import {randomUUID} from 'node:crypto';
import type {SupabaseClient} from '@supabase/supabase-js';
import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {regionalFacebookProvider} from '../apps/api/src/onboarding/regional-research';
import {collectRegionalAudience} from '../apps/api/src/onboarding/regional-providers';
import {sealChannel} from '../apps/api/src/onboarding/channel-vault';
const facts={city:{status:'provided' as const,value:'Sumaré - SP'},uf:{status:'provided' as const,value:'SP'},services:{status:'provided' as const,value:'Cardiologia'}};
const graph=vi.fn(async<T>(path:string):Promise<T>=>(path==='search'?{data:[{key:'123',name:'Sumaré',country_code:'BR',region:'São Paulo'}]}:{data:{estimate_ready:true,users_lower_bound:10,users_upper_bound:20}}) as T);
const transport:typeof fetch=async input=>{if(new URL(String(input)).hostname==='serpapi.com')return Response.json({related_queries:{top:[{query:'consulta local',extracted_value:60}],rising:[]}});throw new Error('Fixture IBGE offline');};
describe('Regional worker tenant Meta bridge — isolated encrypted fixtures',()=>{
 beforeEach(()=>{vi.stubEnv('SECRETS_ENCRYPTION_KEY','a'.repeat(64));vi.stubEnv('SERPAPI_API_KEY','fixture-key');vi.stubEnv('X_BEARER_TOKEN','');graph.mockClear();});afterEach(()=>vi.unstubAllEnvs());
 function setup(change?:(kind:'meta'|'ads',read:number,value:Record<string,unknown>)=>Record<string,unknown>|null){
  const job={companyId:randomUUID(),actorId:randomUUID()},channel={remote_id:'123456789',cipher:sealChannel(job.companyId,{userToken:'private-fixture-user-token'}),metadata:{scopes:['ads_read'],tasks:[]}},account={status:'connected',account_id:'act_987654321',source_page:channel.remote_id};let reads=0;
  const rpc=vi.fn(async(name:string,args:Record<string,unknown>)=>{expect(args.p_company_id).toBe(job.companyId);expect(args.p_actor).toBe(job.actorId);if(name==='read_company_meta_server'){expect(args.p_action).toBe('marketing.write');return {data:change?.('meta',++reads,structuredClone(channel))??(change?null:channel),error:null};}expect(name).toBe('ad_credentials_server');expect(args.p_write).toBeNull();expect(args.p_provider).toBe('meta');return {data:change?.('ads',reads,structuredClone(account))??(change?null:account),error:null};});return {job,channel,account,rpc,provider:regionalFacebookProvider({rpc} as unknown as SupabaseClient,job)};
 }
 it('uses only the tenant account and user token and rechecks before persisting observations',async()=>{const fixture=setup();const data=await collectRegionalAudience(facts,fixture.provider,transport,graph);expect(data.facebook).toMatchObject({state:'available',cityKey:'123'});expect(fixture.rpc).toHaveBeenCalledTimes(4);expect(graph.mock.calls.filter(c=>c[0]!=='search').every(c=>c[0]==='act_987654321/reachestimate')).toBe(true);expect(JSON.stringify(data)).not.toContain('private-fixture-user-token');expect(data.trends.state).toBe('available');});
 it.each(['account','page','scope','credential'])('discards only Meta observations after %s changes',async kind=>{const fixture=setup((source,read,value)=>{if(read===2){if(source==='ads'&&kind==='account')return {...value,account_id:'act_111111111'};if(source==='ads'&&kind==='page')return {...value,source_page:'111111111'};if(source==='meta'&&kind==='scope')return {...value,metadata:{scopes:[],tasks:[]}};if(source==='meta'&&kind==='credential')return {...value,cipher:sealChannel(String(fixture.job.companyId),{userToken:'replacement-token'})};}return value;});const data=await collectRegionalAudience(facts,fixture.provider,transport,graph);expect(data.facebook).toMatchObject({state:'unavailable',estimates:[],cityKey:null});expect(data.trends.state).toBe('available');expect(data.topics?.google.state).toBe('available');});
 it.each(['scope','page'])('makes no Meta request for initially invalid %s',async kind=>{const fixture=setup((source,_read,value)=>source==='meta'&&kind==='scope'?{...value,metadata:{scopes:['pages_read_engagement']}}:source==='ads'&&kind==='page'?{...value,source_page:'111111111'}:value);const data=await collectRegionalAudience(facts,fixture.provider,transport,graph);expect(graph).not.toHaveBeenCalled();expect(data.facebook?.state).toBe('unavailable');expect(data.trends.state).toBe('available');});
 it('keeps missing account unconfigured and rejects a vault secret from another tenant',async()=>{const missing=setup((source,_read,value)=>source==='ads'?null:value);expect((await collectRegionalAudience(facts,missing.provider,transport,graph)).facebook?.state).toBe('unconfigured');expect(graph).not.toHaveBeenCalled();const wrong=setup((source,_read,value)=>source==='meta'?{...value,cipher:sealChannel(randomUUID(),{userToken:'other-tenant-fixture-token'})}:value);const data=await collectRegionalAudience(facts,wrong.provider,transport,graph);expect(graph).not.toHaveBeenCalled();expect(data.facebook?.state).toBe('unavailable');expect(JSON.stringify(data)).not.toContain('other-tenant-fixture-token');});
});
