import {describe,it,expect,vi,afterEach} from 'vitest';
import {flowFromRules,runServiceFlow,serviceFlowSchema} from '../packages/contracts/src/service-flow';
import {validateMedia,evolutionMedia} from '../apps/api/src/inbox/media';
import {generateServicePrompt,ATTENDANCE_MODEL} from '../apps/api/src/inbox/assistant';
afterEach(()=>{vi.unstubAllGlobals();vi.unstubAllEnvs();});
describe('Visual attendance flow',()=>{
 it('preserves legacy decisions, accents and fallback in an executable graph',()=>{const g=flowFromRules([{match:'natação',reply:'Conheça nossa piscina.',handoff:false},{match:'preço',reply:'A equipe confirmará as condições.',handoff:true}],'Vamos conversar com a equipe.');expect(serviceFlowSchema.safeParse(g).success).toBe(true);expect(runServiceFlow(g,'NATACAO')).toEqual({text:'Conheça nossa piscina.',handoff:false});expect(runServiceFlow(g,'preço')).toEqual({text:'A equipe confirmará as condições.',handoff:true});expect(runServiceFlow(g,'outro')).toEqual({text:'Vamos conversar com a equipe.',handoff:true});});
 it('rejects cycles, disconnected blocks and incomplete branch exits',()=>{const g=flowFromRules([{match:'oi',reply:'Olá',handoff:false}],'Equipe');expect(serviceFlowSchema.safeParse({...g,edges:g.edges.filter(e=>e.port!=='no')}).success).toBe(false);expect(serviceFlowSchema.safeParse({...g,edges:[...g.edges,{id:'loop',source:'reply0',target:'rule0',port:'next'}]}).success).toBe(false);expect(serviceFlowSchema.safeParse({...g,nodes:[...g.nodes,{...g.nodes[1]!,id:'lost'}]}).success).toBe(false);});
 it('evaluates the chosen connections and concatenates sequential messages',()=>{const g=flowFromRules([],'');g.nodes.push({id:'end',kind:'handoff',label:'Equipe',text:'A equipe pode ajudar.',position:{x:600,y:160}});g.edges.push({id:'reply_end',source:'reply',target:'end',port:'next'});expect(runServiceFlow(g,'oi')).toEqual({text:'Olá! Como podemos ajudar?\n\nA equipe pode ajudar.',handoff:true});});
});
describe('Inbox files',()=>{
 it('accepts PDF and audio signatures but rejects HTML, mismatches and oversized content',()=>{expect(validateMedia({base64:Buffer.from('%PDF-1.4\nexample').toString('base64'),mimetype:'application/pdf',fileName:'guia.pdf'}).kind).toBe('document');expect(validateMedia({base64:Buffer.from('OggS audio fixture').toString('base64'),mimetype:'audio/ogg; codecs=opus',fileName:'fala.ogg'}).kind).toBe('audio');expect(()=>validateMedia({base64:Buffer.from('<script>bad</script>').toString('base64'),mimetype:'application/pdf',fileName:'guia.pdf'})).toThrow();expect(()=>validateMedia({base64:Buffer.alloc(8*1024*1024+1).toString('base64'),mimetype:'image/png',fileName:'foto.png'})).toThrow();expect(()=>validateMedia({base64:'https://internal/secret',mimetype:'image/png',fileName:'foto.png'})).toThrow();});
 it('does not download a provider message belonging to another conversation',async()=>{vi.stubEnv('EVOLUTION_API_URL','https://provider.example');vi.stubEnv('EVOLUTION_API_KEY','test-key');const fetch=vi.fn().mockResolvedValue({ok:true,json:async()=>({messages:{records:[{key:{id:'abc',remoteJid:'999999@s.whatsapp.net'},message:{imageMessage:{}}}]}})});vi.stubGlobal('fetch',fetch);await expect(evolutionMedia('askadia-company','111111@s.whatsapp.net','abc')).rejects.toThrow('Arquivo não encontrado');expect(fetch).toHaveBeenCalledTimes(1);});
 it('does not expose view-once media through the download API',async()=>{vi.stubEnv('EVOLUTION_API_URL','https://provider.example');vi.stubEnv('EVOLUTION_API_KEY','test-key');const fetch=vi.fn().mockResolvedValue({ok:true,json:async()=>({messages:{records:[{key:{id:'abc',remoteJid:'111111@s.whatsapp.net'},message:{viewOnceMessage:{message:{imageMessage:{}}}}}]}})});vi.stubGlobal('fetch',fetch);await expect(evolutionMedia('askadia-company','111111@s.whatsapp.net','abc')).rejects.toThrow('visualização única');expect(fetch).toHaveBeenCalledTimes(1);});
});
it('generates an editable prompt with the selected channel and only supplied company context',async()=>{vi.stubEnv('OPENAI_API_KEY','test-key');vi.stubEnv('OPENAI_MODEL_ATTENDANCE','gpt-6-luna');let request:Record<string,unknown>={};vi.stubGlobal('fetch',vi.fn(async(_url:unknown,init:RequestInit)=>{request=JSON.parse(String(init.body));return new Response(JSON.stringify({choices:[{message:{content:'Atenda a Empresa A com os serviços confirmados.'}}]}),{headers:{'Content-Type':'application/json'}});}));const out=await generateServicePrompt({name:{value:'Empresa A',status:'provided'}},'whatsapp');expect(out.prompt).toContain('Empresa A');expect(request.model).toBe(ATTENDANCE_MODEL);expect(request.store).toBe(false);expect(JSON.stringify(request.messages)).toContain('whatsapp');});
