import {randomUUID} from 'node:crypto';
import {beforeEach,afterEach,describe,it,expect,vi} from 'vitest';
import {MemoryStore} from './helpers/firestore-memory';
import type {Row} from '../apps/api/src/platform/firestore/store';
import {hash,type FirestoreActor} from '../apps/api/src/platform/firestore/access';
import {socialPublicationRpc} from '../apps/api/src/platform/firestore/social-publication';
import {InstagramPublisher,runSocialPublication,type PublicationDependencies} from '../apps/api/src/social/publication';
// Fictional clinics and mocked Meta/storage only. No real provider request.
describe('approved Instagram publication queue',()=>{
 let store:MemoryStore,company:string,owner:string,item:string,asset:string,id:string,channel:string;
 const service:FirestoreActor={role:'service_role',id:null};const customer=()=>({role:'authenticated' as const,id:owner});
 const call=(name:string,args:Row={},actor:FirestoreActor=service)=>store.run(tx=>socialPublicationRpc(tx,actor,name,args));
 const create=()=>call('create_social_publication',{p_company_id:company,p_id:id,p_item_id:item,p_creative_id:asset,p_caption:'Fixture administrative caption',p_scheduled_at:new Date(Date.now()+600000).toISOString()},customer());
 const approve=(fetch=true)=>call('approve_social_publication',{p_company_id:company,p_id:id,p_revision:1,p_provider_fetch:fetch},customer());
 const control=(action:string)=>call('control_social_publication',{p_company_id:company,p_id:id,p_revision:1,p_action:action},customer());
 const deps=():PublicationDependencies=>({rpc:(name,args)=>call(name,args),assetUrl:vi.fn(async()=> 'https://fixture.example.com/private-signed-jpeg'),provider:{create:vi.fn(async()=> '111111'),status:vi.fn(async()=> 'FINISHED'),publish:vi.fn(async()=> '222222')}});
 beforeEach(async()=>{vi.useFakeTimers();vi.setSystemTime(new Date('2026-10-07T12:00:00Z'));store=new MemoryStore();company=randomUUID();owner=randomUUID();item=randomUUID();asset=randomUUID();id=randomUUID();channel=randomUUID();await store.run(async tx=>{const workspace=randomUUID(),brief=randomUUID(),objectPath=company+'/creative/fixture.jpg';tx.put('companies',company,{id:company,workspace_id:workspace});tx.put('workspace_members',workspace+'_'+owner,{role:'owner'});tx.put('company_onboarding',company,{revision:1,confirmed_revision:1,profile_version:1});tx.put('company_profile_versions',company+'_1',{company_id:company,version:1,facts:{}});tx.put('company_journey_state',company+'_1',{company_id:company,profile_version:1,brief_id:brief});tx.put('company_strategy_briefs',brief,{id:brief,company_id:company,generation:1,status:'approved'});tx.put('company_calendar_items',item,{id:item,company_id:company,brief_id:brief,generation:1,profile_version:1,revision:1,approved_revision:1,status:'approved',format:'imagem',details:{caption:'Fixture'},position:0});tx.put('company_creatives',asset,{id:asset,company_id:company,item_id:item,revision:1,frame:0,mime:'image/jpeg',object_path:objectPath});tx.put('storage_objects',hash('company-assets/'+objectPath),{company_id:company,path:objectPath,status:'ready',mime:'image/jpeg',sha256:'a'.repeat(64)});tx.put('company_channels',channel,{id:channel,company_id:company,provider:'meta',status:'connected',remote_id:'12345',metadata:{instagramId:'67890',publishingReady:true,scopes:['instagram_content_publish']}});tx.put('channel_secrets',channel,{channel_id:channel,company_id:company,cipher:'fixture-encrypted'});});});
 afterEach(()=>vi.useRealTimers());
 const claim=async()=>{vi.advanceTimersByTime(600001);return await call('claim_social_publication_server') as Row;};
 it('draft approval is separate from content approval and authorizes temporary provider fetch explicitly',async()=>{const draft=await create() as Row;expect(draft.status).toBe('draft');expect(await claim()).toBeNull();await expect(approve(false)).rejects.toMatchObject({code:'22023'});});
 it('denies cross tenant reads through mutations and service calls from customers',async()=>{await expect(call('create_social_publication',{p_company_id:company,p_id:id},{role:'authenticated',id:randomUUID()})).rejects.toMatchObject({code:'42501'});await expect(call('claim_social_publication_server',{},customer())).rejects.toMatchObject({code:'42501'});});
 it('deduplicates intent by content revision and Instagram account',async()=>{await create();const prior=id;id=randomUUID();await expect(create()).rejects.toMatchObject({code:'40001'});id=prior;expect((await create() as Row).id).toBe(prior);});
 it('claims atomically and publishes only after container readiness with durable steps',async()=>{await create();await approve();vi.advanceTimersByTime(600001);const jobs=await Promise.all([call('claim_social_publication_server'),call('claim_social_publication_server')]);expect(jobs.filter(Boolean)).toHaveLength(1);const d=deps();await runSocialPublication(jobs.find(Boolean) as Row,d);expect(d.provider!.create).toHaveBeenCalledTimes(1);expect(d.provider!.publish).toHaveBeenCalledWith('67890','111111');const row=await store.run(tx=>tx.get('company_social_publications',id));expect(row).toMatchObject({status:'published',remote:{containerId:'111111',mediaId:'222222'}});});
 it('revocation before execution makes no external mutation or signed URL',async()=>{await create();await approve();const job=await claim();await control('revoke');const d=deps();await runSocialPublication(job,d);expect(d.assetUrl).not.toHaveBeenCalled();expect(d.provider!.create).not.toHaveBeenCalled();expect(d.provider!.publish).not.toHaveBeenCalled();});
 it('uncertain container response never creates another container after restart',async()=>{await create();await approve();const d=deps();vi.mocked(d.provider!.create).mockRejectedValue(new Error('timeout'));await runSocialPublication(await claim(),d);vi.advanceTimersByTime(60001);const retry=await call('claim_social_publication_server') as Row;expect(retry.reconcileOnly).toBe(true);await runSocialPublication(retry,d);expect(d.provider!.create).toHaveBeenCalledTimes(1);expect(d.provider!.publish).not.toHaveBeenCalled();});
 it('uncertain publish reconciles PUBLISHED without repeating media_publish',async()=>{await create();await approve();const d=deps();vi.mocked(d.provider!.publish).mockRejectedValue(new Error('timeout'));await runSocialPublication(await claim(),d);await control('revoke');vi.advanceTimersByTime(60001);vi.mocked(d.provider!.status).mockResolvedValue('PUBLISHED');await runSocialPublication(await call('claim_social_publication_server') as Row,d);expect(d.provider!.publish).toHaveBeenCalledTimes(1);expect(await store.run(tx=>tx.get('company_social_publications',id))).toMatchObject({status:'published',desired:'pause'});});
 it('edited content, changed account and expired lease invalidate approval',async()=>{await create();await approve();const job=await claim();await store.run(async tx=>{const row=(await tx.get('company_calendar_items',item))!;tx.put('company_calendar_items',item,{...row,revision:2});});expect(await call('social_publication_guard_server',{p_id:id,p_token:job.lease_token})).toBe(false);vi.advanceTimersByTime(300001);await expect(call('social_publication_step_server',{p_id:id,p_token:job.lease_token,p_step:'container'})).rejects.toMatchObject({code:'40001'});});
 it('unsupported private PNG media is rejected before account mutation',async()=>{await store.run(async tx=>{const creative=(await tx.get('company_creatives',asset))!,key=hash('company-assets/'+creative.object_path),object=(await tx.get('storage_objects',key))!;tx.put('storage_objects',key,{...object,mime:'image/png'});});await expect(create()).rejects.toMatchObject({code:'22023'});});
 it('records publication accepted during revocation as published without promising retraction',async()=>{await create();await approve();const d=deps();vi.mocked(d.provider!.publish).mockImplementation(async()=>{await control('revoke');return '222222';});await runSocialPublication(await claim(),d);expect(await store.run(tx=>tx.get('company_social_publications',id))).toMatchObject({status:'published',desired:'pause'});await expect(control('cancel')).rejects.toMatchObject({code:'40001'});});
 it('official adapter selects image/reels fields and validates provider ids',async()=>{const graph=vi.fn().mockResolvedValueOnce({id:'111'}).mockResolvedValueOnce({id:'222'}).mockResolvedValueOnce({status_code:'FINISHED'}).mockResolvedValueOnce({id:'333'});const provider=new InstagramPublisher('fixture-token',graph);await provider.create({instagramId:'67890',format:'image',caption:'Fixture'},'https://fixture.example.com/a.jpg');await provider.create({instagramId:'67890',format:'reels',caption:'Fixture'},'https://fixture.example.com/a.mp4');expect(graph.mock.calls[0][3]).toEqual({image_url:'https://fixture.example.com/a.jpg',caption:'Fixture'});expect(graph.mock.calls[1][3]).toMatchObject({media_type:'REELS'});expect(await provider.status('111')).toBe('FINISHED');expect(await provider.publish('67890','111')).toBe('333');expect(graph.mock.calls[3][0]).toBe('67890/media_publish');});
 it('binds a prepared JPEG derivative to the exact approved source hash',async()=>{const source=await call('prepare_social_media_context_server',{p_company_id:company,p_actor:owner,p_item_id:item,p_creative_id:asset}) as Row;await store.run(async tx=>tx.put('storage_objects',hash('company-assets/'+source.targetPath),{company_id:company,status:'ready',mime:'image/jpeg',sha256:'b'.repeat(64)}));await call('record_social_media_server',{p_company_id:company,p_actor:owner,p_item_id:item,p_creative_id:asset,p_id:source.key,p_source_sha256:source.sourceSha256});const row=await create() as Row;expect(row.snapshot).toMatchObject({assetSha256:'b'.repeat(64),objectPath:source.targetPath});expect(row.snapshot.media[0].preparedId).toBe(source.key);await expect(call('record_social_media_server',{p_company_id:company,p_actor:owner,p_item_id:item,p_creative_id:asset,p_id:source.key,p_source_sha256:'c'.repeat(64)})).rejects.toMatchObject({code:'40001'});});
 it('publishes approved JPEG carousel children and a parent with independent durable steps',async()=>{const second=randomUUID(),path=company+'/creative/second.jpg';await store.run(async tx=>{const row=(await tx.get('company_calendar_items',item))!;tx.put('company_calendar_items',item,{...row,format:'carrossel',details:{caption:'Fixture',slides:[{text:'One'},{text:'Two'}]}});tx.put('company_creatives',second,{id:second,company_id:company,item_id:item,revision:1,frame:1,mime:'image/jpeg',object_path:path});tx.put('storage_objects',hash('company-assets/'+path),{company_id:company,status:'ready',mime:'image/jpeg',sha256:'b'.repeat(64)});});const draft=await create() as Row;expect(draft.snapshot.format).toBe('carousel');expect(draft.snapshot.media).toHaveLength(2);await approve();const d=deps();d.provider!.child=vi.fn().mockResolvedValueOnce('111').mockResolvedValueOnce('222');d.provider!.carousel=vi.fn(async()=> '333');await runSocialPublication(await claim(),d);expect(d.provider!.child).toHaveBeenCalledTimes(2);expect(d.provider!.carousel).toHaveBeenCalledWith(expect.objectContaining({format:'carousel'}),['111','222']);expect(d.provider!.publish).toHaveBeenCalledWith('67890','333');expect(d.provider!.create).not.toHaveBeenCalled();});
 it('never duplicates a carousel child whose creation result was lost',async()=>{const second=randomUUID(),path=company+'/creative/second.jpg';await store.run(async tx=>{const row=(await tx.get('company_calendar_items',item))!;tx.put('company_calendar_items',item,{...row,format:'carrossel',details:{caption:'Fixture',slides:[{},{}]}});tx.put('company_creatives',second,{id:second,company_id:company,item_id:item,revision:1,frame:1,object_path:path});tx.put('storage_objects',hash('company-assets/'+path),{company_id:company,status:'ready',mime:'image/jpeg',sha256:'b'.repeat(64)});});await create();await approve();const d=deps();d.provider!.child=vi.fn(async()=>{throw new Error('timeout');});d.provider!.carousel=vi.fn(async()=> '333');await runSocialPublication(await claim(),d);vi.advanceTimersByTime(60001);const retry=await call('claim_social_publication_server') as Row;expect(retry.reconcileOnly).toBe(true);await runSocialPublication(retry,d);expect(d.provider!.child).toHaveBeenCalledTimes(1);expect(d.provider!.carousel).not.toHaveBeenCalled();expect(d.provider!.publish).not.toHaveBeenCalled();});

 it('editing a queued caption or schedule creates a new unapproved revision',async()=>{await create();await approve();const revised=await call('edit_social_publication',{p_company_id:company,p_id:id,p_revision:1,p_caption:'Revised fixture caption',p_scheduled_at:new Date(Date.now()+1200000).toISOString()},customer()) as Row;expect(revised).toMatchObject({revision:2,status:'draft',approved_revision:null,provider_fetch_approved:false,snapshot:{caption:'Revised fixture caption'}});await expect(approve()).rejects.toMatchObject({code:'40001'});expect(await claim()).toBeNull();});
 it('disallows rewriting a caption after a provider step has started',async()=>{await create();await approve();const job=await claim();await call('social_publication_step_server',{p_id:id,p_token:job.lease_token,p_step:'container'});await expect(call('edit_social_publication',{p_company_id:company,p_id:id,p_revision:1,p_caption:'Changed',p_scheduled_at:new Date(Date.now()+600000).toISOString()},customer())).rejects.toMatchObject({code:'40001'});});
 it('uses official image children and carousel parent parameters',async()=>{const graph=vi.fn().mockResolvedValueOnce({id:'111'}).mockResolvedValueOnce({id:'333'}),provider=new InstagramPublisher('fixture-token',graph);await provider.child('67890','https://fixture.example.com/1.jpg');await provider.carousel({instagramId:'67890',caption:'Fixture'},['111','222']);expect(graph.mock.calls[0][3]).toEqual({image_url:'https://fixture.example.com/1.jpg',is_carousel_item:true});expect(graph.mock.calls[1][3]).toEqual({media_type:'CAROUSEL',children:'111,222',caption:'Fixture'});});

});
