import {paidCompanyFixture} from './helpers/paid-company';
import {afterAll,afterEach,beforeAll,describe,expect,it,vi} from 'vitest';
import {PGlite} from '@electric-sql/pglite';
import {readFileSync,readdirSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
import {createVisual} from '../apps/api/src/ai/images';
import {agentModel} from '../apps/api/src/ai/models';
let db:PGlite,company:string,foreign:string;const owner=randomUUID(),other=randomUUID(),source=randomUUID(),foreignSource=randomUUID();
async function as(id:string){await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec('set role authenticated');}
async function server(){await db.exec('reset role;set role service_role');}
async function scalar<T=unknown>(sql:string,args:unknown[]=[]):Promise<T>{return Object.values((await db.query<Record<string,T>>(sql,args)).rows[0]!)[0]!;}
const request=(sourceId=source)=>({id:randomUUID(),kind:'site_image',sourceId,planId:null,campaignIndex:null,instructions:'Ajustar luz e preservar o espaço real.',ratio:'16:9',references:[]});
type Job={id:string;companyId:string;token:string;references:{id:string;path:string}[]};
describe('Persistent visual work and tenant boundaries',()=>{
 beforeAll(async()=>{db=new PGlite();await db.exec(`create role anon nologin;create role authenticated nologin;create role service_role nologin;create schema auth;create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz,raw_user_meta_data jsonb default '{}');create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;grant usage on schema auth to authenticated,anon;grant execute on function auth.uid() to authenticated,anon;create schema storage;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text references storage.buckets(id),name text);alter table storage.objects enable row level security;grant usage on schema storage to authenticated,anon;grant select,insert,update,delete on storage.objects to authenticated;`);for(const f of readdirSync('supabase/migrations').filter(f=>f.endsWith('.sql')).sort())await db.exec(readFileSync('supabase/migrations/'+f,'utf8').replace('create extension if not exists pgcrypto;',''));
  for(const id of [owner,other]){await db.query('insert into auth.users(id,email,email_confirmed_at) values($1,$2,now())',[id,id+'@example.test']);await db.query('insert into public.profiles(id,display_name) values($1,$2)',[id,'Fixture']);}
  await as(owner);company=(await scalar<{companyId:string}>('select public.begin_company_onboarding($1)',[randomUUID()])).companyId;await as(other);foreign=(await scalar<{companyId:string}>('select public.begin_company_onboarding($1)',[randomUUID()])).companyId;
  await db.exec('reset role');for(const [c,u,id] of [[company,owner,source],[foreign,other,foreignSource]]){await db.query("insert into public.company_profile_versions(company_id,version,facts,confirmed_by) values($1,1,'{}',$2)",[c,u]);await db.query('update public.company_onboarding set profile_version=1,confirmed_revision=revision where company_id=$1',[c]);const path=c+'/onboarding/'+id+'.png';await db.query("insert into storage.objects(bucket_id,name) values('company-assets',$1)",[path]);await db.query("insert into public.onboarding_attachments(id,company_id,name,mime,size,object_path,uploaded_by) values($1,$2,'Original','image/png',10,$3,$4)",[id,c,path,u]);}
 await paidCompanyFixture(db,company);},120000);
 afterAll(async()=>{await db?.close();});
 it('rejects foreign originals and binds a repeated request to its exact contents',async()=>{await as(owner);await expect(scalar('select public.enqueue_visual_job($1,$2)',[company,request(foreignSource)])).rejects.toThrow('Company materials');const req=request();expect(await scalar('select public.enqueue_visual_job($1,$2)',[company,req])).toBe(req.id);expect(await scalar('select public.enqueue_visual_job($1,$2)',[company,req])).toBe(req.id);await expect(scalar('select public.enqueue_visual_job($1,$2)',[company,{...req,instructions:'Outra edição'}])).rejects.toThrow('Request changed');await as(other);expect(await scalar('select count(*)::int from public.company_visual_jobs where company_id=$1',[company])).toBe(0);await expect(scalar('select public.claim_visual_job_server()')).rejects.toThrow();});
 it('saves a separate generated file without changing the original or publishing the site',async()=>{await server();const j=await scalar<Job>('select public.claim_visual_job_server()');expect(j.companyId).toBe(company);expect(j.references[0]!.id).toBe(source);expect(await scalar('select public.finish_visual_job_server($1,$2,null)',[j.id,randomUUID()])).toBe(false);const id=randomUUID(),path=company+'/onboarding/'+id+'.png';await db.exec('reset role');await db.query("insert into storage.objects(bucket_id,name) values('company-assets',$1)",[path]);await server();expect(await scalar('select public.finish_visual_job_server($1,$2,$3)',[j.id,j.token,{attachmentId:id,mime:'image/png',size:10,model:'fixture'}])).toBe(true);await as(owner);expect(await scalar('select result_attachment_id from public.company_visual_jobs where id=$1',[j.id])).toBe(id);expect(await scalar('select object_path from public.onboarding_attachments where id=$1',[source])).toBe(company+'/onboarding/'+source+'.png');expect(await scalar('select count(*)::int from public.company_sites where company_id=$1 and published is not null',[company])).toBe(0);});
 it('discards results when the profile changes during image generation',async()=>{await as(owner);await scalar('select public.enqueue_visual_job($1,$2)',[company,request()]);await server();const j=await scalar<Job>('select public.claim_visual_job_server()');await db.exec('reset role');await db.query('update public.company_onboarding set revision=revision+1 where company_id=$1',[company]);await server();expect(await scalar('select public.finish_visual_job_server($1,$2,null)',[j.id,j.token])).toBe(false);await as(owner);expect(await scalar('select status from public.company_visual_jobs where id=$1',[j.id])).toBe('stale');});
 it('queues real creative jobs from a completed paid proposal and gates production by strategic approval',async()=>{await db.exec('reset role');await db.query('update public.company_onboarding set confirmed_revision=revision where company_id=$1',[company]);await as(owner);const id=randomUUID();await scalar('select public.begin_paid_plan($1,$2,100,7)',[company,id]);await server();await scalar('select public.finish_paid_plan_server($1,$2,$3,$4,$5)',[company,owner,id,{summary:'Fixture',campaigns:[{name:'Campanha',provider:'meta',copy:'Conheça a academia',creativeBrief:'Use a marca',investment:100}],unknowns:[]},'fixture']);expect(await scalar('select public.claim_visual_job_server()')).toBeNull();await as(owner);expect(await scalar("select count(*)::int from public.company_visual_jobs where plan_id=$1 and kind='campaign_creative' and status='pending'",[id])).toBe(1);await as(other);await expect(scalar('select public.enqueue_visual_job($1,$2)',[foreign,{...request(),kind:'campaign_creative',sourceId:null,planId:id,campaignIndex:0}])).rejects.toThrow('Current campaign');});
});
afterEach(()=>{vi.unstubAllEnvs();vi.unstubAllGlobals();});
describe('Provider image editing and runtime model routing',()=>{
 it('uses the selected model at call time and sends the original to the image editor',async()=>{vi.stubEnv('OPENAI_MODEL_ATTENDANCE','gpt-6-luna');expect(agentModel('attendance')).toBe('gpt-6-luna');vi.stubEnv('OPENAI_MODEL_ATTENDANCE','gpt-6-sol');expect(agentModel('attendance')).toBe('gpt-6-sol');vi.stubEnv('OPENAI_API_KEY','fixture');vi.stubEnv('OPENAI_MODEL_IMAGE','fixture-image-model');const fetcher=vi.fn().mockResolvedValue(new Response(JSON.stringify({data:[{b64_json:'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl6dRkAAAAASUVORK5CYII='}]})));vi.stubGlobal('fetch',fetcher);await createVisual({kind:'site_image',ratio:'16:9',instructions:'Melhorar a luz',facts:{}},[{name:'Original',mime:'image/png',bytes:Buffer.from('original')}]);const body=fetcher.mock.calls[0]![1].body as FormData;expect(fetcher.mock.calls[0]![0]).toBe('https://api.openai.com/v1/images/edits');expect(body.get('size')).toBe('2048x1152');expect(await (body.get('image[]') as File).text()).toBe('original');expect(body.get('prompt')).toContain('Preserve pessoas');});
 it('never calls a provider for an edit without the original and does not fake quota success',async()=>{const fetcher=vi.fn();vi.stubGlobal('fetch',fetcher);await expect(createVisual({kind:'site_image',ratio:'16:9',instructions:'Luz',facts:{}},[])).rejects.toThrow('original');expect(fetcher).not.toHaveBeenCalled();vi.stubEnv('OPENAI_API_KEY','fixture');vi.stubEnv('OPENAI_MODEL_IMAGE','fixture-image-model');fetcher.mockResolvedValue(new Response('{}',{status:429}));await expect(createVisual({kind:'campaign_creative',ratio:'4:5',instructions:'',facts:{}},[])).rejects.toThrow('crédito');});
});
