import {afterEach,beforeEach,describe,it,expect,vi} from 'vitest';
import {randomUUID,createHmac} from 'node:crypto';
import {InboxAutomation} from '../apps/api/src/inbox/automation';
vi.mock('../apps/api/src/inbox/assistant',()=>({draftServiceReply:vi.fn(async()=>({text:'Resposta administrativa fixture',handoff:false}))}));
import {MemoryStore} from './helpers/firestore-memory';
import {whatsappCloudRpc} from '../apps/api/src/platform/firestore/whatsapp-cloud';
import {inboxRpc} from '../apps/api/src/platform/firestore/inbox';
import {channelRpc} from '../apps/api/src/platform/firestore/channels';
import {sealChannel} from '../apps/api/src/onboarding/channel-vault';
import {cloudGraph,verifyCloudNumber,verifyCloudSignature,verifyCloudChallenge,cloudWebhookEvents,configuredCloudCredentials} from '../apps/api/src/inbox/whatsapp-cloud';
import type {FirestoreActor} from '../apps/api/src/platform/firestore/access';
import type {Row} from '../apps/api/src/platform/firestore/store';

describe('official WhatsApp Cloud adapter and native inbox (fixtures only)',()=>{
 let store:MemoryStore,company:string,actor:FirestoreActor,other:FirestoreActor;const service:FirestoreActor={role:'service_role',id:null},phone='123456789',waba='987654321',peer='5511999999999',thread=peer+'@s.whatsapp.net',credentials={token:'fixture-token-never-real',phoneId:phone,wabaId:waba};
 const rpc=(name:string,args:Row={},who=actor)=>store.run(tx=>(name!=='inbox_cloud_messages_server'&&name.startsWith('inbox_')||name==='finish_inbox_dispatch'||name==='take_inbox_conversation'?inboxRpc:name==='disconnect_company_channel'?channelRpc:whatsappCloudRpc)(tx,who,name,{p_company_id:company,...args}));
 const connect=()=>rpc('save_whatsapp_cloud_channel_server',{p_actor:actor.id,p_phone_id:phone,p_waba_id:waba,p_name:'Clínica fictícia',p_verified:true,p_platform:'CLOUD_API',p_cipher:sealChannel(company,credentials)},service);
 const inbound=(body='Olá',time=new Date().toISOString(),messageId=randomUUID())=>rpc('ingest_whatsapp_cloud_server',{p_event:{phoneId:phone,wabaId:waba,messageId,peer,time,body,kind:'text',name:'Contato fictício'}},service);
 beforeEach(async()=>{store=new MemoryStore();company=randomUUID();actor={role:'authenticated',id:randomUUID()};other={role:'authenticated',id:randomUUID()};vi.stubEnv('SECRETS_ENCRYPTION_KEY','a'.repeat(64));vi.stubEnv('META_GRAPH_API_VERSION','v99.0');vi.stubEnv('WHATSAPP_CLOUD_APP_SECRET','fixture-signature-secret');vi.stubEnv('WHATSAPP_CLOUD_VERIFY_TOKEN','fixture-verify-token');vi.stubGlobal('fetch',vi.fn().mockRejectedValue(new Error('Unexpected real network call')));const workspace=randomUUID();await store.run(async tx=>{tx.put('companies',company,{id:company,workspace_id:workspace});tx.put('workspace_members',workspace+'_'+actor.id,{workspace_id:workspace,user_id:actor.id,role:'owner'});});});
 afterEach(()=>{vi.unstubAllGlobals();vi.unstubAllEnvs();});
 it('keeps credentials assigned to one tenant and never accepts client-supplied tokens',()=>{vi.stubEnv('WHATSAPP_CLOUD_CREDENTIALS_JSON',JSON.stringify({[company]:credentials}));expect(configuredCloudCredentials(company)).toEqual(credentials);expect(()=>configuredCloudCredentials(randomUUID())).toThrow();});
 it('verifies WABA membership, verified number and official platform using GET only',async()=>{const fetch=vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({data:[{id:phone}]}))).mockResolvedValueOnce(new Response(JSON.stringify({id:phone,verified_name:'Clínica fictícia',code_verification_status:'VERIFIED',platform_type:'CLOUD_API'})));vi.stubGlobal('fetch',fetch);expect(await verifyCloudNumber(credentials)).toMatchObject({phoneId:phone,wabaId:waba});expect(fetch.mock.calls.every(c=>c[1].method==='GET')).toBe(true);expect(fetch.mock.calls[0][0].href).toContain('/'+waba+'/phone_numbers');});
 it('rejects unverified provider evidence and sanitizes 401/403/429/5xx/timeouts',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({data:[{id:phone}]}))).mockResolvedValueOnce(new Response(JSON.stringify({id:phone,code_verification_status:'NOT_VERIFIED',platform_type:'CLOUD_API'}))));await expect(verifyCloudNumber(credentials)).rejects.toThrow();for(const status of [401,403,429,500]){vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response('fixture-secret-provider-body',{status})));await expect(cloudGraph(phone,'messages',credentials.token,{text:{body:'Fixture'}})).rejects.toThrow();}vi.stubGlobal('fetch',vi.fn().mockRejectedValue(new Error('secret token timeout')));await expect(cloudGraph(phone,'',credentials.token)).rejects.toThrow('O WhatsApp oficial não confirmou esta operação.');});
 it('verifies exact raw-byte signature and webhook challenge before ingestion',()=>{const raw=Buffer.from('{"fixture":true}'),signature='sha256='+createHmac('sha256','fixture-signature-secret').update(raw).digest('hex');expect(()=>verifyCloudSignature(raw,signature)).not.toThrow();expect(()=>verifyCloudSignature(Buffer.from('{ "fixture":true}'),signature)).toThrow();expect(()=>verifyCloudSignature(undefined,signature)).toThrow();expect(verifyCloudChallenge({'hub.mode':'subscribe','hub.verify_token':'fixture-verify-token','hub.challenge':'123'})).toBe('123');expect(()=>verifyCloudChallenge({'hub.mode':'subscribe','hub.verify_token':'wrong','hub.challenge':'123'})).toThrow();});
 it('normalizes signed text without fetching media or trusting unknown event shapes',()=>{const raw=Buffer.from(JSON.stringify({object:'whatsapp_business_account',entry:[{id:waba,changes:[{field:'messages',value:{metadata:{phone_number_id:phone},messages:[{from:peer,id:'wamid.fixture',timestamp:String(Math.floor(Date.now()/1000)),type:'text',text:{body:'Administrativo'}}]}}]}]}));expect(cloudWebhookEvents(raw)[0]).toMatchObject({phoneId:phone,wabaId:waba,peer,body:'Administrativo'});expect(()=>cloudWebhookEvents(Buffer.from('{}'))).toThrow();expect(fetch).not.toHaveBeenCalled();});
 it('stays pending until signed webhook delivery and idempotently receives duplicates',async()=>{expect((await connect() as Row).status).toBe('pending');const messageId=randomUUID();expect(await inbound('Olá',new Date().toISOString(),messageId)).toEqual({received:true});expect(await inbound('Olá',new Date().toISOString(),messageId)).toEqual({duplicate:true});expect((await store.run(tx=>tx.list('company_channels')))[0].status).toBe('connected');const messages=await rpc('read_whatsapp_cloud_inbox',{p_thread:thread}) as Row[];expect(messages).toHaveLength(1);expect(messages[0].fromMe).toBe(false);});
 it('denies actor and tenant spoofing before returning vault material',async()=>{await expect(rpc('save_whatsapp_cloud_channel_server',{p_actor:actor.id})).rejects.toMatchObject({code:'42501'});await connect();await expect(rpc('read_company_whatsapp_server',{p_actor:other.id,p_action:'crm.read'},service)).rejects.toMatchObject({code:'42501'});await expect(rpc('read_whatsapp_cloud_inbox',{},other)).rejects.toMatchObject({code:'42501'});expect(await rpc('ingest_whatsapp_cloud_server',{p_event:{phoneId:phone,wabaId:'111111111',messageId:randomUUID(),peer,time:new Date().toISOString(),body:'Forged',kind:'text',name:''}},service)).toEqual({ignored:true});});
 it('requires human takeover, 24h inbound window, dedup and opt-out before reserving send',async()=>{await connect();await inbound();const args={p_thread:thread,p_id:randomUUID(),p_body:'Informação administrativa'};await expect(rpc('reserve_whatsapp_cloud_dispatch',args)).rejects.toMatchObject({code:'42501'});await rpc('take_inbox_conversation',{p_channel:'whatsapp',p_thread:thread});expect(await rpc('reserve_whatsapp_cloud_dispatch',args)).toBe(true);expect(await rpc('reserve_whatsapp_cloud_dispatch',args)).toBe(false);await rpc('finish_inbox_dispatch',{p_id:args.p_id,p_state:'uncertain',p_provider_id:null});expect(await rpc('reserve_whatsapp_cloud_dispatch',{...args,p_id:randomUUID()})).toBe(false);await inbound('STOP');await expect(rpc('reserve_whatsapp_cloud_dispatch',{...args,p_id:randomUUID(),p_body:'Different'})).rejects.toMatchObject({code:'42501'});});
 it('closes old service windows and filters retained history without inventing provider history',async()=>{await connect();await inbound('Antigo',new Date(Date.now()-2*86400000).toISOString());await rpc('take_inbox_conversation',{p_channel:'whatsapp',p_thread:thread});await expect(rpc('reserve_whatsapp_cloud_dispatch',{p_thread:thread,p_id:randomUUID(),p_body:'Olá'})).rejects.toMatchObject({code:'22023'});const row=(await store.run(tx=>tx.list('whatsapp_cloud_messages')))[0];await store.run(async tx=>tx.put('whatsapp_cloud_messages',row.id,{...row,expires_at:new Date(Date.now()-1000).toISOString()}));expect(await rpc('read_whatsapp_cloud_inbox',{p_thread:thread})).toEqual([]);});
 it('does not manually repeat an automatic dispatch with an uncertain outcome',async()=>{await connect();await inbound();await rpc('take_inbox_conversation',{p_channel:'whatsapp',p_thread:thread});await store.run(async tx=>tx.put('inbox_auto_jobs','fixture-uncertain',{company_id:company,thread,body:'Resposta pendente',state:'uncertain'}));expect(await rpc('reserve_whatsapp_cloud_dispatch',{p_thread:thread,p_id:randomUUID(),p_body:'Resposta pendente'})).toBe(false);});
 it('requires retained inbound history for the currently connected official number',async()=>{await connect();await inbound();await rpc('take_inbox_conversation',{p_channel:'whatsapp',p_thread:thread});const channel=(await store.run(tx=>tx.list('company_channels')))[0],message=(await store.run(tx=>tx.list('whatsapp_cloud_messages')))[0];await store.run(async tx=>tx.put('company_channels',channel.id,{...channel,remote_id:'111111111'}));await expect(rpc('reserve_whatsapp_cloud_dispatch',{p_thread:thread,p_id:randomUUID(),p_body:'Número novo'})).rejects.toMatchObject({code:'22023'});await store.run(async tx=>{tx.put('company_channels',channel.id,channel);tx.put('whatsapp_cloud_messages',message.id,{...message,expires_at:new Date(Date.now()-1000).toISOString()});});await expect(rpc('reserve_whatsapp_cloud_dispatch',{p_thread:thread,p_id:randomUUID(),p_body:'Histórico expirado'})).rejects.toMatchObject({code:'22023'});});
 async function automatic(){await connect();await inbound();await store.run(async tx=>{tx.put('company_onboarding',company,{company_id:company,revision:1,confirmed_revision:1,profile_version:1});tx.put('company_profile_versions',company+'_1',{company_id:company,version:1,facts:{name:{value:'Clínica fictícia',status:'provided'}}});tx.put('company_subscriptions',company,{company_id:company,status:'active',current_period_end:new Date(Date.now()+86400000).toISOString()});});
  await store.run(tx=>inboxRpc(tx,actor,'save_service_settings',{p_company_id:company,p_settings:{channel:'whatsapp',revision:0,mode:'ai',prompt:'Atendimento administrativo',rules:[],fallback:'Equipe humana',automatic:true}}));
  await store.run(tx=>inboxRpc(tx,actor,'save_service_policy',{p_company_id:company,p_policy:{revision:1,profileVersion:1,timezone:'UTC',hours:Array.from({length:7},(_,day)=>({day,start:0,end:1440})),reviewed:true}}));const contact=(await store.run(tx=>tx.list('contacts')))[0];await store.run(tx=>inboxRpc(tx,actor,'save_contact_consent',{p_company_id:company,p_contact_id:contact.id,p_consent:true,p_opt_out:false,p_evidence:'Fixture com consentimento'}));await store.run(async tx=>{const row=await tx.get('company_service_settings',company+'_whatsapp');tx.put('company_service_settings',company+'_whatsapp',{...row,enabled_since:new Date(Date.now()-60000).toISOString()});});await inbound('Nova mensagem');
 }
 function worker(){const instance=new InboxAutomation() as unknown as {db:{rpc:(name:string,args:Row)=>Promise<{data:unknown;error:unknown}>};cloudCompany:(target:Row)=>Promise<void>};instance.db={rpc:async(name,args)=>{try{return {data:await rpc(name,args,service),error:null};}catch(error){return {data:null,error};}}};return instance;}
 it('does not automate a reply using inbound history for a replaced number',async()=>{await automatic();const channel=(await store.run(tx=>tx.list('company_channels')))[0];await store.run(async tx=>tx.put('company_channels',channel.id,{...channel,remote_id:'111111111'}));expect(await rpc('inbox_auto_claim',{p_thread:thread,p_message_id:randomUUID(),p_time:new Date().toISOString()},service)).toBeNull();});
 it('uses the single automation executor for official text and blocks repeat dispatch',async()=>{await automatic();const targets=await rpc('inbox_auto_targets',{},service) as Row[];expect(targets[0]).toMatchObject({provider:'whatsapp_cloud',phoneId:phone});const fetch=vi.fn().mockResolvedValue(new Response(JSON.stringify({messages:[{id:'wamid.auto-fixture'}]})));vi.stubGlobal('fetch',fetch);const instance=worker();await instance.cloudCompany(targets[0]);expect(fetch).toHaveBeenCalledTimes(1);expect(JSON.parse(fetch.mock.calls[0][1].body)).toMatchObject({messaging_product:'whatsapp',to:peer,text:{body:'Resposta administrativa fixture'}});expect((await store.run(tx=>tx.list('inbox_auto_jobs')))[0].state).toBe('sent');await instance.cloudCompany(targets[0]);expect(fetch).toHaveBeenCalledTimes(1);});
 it('persists uncertain official automation on timeout without retrying provider calls',async()=>{await automatic();const target=(await rpc('inbox_auto_targets',{},service) as Row[])[0],instance=worker(),fetch=vi.fn().mockRejectedValue(new Error('Timeout fixture'));vi.stubGlobal('fetch',fetch);await instance.cloudCompany(target);expect((await store.run(tx=>tx.list('inbox_auto_jobs')))[0].state).toBe('uncertain');await instance.cloudCompany(target);expect(fetch).toHaveBeenCalledTimes(1);});
 it('records provider-accepted outgoing text and removes vault access on disconnect',async()=>{await connect();await inbound();await rpc('take_inbox_conversation',{p_channel:'whatsapp',p_thread:thread});const id=randomUUID();await rpc('reserve_whatsapp_cloud_dispatch',{p_thread:thread,p_id:id,p_body:'Resposta'});await rpc('finish_inbox_dispatch',{p_id:id,p_state:'sent',p_provider_id:'wamid.outgoing-fixture'});expect((await rpc('read_whatsapp_cloud_inbox',{p_thread:thread}) as Row[]).find(m=>m.fromMe)).toMatchObject({body:'Resposta',status:'accepted'});await rpc('disconnect_company_channel',{p_provider:'whatsapp_cloud'});expect(await rpc('read_company_whatsapp_server',{p_actor:actor.id,p_action:'crm.read'},service)).toBeNull();expect(fetch).not.toHaveBeenCalled();});
});
