import {z} from 'zod';
export const studentSchema=z.object({externalId:z.string().trim().min(1).max(100),name:z.string().trim().min(1).max(150),phone:z.string().regex(/^\+[1-9][0-9]{7,14}$/),birthday:z.iso.date().nullable(),lastAttendance:z.iso.datetime({offset:true}).nullable(),status:z.enum(['active','inactive']),consent:z.boolean(),tag:z.string().trim().max(80).default('')}).strict();
export type CampaignStudent=z.infer<typeof studentSchema>;
export const messageCampaignSchema=z.object({id:z.uuid(),revision:z.number().int().nonnegative(),name:z.string().trim().min(1).max(120),trigger:z.enum(['birthday','absence','selected']),recipientIds:z.array(z.uuid()).max(500).default([]),absenceDays:z.number().int().min(1).max(365),sendTime:z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/),message:z.string().trim().min(1).max(2000),tag:z.string().trim().max(80).default(''),activeOnly:z.boolean(),startDate:z.iso.date(),endDate:z.iso.date().nullable(),maxDataAgeDays:z.number().int().min(1).max(30),dailyLimit:z.number().int().min(1).max(200)}).strict().refine(v=>v.trigger!=='selected'||v.recipientIds.length>0,{message:'Selecione os contatos'}).refine(v=>!v.endDate||v.endDate>=v.startDate,{message:'Data final anterior à inicial'}).refine(v=>[...v.message.matchAll(/\{\{([^}]+)\}\}/g)].every(m=>['nome','clinica','academia','dias_ausente'].includes(m[1]!.trim())),{message:'Use apenas nome, clinica e dias_ausente como variáveis'});
export type MessageCampaignInput=z.infer<typeof messageCampaignSchema>;
export type MessageCampaign=MessageCampaignInput&{status:'draft'|'active'|'paused';timezone:string;updatedAt:string};
export function personalizeCampaign(message:string,student:{name:string;daysAbsent:number|null},companyName:string){return message.replace(/\{\{\s*(nome|clinica|academia|dias_ausente)\s*\}\}/g,(_,key:string)=>key==='nome'?student.name:(key==='academia'||key==='clinica')?companyName:String(student.daysAbsent??''));}
export function parseStudentsCsv(csv:string):CampaignStudent[]{
 const lines=csv.replace(/^\uFEFF/,'').split(/\r?\n/).filter(l=>l.trim());if(lines.length<2||lines.length>501)throw new Error('Importe entre 1 e 500 contatos por arquivo.');
 const split=(line:string)=>{const fields:string[]=[];let value='',quoted=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(quoted&&line[i+1]==='"'){value+='"';i++;}else quoted=!quoted;}else if(c===';'&&!quoted){fields.push(value.trim());value='';}else value+=c;}if(quoted)throw new Error('Aspas não fechadas no CSV.');fields.push(value.trim());return fields;};
 const header=split(lines[0]!);const expected=['id_paciente','nome','telefone','nascimento','ultimo_atendimento','situacao','autoriza_mensagens','grupo'];const legacy=['id_aluno','nome','telefone','nascimento','ultima_presenca','situacao','autoriza_mensagens','grupo'];if(header.join(';')!==expected.join(';')&&header.join(';')!==legacy.join(';'))throw new Error('Use o cabeçalho do modelo CSV fornecido.');
 const ids=new Set<string>();return lines.slice(1).map((line,index)=>{const row=split(line);if(row.length!==8)throw new Error('Confira as colunas da linha '+(index+2)+'.');const [externalId,name,phone,birthday,lastAttendance,status,consent,tag]=row;if(!['sim','nao'].includes(consent!)||!['ativo','inativo'].includes(status!))throw new Error('Situação ou autorização inválida na linha '+(index+2)+'.');const parsed=studentSchema.safeParse({externalId,name,phone,birthday:birthday||null,lastAttendance:lastAttendance||null,status:status==='ativo'?'active':'inactive',consent:consent==='sim',tag});if(!parsed.success)throw new Error('Dados inválidos na linha '+(index+2)+'. Use telefone internacional, data AAAA-MM-DD e presença com data/hora e fuso.');if(ids.has(parsed.data.externalId))throw new Error('ID de contato duplicado no arquivo.');ids.add(parsed.data.externalId);return parsed.data;});
}
