import {z} from 'zod';

export const supportStatuses=['open','in_progress','waiting_customer','resolved'] as const;
export type SupportStatus=typeof supportStatuses[number];
export const supportStatusLabels:Record<SupportStatus,string>={open:'Aberto',in_progress:'Em atendimento',waiting_customer:'Aguardando você',resolved:'Resolvido'};
export const supportTranscriptSchema=z.array(z.object({role:z.enum(['user','assistant']),text:z.string().trim().min(1).max(2000)}).strict()).max(8);
export const supportTicketSchema=z.object({requestId:z.uuid(),companyId:z.uuid().nullable(),subject:z.string().trim().min(5).max(160),message:z.string().trim().min(10).max(4000),page:z.string().max(160).regex(/^\/[a-zA-Z0-9/_-]*$/),transcript:supportTranscriptSchema.default([])}).strict();
export const supportReplySchema=z.object({requestId:z.uuid(),message:z.string().trim().min(1).max(4000)}).strict();
export type SupportTicket={id:string;number:number;company_id:string|null;company_name:string|null;created_by:string;subject:string;status:SupportStatus;page:string;transcript:z.infer<typeof supportTranscriptSchema>;created_at:string;updated_at:string;version:number};
export type SupportMessage={id:string;ticket_id:string;author_id:string;author_kind:'customer'|'staff';body:string;created_at:string};
export type SupportDetail={ticket:SupportTicket;messages:SupportMessage[]};
export const supportProtocol=(value:number)=>'ASK-'+String(value).padStart(6,'0');

export type SupportArticle={id:string;group:string;title:string;answer:string;keywords:string;updatedAt:string};
export const supportGroups=[{id:'acesso',title:'Acesso e primeiros passos'},{id:'planos-ajuda',title:'Planos e contratação'},{id:'conteudo-ajuda',title:'Estratégia e publicações'},{id:'conexoes-ajuda',title:'Atendimento e integrações'},{id:'site-ajuda',title:'Site e endereço da clínica'}];
const record=(id:string,group:string,title:string,answer:string,keywords:string):SupportArticle=>({id,group,title,answer,keywords,updatedAt:'2026-09-29'});
/** Reviewed product guidance only. Never index credentials, internal logs or another customer's conversations. */
export const supportArticles:SupportArticle[]=[
 record('recuperar-senha','acesso','Esqueci minha senha. Como recupero?','Abra a página de login e escolha “Esqueci minha senha”. Informe o e-mail da sua conta e siga as instruções recebidas. Confira spam e se o endereço foi digitado corretamente.','senha esqueci recuperar redefinir acesso login entrar'),
 record('primeiros-passos','acesso','Por onde começo depois de criar a conta?','Confirme seu e-mail e entre no sistema. Na conversa inicial, informe o nome e a cidade da clínica, confirme o estabelecimento e responda às perguntas. Depois, escolha um plano e confirme o checkout. A pesquisa e a criação com IA só começam após essa confirmação.','cadastro conta onboarding começar comecar iniciar email confirmação'),
 record('atualizar-perfil','acesso','Como atualizo as informações da clínica?','Abra Perfil e marca para consultar os dados confirmados. Na Estratégia, use a opção de consultar e atualizar o perfil para revisar a conversa. Alterações podem exigir nova pesquisa, estratégia e aprovações.','perfil marca clínica dados endereço cidade atualizar corrigir informações'),
 record('checkout-bloqueado','planos-ajuda','O botão de escolher o plano está desabilitado.','Se a seleção mostrar “Contratação disponível em breve”, o checkout está indisponível neste ambiente. Seu onboarding continua salvo. Abra um chamado para a equipe verificar a configuração. Se a tela pedir o responsável pelo workspace, entre com a conta proprietária.','plano planos comprar compra checkout contratação botao botão escolher desativado desabilitado bloqueado disponível breve deploy'),
 record('planos-valores','planos-ajuda','Quais são os planos e as parcelas?','Os valores são por empresa: mensal recorrente de R$ 1.597 ou semestral de R$ 8.000, em até 6 parcelas no cartão. Em 6 vezes, são cinco parcelas de R$ 1.333,33 e a última de R$ 1.333,35. Anúncios e provedores externos são cobrados à parte.','preço preço valores valor mensal semestral parcelas cartão orçamento assinatura planos'),
 record('checkout-teste','planos-ajuda','O checkout de teste faz uma cobrança?','Não. Quando a tela indicar ambiente de teste, a confirmação é uma simulação sem cartão ou cobrança real. O teste libera sete dias de acesso à IA para aquela empresa. Confira o resumo e a indicação de teste antes de confirmar.','teste pagamento cobrança cobrado simulado simulação cartão sete dias ia'),
 record('etapas-estrategia','conteudo-ajuda','Como aprovo minha estratégia?','Na Estratégia, revise as etapas: concorrentes e análise; planos de longo, médio e curto prazo; publicações; campanhas de mensagens; campanhas de tráfego. O diagnóstico vem após a análise dos concorrentes. Aprove cada etapa para continuar. Alterações invalidam a aprovação da versão anterior.','estratégia etapas diagnóstico aprovar aprovação plano marketing metas'),
 record('instagram-concorrentes','conteudo-ajuda','Onde encontro a pesquisa dos concorrentes no Instagram?','A pesquisa aparece em Estratégia → Concorrentes e análise após a confirmação do plano. Confira os candidatos encontrados e confirme o perfil correto. Nomes parecidos não comprovam a identidade. Métricas dependem da disponibilidade da integração; dados ausentes não são estimados como reais.','instagram concorrentes pesquisa perfis análise resultados busca google'),
 record('geracao-bloqueada','conteudo-ajuda','Por que o botão de gerar está desabilitado?','Confira a mensagem ao lado do botão. A geração exige plano confirmado, permissões, aprovações da etapa e disponibilidade do provedor. O calendário mostra o andamento da preparação. Se todos os requisitos estiverem atendidos e o erro persistir, abra um chamado.','gerar geração criativo imagem imagens desabilitado erro falha calendário conteúdo'),
 record('aprovar-conteudo','conteudo-ajuda','Quando os criativos são preparados e aprovados?','As ideias e as datas são apresentadas para aprovação. Os criativos são preparados com antecedência de sete dias para revisão. Abra a peça no calendário, confira texto e material e aprove a versão final. Alterar o conteúdo exige nova aprovação.','criativos semana antecedência sete dias data datas calendário aprovar postagem publicação'),
 record('publicacao-video','conteudo-ajuda','Como finalizo uma publicação em vídeo?','Abra a publicação no calendário, consulte o roteiro, grave e edite o material. Envie o vídeo final pela própria publicação, revise e aprove a peça. O roteiro sozinho não representa um vídeo pronto.','video vídeo roteiro gravar upload arquivo enviar finalizar'),
 record('publicacao-status','conteudo-ajuda','Uma publicação com data já está nas redes sociais?','Uma data no calendário representa planejamento. Confira o status da publicação e a conexão do canal. A aprovação da peça, a autorização do canal e a confirmação de publicação são etapas diferentes; não considere uma peça publicada só porque tem data.','post postado publicado publicação publicar rede redes status agendado agendamento'),
 record('limites-atendimento','conexoes-ajuda','A IA realiza atendimento médico ou confirma consultas?','A MedSI apoia o atendimento administrativo. A equipe confirma horários e cuida das questões clínicas. O assistente não faz diagnóstico, prescrição ou interpretação de exames. Não envie prontuários ou dados de saúde para preparar marketing. A conexão de uma agenda clínica exige um conector homologado.','médico médica sintomas diagnóstico exames prontuário consulta consultas agenda agendamento confirmação tratamento'),
 record('whatsapp-automacao','conexoes-ajuda','Conectei o WhatsApp, mas a IA não responde.','Conectar o número não ativa a automação. Abra Configuração de Atendimento, selecione IA ou fluxo, revise as informações, faça o teste e habilite a resposta automática. Ao assumir uma conversa, o atendimento humano pausa a IA.','whatsapp responde responder resposta automático automação evolution fluxo atendimento ia'),
 record('enviar-mensagem','conexoes-ajuda','Não consigo enviar uma mensagem pela caixa de entrada.','Verifique se o canal está conectado e assuma o atendimento da conversa para habilitar o envio. Se houver erro, preserve o texto e confira a mensagem apresentada antes de tentar novamente.','enviar envio mensagem mensagens caixa entrada chat conversa assumir'),
 record('conectar-whatsapp','conexoes-ajuda','Como conecto o WhatsApp pela Evolution?','Abra Integrações da empresa e a conexão WhatsApp. Solicite o QR code e leia-o pelo WhatsApp do número autorizado. Aguarde a conexão ser confirmada. A automação é configurada separadamente em Configuração de Atendimento.','whatsapp conectar conexão evolution qrcode qr code desconectado integrações'),
 record('meta-mensagens','conexoes-ajuda','Instagram e Facebook não mostram mensagens.','Confira em Integrações as permissões de mensagens e a Página selecionada. Autorizar publicações não significa autorizar o Direct ou Messenger. A disponibilidade depende dos requisitos e da homologação da Meta.','instagram facebook meta direct messenger mensagens permissões página'),
 record('campanhas-trafego','conexoes-ajuda','Como os anúncios são ativados?','Revise orçamento, público, texto, criativo, região e datas na campanha. Após a aprovação, a execução segue a programação quando a integração e a conta de anúncios estão disponíveis. Bloqueios de saldo e do provedor aparecem no acompanhamento. Aprovar não comprova que o anúncio já está sendo entregue.','anúncios anuncio ads meta facebook google tráfego campanha orçamento saldo insuficiente ativação'),
 record('campanhas-relacionamento','conexoes-ajuda','Como uso aniversários e ausência nas campanhas?','Importe dados atualizados dos pacientes ou configure o recebimento pela API da empresa. Revise consentimentos, condições, destinatários, texto e horários. Após a aprovação, o envio segue a programação e depende do canal conectado.','aniversário ausência pacientes campanhas relacionamento vendas público destinatários condições'),
 record('editar-site','site-ajuda','Como edito o site sem mudar a página publicada?','Em Meu site, clique em Editar site. As alterações ficam no rascunho enquanto você revisa a prévia. Publicar é uma ação separada. Salve os textos antes de configurar o domínio.','site landing página editar edição imagem imagem texto rascunho publicar'),
 record('dominio-site','site-ajuda','Meu domínio ou subdomínio não abre.','Reservar o nome não publica a página. Confira se o site foi publicado e se DNS, encaminhamento e HTTPS foram configurados. A aba Domínio e endereço mostra a situação e as orientações disponíveis.','domínio subdomínio dns endereço https certificado site abre abrir reservado'),
];
const normalize=(value:string)=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9 ]/g,' ');
const stop=new Set('como para porque por que nao não uma uns das dos meu meus minha minhas esse essa isso esta está estou tenho tem foi ser com sem muito mais onde qual quais quero preciso ajuda problema sistema consigo fazer funciona funcionar erro falha'.split(' '));
const tokens=(value:string)=>[...new Set(normalize(value).split(/\s+/).filter(word=>word.length>2&&!stop.has(word)))];
export function searchSupport(question:string):{kind:'answer'|'suggestions'|'handoff';articles:SupportArticle[]}{
 const normalized=normalize(question);
 if(/\b(humano|especialista|atendente|chamado)\b|nao resolveu|nao funcionou|continua igual/.test(normalized))return {kind:'handoff',articles:[]};
 const words=tokens(question);if(!words.length)return {kind:'handoff',articles:[]};
 const documents=supportArticles.map(article=>({article,terms:tokens(article.title+' '+article.keywords)}));
 const matches=documents.map(({article,terms})=>{const hits=words.filter(word=>terms.includes(word));return {article,hits:hits.length,coverage:hits.length/words.length,score:hits.reduce((sum,word)=>sum+Math.log(1+documents.length/(1+documents.filter(d=>d.terms.includes(word)).length)),0)};}).filter(x=>x.hits>0).sort((a,b)=>b.score-a.score);
 const first=matches[0];if(!first||first.coverage<0.3)return {kind:'handoff',articles:[]};
 const certain=first.hits>=2&&first.coverage>=0.5&&(!matches[1]||first.score>matches[1].score*1.2);
 return {kind:certain?'answer':'suggestions',articles:matches.slice(0,certain?1:3).map(x=>x.article)};
}
