import Link from 'next/link';
import { ArrowRight, Check, Palette, Target, CalendarDays } from 'lucide-react';
import { MarketingShell, ProductPreview, SectionHeading, FinalCta, Faq, marketingMetadata, signupHref } from '../../../components/marketing-site';
import s from '../../home.module.css';
export const metadata=marketingMetadata('Conteúdo e estratégia para sua clínica','Uma estratégia com a identidade da sua clínica. Planeje temas, prepare textos e artes com IA e organize as aprovações no calendário da MedSI.','/lp/marketing-medico');
export default function MarketingMedico(){return <MarketingShell focused>
  <section className={s.hero}><div className={s.heroCopy}><span className={s.eyebrow}>ESTRATÉGIA E CONTEÚDO PARA MÉDICOS E CLÍNICAS</span><h1>Apresente o cuidado da sua clínica.<br/><span>Desde o primeiro contato.</span></h1><p>Seu espaço, sua equipe e suas especialidades têm histórias para contar. A MedSI ajuda a transformar tudo isso em conteúdo com propósito, consistência e a identidade da sua marca.</p><div className={s.actions}><Link href={signupHref} className={s.primary}>Quero organizar meu marketing <ArrowRight size={18}/></Link></div><p className={s.microcopy}>Crie seu acesso e comece pelo perfil da clínica.</p></div><ProductPreview/></section>
  <section className={s.section} id="beneficios"><SectionHeading eyebrow="DA IDEIA SOLTA AO CALENDÁRIO" title="Quando há direção, cada publicação tem um papel." description="Apresentar suas especialidades. Valorizar sua estrutura. Explicar seus diferenciais. Em vez de partir de uma página em branco, comece com um plano para o seu negócio."/><div className={s.benefitGrid}>
    <article><span className={s.featureIcon}><Target size={23}/></span><h3>Estratégia com contexto.</h3><p>A IA usa as informações confirmadas no onboarding para propor posicionamento, objetivos, temas e ações. Você pode editar ou pedir ajustes antes de aprovar.</p></article>
    <article><span className={s.featureIcon}><Palette size={23}/></span><h3>Uma marca reconhecível.</h3><p>Fotos da clínica, logo e referências orientam os textos e o design. Você confere se cada peça está de acordo com o que quer comunicar.</p></article>
    <article><span className={s.featureIcon}><CalendarDays size={23}/></span><h3>Uma rotina possível.</h3><p>Ideias distribuídas no calendário, com datas de planejamento, status e tarefas. Sua equipe sabe o que precisa revisar, gravar ou enviar.</p></article>
  </div></section>
  <section className={s.workflowSection}><div className={s.workflowInner}><div><span className={s.eyebrow}>SEU CONHECIMENTO VIRA MATÉRIA-PRIMA</span><h2>Uma conversa sobre sua clínica.<br/><span>Um plano para mostrar seu valor.</span></h2><p>Você traz o que só quem vive a operação conhece. A MedSI ajuda a organizar e transformar esse conhecimento em comunicação.</p><Link className={s.lightButton} href={signupHref}>Apresentar minha clínica <ArrowRight size={17}/></Link></div><ol className={s.steps}>{[['Apresente o negócio','Conte sobre público, especialidades, diferenciais e objetivos. Envie fotos e referências.'],['Ajuste a direção','Revise o diagnóstico e a proposta de estratégia. Peça mudanças quando necessário.'],['Acompanhe a produção','Textos, roteiros e artes ficam no calendário. Envie os vídeos depois de gravar e editar.'],['Aprove a versão certa','Confira legenda e material final antes da aprovação. Planeje canal, data e horário.']].map(([title,body],i)=><li key={title}><span>0{i+1}</span><div><h3>{title}</h3><p>{body}</p></div></li>)}</ol></div></section>
  <section className={s.section}><SectionHeading eyebrow="O QUE VOCÊ ORGANIZA NA MEDSI" title="Uma operação de conteúdo que sua equipe consegue acompanhar."/><div className={s.solutionGrid}><article><h3>Da estratégia à peça.</h3><ul className={s.checks}>{['Diagnóstico e posicionamento propostos pela IA','Calendário com temas e contexto sazonal','Legendas, roteiros e artes para revisar','Histórico de versões e aprovações'].map(t=><li key={t}><Check size={17}/>{t}</li>)}</ul></article><article><h3>Do material à presença digital.</h3><ul className={s.checks}>{['Materiais e identidade separados por clínica','Tarefas de gravação e envio de vídeos','Criação e edição de uma página da clínica','Equipe com papéis e acessos definidos'].map(t=><li key={t}><Check size={17}/>{t}</li>)}</ul></article></div></section>
  <Faq items={[
    ['A IA cria conteúdo sem conhecer minha clínica?','A preparação parte das informações que você confirma e dos materiais enviados. Quanto melhor esse contexto, mais referências a MedSI tem para orientar a criação. Você pode corrigir o perfil e revisar a estratégia.'],
    ['Posso mudar os textos e pedir outra estratégia?','Sim. A estratégia pode receber ajustes e feedback para uma nova proposta. Você também revisa os materiais. Alterações relevantes exigem nova aprovação da versão.'],
    ['Os vídeos são gerados prontos?','A MedSI prepara roteiros. A gravação, edição e envio do arquivo final ficam com sua equipe ou fornecedor de vídeo.'],
    ['As publicações já são enviadas automaticamente às redes?','O calendário organiza a produção, as datas de planejamento e as aprovações. A publicação automática nas redes ainda está em evolução e depende das integrações autorizadas. Não considere uma data no calendário como confirmação de postagem.'],
    ['Preciso contratar ao criar minha conta?','O cadastro não gera assinatura nem cobrança automática. A disponibilidade dos recursos e os limites de uso são apresentados no ambiente da empresa.'],
  ]}/>
  <FinalCta title="Sua clínica já tem o que mostrar. Dê direção a essa história." description="Comece pelo seu negócio. Construa uma presença que tenha a sua identidade." label="Começar meu planejamento"/>
</MarketingShell>;}
