import {randomBytes,createHash,randomUUID} from 'node:crypto';
import {BadRequestException,Body,Controller,ForbiddenException,Get,Param,Post,Req,ServiceUnavailableException,UseGuards} from '@nestjs/common';
import {z} from 'zod';
import {metaPermissions,metaAccess} from '@askadia/contracts';
import {AuthGuard,type AuthRequest} from '../identity/auth';
import {result} from '../identity/service';
const hash=(s:string)=>createHash('sha256').update(s).digest('hex');
import {secretKey,sealChannel,openChannel} from './channel-vault';
export {sealChannel,openChannel} from './channel-vault';
function parse<T>(s:z.ZodType<T>,v:unknown){const p=s.safeParse(v);if(!p.success)throw new BadRequestException('Confira os dados da conexão.');return p.data;}
async function owner(r:AuthRequest,company:string){parse(z.uuid(),company);const c=result<{actions:string[]}>(await r.actor.client.rpc('company_capabilities',{p_company_id:company}));if(!c.actions.includes('billing.manage'))throw new ForbiddenException('O proprietário precisa autorizar a conexão da empresa.');}
export function metaConfigured(){let secureOrigin=false;try{const origin=new URL(process.env.WEB_ORIGIN||'http://127.0.0.1:3000');secureOrigin=origin.protocol==='https:'&&!['localhost','127.0.0.1'].includes(origin.hostname);}catch{/* Invalid deployment origin keeps OAuth unavailable. */}return secureOrigin&&Boolean(process.env.META_APP_ID&&process.env.META_APP_SECRET&&/^v\d+\.\d+$/.test(process.env.META_GRAPH_API_VERSION??'')&&process.env.SECRETS_ENCRYPTION_KEY);}
function metaVersion(){if(!metaConfigured())throw new ServiceUnavailableException('Configure o aplicativo Meta e a origem pública HTTPS da MedSI. Cada empresa fará sua própria autorização depois.');return process.env.META_GRAPH_API_VERSION!;}
const redirect=()=>new URL('/api/connections/meta/callback',process.env.WEB_ORIGIN||'http://127.0.0.1:3000').href;
export type MetaPage={id:string;name:string;access_token:string;tasks?:string[];instagram_business_account?:{id:string;username?:string}};
class MetaGraphError extends ServiceUnavailableException{constructor(public readonly providerCode:number|null){super(providerCode===190?'A autorização da Meta expirou. Conecte novamente para escolher a Página.':'A Meta recusou a consulta. Confira as permissões e reconecte a conta.');}}
async function graph<T>(path:string,token:string,params:Record<string,string>={}):Promise<T>{const url=new URL('https://graph.facebook.com/'+metaVersion()+'/'+path);for(const [k,v] of Object.entries(params))url.searchParams.set(k,v);const r=await fetch(url,{headers:{Authorization:'Bearer '+token},signal:AbortSignal.timeout(12000),redirect:'error'});if(!r.ok){const error=await r.json().catch(()=>null) as {error?:{code?:number}}|null;throw new MetaGraphError(typeof error?.error?.code==='number'?error.error.code:null);}return r.json() as Promise<T>;}
export async function metaPages(token:string,scopes:string[]){
 const out:MetaPage[]=[];let after:string|undefined;let instagram=scopes.includes('instagram_basic');let instagramUnavailable=!instagram;
 for(let n=0;n<10;n++){
  const params={fields:'id,name,access_token,tasks'+(instagram?',instagram_business_account{id,username}':''),limit:'100',...(after?{after}:{})};
  type PageResult={data:MetaPage[];paging?:{cursors?:{after?:string};next?:string}};
  let p:PageResult;
  try{p=await graph<PageResult>('me/accounts',token,params);}catch(error){
   if(!instagram||!(error instanceof MetaGraphError)||![10,100,200].includes(error.providerCode??0))throw error;
   // Optional Instagram fields must not hide Facebook Pages the user can authorize.
   instagram=false;instagramUnavailable=true;p=await graph<PageResult>('me/accounts',token,{...params,fields:'id,name,access_token,tasks'});
  }
  if(!Array.isArray(p.data)||p.data.some(page=>typeof page.id!=='string'||!/^\d+$/.test(page.id)||typeof page.name!=='string'))throw new ServiceUnavailableException('A Meta não retornou uma lista válida de Páginas. Tente conectar novamente.');
  out.push(...p.data);if(!p.paging?.next)break;after=p.paging.cursors?.after;if(!after)break;
 }
 return {pages:Array.from(new Map(out.map(page=>[page.id,page])).values()),instagramUnavailable};
}
async function metaScopes(token:string){const permissions=await graph<{data:{permission:string;status:string}[]}>('me/permissions',token);return permissions.data.filter(p=>p.status==='granted').map(p=>p.permission);}
type MetaSelection={pages:MetaPage[];userToken?:string;scopes:string[];expiresAt:string|null;instagramUnavailable?:boolean};
export class EvolutionError extends ServiceUnavailableException{constructor(public readonly providerStatus:number){super(providerStatus===401||providerStatus===403?'A Evolution recusou a credencial. Confira a chave configurada no servidor.':providerStatus===404?'A instância ainda não existe na Evolution.':providerStatus===429?'A Evolution atingiu o limite de solicitações. Tente novamente em instantes.':'A Evolution não concluiu a operação. Confira o servidor e tente novamente.');}}
export async function findEvolutionInstance(instance:string){try{const list=await evolutionRequest('/instance/fetchInstances?instanceName='+encodeURIComponent(instance)) as unknown as {name?:string;instance?:{instanceName?:string}}[];if(!Array.isArray(list))throw new ServiceUnavailableException('A Evolution retornou uma lista de instâncias inválida.');return list.some(i=>(i.name??i.instance?.instanceName)===instance);}catch(e){if(e instanceof EvolutionError&&e.providerStatus===404)return false;throw e;}}
export async function ensureEvolutionInstance(instance:string){if(await findEvolutionInstance(instance))return;try{await evolutionRequest('/instance/create',{instanceName:instance,integration:'WHATSAPP-BAILEYS',qrcode:true,groupsIgnore:true,syncFullHistory:false,readMessages:false,readStatus:false});}catch(e){if(e instanceof EvolutionError&&[400,409].includes(e.providerStatus)&&await findEvolutionInstance(instance))return;throw e;}}
export async function evolutionRequest(path:string,body?:unknown,options?:{timeout:number;maxBytes:number}){const raw=process.env.EVOLUTION_API_URL,key=process.env.EVOLUTION_API_KEY;if(!raw||!key)throw new ServiceUnavailableException('Servidor Evolution ainda não configurado.');const base=new URL(raw);if(base.protocol!=='https:'||base.username||base.password)throw new ServiceUnavailableException('Configure uma URL HTTPS válida para a Evolution.');const response=await fetch(new URL(path,base),{method:body?'POST':'GET',headers:{apikey:key,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(options?.timeout??15000),redirect:'error'});if(!response.ok)throw new EvolutionError(response.status);if(options&&response.body){const reader=response.body.getReader();const chunks:Uint8Array[]=[];let size=0;try{for(;;){const next=await reader.read();if(next.done)break;size+=next.value.length;if(size>options.maxBytes){await reader.cancel();throw new ServiceUnavailableException('Arquivo acima do limite permitido.');}chunks.push(next.value);}return JSON.parse(Buffer.concat(chunks).toString('utf8')) as Record<string,unknown>;}finally{reader.releaseLock();}}return response.json() as Promise<Record<string,unknown>>;}
@Controller('onboarding')
@UseGuards(AuthGuard)
export class ChannelsController{
 @Get('companies/:id/channels') async list(@Req() r:AuthRequest,@Param('id') company:string){parse(z.uuid(),company);const c=result<{actions:string[]}>(await r.actor.client.rpc('company_capabilities',{p_company_id:company}));if(!c.actions.includes('marketing.read'))throw new ForbiddenException();return {channels:result(await r.actor.client.from('company_channels').select('*').eq('company_id',company)),metaConfigured:metaConfigured(),evolutionConfigured:Boolean(process.env.EVOLUTION_API_URL&&process.env.EVOLUTION_API_KEY),canConnect:c.actions.includes('billing.manage'),webhookConfigured:false};}
 @Post('companies/:id/channels/meta/start') async start(@Req() r:AuthRequest,@Param('id') company:string,@Body() body:unknown){await owner(r,company);const input=parse(z.object({features:z.array(z.enum(['insights','publishing','ads','messaging'])).max(4).default([])}).strict(),body??{});const version=metaVersion(),session=randomUUID(),nonce=randomBytes(32).toString('hex');result(await r.actor.client.rpc('begin_meta_session',{p_company_id:company,p_id:session,p_hash:hash(nonce)}));const url=new URL('https://www.facebook.com/'+version+'/dialog/oauth');url.searchParams.set('client_id',process.env.META_APP_ID!);url.searchParams.set('redirect_uri',redirect());url.searchParams.set('state',session+'.'+nonce);url.searchParams.set('response_type','code');url.searchParams.set('scope',metaPermissions(input.features).join(','));url.searchParams.set('auth_type','rerequest');return {url:url.href};}
 @Post('channels/meta/callback') async callback(@Req() r:AuthRequest,@Body() body:unknown){
  const input=parse(z.object({state:z.string().regex(/^[a-f0-9-]{36}\.[a-f0-9]{64}$/),code:z.string().min(1).max(4000)}).strict(),body);const [session,nonce]=input.state.split('.');const company=result<string>(await r.actor.client.rpc('consume_meta_session',{p_id:session,p_hash:hash(nonce!)}));await owner(r,company);
  const exchange=new URL('https://graph.facebook.com/'+metaVersion()+'/oauth/access_token');const tokenResponse=await fetch(exchange,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:process.env.META_APP_ID!,client_secret:process.env.META_APP_SECRET!,redirect_uri:redirect(),code:input.code}),signal:AbortSignal.timeout(12000),redirect:'error'});if(!tokenResponse.ok)throw new BadRequestException('A autorização Meta expirou ou foi recusada. Tente conectar novamente.');const token=await tokenResponse.json() as {access_token:string;expires_in?:number};if(!token.access_token)throw new BadRequestException('A Meta não retornou autorização.');
  const scopes=await metaScopes(token.access_token);const discovered=await metaPages(token.access_token,scopes);result(await r.actor.client.rpc('save_meta_selection',{p_id:session,p_cipher:sealChannel(company,{...discovered,userToken:token.access_token,scopes,expiresAt:token.expires_in?new Date(Date.now()+token.expires_in*1000).toISOString():null})}));return {companyId:company,sessionId:session};
 }
 @Post('companies/:id/channels/meta/pages') async pages(@Req() r:AuthRequest,@Param('id') company:string,@Body() body:unknown){
  await owner(r,company);const {sessionId,refresh}=parse(z.object({sessionId:z.uuid(),refresh:z.boolean().default(false)}).strict(),body);
  const cipher=result<string>(await r.actor.client.rpc('read_meta_selection',{p_company_id:company,p_id:sessionId}));let selection=openChannel<MetaSelection>(company,cipher);
  if(refresh){if(!selection.userToken)throw new BadRequestException('Conecte novamente para atualizar as Páginas autorizadas.');const scopes=await metaScopes(selection.userToken);selection={...selection,...await metaPages(selection.userToken,scopes),scopes};result(await r.actor.client.rpc('save_meta_selection',{p_id:sessionId,p_cipher:sealChannel(company,selection)}));}
  return {pages:selection.pages.map(p=>({id:p.id,name:p.name,instagramId:p.instagram_business_account?.id,instagramName:p.instagram_business_account?.username,canConnect:typeof p.access_token==='string'&&p.access_token.length>0})),instagramUnavailable:selection.instagramUnavailable??false,missingPagePermission:!selection.scopes.includes('pages_show_list')};
 }
 @Post('companies/:id/channels/meta/select') async select(@Req() r:AuthRequest,@Param('id') company:string,@Body() body:unknown){await owner(r,company);const input=parse(z.object({sessionId:z.uuid(),pageId:z.string().regex(/^\d+$/)}).strict(),body);const cipher=result<string>(await r.actor.client.rpc('read_meta_selection',{p_company_id:company,p_id:input.sessionId}));const session=openChannel<{pages:MetaPage[];userToken?:string;scopes:string[];expiresAt:string|null}>(company,cipher);const page=session.pages.find(p=>p.id===input.pageId);if(!page)throw new ForbiddenException('Selecione uma página autorizada.');if(typeof page.access_token!=='string'||!page.access_token)throw new ForbiddenException('A Meta não liberou acesso a esta Página. Revise as permissões no Facebook e conecte novamente.');await graph(page.id,page.access_token,{fields:'id'});return result(await r.actor.client.rpc('save_company_channel',{p_company_id:company,p_provider:'meta',p_remote:page.id,p_name:page.name,p_status:'connected',p_metadata:{tasks:page.tasks??[],access:metaAccess(session.scopes,page.instagram_business_account?.id??null,page.tasks??[]),instagramId:page.instagram_business_account?.id??null,instagramName:page.instagram_business_account?.username??null,scopes:session.scopes,expiresAt:session.expiresAt,publishingReady:session.scopes.includes('instagram_content_publish')&&Boolean(page.instagram_business_account),insightsReady:session.scopes.includes('instagram_manage_insights')&&Boolean(page.instagram_business_account)},p_cipher:sealChannel(company,{token:page.access_token,userToken:session.userToken}),p_session:input.sessionId}));}
 @Post('companies/:id/channels/evolution/connect') async connect(@Req() r:AuthRequest,@Param('id') company:string){await owner(r,company);secretKey();const instance='askadia-'+company;await ensureEvolutionInstance(instance);
  const current=await evolutionRequest('/instance/connectionState/'+encodeURIComponent(instance));if((current.instance as {state?:string}|undefined)?.state==='open'){await this.state(r,company);return {qr:null,message:'WhatsApp já conectado. Abra a Caixa de entrada para consultar suas conversas.'};}
  const qr=await evolutionRequest('/instance/connect/'+encodeURIComponent(instance));result(await r.actor.client.rpc('save_company_channel',{p_company_id:company,p_provider:'evolution',p_remote:instance,p_name:'WhatsApp da empresa',p_status:'pending',p_metadata:{webhookReady:false,transport:'WHATSAPP-BAILEYS'},p_cipher:sealChannel(company,{instance})}));const base64=typeof qr.base64==='string'&&qr.base64.startsWith('data:image/png;base64,')?qr.base64:null;return {qr:base64,message:base64?'Leia o QR code no WhatsApp da empresa.':'QR code indisponível. Confira o estado da instância.'};
 }
 @Post('companies/:id/channels/evolution/status') async state(@Req() r:AuthRequest,@Param('id') company:string){await owner(r,company);const instance='askadia-'+company;const state=await evolutionRequest('/instance/connectionState/'+encodeURIComponent(instance));const status=(state.instance as {state?:string}|undefined)?.state;return result(await r.actor.client.rpc('save_company_channel',{p_company_id:company,p_provider:'evolution',p_remote:instance,p_name:'WhatsApp da empresa',p_status:status==='open'?'connected':'pending',p_metadata:{webhookReady:false,connectionState:status??'unknown',transport:'WHATSAPP-BAILEYS'},p_cipher:sealChannel(company,{instance})}));}
 @Post('companies/:id/channels/disconnect') async disconnect(@Req() r:AuthRequest,@Param('id') company:string,@Body() body:unknown){await owner(r,company);const input=parse(z.object({provider:z.enum(['meta','evolution'])}).strict(),body);result(await r.actor.client.rpc('disconnect_company_channel',{p_company_id:company,p_provider:input.provider}));return {ok:true};}
}
