import {MarketingShell,Faq,marketingMetadata} from '../../components/marketing-site';
import {PricingCards,PricingFeatures} from '../../components/pricing';
import s from '../../components/purchase.module.css';
export const metadata=marketingMetadata('Planos para colocar seu marketing em movimento','Todos os recursos da MedSI por empresa. Mensal por R$ 1.597 ou semestral por R$ 8.000 em até 6x no cartão. Comece pelo cadastro e onboarding gratuitos.','/planos');
export default function Plans(){return <MarketingShell><div className={s.pricing}><header className={s.pricingHeading}><span className={s.badge}>SEU PRÓXIMO CAPÍTULO COMEÇA AQUI</span><h1>Uma direção para crescer.<br/>Um plano para executar.</h1><p>Conte sobre sua empresa gratuitamente. Depois, escolha seu plano para a MedSI transformar suas metas em estratégia, conteúdo e ações que você aprova.</p></header><PricingCards/><p className={s.disclosure}>Cadastro e onboarding gratuitos. A geração com IA começa após a confirmação do plano. Checkout em modo de teste: nenhuma cobrança real será feita.</p><PricingFeatures/></div><Faq items={[
 ['O que significa começar grátis?','Você cria sua conta, confirma seu e-mail e responde ao onboarding sem pagar. A estratégia e as demais gerações com IA são liberadas após a confirmação do plano. Por enquanto, essa confirmação acontece em um checkout de teste, sem cobrança.'],
 ['Como funciona o plano semestral?','São R$ 8.000 por empresa para seis meses, em até 6 vezes no cartão: cinco parcelas de R$ 1.333,33 e a última de R$ 1.333,35. Os recursos são os mesmos do plano mensal recorrente de R$ 1.597.'],
 ['O que é a Implementação Assistida?','É o acompanhamento para iniciar o uso da MedSI. O serviço vale R$ 3.500 e será um brinde para os 100 primeiros clientes. O checkout de teste não cobra valores nem reserva uma vaga da promoção.'],
 ['Tenho mais de uma empresa. Como funciona?','Cada empresa criada no workspace tem seu próprio plano, perfil e estratégia. A contratação de uma empresa não libera as demais.'],
 ['A IA pode publicar ou investir sem eu aprovar?','As propostas e os criativos passam pela sua aprovação. Campanhas aprovadas com orçamento ou público, conteúdo e programação podem ser executadas nas datas autorizadas, conforme as integrações disponíveis.'],
 ['O investimento nos anúncios está incluído?','Não. A verba paga à Meta e ao Google e os custos de serviços externos conectados são separados da assinatura.']
 ]}/></MarketingShell>;}
