import {createHash} from 'node:crypto';
import type {AdSpec} from '@askadia/contracts';
export type AdProblem='insufficient_funds'|'billing'|'authorization'|'configuration'|'restricted'|'provider'|'uncertain'|'changed';
export class AdProviderError extends Error{constructor(public kind:AdProblem,message:string,public definitive=false,public code:string|null=null){super(message);}}
export function classifyAdError(provider:'meta'|'google',status:number,value:unknown){
 const obj=value as {error?:{code?:number;error_subcode?:number;message?:string;error_user_msg?:string;error_user_title?:string;details?:{errors?:{errorCode?:Record<string,string>;message?:string}[]}[]}};
 const e=obj?.error,details=e?.details?.flatMap(d=>d.errors??[])??[],codes=details.flatMap(d=>Object.values(d.errorCode??{})),message=[e?.message,e?.error_user_msg,e?.error_user_title,...details.map(d=>d.message)].filter(Boolean).join(' ');
 const definite=status>=400&&status<500&&status!==408&&status!==429;
 const code=provider==='meta'?[e?.code,e?.error_subcode].filter(x=>x!==undefined).join(':'):codes.join(',').slice(0,200);
 if(/insufficient (funds|balance|credit)|not enough funds|saldo insuficiente|fundos insuficientes/i.test(message)||codes.some(c=>/INSUFFICIENT_(FUNDS|BALANCE)/.test(c)))return new AdProviderError('insufficient_funds','A plataforma informou saldo insuficiente. Adicione crédito ou regularize o pagamento na conta de anúncios. A programação aprovada será retomada dentro do período autorizado.',definite,code);
 if(codes.some(c=>/BILLING|PAYMENT|BUDGET_EXHAUSTED/.test(c))||/payment (failed|failure|method)|unsettled|pagamento (recusado|pendente)/i.test(message))return new AdProviderError('billing','A plataforma informou um problema de faturamento. Confira pagamentos e limites na conta de anúncios.',definite,code);
 if(status===401||status===403||e?.code===190||codes.some(c=>/AUTHORIZATION|AUTHENTICATION|DEVELOPER_TOKEN|CLOUD_PROJECT/.test(c)))return new AdProviderError('authorization','A plataforma recusou a autorização. Reconecte a conta e confira o acesso da API.',definite,code);
 return new AdProviderError(status>=500||status===408?'uncertain':'provider',status>=500||status===408?'A plataforma não confirmou o resultado. A MedSI vai reconciliar a execução antes de criar outro anúncio.':'A plataforma recusou a operação. Revise a campanha, a situação da conta e as permissões da integração.',definite,code);
}
export async function metaAdRequest<T>(path:string,token:string,params:Record<string,string>={},body?:unknown):Promise<T>{
 const version=process.env.META_GRAPH_API_VERSION;if(!/^v[0-9]+\.[0-9]+$/.test(version??''))throw new AdProviderError('configuration','Versão Meta não configurada.');
 if(!/^[a-zA-Z0-9_/-]+$/.test(path)||path.includes('..'))throw new Error('Invalid provider path');
 const url=new URL('https://graph.facebook.com/'+version+'/'+path);for(const [k,v]of Object.entries(params))url.searchParams.set(k,v);
 let response:Response;try{response=await fetch(url,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined,redirect:'error',signal:AbortSignal.timeout(20000)});}catch{throw new AdProviderError('uncertain','Não foi possível confirmar o resultado da Meta. Aguardando reconciliação.');}
 const value=await response.json().catch(()=>null);if(!response.ok)throw classifyAdError('meta',response.status,value);if(!value)throw new AdProviderError('uncertain','A Meta não confirmou o resultado.');return value as T;
}
export async function googleAdRequest<T>(path:string,token:string,body?:unknown,managerId?:string):Promise<T>{
 if(!/^v[0-9]+$/.test(process.env.GOOGLE_ADS_API_VERSION??'')||!process.env.GOOGLE_ADS_DEVELOPER_TOKEN)throw new AdProviderError('configuration','Configure o acesso Google Ads da plataforma.');
 if(!/^[a-zA-Z0-9_/:~-]+$/.test(path)||path.includes('..'))throw new Error('Invalid provider path');
 let response:Response;try{response=await fetch('https://googleads.googleapis.com/'+process.env.GOOGLE_ADS_API_VERSION+'/'+path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+token,'developer-token':process.env.GOOGLE_ADS_DEVELOPER_TOKEN,'Content-Type':'application/json',...(managerId?{'login-customer-id':managerId}:{})},body:body?JSON.stringify(body):undefined,redirect:'error',signal:AbortSignal.timeout(20000)});}catch{throw new AdProviderError('uncertain','Não foi possível confirmar o resultado do Google Ads. Aguardando reconciliação.');}
 const value=await response.json().catch(()=>null);if(!response.ok)throw classifyAdError('google',response.status,value);if(!value)throw new AdProviderError('uncertain','O Google Ads não confirmou o resultado.');return value as T;
}
export const adMarker=(id:string,revision:number)=>'MEDSI-'+id+'-v'+revision;
export function accountDate(iso:string,timezone:string){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:timezone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(new Date(iso));const get=(name:string)=>parts.find(p=>p.type===name)!.value;return get('year')+'-'+get('month')+'-'+get('day')+' '+get('hour')+':'+get('minute')+':'+get('second');}
export function googleCampaignOperations(spec:AdSpec,marker:string){
 const base='customers/'+spec.accountId+'/',budget=base+'campaignBudgets/-1',campaign=base+'campaigns/-2',group=base+'adGroups/-3';
 return [
 {campaignBudgetOperation:{create:{resourceName:budget,name:marker,period:'CUSTOM_PERIOD',totalAmountMicros:String(spec.budgetCents*10000),explicitlyShared:false,deliveryMethod:'STANDARD'}}},
 {campaignOperation:{create:{resourceName:campaign,name:marker+' '+spec.name,status:'PAUSED',advertisingChannelType:'SEARCH',campaignBudget:budget,manualCpc:{},startDateTime:accountDate(spec.startsAt,spec.timezone),endDateTime:accountDate(spec.endsAt,spec.timezone),networkSettings:{targetGoogleSearch:true,targetSearchNetwork:false,targetContentNetwork:false,targetPartnerSearchNetwork:false},geoTargetTypeSetting:{positiveGeoTargetType:'PRESENCE',negativeGeoTargetType:'PRESENCE'},containsEuPoliticalAdvertising:'DOES_NOT_CONTAIN_EU_POLITICAL_ADVERTISING'}}},
 {campaignCriterionOperation:{create:{campaign,proximity:{geoPoint:{latitudeInMicroDegrees:Math.round(spec.location.latitude*1e6),longitudeInMicroDegrees:Math.round(spec.location.longitude*1e6)},radius:spec.copy.radiusKm,radiusUnits:'KILOMETERS'}}}},
 {campaignCriterionOperation:{create:{campaign,language:{languageConstant:'languageConstants/1014'}}}},
 {adGroupOperation:{create:{resourceName:group,name:marker,status:'ENABLED',campaign,type:'SEARCH_STANDARD',cpcBidMicros:String(spec.copy.maxCpcCents*10000)}}},
 ...spec.copy.keywords.map(text=>({adGroupCriterionOperation:{create:{adGroup:group,status:'ENABLED',keyword:{text,matchType:'PHRASE'}}}})),
 {adGroupAdOperation:{create:{adGroup:group,status:'ENABLED',ad:{name:marker,finalUrls:[spec.destination],responsiveSearchAd:{headlines:spec.copy.headlines.map(text=>({text})),descriptions:spec.copy.descriptions.map(text=>({text}))}}}}}
 ];
}
export type DurableStep=(key:string,payload:unknown,create:()=>Promise<string>,reconcile:()=>Promise<string|null>)=>Promise<string>;
export type AdRemote={campaign?:string;adset?:string;ad?:string;creative?:string;image?:string;google?:string;complete?:string};
export type AdProviderContext={token:string;managerId?:string};
export class CampaignProvider{
 constructor(readonly spec:AdSpec,readonly context:AdProviderContext,readonly marker:string){}
 private meta<T>(path:string,params:Record<string,string>={},body?:unknown){return metaAdRequest<T>(path,this.context.token,params,body);}
 private google<T>(path:string,body?:unknown){return googleAdRequest<T>(path,this.context.token,body,this.context.managerId);}
 async account(){
  if(this.spec.format==='meta_traffic_image'){const a=await this.meta<{currency:string;timezone_name:string;account_status:number}>(this.spec.accountId,{fields:'currency,timezone_name,account_status'});if(a.currency!==this.spec.currency||a.timezone_name!==this.spec.timezone)throw new AdProviderError('changed','Moeda ou fuso da conta mudou. Revise a campanha.');if(a.account_status!==1)throw new AdProviderError(a.account_status===3?'billing':'restricted','A Meta informou uma restrição na conta. Confira o faturamento e a situação da conta.');return;}
  const a=await this.search<{customer:{currencyCode:string;timeZone:string;status:string}}>('SELECT customer.currency_code,customer.time_zone,customer.status FROM customer LIMIT 1');const c=a[0]?.customer;if(!c||c.currencyCode!==this.spec.currency||c.timeZone!==this.spec.timezone)throw new AdProviderError('changed','Moeda ou fuso da conta mudou. Revise a campanha.');if(c.status!=='ENABLED')throw new AdProviderError('restricted','A conta Google Ads não está habilitada para veicular.');
 }
 async search<T>(query:string){const data=await this.google<{results?:T[]}>('customers/'+this.spec.accountId+'/googleAds:search',{query});return data.results??[];}
 private async findMeta(edge:string){let after:string|undefined;const found:string[]=[];for(let i=0;i<20;i++){const r: {data:{id:string;name:string}[];paging?:{next?:string;cursors?:{after?:string}}}=await this.meta(this.spec.accountId+'/'+edge,{fields:'id,name',limit:'100',...(after?{after}:{})});found.push(...r.data.filter(x=>x.name===this.marker).map(x=>x.id));after=r.paging?.next?r.paging.cursors?.after:undefined;if(!after){if(found.length>1)throw new AdProviderError('uncertain','Mais de um objeto correspondente foi encontrado. Revisão necessária.');return found[0]??null;}}throw new AdProviderError('uncertain','A consulta de reconciliação foi parcial. Nenhum objeto será recriado.');}
 async provision(step:DurableStep,bytes:Buffer|null):Promise<AdRemote>{
  await this.account();
  if(this.spec.format==='google_search'){
   const payload={mutateOperations:googleCampaignOperations(this.spec,this.marker),partialFailure:false};
   const campaign=await step('google',payload,async()=>{const r=await this.google<{mutateOperationResponses?:{campaignResult?:{resourceName:string}}[]}>('customers/'+this.spec.accountId+'/googleAds:mutate',payload);const id=r.mutateOperationResponses?.find(v=>v.campaignResult)?.campaignResult?.resourceName;if(!id)throw new AdProviderError('uncertain','Google não confirmou a campanha criada.');return id;},async()=>{const rows=await this.search<{campaign:{resourceName:string}}>("SELECT campaign.resource_name FROM campaign WHERE campaign.name LIKE '"+this.marker+"%'");if(rows.length>1)throw new AdProviderError('uncertain','Mais de uma campanha Google corresponde à execução.');return rows[0]?.campaign.resourceName??null;});
   return {google:campaign,complete:'true'};
  }
  if(!bytes||createHash('sha256').update(bytes).digest('hex')!==this.spec.imageSha256)throw new AdProviderError('changed','O arquivo do criativo mudou. Gere e aprove uma nova proposta.');
  const createMeta=async(edge:string,payload:unknown)=>{const r=await this.meta<{id:string}>(this.spec.accountId+'/'+edge,{},payload);if(!r.id)throw new AdProviderError('uncertain','A Meta não confirmou o identificador criado.');return r.id;};
  const campaignPayload={name:this.marker,objective:'OUTCOME_TRAFFIC',status:'PAUSED',special_ad_categories:[]};
  const campaign=await step('campaign',campaignPayload,()=>createMeta('campaigns',campaignPayload),()=>this.findMeta('campaigns'));
  const imagePayload={name:this.marker,sha256:this.spec.imageSha256};
  const image=await step('image',imagePayload,async()=>{const r=await this.meta<{images:Record<string,{hash:string}>}>(this.spec.accountId+'/adimages',{}, {name:this.marker,bytes:bytes.toString('base64')});const hash=Object.values(r.images??{})[0]?.hash;if(!hash)throw new AdProviderError('uncertain','Upload sem confirmação da Meta.');return hash;},async()=>{const r=await this.meta<{data:{name:string;hash:string}[]}>(this.spec.accountId+'/adimages',{fields:'name,hash',limit:'100'});const found=r.data.filter(i=>i.name===this.marker);return found.length===1?found[0]!.hash:null;});
  const creativePayload={name:this.marker,object_story_spec:{page_id:this.spec.pageId,link_data:{image_hash:image,link:this.spec.destination,message:this.spec.copy.text,name:this.spec.copy.headline,call_to_action:{type:'LEARN_MORE',value:{link:this.spec.destination}}}}};
  const creative=await step('creative',creativePayload,()=>createMeta('adcreatives',creativePayload),()=>this.findMeta('adcreatives'));
  const adsetPayload={name:this.marker,campaign_id:campaign,lifetime_budget:this.spec.budgetCents,billing_event:'IMPRESSIONS',optimization_goal:'LINK_CLICKS',bid_strategy:'LOWEST_COST_WITHOUT_CAP',destination_type:'WEBSITE',status:'PAUSED',start_time:this.spec.startsAt,end_time:this.spec.endsAt,targeting:{age_min:18,geo_locations:{custom_locations:[{latitude:this.spec.location.latitude,longitude:this.spec.location.longitude,radius:this.spec.copy.radiusKm,distance_unit:'kilometer'}]},publisher_platforms:['facebook','instagram'],facebook_positions:['feed'],instagram_positions:['stream']}};
  const adset=await step('adset',adsetPayload,()=>createMeta('adsets',adsetPayload),()=>this.findMeta('adsets'));
  const adPayload={name:this.marker,adset_id:adset,creative:{creative_id:creative},status:'PAUSED'};
  const ad=await step('ad',adPayload,()=>createMeta('ads',adPayload),()=>this.findMeta('ads'));
  return {campaign,image,creative,adset,ad,complete:'true'};
 }

 async verify(remote:AdRemote){
  if(this.spec.format==='meta_traffic_image'){
   if(!remote.campaign||!remote.adset||!remote.ad||!remote.creative)throw new AdProviderError('uncertain','A hierarquia da Meta ainda não está completa.');
   const campaign=await this.meta<{account_id:string;objective:string}>(remote.campaign,{fields:'account_id,objective'});
   const set=await this.meta<{campaign_id:string;lifetime_budget:string;daily_budget?:string;start_time:string;end_time:string;targeting:{age_min?:number;genders?:number[];custom_audiences?:unknown[];flexible_spec?:unknown[];publisher_platforms?:string[];facebook_positions?:string[];instagram_positions?:string[];targeting_automation?:{advantage_audience?:number};geo_locations?:{custom_locations?:{latitude:number;longitude:number;radius:number;distance_unit:string}[]}}}>(remote.adset,{fields:'campaign_id,lifetime_budget,daily_budget,start_time,end_time,targeting'});
   const creative=await this.meta<{object_story_spec?:{page_id?:string;link_data?:{link?:string;image_hash?:string;message?:string;name?:string}}}>(remote.creative,{fields:'object_story_spec'});
   const ad=await this.meta<{adset_id:string;creative:{id:string}}>(remote.ad,{fields:'adset_id,creative{id}'});
   const geo=set.targeting?.geo_locations?.custom_locations,link=creative.object_story_spec?.link_data;
   if(campaign.account_id!==this.spec.accountId.replace(/^act_/,'')||campaign.objective!=='OUTCOME_TRAFFIC'||set.campaign_id!==remote.campaign||Number(set.lifetime_budget)!==this.spec.budgetCents||Number(set.daily_budget??0)!==0||Date.parse(set.start_time)!==Date.parse(this.spec.startsAt)||Date.parse(set.end_time)!==Date.parse(this.spec.endsAt)||set.targeting.age_min!==18||set.targeting.genders?.length||set.targeting.custom_audiences?.length||set.targeting.flexible_spec?.length||set.targeting.targeting_automation?.advantage_audience===1||JSON.stringify([...(set.targeting.publisher_platforms??[])].sort())!==JSON.stringify(['facebook','instagram'])||JSON.stringify(set.targeting.facebook_positions??[])!==JSON.stringify(['feed'])||JSON.stringify(set.targeting.instagram_positions??[])!==JSON.stringify(['stream'])||Object.keys(set.targeting.geo_locations??{}).some(k=>!['custom_locations','location_types'].includes(k))||geo?.length!==1||Math.abs(Number(geo[0]?.latitude)-this.spec.location.latitude)>0.00001||Math.abs(Number(geo[0]?.longitude)-this.spec.location.longitude)>0.00001||Number(geo[0]?.radius)!==this.spec.copy.radiusKm||geo[0]?.distance_unit!=='kilometer'||creative.object_story_spec?.page_id!==this.spec.pageId||link?.link!==this.spec.destination||link?.image_hash!==remote.image||link?.message!==this.spec.copy.text||link?.name!==this.spec.copy.headline||ad.adset_id!==remote.adset||ad.creative.id!==remote.creative)throw new AdProviderError('changed','A configuração na Meta difere da versão aprovada. A campanha será pausada para revisão.');return;
  }
  if(!remote.google?.startsWith('customers/'+this.spec.accountId+'/campaigns/')||!/^customers\/[0-9]+\/campaigns\/[0-9]+$/.test(remote.google))throw new AdProviderError('changed','Campanha Google não corresponde à conta aprovada.');
  const where=" WHERE campaign.resource_name = '"+remote.google+"'";
  const rows=await this.search<{campaign:{startDateTime:string;endDateTime:string;advertisingChannelType:string};campaignBudget:{period:string;totalAmountMicros:string}}>('SELECT campaign.start_date_time,campaign.end_date_time,campaign.advertising_channel_type,campaign_budget.period,campaign_budget.total_amount_micros FROM campaign'+where);
  const c=rows[0];if(!c||c.campaign.advertisingChannelType!=='SEARCH'||c.campaignBudget.period!=='CUSTOM_PERIOD'||Number(c.campaignBudget.totalAmountMicros)!==this.spec.budgetCents*10000||c.campaign.startDateTime!==accountDate(this.spec.startsAt,this.spec.timezone)||c.campaign.endDateTime!==accountDate(this.spec.endsAt,this.spec.timezone))throw new AdProviderError('changed','Orçamento ou período no Google difere da aprovação. A campanha será pausada.');
  const ads=await this.search<{adGroupAd:{ad:{finalUrls:string[];responsiveSearchAd:{headlines:{text:string}[];descriptions:{text:string}[]}}};adGroup:{cpcBidMicros:string}}>('SELECT ad_group_ad.ad.final_urls,ad_group_ad.ad.responsive_search_ad.headlines,ad_group_ad.ad.responsive_search_ad.descriptions,ad_group.cpc_bid_micros FROM ad_group_ad'+where+" AND ad_group_ad.status != 'REMOVED'");
  const texts=(a:string[])=>JSON.stringify([...a].sort());const a=ads[0];if(ads.length!==1||!a||a.adGroupAd.ad.finalUrls?.length!==1||a.adGroupAd.ad.finalUrls[0]!==this.spec.destination||Number(a.adGroup.cpcBidMicros)!==this.spec.copy.maxCpcCents*10000||texts(a.adGroupAd.ad.responsiveSearchAd?.headlines?.map(x=>x.text)??[])!==texts(this.spec.copy.headlines)||texts(a.adGroupAd.ad.responsiveSearchAd?.descriptions?.map(x=>x.text)??[])!==texts(this.spec.copy.descriptions))throw new AdProviderError('changed','O anúncio Google difere do conteúdo aprovado. A campanha será pausada.');
  const regions=await this.search<{campaignCriterion:{type:string;negative:boolean;proximity?:{radius:number;radiusUnits:string;geoPoint:{latitudeInMicroDegrees:string;longitudeInMicroDegrees:string}};language?:{languageConstant:string}}}>('SELECT campaign_criterion.type,campaign_criterion.negative,campaign_criterion.proximity,campaign_criterion.language.language_constant FROM campaign_criterion'+where+" AND campaign_criterion.status != 'REMOVED'");
  const proximity=regions.filter(r=>r.campaignCriterion.type==='PROXIMITY'),languages=regions.filter(r=>r.campaignCriterion.type==='LANGUAGE'),geo=proximity[0]?.campaignCriterion.proximity;
  if(regions.length!==2||proximity.length!==1||languages.length!==1||regions.some(r=>r.campaignCriterion.negative)||!geo||Number(geo.radius)!==this.spec.copy.radiusKm||geo.radiusUnits!=='KILOMETERS'||Number(geo.geoPoint.latitudeInMicroDegrees)!==Math.round(this.spec.location.latitude*1e6)||Number(geo.geoPoint.longitudeInMicroDegrees)!==Math.round(this.spec.location.longitude*1e6)||languages[0]?.campaignCriterion.language?.languageConstant!=='languageConstants/1014')throw new AdProviderError('changed','A região ou o idioma Google mudou fora da aprovação. A campanha será pausada.');
  const keywords=await this.search<{adGroupCriterion:{type:string;negative:boolean;keyword?:{text:string;matchType:string}}}>('SELECT ad_group_criterion.type,ad_group_criterion.negative,ad_group_criterion.keyword.text,ad_group_criterion.keyword.match_type FROM ad_group_criterion'+where+" AND ad_group_criterion.status != 'REMOVED'");
  if(keywords.some(k=>k.adGroupCriterion.type!=='KEYWORD'||k.adGroupCriterion.negative||k.adGroupCriterion.keyword?.matchType!=='PHRASE')||texts(keywords.map(k=>k.adGroupCriterion.keyword?.text??''))!==texts(this.spec.copy.keywords))throw new AdProviderError('changed','As palavras-chave Google mudaram fora da aprovação. A campanha será pausada.');
 }
 async activate(remote:AdRemote,guard:()=>Promise<void>){
  await this.account();await this.verify(remote);if(Date.parse(this.spec.startsAt)>Date.now()||Date.parse(this.spec.endsAt)<=Date.now())throw new AdProviderError('changed','Fora do período aprovado.');
  if(this.spec.format==='google_search'){if(!remote.google)throw new AdProviderError('uncertain','Campanha Google sem confirmação.');await guard();await this.google('customers/'+this.spec.accountId+'/campaigns:mutate',{operations:[{update:{resourceName:remote.google,status:'ENABLED'},updateMask:'status'}]});}
  else{if(!remote.campaign||!remote.adset||!remote.ad)throw new AdProviderError('uncertain','Criação incompleta na Meta.');for(const id of [remote.ad,remote.adset,remote.campaign]){await guard();await this.meta(id,{}, {status:'ACTIVE'});}}
 }
 async pause(remote:AdRemote){if(this.spec.format==='google_search'){if(remote.google&&!remote.google.startsWith('customers/'+this.spec.accountId+'/campaigns/'))throw new AdProviderError('changed','Conta Google divergente.');if(remote.google)await this.google('customers/'+this.spec.accountId+'/campaigns:mutate',{operations:[{update:{resourceName:remote.google,status:'PAUSED'},updateMask:'status'}]});}else if(remote.campaign)await this.meta(remote.campaign,{}, {status:'PAUSED'});}
 async observe(remote:AdRemote){
  await this.account();
  if(this.spec.format==='meta_traffic_image'){if(!remote.campaign)throw new AdProviderError('uncertain','Campanha sem confirmação.');const c=await this.meta<{status:string;effective_status:string}>(remote.campaign,{fields:'status,effective_status'});const ad=remote.ad?await this.meta<{effective_status:string;issues_info?:{error_summary?:string;error_message?:string;error_code?:number}[]}>(remote.ad,{fields:'effective_status,issues_info'}):null;
   for(const issue of ad?.issues_info??[]){const error=classifyAdError('meta',400,{error:{message:issue.error_summary+' '+issue.error_message,code:issue.error_code}});if(['insufficient_funds','billing'].includes(error.kind))throw error;}
   return {status:c.status,effectiveStatus:ad?.effective_status??c.effective_status,deliveryConfirmed:false,eligible:ad?.effective_status==='ACTIVE',issueCount:ad?.issues_info?.length??0};
  }
  if(!remote.google)throw new AdProviderError('uncertain','Campanha sem confirmação.');const rows=await this.search<{campaign:{status:string;servingStatus:string;primaryStatus:string;primaryStatusReasons?:string[]}}>("SELECT campaign.status,campaign.serving_status,campaign.primary_status,campaign.primary_status_reasons FROM campaign WHERE campaign.resource_name = '"+remote.google+"'");const c=rows[0]?.campaign;if(!c)throw new AdProviderError('uncertain','Campanha Google não localizada.');return {status:c.status,effectiveStatus:c.primaryStatus,servingStatus:c.servingStatus,reasons:c.primaryStatusReasons??[],deliveryConfirmed:false,eligible:c.primaryStatus==='ELIGIBLE'&&c.servingStatus==='SERVING'};
 }
}
