import {serviceDatabase} from '../platform/service';

import {BadRequestException,ForbiddenException,ServiceUnavailableException} from '@nestjs/common';
import {z} from 'zod';
import {AuthRequest} from '../identity/auth';
import {result} from '../identity/service';
import {openChannel} from '../onboarding/channels';
import {metaContext,metaGraph,type MetaCollection} from '../inbox/meta';
export const serviceDb=serviceDatabase;
export async function adsAccess(r:AuthRequest,company:string,action='marketing.read'){if(!z.uuid().safeParse(company).success)throw new BadRequestException();const cap=result<{actions:string[]}>(await r.actor.client.rpc('company_capabilities',{p_company_id:company}));if(!cap.actions.includes(action))throw new ForbiddenException();return cap;}
export type AdConnection={provider:'google'|'meta';status:string;account_id:string|null;name:string;source_page:string|null;cipher:string|null;login_customer_id?:string|null};
export async function credentials(r:AuthRequest,company:string,provider:'google'|'meta',write?:Record<string,unknown>){await adsAccess(r,company,write?'billing.manage':'marketing.read');return result<AdConnection|null>(await serviceDb().rpc('ad_credentials_server',{p_company_id:company,p_actor:r.actor.id,p_provider:provider,p_write:write??null}));}
export function googleConfigured(){return Boolean(process.env.GOOGLE_ADS_CLIENT_ID&&process.env.GOOGLE_ADS_CLIENT_SECRET&&process.env.GOOGLE_ADS_DEVELOPER_TOKEN&&/^v\d+$/.test(process.env.GOOGLE_ADS_API_VERSION??'')&&process.env.WEB_ORIGIN?.startsWith('https://'));}
export async function googleToken(body:Record<string,string>){if(!googleConfigured())throw new ServiceUnavailableException('Configure OAuth e token de desenvolvedor Google Ads no servidor.');const response=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:process.env.GOOGLE_ADS_CLIENT_ID!,client_secret:process.env.GOOGLE_ADS_CLIENT_SECRET!,...body}),signal:AbortSignal.timeout(15000),redirect:'error'});if(!response.ok)throw new BadRequestException('A autorização Google expirou ou foi recusada. Reconecte a conta.');return response.json() as Promise<{access_token:string;refresh_token?:string;scope?:string}>;}
export async function googleRequest<T>(path:string,token:string,body?:unknown,managerId:string|null=process.env.GOOGLE_ADS_LOGIN_CUSTOMER_ID??null){if(!googleConfigured())throw new ServiceUnavailableException('Google Ads não configurado.');const response=await fetch('https://googleads.googleapis.com/'+process.env.GOOGLE_ADS_API_VERSION+'/'+path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+token,'developer-token':process.env.GOOGLE_ADS_DEVELOPER_TOKEN!,'Content-Type':'application/json',...(managerId?{'login-customer-id':managerId}:{})},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(20000),redirect:'error'});if(!response.ok)throw new ServiceUnavailableException('O Google Ads recusou a consulta. Confira acesso à conta, nível de acesso da API e token de desenvolvedor.');return response.json() as Promise<T>;}
export async function googleAccessToken(r:AuthRequest,company:string){const c=await credentials(r,company,'google');if(!c?.cipher||c.status==='disconnected')throw new BadRequestException('Conecte o Google Ads em Integrações.');const secret=openChannel<{refreshToken:string}>(company,c.cipher);const token=await googleToken({grant_type:'refresh_token',refresh_token:secret.refreshToken});return {connection:c,token:token.access_token};}
export async function googleSearch<T>(account:string,token:string,query:string,managerId:string|null=process.env.GOOGLE_ADS_LOGIN_CUSTOMER_ID??null){if(!/^\d{6,20}$/.test(account))throw new BadRequestException('Conta inválida.');const rows:T[]=[];let next:string|undefined;for(let i=0;i<10;i++){const page=await googleRequest<{results?:T[];nextPageToken?:string}>('customers/'+account+'/googleAds:search',token,{query,...(next?{pageToken:next}:{})},managerId);rows.push(...page.results??[]);next=page.nextPageToken;if(!next)break;}return {rows,truncated:Boolean(next)};}
export type AdNode={id:string;parentId:string|null;name:string;status:string;type:string;budget:string|null};
export async function metaAccounts(r:AuthRequest,company:string){await adsAccess(r,company,'billing.manage');const c=await metaContext(r,company,'billing.manage');if(!c.access.adsRead||!c.userToken)throw new BadRequestException('Atualize a autorização Meta incluindo Tráfego pago.');const rows:{id:string;name:string;currency?:string}[]=[];let after:string|undefined;for(let i=0;i<10;i++){const page:MetaCollection<{id:string;name:string;currency?:string}>=await metaGraph('me/adaccounts',c.userToken,{fields:'id,name,currency',limit:'100',...(after?{after}:{})});rows.push(...page.data);after=page.paging?.next?page.paging.cursors?.after:undefined;if(!after)break;}return {accounts:rows,truncated:Boolean(after),sourcePage:c.page};}
export async function metaHierarchy(r:AuthRequest,company:string){const binding=await credentials(r,company,'meta'),c=await metaContext(r,company,'marketing.read');if(binding?.status!=='connected'||!binding.account_id||binding.source_page!==c.page)throw new BadRequestException('Escolha a conta de anúncios Meta desta empresa em Integrações.');if(!c.userToken||!c.access.adsRead)throw new BadRequestException('Atualize a autorização Meta para consultar anúncios.');const nodes:AdNode[]=[];let truncated=false;
 for(const [edge,fields] of [['campaigns','id,name,status,objective,daily_budget,lifetime_budget'],['adsets','id,name,status,campaign_id,daily_budget,lifetime_budget'],['ads','id,name,status,adset_id']] as const){let after:string|undefined;for(let i=0;i<20;i++){const page:MetaCollection<Record<string,string>>=await metaGraph(binding.account_id+'/'+edge,c.userToken,{fields,limit:'100',...(after?{after}:{})});nodes.push(...page.data.map(v=>({id:v.id!,name:v.name!,parentId:v.adset_id??v.campaign_id??null,status:v.status??'',type:edge==='campaigns'?'campaign':edge==='adsets'?'group':'ad',budget:v.daily_budget?String(Number(v.daily_budget)/100)+' / dia':v.lifetime_budget?String(Number(v.lifetime_budget)/100)+' total':null})));after=page.paging?.next?page.paging.cursors?.after:undefined;if(!after)break;}truncated ||= Boolean(after);}
 const account=await metaGraph<{currency:string}>(binding.account_id,c.userToken,{fields:'currency'});await adsAccess(r,company);return {nodes,truncated,currency:account.currency,account:binding.name,queriedAt:new Date().toISOString()};
}
export async function googleHierarchy(r:AuthRequest,company:string){const {connection:c,token}=await googleAccessToken(r,company);if(c.status!=='connected'||!c.account_id)throw new BadRequestException('Selecione a conta Google Ads desta empresa.');const nodes:AdNode[]=[];let truncated=false,currency='';
 const campaigns=await googleSearch<{campaign:{id:string;name:string;status:string;advertisingChannelType:string};campaignBudget:{amountMicros?:string;totalAmountMicros?:string;period?:string};customer:{currencyCode:string}}>(c.account_id,token,'SELECT campaign.id,campaign.name,campaign.status,campaign.advertising_channel_type,campaign_budget.amount_micros,campaign_budget.total_amount_micros,campaign_budget.period,customer.currency_code FROM campaign',c.login_customer_id??null);truncated ||= campaigns.truncated;
 for(const v of campaigns.rows){currency=v.customer.currencyCode;nodes.push({id:v.campaign.id,parentId:null,name:v.campaign.name,status:v.campaign.status,type:'campaign',budget:v.campaignBudget?.period==='CUSTOM_PERIOD'&&v.campaignBudget.totalAmountMicros?String(Number(v.campaignBudget.totalAmountMicros)/1e6)+' total':v.campaignBudget?.amountMicros?String(Number(v.campaignBudget.amountMicros)/1e6)+' / dia':null});}
 const groups=await googleSearch<{adGroup:{id:string;name:string;status:string};campaign:{id:string}}>(c.account_id,token,'SELECT ad_group.id,ad_group.name,ad_group.status,campaign.id FROM ad_group',c.login_customer_id??null);truncated ||= groups.truncated;nodes.push(...groups.rows.map(v=>({id:v.adGroup.id,parentId:v.campaign.id,name:v.adGroup.name,status:v.adGroup.status,type:'group',budget:null})));
 const ads=await googleSearch<{adGroupAd:{status:string;ad:{id:string;name?:string;type:string}};adGroup:{id:string}}>(c.account_id,token,'SELECT ad_group_ad.ad.id,ad_group_ad.ad.name,ad_group_ad.ad.type,ad_group_ad.status,ad_group.id FROM ad_group_ad',c.login_customer_id??null);truncated ||= ads.truncated;nodes.push(...ads.rows.map(v=>({id:v.adGroupAd.ad.id,parentId:v.adGroup.id,name:v.adGroupAd.ad.name||v.adGroupAd.ad.type,status:v.adGroupAd.status,type:'ad',budget:null})));
 // Performance Max uses asset groups instead of conventional ads.
 const assets=await googleSearch<{assetGroup:{id:string;name:string;status:string};campaign:{id:string}}>(c.account_id,token,'SELECT asset_group.id,asset_group.name,asset_group.status,campaign.id FROM asset_group',c.login_customer_id??null);truncated ||= assets.truncated;nodes.push(...assets.rows.map(v=>({id:'asset:'+v.assetGroup.id,parentId:v.campaign.id,name:v.assetGroup.name+' · grupo de recursos',status:v.assetGroup.status,type:'group',budget:null})));
 await adsAccess(r,company);return {nodes,truncated,currency,account:c.name,queriedAt:new Date().toISOString()};
}
