import {BadRequestException,Body,Controller,ForbiddenException,Get,Param,Post,Req,ServiceUnavailableException,UseGuards} from '@nestjs/common';
import {z} from 'zod';
import {messageCampaignSchema,parseStudentsCsv,personalizeCampaign} from '@askadia/contracts';
import {AuthGuard,type AuthRequest} from '../identity/auth';
import {result} from '../identity/service';
import {firestoreBackend} from '../platform/config';
import {campaignDeliveryReady} from './delivery';
function parse<T>(schema:z.ZodType<T>,body:unknown){const p=schema.safeParse(body);if(!p.success)throw new BadRequestException('Confira os dados da campanha.');return p.data;}
async function access(r:AuthRequest,id:string,write=false){parse(z.uuid(),id);const c=result<{actions:string[]}>(await r.actor.client.rpc('company_capabilities',{p_company_id:id}));if(!c.actions.includes(write?'marketing.write':'marketing.read')||!c.actions.includes(write?'crm.write':'crm.read'))throw new ForbiddenException('Você precisa de acesso a marketing e CRM nesta empresa.');return c;}
export function campaignDto(c:Record<string,unknown>,timezone:string){return {id:c.id,name:c.name,revision:c.revision,trigger:c.trigger,recipientIds:c.recipient_ids??[],absenceDays:c.absence_days,sendTime:String(c.send_time).slice(0,5),message:c.message,tag:c.tag,activeOnly:c.active_only,startDate:c.start_date,endDate:c.end_date,maxDataAgeDays:c.max_data_age_days,dailyLimit:c.daily_limit,status:c.status,timezone,updatedAt:c.updated_at};}
@Controller('onboarding/companies/:id/campaigns')
@UseGuards(AuthGuard)
export class CampaignsController{
 @Get() async list(@Req() r:AuthRequest,@Param('id') id:string){const cap=await access(r,id);const [company,campaigns,students,deliveries]=await Promise.all([r.actor.client.from('companies').select('name,timezone').eq('id',id).single(),r.actor.client.from('message_campaigns').select('*').eq('company_id',id).order('updated_at',{ascending:false}),r.actor.client.from('campaign_students').select('id,name,phone,birthday,last_attendance,status,consent,source,updated_at',{count:'exact'}).eq('company_id',id).order('updated_at',{ascending:false}).limit(30),r.actor.client.from('message_campaign_deliveries').select(firestoreBackend()?'id,campaign_id,state,error,attempts,created_at':'id,campaign_id,state,created_at').eq('company_id',id).order('created_at',{ascending:false}).limit(100)]);if(campaigns.error?.code==='PGRST205')throw new ServiceUnavailableException('As campanhas aguardam a atualização do banco de dados.');const co=result(company);return {transport:firestoreBackend()?'whatsapp_cloud':'legacy_evolution',outsideWindowRequiresApprovedTemplate:firestoreBackend(),campaigns:result(campaigns).map(c=>campaignDto(c,co.timezone)),students:result(students),studentCount:students.count,deliveries:result(deliveries),companyName:co.name,timezone:co.timezone,canWrite:cap.actions.includes('marketing.write')&&cap.actions.includes('crm.write'),deliveryReady:campaignDeliveryReady()};}
 @Get('recipients') async recipients(@Req() r:AuthRequest,@Param('id') id:string){await access(r,id);return {students:result(await r.actor.client.from('campaign_students').select('id,name,phone,consent,tag').eq('company_id',id).order('name').limit(1000)),contacts:result(await r.actor.client.from('contacts').select('id,name,phone_e164').eq('company_id',id).order('name').limit(1000))};}
 @Post('recipients/register') async register(@Req() r:AuthRequest,@Param('id') id:string,@Body() body:unknown){await access(r,id,true);const input=parse(z.object({contactIds:z.array(z.uuid()).min(1).max(500),evidence:z.string().trim().min(5).max(500),confirmed:z.literal(true)}).strict(),body);return {ids:result(await r.actor.client.rpc('register_campaign_contacts',{p_company_id:id,p_contacts:input.contactIds,p_evidence:input.evidence}))};}
 @Post('recipients/revoke') async revoke(@Req() r:AuthRequest,@Param('id') id:string,@Body() body:unknown){await access(r,id,true);const input=parse(z.object({id:z.uuid()}).strict(),body);result(await r.actor.client.rpc('revoke_campaign_contact',{p_company_id:id,p_id:input.id}));return {ok:true};}
 @Post('save') async save(@Req() r:AuthRequest,@Param('id') id:string,@Body() body:unknown){await access(r,id,true);const input=parse(messageCampaignSchema,body);input.message=input.message.replace(/\{\{\s*clinica\s*\}\}/g,'{{academia}}').replace(/\{\{\s*(nome|academia|dias_ausente)\s*\}\}/g,'{{$1}}');return result(await r.actor.client.rpc('save_message_campaign',{p_company_id:id,p_data:input}));}
 @Post('students/import') async students(@Req() r:AuthRequest,@Param('id') id:string,@Body() body:unknown){await access(r,id,true);const {csv}=parse(z.object({csv:z.string().max(240000)}).strict(),body);let students;try{students=parseStudentsCsv(csv);}catch(e){throw new BadRequestException(e instanceof Error?e.message:'Arquivo inválido.');}return {imported:result(await r.actor.client.rpc('import_campaign_students',{p_company_id:id,p_students:students,p_source:'csv'}))};}
 @Post('preview') async preview(@Req() r:AuthRequest,@Param('id') id:string,@Body() body:unknown){await access(r,id,true);const input=parse(z.object({id:z.uuid()}).strict(),body);const preview=result<{revision:number;total:number;students:{student_id:string;name:string;phone:string;days_absent:number|null}[]}>(await r.actor.client.rpc('preview_message_campaign',{p_company_id:id,p_id:input.id}));const c=result<{message:string}>(await r.actor.client.from('message_campaigns').select('message').eq('company_id',id).eq('id',input.id).single()),co=result<{name:string}>(await r.actor.client.from('companies').select('name').eq('id',id).single());if(!c||!co)throw new ForbiddenException('Campanha indisponível.');return {...preview,students:preview.students.map(s=>({...s,message:personalizeCampaign(c.message,{name:s.name,daysAbsent:s.days_absent},co.name)}))};}
 @Post('activation') async activate(@Req() r:AuthRequest,@Param('id') id:string,@Body() body:unknown){await access(r,id,true);const input=parse(z.object({id:z.uuid(),revision:z.number().int().positive(),active:z.boolean(),confirmed:z.literal(true)}).strict(),body);if(input.active&&!campaignDeliveryReady())throw new ServiceUnavailableException('O serviço de campanhas não está disponível. O rascunho permanece salvo.');result(await r.actor.client.rpc('activate_message_campaign',{p_company_id:id,p_id:input.id,p_revision:input.revision,p_active:input.active}));return {ok:true};}
}
