import Link from 'next/link';
import { ArrowRight, Check, MessageCircle, Users, Workflow } from 'lucide-react';
import { MarketingShell, ProductPreview, SectionHeading, FinalCta, Faq, marketingMetadata, signupHref } from '../../../components/marketing-site';
import s from '../../home.module.css';
export const metadata=marketingMetadata('Atendimento e CRM para clínicas','Organize conversas, acompanhe interessados e prepare ações de relacionamento com pacientes. Conheça o atendimento com IA e o CRM da MedSI.','/lp/atendimento-medico');
export default function AtendimentoMedico(){return <MarketingShell focused>
  <section className={s.hero}><div className={s.heroCopy}><span className={s.eyebrow}>ATENDIMENTO E RELACIONAMENTO PARA MÉDICOS E CLÍNICAS</span><h1>O interesse chegou.<br/><span>Dê à conversa um próximo passo.</span></h1><p>Uma pergunta sobre atendimento pode ser o começo de uma consulta. Organize o WhatsApp, acompanhe cada oportunidade no CRM e coloque sua equipe e a IA para trabalhar com o mesmo contexto.</p><div className={s.actions}><Link href={signupHref} className={s.primary}>Quero organizar meu atendimento <ArrowRight size={18}/></Link></div><p className={s.microcopy}>Você conecta o canal, configura e decide quando ativar.</p></div><ProductPreview kind="inbox"/></section>
  <section className={s.section}><SectionHeading eyebrow="UM BOM ATENDIMENTO TEM CONTINUIDADE" title="Saiba quem chegou. Entenda o interesse. Acompanhe a evolução." description="A MedSI reúne as ferramentas para sua equipe dar sequência ao relacionamento, da primeira dúvida ao acompanhamento no funil."/><div className={s.benefitGrid}>
    <article><span className={s.featureIcon}><MessageCircle size={23}/></span><h3>Conversas com contexto.</h3><p>Consulte mensagens e histórico, use atalhos e prepare sugestões com IA. Envie textos e os tipos de mídia disponíveis no canal conectado.</p></article>
    <article><span className={s.featureIcon}><Users size={23}/></span><h3>Oportunidades visíveis.</h3><p>Organize contatos em Kanban ou lista. Abra o histórico do cliente e continue a conversa na caixa de entrada.</p></article>
    <article><span className={s.featureIcon}><Workflow size={23}/></span><h3>Uma IA com a sua orientação.</h3><p>Configure o prompt com as informações da clínica ou monte um fluxo. Ative o atendimento automático quando estiver pronto e assuma sempre que precisar.</p></article>
  </div></section>
  <section className={s.workflowSection}><div className={s.workflowInner}><div><span className={s.eyebrow}>RELACIONAMENTO ALÉM DA PRIMEIRA CONVERSA</span><h2>Lembre das pessoas.<br/><span>No momento que faz sentido.</span></h2><p>Prepare campanhas de aniversário, continuidade de contato ou mensagens para contatos selecionados. Revise as condições e os destinatários antes de ativar.</p><Link className={s.lightButton} href={signupHref}>Conhecer a MedSI <ArrowRight size={17}/></Link></div><ol className={s.steps}>{[['Aniversários','Planeje uma mensagem personalizada para celebrar o dia de cada pessoa.'],['Continuidade do contato','Organize o contato com pessoas selecionadas pela equipe, conforme consentimento e registros atualizados. O prazo não representa recomendação clínica de retorno.'],['Campanhas para públicos selecionados','Escolha contatos elegíveis e prepare uma comunicação de relacionamento ou vendas.']].map(([title,body],i)=><li key={title}><span>0{i+1}</span><div><h3>{title}</h3><p>{body}</p></div></li>)}</ol></div></section>
  <section className={s.section}><SectionHeading eyebrow="AUTOMAÇÃO COM CONTROLE" title="Sua equipe participa. Sua clínica define as regras."/><div className={s.solutionGrid}><article><h3>Prepare o atendimento.</h3><ul className={s.checks}>{['Informações administrativas próprias de cada clínica','Escolha entre atendimento humano, IA ou fluxo','Teste o comportamento antes da ativação','Tomada humana quando a conversa precisar'].map(t=><li key={t}><Check size={17}/>{t}</li>)}</ul></article><article><h3>Cuide do relacionamento.</h3><ul className={s.checks}>{['Contatos autorizados por importação ou API de recebimento','Condições de aniversário, ausência e seleção de contatos','Elegibilidade e consentimento para as campanhas','Revisão, horários e limites de envio'].map(t=><li key={t}><Check size={17}/>{t}</li>)}</ul></article></div></section>
  <Faq items={[
    ['A IA responde assim que conecto o WhatsApp?','Não. Depois da conexão, configure o prompt ou fluxo na Configuração de Atendimento, teste e ative as respostas automáticas. Conectar o número não ativa a IA.'],
    ['Minha equipe pode assumir uma conversa?','Sim. Ao assumir o atendimento, você pausa a atuação automática naquela conversa e passa a responder. A retomada da IA é uma ação explícita.'],
    ['Posso enviar campanhas para qualquer contato?','Campanhas exigem destinatários elegíveis e consentimento, além da revisão e ativação. Cadastros e dados de contato precisam estar atualizados para que as condições sejam confiáveis.'],
    ['A IA orienta sobre sintomas ou tratamentos?','O assistente atua no atendimento administrativo e encaminha questões clínicas à equipe de saúde. Não faz diagnóstico, prescrição ou interpretação de exames.'],
    ['Integra com meu sistema de gestão?','A MedSI tem importação e API de recebimento de dados por empresa. A integração depende do que o seu sistema disponibiliza e da configuração do conector. Não há compatibilidade automática garantida com todos os fornecedores.'],
    ['Instagram e Facebook também aparecem na caixa de entrada?','A disponibilidade depende das permissões concedidas, da Página selecionada, dos requisitos da Meta e da homologação do canal. Confira o estado de cada conexão em Integrações.'],
  ]}/>
  <FinalCta title="Cada conversa merece atenção. Sua equipe merece organização." description="Comece a estruturar o atendimento e o relacionamento da sua clínica na MedSI." label="Começar com minha clínica"/>
</MarketingShell>;}
