import {agentModelsConfigured} from '../ai/models';
import {firestoreBackend} from '../platform/config';
import {hostingConfigured,provisionSiteDomain,provisionPublishedSite} from './hosting';
import {Controller,Get,Post,Body,Param,Query,Req,Res,UseGuards,BadRequestException,NotFoundException,ServiceUnavailableException} from '@nestjs/common';
import {Resolver} from 'node:dns/promises';
import {z} from 'zod';
import {generateSite} from './generation';
import {siteContentSchema,siteDomain,renderSite,type SiteContent,type OnboardingSnapshot} from '@askadia/contracts';
import {AuthGuard,type AuthRequest} from '../identity/auth';
import {result} from '../identity/service';
import {adsAccess,serviceDb} from '../campaigns/ads';
function parse<T>(s:z.ZodType<T>,v:unknown){const p=s.safeParse(v);if(!p.success)throw new BadRequestException('Confira os campos do site.');return p.data;}
type Site={slug:string|null;revision:number;profile_version:number;draft:SiteContent|null;published:SiteContent|null;published_revision:number|null;approval?:{revision:number;revoked_at:string|null}|null;published_approval?:{revision:number;revoked_at:string|null}|null};
type Domain={hostname:string;verification_token:string;dns_verified_at:string|null};
function domain(v:string){try{return siteDomain(v);}catch{throw new BadRequestException('Informe somente o domínio público, sem https ou caminho.');}}
@Controller('onboarding/companies/:id/site')
@UseGuards(AuthGuard)
export class CompanySiteController{
 @Get() async read(@Req() r:AuthRequest,@Param('id') company:string){const cap=await adsAccess(r,company);const [site,d,jobs]=await Promise.all([r.actor.client.from('company_sites').select('*').eq('company_id',company).maybeSingle(),r.actor.client.from('company_site_domains').select('*').eq('company_id',company).maybeSingle(),firestoreBackend()?r.actor.client.from('company_site_jobs').select('id,status,error,created_at,updated_at,result_revision').eq('company_id',company).order('created_at',{ascending:false}).limit(1).maybeSingle():Promise.resolve({data:null,error:null})]);return {generationAvailable:agentModelsConfigured('site')&&(!firestoreBackend()||process.env.CONTENT_AUTOPREP_ENABLED!=='false'),generation:result(jobs),site:result<Site|null>(site),domain:result<Domain|null>(d),canEdit:cap.actions.includes('marketing.write'),canPublish:cap.actions.includes(firestoreBackend()?'site.approve':'content.approve'),canDomain:cap.actions.includes('billing.manage'),target:process.env.SITES_CNAME_TARGET||new URL(process.env.WEB_ORIGIN!).hostname,serverIp:process.env.SITES_SERVER_IP||null,hostingConfigured:hostingConfigured(),platformDomain:process.env.SITES_PLATFORM_DOMAIN||new URL(process.env.WEB_ORIGIN!).hostname,publicUrl:new URL('/s/'+company,process.env.WEB_ORIGIN!).href};}
 @Post('generate') async generate(@Req() r:AuthRequest,@Param('id') company:string,@Body() body:unknown){await adsAccess(r,company,'marketing.write');const input=parse(z.object({id:z.uuid(),revision:z.number().int().min(0),feedback:z.string().max(2000).default('')}).strict(),body);if(!agentModelsConfigured('site'))throw new ServiceUnavailableException('Configure a OpenAI e o modelo de site para criar o rascunho.');const profile=result<OnboardingSnapshot>(await r.actor.client.rpc('company_onboarding_read',{p_company_id:company}));if(!profile.confirmedProfile)throw new BadRequestException('Confirme o perfil antes de gerar o site.');if(firestoreBackend()){if(process.env.CONTENT_AUTOPREP_ENABLED==='false')throw new ServiceUnavailableException('A geração de site está pausada no servidor.');const job=result(await r.actor.client.rpc('enqueue_company_site',{p_company_id:company,p_id:input.id,p_revision:input.revision,p_profile_version:profile.confirmedProfile.version,p_feedback:input.feedback}));return {queued:true,job};}const reserved=result(await r.actor.client.rpc('reserve_site_generation',{p_company_id:company,p_id:input.id}));if(reserved===false)throw new BadRequestException('Esta geração já foi solicitada. Atualize a página.');const current=result<Site|null>(await r.actor.client.from('company_sites').select('*').eq('company_id',company).maybeSingle());if((current?.revision??0)!==input.revision)throw new BadRequestException('O site mudou. Atualize a página.');
  const materials=result(await r.actor.client.from('onboarding_attachments').select('id,name,mime,visual_description,description_status').eq('company_id',company).in('mime',['image/jpeg','image/png','image/webp']));let content:SiteContent;
  try{content=await generateSite(profile.confirmedProfile.facts,materials,current?.draft??null,input.feedback);}catch{throw new ServiceUnavailableException('Não foi possível gerar o site. O rascunho anterior foi preservado.');}
  return result(await r.actor.client.rpc('save_company_site',{p_company_id:company,p_revision:input.revision,p_profile_version:profile.confirmedProfile.version,p_content:content}));
 }
 @Post('save') async save(@Req() r:AuthRequest,@Param('id') company:string,@Body() body:unknown){const input=parse(z.object({revision:z.number().int().min(0),profileVersion:z.number().int().positive(),content:siteContentSchema}).strict(),body);await adsAccess(r,company,'marketing.write');return result(await r.actor.client.rpc('save_company_site',{p_company_id:company,p_revision:input.revision,p_profile_version:input.profileVersion,p_content:input.content}));}
 @Post('publish') async publish(@Req() r:AuthRequest,@Param('id') company:string,@Body() body:unknown){const input=parse(z.object({revision:z.number().int().positive(),publish:z.boolean()}).strict(),body);await adsAccess(r,company,firestoreBackend()?'site.approve':'content.approve');if(input.publish){const s=result<Site|null>(await r.actor.client.from('company_sites').select('*').eq('company_id',company).maybeSingle());parse(siteContentSchema,s?.draft);if(firestoreBackend())result(await r.actor.client.rpc('approve_company_site',{p_company_id:company,p_revision:input.revision}));}result(await r.actor.client.rpc('publish_company_site',{p_company_id:company,p_revision:input.revision,p_publish:input.publish}));if(!input.publish)return {ok:true};const [site,custom]=await Promise.all([r.actor.client.from('company_sites').select('slug').eq('company_id',company).maybeSingle(),r.actor.client.from('company_site_domains').select('hostname,dns_verified_at').eq('company_id',company).maybeSingle()]);if(site.error||custom.error)return {ok:true,hosting:{status:'failed',message:'Site publicado no link da MedSI. Confira os endereços em Domínio e endereço e tente Publicar novamente.'}};const hosting=await provisionPublishedSite(company,site.data?.slug??null,custom.data);return {ok:true,hosting};}
 @Post('domain') async setDomain(@Req() r:AuthRequest,@Param('id') company:string,@Body() body:unknown){await adsAccess(r,company,'billing.manage');const input=parse(z.object({hostname:z.string().max(253).nullable()}).strict(),body);const host=input.hostname?domain(input.hostname):null;const platform=new URL(process.env.WEB_ORIGIN!).hostname;if(host&&(host===platform||host.endsWith('.'+platform)))throw new BadRequestException('Use o domínio da clínica.');result(await r.actor.client.rpc('set_site_domain',{p_company_id:company,p_hostname:host}));return {ok:true};}
 @Post('subdomain') async subdomain(@Req() r:AuthRequest,@Param('id') company:string,@Body() body:unknown){await adsAccess(r,company,'billing.manage');const input=parse(z.object({slug:z.string().regex(/^[a-z0-9][a-z0-9-]{1,58}[a-z0-9]$/)}).strict(),body);result(await r.actor.client.rpc('set_site_slug',{p_company_id:company,p_slug:input.slug}));const host=input.slug+'.'+(process.env.SITES_PLATFORM_DOMAIN||new URL(process.env.WEB_ORIGIN!).hostname);return {message:'Endereço reservado: '+host+'. Revise e publique o site antes de solicitar a hospedagem e o HTTPS.'};}
 @Post('verify-domain') async verify(@Req() r:AuthRequest,@Param('id') company:string){await adsAccess(r,company,'billing.manage');const d=result<Domain|null>(await r.actor.client.from('company_site_domains').select('*').eq('company_id',company).maybeSingle());if(!d)throw new BadRequestException('Cadastre o domínio primeiro.');const resolver=new Resolver({timeout:4000,tries:1}),target=process.env.SITES_CNAME_TARGET||new URL(process.env.WEB_ORIGIN!).hostname;const [txt,cnames,ips]=await Promise.all([resolver.resolveTxt('_askadia.'+d.hostname).catch(()=>[]),resolver.resolveCname(d.hostname).catch(()=>[]),resolver.resolve4(d.hostname).catch(()=>[])]);const ownership=txt.some(parts=>parts.join('')==='askadia='+d.verification_token),pointsTo=cnames.some(n=>n.replace(/\.$/,'').toLowerCase()===target)||Boolean(process.env.SITES_SERVER_IP&&ips.some(ip=>typeof ip==='string'&&ip===process.env.SITES_SERVER_IP));if(!ownership||!pointsTo)return {verified:false,message:!ownership?'O registro TXT ainda não foi encontrado. Confira o valor e aguarde a propagação.':'Propriedade confirmada, mas o apontamento CNAME/A ainda não está correto.'};result(await serviceDb().rpc('verify_site_domain_server',{p_company_id:company,p_actor:r.actor.id,p_hostname:d.hostname,p_token:d.verification_token}));const published=result<Site|null>(await r.actor.client.from('company_sites').select('*').eq('company_id',company).maybeSingle());const publishedApproval=published?.published_approval??published?.approval;if(!published?.published||firestoreBackend()&&(!publishedApproval||publishedApproval.revoked_at||publishedApproval.revision!==published.published_revision))return {verified:true,message:'DNS verificado. Revise e publique o site antes de configurar a hospedagem.'};if(hostingConfigured()){try{await provisionSiteDomain(company,d.hostname);result(await serviceDb().rpc('verify_site_domain_server',{p_company_id:company,p_actor:r.actor.id,p_hostname:d.hostname,p_token:d.verification_token,p_routed:true}));return {verified:true,message:'DNS verificado e domínio encaminhado à hospedagem. A emissão automática do HTTPS pode levar alguns minutos. Abra o domínio para conferir antes de divulgar.'};}catch{return {verified:true,message:'DNS verificado. Não foi possível configurar HTTPS na hospedagem. Confira a integração Easypanel ou tente novamente.'};}}return {verified:true,message:'DNS verificado. Cadastre este domínio no serviço MedSI do Easypanel com HTTPS antes de divulgar o endereço. A página já pode ser publicada no link da plataforma.'};}
}
const security={'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Content-Security-Policy':"default-src 'none'; img-src 'self' https:; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'; frame-ancestors 'none'",'Referrer-Policy':'strict-origin-when-cross-origin'};
type Reply={setHeader:(k:string,v:string)=>void;send:(body:string|Buffer)=>void};
@Controller('public-sites')
export class PublicSiteController{
 async record(company:string|null,hostname:string|null,slug:string|null=null){return result<{companyId:string;content:SiteContent;revision:number}|null>(await serviceDb().rpc('read_published_site_server',{p_company_id:company,p_hostname:hostname,p_slug:slug}));}
 @Get('domain') async custom(@Query('host') host:string,@Res() res:Reply){const hostname=domain(host??''),platform=process.env.SITES_PLATFORM_DOMAIN||new URL(process.env.WEB_ORIGIN!).hostname,slug=hostname.endsWith('.'+platform)?hostname.slice(0,-platform.length-1):null;const s=await this.record(null,slug?null:hostname,slug);if(!s)throw new NotFoundException();this.html(s,res);}
 @Get(':id') async read(@Param('id') id:string,@Res() res:Reply){const s=await this.record(parse(z.uuid(),id),null);if(!s)throw new NotFoundException();this.html(s,res);}
 html(s:{companyId:string;content:SiteContent},res:Reply){Object.entries(security).forEach(([k,v])=>res.setHeader(k,v));res.setHeader('Content-Type','text/html; charset=utf-8');res.send(renderSite(s.content,id=>new URL('/api/sites/'+s.companyId+'/media/'+id,process.env.WEB_ORIGIN!).href));}
 @Get(':id/media/:asset') async media(@Param('id') id:string,@Param('asset') asset:string,@Res() res:Reply){const s=await this.record(parse(z.uuid(),id),null);parse(z.uuid(),asset);if(!s||!siteContentSchema.safeParse(s.content).success||!([...s.content.images,s.content.logo].includes(asset)))throw new NotFoundException();const db=serviceDb(),file=result<{object_path:string;mime:string}|null>(await db.from('onboarding_attachments').select('object_path,mime').eq('company_id',id).eq('id',asset).maybeSingle());if(!file||!['image/png','image/jpeg','image/webp'].includes(file.mime)||typeof file.object_path!=='string'||!file.object_path.startsWith(id+'/'))throw new NotFoundException();const blob=await db.storage.from('company-assets').download(file.object_path);if(blob.error||!blob.data)throw new NotFoundException();res.setHeader('Content-Type',file.mime);res.setHeader('Cache-Control','no-store');res.setHeader('X-Content-Type-Options','nosniff');res.send(Buffer.from(await blob.data.arrayBuffer()));}
}
