import {createHmac,timingSafeEqual} from 'node:crypto';
import {BadRequestException,ForbiddenException,ServiceUnavailableException} from '@nestjs/common';
import {z} from 'zod';
const credentialsSchema=z.object({token:z.string().min(1).max(10000),wabaId:z.string().regex(/^\d+$/),phoneId:z.string().regex(/^\d+$/)}).strict();
export type CloudCredentials=z.infer<typeof credentialsSchema>;
/** Credentials are provisioned through the server environment/vault, never chat
 * or browser. Explicit company assignment prevents global-token tenant reuse. */
export function configuredCloudCredentials(company:string):CloudCredentials {
 try{const rows=JSON.parse(process.env.WHATSAPP_CLOUD_CREDENTIALS_JSON??'{}');return credentialsSchema.parse(rows[company]);}catch{throw new ServiceUnavailableException('Configure a credencial oficial WhatsApp desta empresa pelo canal seguro do servidor.');}
}
export function cloudConfigured(company?:string){const key=process.env.SECRETS_ENCRYPTION_KEY;if(!/^[a-f0-9]{64}$/i.test(key??'')||!/^v\d+\.\d+$/.test(process.env.META_GRAPH_API_VERSION??'')||!(process.env.WHATSAPP_CLOUD_APP_SECRET||process.env.META_APP_SECRET)||!process.env.WHATSAPP_CLOUD_VERIFY_TOKEN)return false;if(company)try{configuredCloudCredentials(company);}catch{return false;}return true;}
export async function cloudGraph<T>(phoneOrWaba:string,edge:string,token:string,body?:unknown):Promise<T>{
 const version=process.env.META_GRAPH_API_VERSION;if(!/^v\d+\.\d+$/.test(version??'')||!/^\d+$/.test(phoneOrWaba)||!['','messages','phone_numbers'].includes(edge))throw new ServiceUnavailableException('Versão ou conta oficial WhatsApp não configurada.');
 const url=new URL('https://graph.facebook.com/'+version+'/'+phoneOrWaba+(edge?'/'+edge:''));if(!edge)url.searchParams.set('fields','id,verified_name,display_phone_number,code_verification_status,platform_type');
 let response:Response;try{response=await fetch(url,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(15000),redirect:'error'});}catch{throw new ServiceUnavailableException('O WhatsApp oficial não confirmou esta operação.');}
 if(!response.ok)throw new ServiceUnavailableException(response.status===429?'Limite de uso do WhatsApp oficial atingido.':response.status===401||response.status===403?'A Meta recusou a credencial ou permissão do WhatsApp oficial.':'A Meta não confirmou a operação do WhatsApp oficial.');
 try{return await response.json() as T;}catch{throw new ServiceUnavailableException('Resposta inválida do WhatsApp oficial.');}
}
export async function verifyCloudNumber(credentials:CloudCredentials){
 const [numbers,phone]=await Promise.all([cloudGraph<{data:{id:string}[]}>(credentials.wabaId,'phone_numbers',credentials.token),cloudGraph<{id:string;verified_name?:string;display_phone_number?:string;code_verification_status?:string;platform_type?:string}>(credentials.phoneId,'',credentials.token)]);
 if(!numbers.data?.some(p=>p.id===credentials.phoneId)||phone.id!==credentials.phoneId||phone.code_verification_status!=='VERIFIED'||phone.platform_type!=='CLOUD_API')throw new BadRequestException('A Meta ainda não confirmou este número na Cloud API. Conclua o registro oficial da empresa.');
 return {phoneId:phone.id,wabaId:credentials.wabaId,name:phone.verified_name||phone.display_phone_number||'WhatsApp oficial'};
}
export function verifyCloudSignature(raw:unknown,signature:unknown,secret=process.env.WHATSAPP_CLOUD_APP_SECRET||process.env.META_APP_SECRET){
 if(!secret)throw new ServiceUnavailableException('Assinatura do webhook oficial não configurada.');if(!Buffer.isBuffer(raw)||raw.length>262144||typeof signature!=='string'||!/^sha256=[a-f0-9]{64}$/.test(signature))throw new ForbiddenException('Assinatura do webhook inválida.');const supplied=Buffer.from(signature.slice(7),'hex'),expected=createHmac('sha256',secret).update(raw).digest();if(!timingSafeEqual(supplied,expected))throw new ForbiddenException('Assinatura do webhook inválida.');
}
export function verifyCloudChallenge(query:unknown){const input=z.object({'hub.mode':z.literal('subscribe'),'hub.verify_token':z.string().min(1).max(500),'hub.challenge':z.string().min(1).max(500)}).strict().safeParse(query),token=process.env.WHATSAPP_CLOUD_VERIFY_TOKEN;if(!token)throw new ServiceUnavailableException('Webhook oficial não configurado.');if(!input.success)throw new ForbiddenException();const supplied=Buffer.from(input.data['hub.verify_token']),expected=Buffer.from(token);if(supplied.length!==expected.length||!timingSafeEqual(supplied,expected))throw new ForbiddenException();return input.data['hub.challenge'];}
const webhookSchema=z.object({object:z.literal('whatsapp_business_account'),entry:z.array(z.object({id:z.string().regex(/^\d+$/),changes:z.array(z.object({field:z.string(),value:z.object({metadata:z.object({phone_number_id:z.string().regex(/^\d+$/)}).passthrough(),contacts:z.array(z.object({wa_id:z.string(),profile:z.object({name:z.string().max(150)}).passthrough()}).passthrough()).optional(),messages:z.array(z.object({from:z.string().regex(/^[1-9][0-9]{5,19}$/),id:z.string().min(1).max(200),timestamp:z.string().regex(/^\d{1,12}$/),type:z.string().max(50),text:z.object({body:z.string().max(6000)}).optional()}).passthrough()).max(100).optional()}).passthrough()}).passthrough()).max(100)}).passthrough()).max(100)}).passthrough();
export function cloudWebhookEvents(raw:Buffer){let value:unknown;try{value=JSON.parse(raw.toString('utf8'));}catch{throw new BadRequestException('Evento WhatsApp inválido.');}const parsed=webhookSchema.safeParse(value);if(!parsed.success)throw new BadRequestException('Evento WhatsApp inválido.');return parsed.data.entry.flatMap(entry=>entry.changes.flatMap(change=>change.field!=='messages'?[]:(change.value.messages??[]).map(message=>({phoneId:change.value.metadata.phone_number_id,wabaId:entry.id,messageId:message.id,peer:message.from,time:new Date(Number(message.timestamp)*1000).toISOString(),body:message.type==='text'?message.text?.body??'':'[Arquivo recebido — resposta administrativa requer equipe]',kind:message.type,name:change.value.contacts?.find(c=>c.wa_id===message.from)?.profile.name??''}))));}
