'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import type {AdExecution,AdSpec} from '@askadia/contracts';
import {Button} from '@askadia/ui';
import {journeyApi} from '../lib/journey-api';
import s from './campaigns.module.css';
type Data={items:AdExecution[];seeds?:{status:string;error:string|null}[];enabled:boolean;canApprove:boolean;canEdit:boolean};
const money=(c:number)=>(c/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const labels:Record<AdExecution['status'],string>={preparing:'Preparando para revisão',draft:'Aguardando aprovação',approved:'Aprovada · criando na plataforma',scheduled:'Criada · início programado',active:'Ativada na plataforma',paused:'Pausada',cancelled:'Cancelada',completed:'Período concluído',blocked:'Precisa de atenção',reconciling:'Confirmando resultado na plataforma',stale:'Aprovação desatualizada'};
export function AdExecutions(props:{companyId:string;noticesOnly?:boolean}){return <CompanyAdExecutions key={props.companyId} {...props}/>;}
function CompanyAdExecutions({companyId,noticesOnly=false}:{companyId:string;noticesOnly?:boolean}){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState<string|null>(null),[editing,setEditing]=useState<AdExecution|null>(null);
 const base='companies/'+companyId+'/ads/executions';
 useEffect(()=>{const c=new AbortController();let timer:ReturnType<typeof setTimeout>;async function refresh(){try{const value=await journeyApi<Data>(base,undefined,c.signal);if(!c.signal.aborted){setData(value);setError('');}}catch(e){if(!c.signal.aborted)setError(e instanceof Error?e.message:'Não foi possível consultar as campanhas.');}finally{if(!c.signal.aborted)timer=setTimeout(()=>void refresh(),15000);}}void refresh();return()=>{c.abort();clearTimeout(timer);};},[base]);
 async function action(item:AdExecution,path:string,body:unknown){if(busy)return;setBusy(item.id);setError('');try{await journeyApi(base+'/'+item.id+'/'+path,body);const value=await journeyApi<Data>(base);setData(value);setEditing(null);}catch(e){setError(e instanceof Error?e.message:'Não foi possível concluir.');}finally{setBusy(null);}}
 const alerts=data?.items.filter(i=>['blocked','reconciling','stale'].includes(i.status))??[],drafts=data?.items.filter(i=>i.status==='draft')??[];
 if(noticesOnly){if(!alerts.length&&!drafts.length&&!data?.seeds?.some(i=>i.error))return null;return <aside className={alerts.length?'error-banner':'info-note'} style={{marginBottom:20}} role={alerts.length?'alert':'status'}><strong>{alerts.length?'Campanhas precisam de atenção':'Campanhas prontas para sua aprovação'}</strong>{alerts.slice(0,3).map(i=><p key={i.id}>{i.spec?.name??(i.provider==='meta'?'Meta Ads':'Google Ads')}: {i.error??labels[i.status]}</p>)}{drafts.length>0&&<p>{drafts.length} campanha(s) aguardando revisão do criativo, público, orçamento e programação.</p>}{data?.seeds?.filter(i=>i.error).map((i,n)=><p key={n}>{i.error}</p>)}<Link href={'/empresa/'+companyId+'/campanhas'}>Revisar tráfego pago →</Link></aside>;}
 return <section style={{marginTop:28}} aria-label="Aprovação e execução de anúncios"><h3>Campanhas preparadas pela MedSI</h3><p>Revise e aprove cada campanha. A MedSI cria os anúncios na plataforma e inicia automaticamente na data aprovada. A liberação para veicular depende da análise de Meta/Google.</p>{error&&<p role="alert" className="error-banner">{error}</p>}{data&&!data.enabled&&<p className="info-note">A execução aguarda habilitação na infraestrutura da MedSI.</p>}{data?.seeds?.filter(i=>i.error).map((i,n)=><p className="info-note" key={n}>{i.error}</p>)}{data&&!data.items.length&&<p>As campanhas são preparadas após as cinco etapas da estratégia, com orçamento confirmado no onboarding. Você também pode gerar outra proposta abaixo.</p>}
 {data?.items.map(item=>{const spec=item.spec,when=(value:string)=>new Date(value).toLocaleString('pt-BR',{timeZone:spec?.timezone});return <article className={s.proposal} key={item.id}><h4>{spec?.name??'Campanha em preparação'} · {item.provider==='meta'?'Meta Ads':'Google Ads'}</h4><p><strong>{labels[item.status]}</strong> · versão {item.revision}</p>{item.error&&<p role="alert" className="error-banner">{item.error}</p>}{spec&&<>
 <p>Conta: <strong>{spec.accountName||spec.accountId}</strong> · {spec.accountId}</p><p><strong>{money(spec.budgetCents)} de orçamento total</strong> · {when(spec.startsAt)} até {when(spec.endsAt)} · {spec.timezone}</p>
 <p><strong>Destino:</strong> <a href={spec.destination} target="_blank" rel="noreferrer">{spec.destination}</a></p><p><strong>Região:</strong> raio de {spec.copy.radiusKm} km de {spec.location.label}</p>
 {spec.format==='meta_traffic_image'?<><p>Público: 18 anos ou mais, todos os gêneros, na região selecionada. Feeds do Facebook e Instagram. Objetivo: cliques para o site.</p>{spec.imageId&&<img src={'/api/onboarding/companies/'+companyId+'/attachments/'+spec.imageId} alt={'Criativo para aprovação: '+spec.name} style={{width:'100%',maxWidth:360,maxHeight:450,objectFit:'contain',borderRadius:12}}/>}<h4>{spec.copy.headline}</h4><p style={{whiteSpace:'pre-wrap'}}>{spec.copy.text}</p><p>Botão: Saiba mais</p></>:<><p>Rede de Pesquisa Google · idioma português · presença na região · CPC máximo {money(spec.copy.maxCpcCents)}.</p><p><strong>Títulos:</strong> {spec.copy.headlines.join(' · ')}</p><p><strong>Descrições:</strong> {spec.copy.descriptions.join(' · ')}</p><p><strong>Palavras-chave, correspondência de frase:</strong> {spec.copy.keywords.join(' · ')}</p><p>O Google combina os títulos e descrições aprovados. Este formato usa anúncios de texto.</p></>}
 {spec.siteRevision!==null&&item.status==='draft'&&<p>O site de destino precisa estar publicado na revisão {spec.siteRevision}. <Link href={'/empresa/'+companyId+'/site'}>Revisar site</Link></p>}
 </>}{item.observed&&<p>Último retorno: {String(item.observed.effectiveStatus??item.observed.status??'indisponível')} · {item.checked_at?new Date(item.checked_at).toLocaleString('pt-BR'):'consulta pendente'}. {item.status==='active'&&item.observed.deliveryConfirmed!==true?'A veiculação ainda não foi confirmada.':''}</p>}
 {['insufficient_funds','billing','restricted','pause_pending'].includes(item.error_kind??'')&&<p><a href={item.provider==='meta'?'https://business.facebook.com/billing_hub/?asset_id='+encodeURIComponent(spec?.accountId.replace(/^act_/,'')??''):'https://ads.google.com/'} target="_blank" rel="noreferrer">Conferir conta e pagamentos na plataforma ↗</a></p>}
 <div className={s.actions}>{item.status==='draft'&&<><Button disabled={!!busy||!data.canApprove||!data.enabled} onClick={()=>void action(item,'approve',{revision:item.revision})}>{busy===item.id?'Aprovando…':'Aprovar orçamento e programar'}</Button><Button disabled={!!busy||!data.canEdit} onClick={()=>setEditing(item)}>Revisar texto e programação</Button></>}{['approved','scheduled','active','blocked','reconciling'].includes(item.status)&&<><Button disabled={!!busy||!data.canApprove} onClick={()=>void action(item,'control',{revision:item.revision,action:'pause'})}>Pausar</Button><Button disabled={!!busy||!data.canApprove} onClick={()=>void action(item,'control',{revision:item.revision,action:'cancel'})}>Cancelar programação</Button></>}{['blocked','reconciling'].includes(item.status)&&<Button disabled={!!busy||!data.canApprove} onClick={()=>void action(item,'control',{revision:item.revision,action:'retry'})}>Verificar novamente</Button>}</div>
 {editing?.id===item.id&&spec&&<AdEdit spec={spec} busy={!!busy} save={next=>void action(item,'edit',{revision:item.revision,spec:next})} cancel={()=>setEditing(null)}/>}
 </article>;})}</section>;
}
function AdEdit({spec,busy,save,cancel}:{spec:AdSpec;busy:boolean;save:(v:AdSpec)=>void;cancel:()=>void}){
 const [value,setValue]=useState(spec);const dateValue=(iso:string)=>{const d=new Date(iso);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);};
 const copy=(patch:Partial<AdSpec['copy']>)=>setValue({...value,copy:{...value.copy,...patch}});
 return <form onSubmit={e=>{e.preventDefault();save(value);}} style={{marginTop:20}}><h4>Revisar campanha</h4><p>Salvar cria uma nova versão e remove qualquer aprovação anterior. Datas abaixo no fuso do seu dispositivo: {Intl.DateTimeFormat().resolvedOptions().timeZone}.</p><div className={s.fields}><label>Nome<input required maxLength={100} value={value.name} onChange={e=>setValue({...value,name:e.target.value})}/></label><label>Orçamento total (R$)<input required type="number" min={1} step="0.01" max={spec.budgetCents/100} value={value.budgetCents/100} onChange={e=>setValue({...value,budgetCents:Math.round(Number(e.target.value)*100)})}/></label><label>Início<input required type="datetime-local" value={dateValue(value.startsAt)} onChange={e=>{if(e.target.value)setValue({...value,startsAt:new Date(e.target.value).toISOString()});}}/></label><label>Fim{spec.format==='google_search'?' (mínimo de 3 dias)':''}<input required type="datetime-local" value={dateValue(value.endsAt)} onChange={e=>{if(e.target.value)setValue({...value,endsAt:new Date(e.target.value).toISOString()});}}/></label><label>Raio local (km)<input required type="number" min={1} max={50} value={value.copy.radiusKm} onChange={e=>copy({radiusKm:Number(e.target.value)})}/></label></div>
 {spec.format==='meta_traffic_image'?<><label>Título<input required minLength={3} maxLength={40} value={value.copy.headline} onChange={e=>copy({headline:e.target.value})}/></label><label>Texto<textarea required minLength={10} maxLength={2000} value={value.copy.text} onChange={e=>copy({text:e.target.value})}/></label></>:<><label>Títulos (um por linha, até 30 caracteres cada)<textarea value={value.copy.headlines.join('\n')} onChange={e=>copy({headlines:e.target.value.split('\n')})}/></label><label>Descrições (uma por linha, até 90 caracteres cada)<textarea value={value.copy.descriptions.join('\n')} onChange={e=>copy({descriptions:e.target.value.split('\n')})}/></label><label>Palavras-chave (uma por linha)<textarea value={value.copy.keywords.join('\n')} onChange={e=>copy({keywords:e.target.value.split('\n')})}/></label><label>CPC máximo (R$)<input type="number" min={0.01} max={100} step="0.01" value={value.copy.maxCpcCents/100} onChange={e=>copy({maxCpcCents:Math.round(Number(e.target.value)*100)})}/></label></>}
 <div className={s.actions}><Button type="submit" disabled={busy}>Salvar nova versão</Button><Button type="button" disabled={busy} onClick={cancel}>Fechar</Button></div></form>;
}
