'use client';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {commercePlans,type AsaasBillingState,type CommercePlanId} from '@askadia/contracts';
import {journeyApi} from '../lib/journey-api';
import {billingCheckoutInput,billingPresentation} from '../lib/asaas-billing';
import {brl} from './pricing';

export function AsaasBillingPanel({companyId,plan='askadia_monthly',initialState,onUpdated}:{companyId:string;plan?:CommercePlanId;initialState?:AsaasBillingState;onUpdated?:(state:AsaasBillingState)=>void}){
 const [state,setState]=useState<AsaasBillingState|null>(initialState??null),[selected,setSelected]=useState<CommercePlanId>(initialState?.checkout?.plan_id??plan),[accepted,setAccepted]=useState(false),[cancelAccepted,setCancelAccepted]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const requestId=useRef<string|null>(null),locked=useRef(false),base='companies/'+companyId+'/purchase';
 useEffect(()=>{const abort=new AbortController();void journeyApi<AsaasBillingState>(base+'/billing',undefined,abort.signal).then(value=>{if(!abort.signal.aborted){setState(value);if(value.checkout?.plan_id&&!['cancelled','expired'].includes(value.checkout.status))setSelected(value.checkout.plan_id);}}).catch(()=>{if(!abort.signal.aborted)setError('Não foi possível carregar sua assinatura. Consulte novamente.');});return()=>abort.abort();},[base]);
 const update=(value:AsaasBillingState)=>{setState(value);onUpdated?.(value);};
 async function refresh(){if(locked.current)return;locked.current=true;setBusy(true);setError('');try{if(state?.subscription?.provider_subscription_id)update(await journeyApi<AsaasBillingState>(base+'/billing/reconcile',{}));else update(await journeyApi<AsaasBillingState>(base+'/billing'));}catch{setError('O provedor não confirmou uma atualização. Sua assinatura continua salva para conciliação.');}finally{locked.current=false;setBusy(false);}}
 async function start(event:FormEvent<HTMLFormElement>){event.preventDefault();if(locked.current||!accepted||!state)return;locked.current=true;setBusy(true);setError('');const form=event.currentTarget;try{
  if(!state.customerConfigured){const fields=new FormData(form);await journeyApi(base+'/billing/customer',{name:String(fields.get('name')??'').trim(),cpfCnpj:String(fields.get('cpfCnpj')??'').replace(/\D/g,''),...(fields.get('email')?{email:String(fields.get('email'))}:{})});setState(current=>current?{...current,customerConfigured:true}:current);form.reset();setAccepted(false);}
  const recover=state.checkout&&['submitting','uncertain','prepared'].includes(state.checkout.status);if(state.subscription&&['cancelled','expired'].includes(state.subscription.status))requestId.current=null;requestId.current??=recover?state.checkout!.id:crypto.randomUUID();const chosen=recover?state.checkout!.plan_id:selected;
  update(await journeyApi<AsaasBillingState>(base+'/checkout',billingCheckoutInput(chosen,requestId.current)));setAccepted(false);
 }catch{setError('Não foi possível concluir. Consulte ou recupere o checkout antes de tentar outra contratação.');try{setState(await journeyApi<AsaasBillingState>(base+'/billing'));}catch{/* Keep the last known state. */}}finally{locked.current=false;setBusy(false);}}
 async function cancel(){if(locked.current||!cancelAccepted)return;locked.current=true;setBusy(true);setError('');try{await journeyApi(base+'/billing/cancel',{});update(await journeyApi<AsaasBillingState>(base+'/billing'));requestId.current=null;setCancelAccepted(false);}catch{setError('O cancelamento ainda não foi confirmado. Consulte a assinatura para acompanhar.');try{setState(await journeyApi<AsaasBillingState>(base+'/billing'));}catch{/* Keep the last known state. */}}finally{locked.current=false;setBusy(false);}}
 if(!state)return <section className="panel" aria-label="Assinatura Asaas sandbox"><h2>Assinatura em sandbox</h2><p role="status">Carregando cobrança…</p>{error&&<p role="alert" className="error-banner">{error}</p>}<button type="button" className="button" disabled={busy} onClick={()=>void refresh()}>Consultar assinatura</button></section>;
 const view=billingPresentation(state),sub=state.subscription,canCreate=!sub||sub.status==='cancelled'||sub.status==='expired'&&sub.provider_status!=='ACTIVE',recover=state.checkout&&['uncertain','submitting','prepared'].includes(state.checkout.status),chosen=commercePlans.find(value=>value.id===(recover?state.checkout!.plan_id:selected))!,invoice=sub?.invoice_url??state.checkout?.invoice_url;
 return <section className="panel" aria-label="Assinatura Asaas sandbox"><span className="tag">Sandbox Asaas · sem dinheiro real</span><h2>Sua assinatura de teste</h2><p role="status">{view.label}</p>{error&&<p role="alert" className="error-banner">{error}</p>}
 {sub?.current_period_end&&<p>Período consultado: até {new Date(sub.current_period_end).toLocaleDateString('pt-BR')}.</p>}
 {invoice&&sub?.status!=='cancelled'&&<p><a className="button button-primary" href={invoice} target="_blank" rel="noreferrer">Abrir pagamento no sandbox</a></p>}
 <p><button className="button" type="button" disabled={busy} onClick={()=>void refresh()}>{busy?'Consultando…':'Consultar pagamento'}</button></p>
 {sub?.status==='expired'&&sub.provider_status==='ACTIVE'&&<p>O período pago terminou. Cancele a recorrência existente antes de contratar outro plano.</p>}
 {canCreate&&<form onSubmit={event=>void start(event)} className="form-stack">
  {recover?<p>Recupere a solicitação existente. A consulta evita criar uma segunda assinatura.</p>:<label>Plano para teste<select value={selected} disabled={busy} onChange={event=>{setSelected(event.target.value as CommercePlanId);requestId.current=null;setAccepted(false);}}>{commercePlans.map(value=><option key={value.id} value={value.id}>{value.name} · {brl(value.totalCents)} por período</option>)}</select></label>}
  <p>{chosen.name}: {brl(chosen.totalCents)}, pagamento integral {chosen.commitmentMonths===1?'por mês':'a cada seis meses'}. Parcelamento indisponível neste sandbox.</p>
  {!state.customerConfigured&&<><p>Use somente os dados de um pagador fictício para homologação.</p><label>Nome do pagador<input name="name" autoComplete="off" required minLength={2} maxLength={200} disabled={busy}/></label><label>CPF ou CNPJ do pagador<input name="cpfCnpj" inputMode="numeric" autoComplete="off" required pattern="[0-9]{11}|[0-9]{14}" minLength={11} maxLength={14} disabled={busy}/></label><label>E-mail de teste (opcional)<input name="email" type="email" autoComplete="off" maxLength={254} disabled={busy}/></label></>}
  <label><input type="checkbox" checked={accepted} disabled={busy} onChange={event=>setAccepted(event.target.checked)}/>Confirmo o plano e o pagamento integral em sandbox, sem dinheiro real.</label><button type="submit" className="button button-primary" disabled={busy||!accepted}>{busy?'Conciliando…':recover?'Recuperar checkout':'Criar assinatura no sandbox'}</button>
 </form>}
 {sub&&sub.status!=='cancelled'&&<div className="form-stack"><label><input type="checkbox" checked={cancelAccepted} disabled={busy} onChange={event=>setCancelAccepted(event.target.checked)}/>Confirmo o cancelamento desta assinatura em sandbox e a interrupção do acesso de teste após a confirmação do provedor.</label><button className="button" type="button" disabled={busy||!cancelAccepted} onClick={()=>void cancel()}>Cancelar assinatura</button></div>}
 <p className="form-note">O acesso depende da confirmação consultada no Asaas. Retornar da página de pagamento mantém a cobrança pendente até a conciliação.</p></section>;
}
