'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {Button} from '@askadia/ui';
import {flowFromRules,serviceFlowSchema,inboxLabels,type InboxBootstrap,type InboxChannel,type ServiceSettings} from '@askadia/contracts';
import {journeyApi} from '../lib/journey-api';
import s from './inbox.module.css';
import {AttendancePolicy} from './attendance-policy';
import {ServiceFlowEditor} from './service-flow-editor';
const blank=(channel:InboxChannel):ServiceSettings=>({channel,revision:0,mode:'human',prompt:'',rules:[],fallback:''});
export function AttendanceSettings({companyId,companyName}:{companyId:string;companyName:string}){
 const base='companies/'+companyId+'/inbox';const [info,setInfo]=useState<InboxBootstrap|null>(null),[channel,setChannel]=useState<InboxChannel>('whatsapp'),[form,setForm]=useState<ServiceSettings>(blank('whatsapp')),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[sample,setSample]=useState(''),[answer,setAnswer]=useState('');
 useEffect(()=>{const c=new AbortController();journeyApi<InboxBootstrap>(base,undefined,c.signal).then(d=>{if(!c.signal.aborted){setInfo(d);setForm(d.settings.find(r=>r.channel==='whatsapp')??blank('whatsapp'));}}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[base]);
 useEffect(()=>{const c=new AbortController();let pending=false;const timer=setInterval(async()=>{if(document.hidden||pending)return;pending=true;try{const next=await journeyApi<InboxBootstrap>(base,undefined,c.signal);if(!c.signal.aborted)setInfo(next);}catch{/* Keep unsaved input during temporary availability failures. */}finally{pending=false;}},20000);return()=>{c.abort();clearInterval(timer);};},[base]);
 function change(p:Partial<ServiceSettings>){setForm(v=>({...v,...p}));setDirty(true);setNotice('');setAnswer('');}
 function select(next:InboxChannel){if(dirty&&!window.confirm('Descartar as alterações ainda não salvas deste canal?'))return;setChannel(next);setForm(info?.settings.find(r=>r.channel===next)??blank(next));setDirty(false);setNotice('');setAnswer('');setError('');}
 async function save(){if(form.mode==='flow'&&form.flow){const checked=serviceFlowSchema.safeParse(form.flow);if(!checked.success){setError(checked.error.issues[0]?.message??'Confira as conexões.');return;}}setBusy(true);setError('');try{const result=await journeyApi<ServiceSettings>(base+'/settings',form);setForm(result);setInfo(v=>v?{...v,settings:[...v.settings.filter(r=>r.channel!==channel),result]}:v);setDirty(false);setNotice('Configuração salva para '+companyName+' · '+inboxLabels[channel]+'.');}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar.');}finally{setBusy(false);}}
 async function preview(){setBusy(true);setError('');setAnswer('');try{const r=await journeyApi<{text:string;model:string|null;handoff:boolean}>(base+'/preview',{channel,text:sample});setAnswer(r.text+(r.handoff?'\n\nEncaminhamento humano indicado.':''));}catch(e){setError(e instanceof Error?e.message:'Não foi possível testar.');}finally{setBusy(false);}}
 async function generatePrompt(){setBusy(true);setError('');try{const r=await journeyApi<{prompt:string}>(base+'/generate-prompt',{channel});change({prompt:r.prompt});setNotice('Prompt gerado com o perfil confirmado. Revise e salve para aplicar.');}catch(e){setError(e instanceof Error?e.message:'Não foi possível gerar o prompt.');}finally{setBusy(false);}}
 if(!info)return <section className={s.settingsCard}><p role={error?'alert':'status'}>{error||'Carregando as configurações desta empresa…'}</p>{error&&<Button variant="outline" onClick={()=>window.location.reload()}>Tentar novamente</Button>}</section>;
 const connection=info.connections.find(c=>c.channel===channel);
 const activationBlock=!info.canConfigure?'Seu perfil não permite configurar o atendimento.':channel!=='whatsapp'?'A resposta automática deste canal depende da integração de mensagens.':!connection?.connected?'Conecte o WhatsApp da empresa em Integrações.':form.mode==='human'?'Selecione IA com prompt ou Fluxo visual para ativar respostas automáticas.':!info.automaticReady?'O processamento automático está indisponível. A disponibilidade é atualizada nesta tela a cada 20 segundos.':'';
 return <div>{error&&<p className="error-banner" role="alert">{error}</p>}<div className={s.settings}><nav className={s.channelMenu} aria-label="Canal de atendimento">{(Object.keys(inboxLabels) as InboxChannel[]).map(c=><button key={c} aria-pressed={channel===c} disabled={busy} onClick={()=>select(c)}>{inboxLabels[c]}<small>{info?.connections.find(v=>v.channel===c)?.connected?'Conectado':'Conexão de mensagens pendente'}</small></button>)}</nav><section className={s.settingsCard}><h2>{inboxLabels[channel]}</h2><p>Assistente exclusivo de <strong>{companyName}</strong> · <strong>{info.model??'IA sem modelo configurado'}</strong></p><p>O perfil confirmado desta empresa é utilizado automaticamente. O prompt abaixo orienta somente o atendimento deste canal.</p><p>{connection?.message} {!connection?.connected&&<Link href={'/empresa/'+companyId+'/integracoes'}>Ver conexões</Link>}</p>{info.aiReady===false&&<p className={s.notice} role="status">A IA está indisponível neste servidor. Você pode configurar e utilizar o atendimento humano.</p>}{!info?.automaticReady&&info.aiReady!==false&&<p className={s.notice}>Nesta etapa, a IA e os fluxos sugerem respostas para revisão na caixa de entrada. O processamento automático não está disponível neste servidor.</p>}
 <form onSubmit={e=>{e.preventDefault();void save();}}><fieldset disabled={busy||!info?.canConfigure}><label>Como atender<select value={form.mode} onChange={e=>change({mode:e.target.value as ServiceSettings['mode'],...(e.target.value==='human'?{automatic:false}:{}),...(e.target.value==='flow'&&!form.flow?{flow:flowFromRules(form.rules,form.fallback)}:{})})}><option value="human">Somente atendimento humano</option><option value="ai">IA com prompt da empresa</option><option value="flow">Fluxo visual de atendimento</option></select></label>{form.mode==='ai'&&<><Button type="button" variant="outline" disabled={busy||info.aiReady===false} onClick={()=>void generatePrompt()}>{busy?'Aguarde…':'Gerar prompt com os dados da empresa'}</Button><label>Instruções do assistente<textarea value={form.prompt} rows={10} maxLength={8000} placeholder="Ex.: Seja acolhedor. Descubra o objetivo do interessado, esclareça as especialidades confirmadas e encaminhe para a equipe agendar uma visita. Não prometa descontos nem horários sem confirmação." onChange={e=>change({prompt:e.target.value})}/><small>Preços, serviços e ofertas vêm do perfil confirmado. Informações desconhecidas devem ser encaminhadas à equipe.</small></label></>}{form.mode==='flow'&&<ServiceFlowEditor value={form.flow??flowFromRules(form.rules,form.fallback)} disabled={busy||!info.canConfigure} onChange={flow=>change({flow})}/>}<label><span><input type="checkbox" checked={form.automatic??false} disabled={!info.automaticReady||channel!=='whatsapp'||form.mode==='human'||!connection?.connected} onChange={e=>change({automatic:e.target.checked})}/> Responder automaticamente às novas mensagens</span><small>Ao salvar com esta opção ativa, o assistente responderá por este canal. Histórico antigo não recebe respostas. Assumir a conversa pausa a IA até você devolver o atendimento. Limite de 100 respostas por dia e empresa.</small></label><p role="status">{activationBlock||(form.automatic?"Resposta automática selecionada. Salve para aplicar.":"Pronto para ativar: marque a opção acima e salve a configuração.")}</p><Button type="submit" disabled={!dirty||!info?.canConfigure}>Salvar configuração</Button>{notice&&<p role="status" className={s.saved}>{notice}</p>}</fieldset></form>
 {form.mode!=='human'&&<section className={s.rule}><h3>Testar sem enviar</h3><p>Salve o canal e confira como o assistente responderia. O teste não envia mensagens a contatos.</p><label>Mensagem de teste<textarea value={sample} rows={2} maxLength={2000} onChange={e=>setSample(e.target.value)}/></label><Button variant="outline" disabled={busy||dirty||!form.revision||!sample.trim()||!info?.canWrite||(form.mode==='ai'&&info.aiReady===false)} onClick={()=>void preview()}>Testar atendimento</Button>{answer&&<p style={{whiteSpace:'pre-wrap'}} role="status">{answer}</p>}</section>}
 {channel==='whatsapp'&&<AttendancePolicy key={companyId} companyId={companyId} revision={form.revision} canConfigure={info.canConfigure}/> }
 </section></div></div>;
}
