'use client';
import {useCallback,useEffect,useState} from 'react';
import {Button} from '@askadia/ui';
import {journeyApi} from '../lib/journey-api';
type Hour={day:number;start:number;end:number};
type State={revision:number;profileVersion:number;valid:boolean;policy:null|{timezone:string;hours:Hour[];approved_at:string}};
const days=['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado'];
const minutes=(value:string)=>Number(value.slice(0,2))*60+Number(value.slice(3));
const time=(value:number)=>String(Math.floor(value/60)).padStart(2,'0')+':'+String(value%60).padStart(2,'0');
export function AttendancePolicy({companyId,revision,canConfigure}:{companyId:string;revision:number;canConfigure:boolean}){
 const base='companies/'+companyId+'/inbox/policy';const [state,setState]=useState<State|null>(null),[timezone,setTimezone]=useState('America/Sao_Paulo'),[hours,setHours]=useState<Hour[]>([]),[reviewed,setReviewed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const load=useCallback(async(signal?:AbortSignal)=>{const data=await journeyApi<State>(base,undefined,signal);if(!signal?.aborted){setState(data);setTimezone(data.policy?.timezone??'America/Sao_Paulo');setHours(data.policy?.hours??[]);setReviewed(false);}},[base]);
 useEffect(()=>{const controller=new AbortController();void load(controller.signal).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[load,revision]);
 async function save(){if(!state)return;setBusy(true);setError('');setMessage('');try{await journeyApi(base,{revision:state.revision,profileVersion:state.profileVersion,timezone,hours,reviewed});await load();setMessage('Horários revisados e vinculados à versão salva.');}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar os horários.');}finally{setBusy(false);}}
 return <section className="form"><h3>Horários e revisão do atendimento</h3><p>A equipe continua disponível para atendimento humano. A automação só poderá agir dentro dos horários revisados, com consentimento registrado e após homologação do canal. Alterar as regras ou o perfil exige nova revisão.</p>{state&&<p role="status">{state.valid?'Revisão válida para a configuração atual.':'A configuração atual ainda precisa de revisão dos horários.'}</p>}{error&&<p className="form-error" role="alert">{error}</p>}<fieldset disabled={busy||!canConfigure}><label>Fuso horário<input value={timezone} onChange={e=>{setTimezone(e.target.value);setReviewed(false);}} required maxLength={100}/></label>{days.map((label,day)=>{const hour=hours.find(h=>h.day===day);return <div className="row" style={{flexWrap:'wrap'}} key={day}><label><span><input type="checkbox" checked={Boolean(hour)} onChange={e=>{setHours(rows=>e.target.checked?[...rows,{day,start:540,end:1080}]:rows.filter(h=>h.day!==day));setReviewed(false);}}/> {label}</span></label>{hour&&<><label>Abre<input type="time" value={time(hour.start)} onChange={e=>{setHours(rows=>rows.map(h=>h.day===day?{...h,start:minutes(e.target.value)}:h));setReviewed(false);}}/></label><label>Fecha<input type="time" value={time(hour.end)} onChange={e=>{setHours(rows=>rows.map(h=>h.day===day?{...h,end:minutes(e.target.value)}:h));setReviewed(false);}}/></label></>}</div>;})}<label><span><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/> Revisei as regras salvas, os horários e o encaminhamento humano desta empresa.</span></label><Button type="button" disabled={!state?.revision||!state.profileVersion||!reviewed||!hours.length} onClick={()=>void save()}>Salvar revisão dos horários</Button>{message&&<p role="status">{message}</p>}</fieldset></section>;
}
