'use client';
import {useEffect,useState} from 'react';
import {Button} from '@askadia/ui';
import {journeyApi} from '../lib/journey-api';
type Data={students:{id:string;name:string;phone:string;consent:boolean;tag:string}[];contacts:{id:string;name:string;phone_e164:string|null}[]};
export function CampaignRecipients({companyId,selected,onChange}:{companyId:string;selected:string[];onChange:(ids:string[])=>void}){
 const base='companies/'+companyId+'/campaigns';const [data,setData]=useState<Data|null>(null),[search,setSearch]=useState(''),[crm,setCrm]=useState<string[]>([]),[evidence,setEvidence]=useState(''),[confirmed,setConfirmed]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{const c=new AbortController();void journeyApi<Data>(base+'/recipients',undefined,c.signal).then(d=>{if(!c.signal.aborted)setData(d);}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[base]);
 async function register(){if(busy)return;setBusy(true);setError('');try{const r=await journeyApi<{ids:string[]}>(base+'/recipients/register',{contactIds:crm,evidence,confirmed});const d=await journeyApi<Data>(base+'/recipients');setData(d);onChange([...new Set([...selected,...r.ids])].slice(0,500));setCrm([]);setConfirmed(false);setEvidence('');}catch(e){setError(e instanceof Error?e.message:'Falha ao registrar.');}finally{setBusy(false);}}
 return <section><h3>Contatos pré-selecionados · {selected.length}/500</h3><p>Envio único por contato nesta campanha, distribuído pelo horário e limite diário. Alterar o texto não reenvia para quem já recebeu.</p>{error&&<p role="alert">{error}</p>}<input aria-label="Buscar destinatários" placeholder="Buscar nome, telefone ou grupo" value={search} onChange={e=>setSearch(e.target.value)}/><div style={{maxHeight:260,overflow:'auto',margin:'12px 0'}}>{data?.students.filter(s=>(s.name+s.phone+s.tag).toLocaleLowerCase('pt-BR').includes(search.toLocaleLowerCase('pt-BR'))).map(s=><div key={s.id} style={{display:'flex',gap:8,alignItems:'center',padding:8}}><label style={{flex:1}}><input style={{width:'auto'}} type="checkbox" disabled={!s.consent||busy||(!selected.includes(s.id)&&selected.length>=500)} checked={selected.includes(s.id)} onChange={e=>onChange(e.target.checked?[...selected,s.id]:selected.filter(id=>id!==s.id))}/> {s.name} · {s.phone} {!s.consent&&'· sem autorização'}</label>{s.consent&&<Button type="button" size="small" variant="ghost" disabled={busy} onClick={async()=>{setBusy(true);try{await journeyApi(base+'/recipients/revoke',{id:s.id});onChange(selected.filter(id=>id!==s.id));setData(await journeyApi<Data>(base+'/recipients'));}catch(e){setError(e instanceof Error?e.message:'Falha ao revogar');}finally{setBusy(false);}}}>Revogar autorização</Button>}</div>)}</div><small>Até 1.000 contatos carregados. Autorização e atualização dos dados são verificadas novamente antes de cada envio.</small><details><summary>Adicionar contatos do CRM com autorização</summary><p>Selecione somente pessoas que autorizaram mensagens comerciais. Ter conversado pelo WhatsApp não registra essa autorização.</p><div style={{maxHeight:220,overflow:'auto'}}>{data?.contacts.filter(c=>c.phone_e164&&(c.name+c.phone_e164).toLocaleLowerCase('pt-BR').includes(search.toLocaleLowerCase('pt-BR'))).map(c=><label key={c.id} style={{display:'block',padding:6}}><input style={{width:'auto'}} type="checkbox" disabled={busy||(!crm.includes(c.id)&&crm.length>=500)} checked={crm.includes(c.id)} onChange={e=>setCrm(e.target.checked?[...crm,c.id]:crm.filter(id=>id!==c.id))}/> {c.name} · {c.phone_e164}</label>)}</div><label>Origem e data da autorização<input maxLength={500} minLength={5} value={evidence} onChange={e=>setEvidence(e.target.value)} placeholder="Ex.: formulário de contato, aceite em 22/09/2026"/></label><label><input style={{width:'auto'}} type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> Confirmo a autorização desses contatos para mensagens comerciais.</label><Button type="button" disabled={busy||!crm.length||!confirmed||evidence.trim().length<5} onClick={()=>void register()}>Registrar autorização e selecionar</Button></details></section>;
}
