'use client';
import {AsaasBillingPanel} from './asaas-billing-panel';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import type {PurchaseState} from '@askadia/contracts';
import {commercePlans} from '@askadia/contracts';
import {journeyApi} from '../lib/journey-api';
export function CompanyPlan({companyId}:{companyId:string}){
 const [data,setData]=useState<PurchaseState|null>(null),[error,setError]=useState('');
 useEffect(()=>{const c=new AbortController();void journeyApi<PurchaseState>('companies/'+companyId+'/purchase',undefined,c.signal).then(d=>{if(!c.signal.aborted)setData(d);}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[companyId]);
 if(error)return <p role="alert" className="error-banner">{error}</p>;if(!data)return <p role="status">Carregando plano…</p>;
 return <><div className="section-heading"><h2>Plano desta empresa</h2><span className="tag">{data.accessMode==='test'?(data.asaasSandboxEnabled?'Pagamento sandbox confirmado':'Ativado em simulação · sem cobrança'):data.aiAllowed?'Ativo':'Sem contratação'}</span></div><section className="panel"><h3>{commercePlans.find(p=>p.id===data.planId)?.name??(data.aiAllowed?'Assinatura existente':'Escolha seu próximo passo')}</h3><p>{data.accessMode==='test'?data.asaasSandboxEnabled?'O Asaas confirmou o pagamento sandbox. O acesso de teste vale até '+new Date(data.testUntil!).toLocaleDateString('pt-BR')+'.':'O pagamento foi simulado. O acesso de teste vale até '+new Date(data.testUntil!).toLocaleDateString('pt-BR')+'. Nenhuma assinatura recorrente real foi iniciada.':data.aiAllowed?'A assinatura está vinculada somente a esta empresa.':'Cadastro e onboarding são gratuitos. Confirme um plano para liberar a IA desta empresa.'}</p><Link className="button button-primary" href={'/comecar?empresa='+companyId}>{data.aiAllowed?'Revisar estratégia':'Continuar cadastro e escolher plano'}</Link></section>{data.asaasSandboxEnabled&&data.canPurchase&&<AsaasBillingPanel companyId={companyId} onUpdated={()=>{void journeyApi<PurchaseState>('companies/'+companyId+'/purchase').then(setData).catch(()=>setError('Não foi possível atualizar o acesso da assinatura. Consulte novamente.'));}}/>}<p className="form-note">{data.asaasSandboxEnabled?'Sandbox: mensal R$ 1.597 por mês ou semestral R$ 8.000 por período, pagamento integral. Parcelamento indisponível.':'Mensal: R$ 1.597/mês. Semestral: R$ 8.000 em até 6x no cartão (5 de R$ 1.333,33 e a última de R$ 1.333,35).'} Preços por empresa. Verba de anúncios e provedores externos são cobrados separadamente.</p><Link href="/planos">Comparar planos e recursos →</Link></>;
}
