'use client';
import {useState} from 'react';
import {Button} from '@askadia/ui';
import {journeyApi} from '../lib/journey-api';
export function ContactConsent({companyId,contacts,refresh}:{companyId:string;contacts:{id:string;name:string;consent?:boolean;opted_out?:boolean}[];refresh:()=>Promise<void>}){
 const [contactId,setContactId]=useState(''),[mode,setMode]=useState<'unknown'|'consent'|'optout'>('unknown'),[evidence,setEvidence]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 async function save(){setBusy(true);setError('');setMessage('');try{await journeyApi('companies/'+companyId+'/inbox/consent',{contactId,consent:mode==='consent',optOut:mode==='optout',evidence});await refresh();setMessage('Preferência do contato registrada. Nenhuma mensagem foi enviada.');}catch(e){setError(e instanceof Error?e.message:'Não foi possível registrar a preferência.');}finally{setBusy(false);}}
 return <details><summary>Consentimento e interrupção de mensagens</summary><form className="form" onSubmit={e=>{e.preventDefault();void save();}}><p>Registre a preferência expressa pelo contato para o atendimento administrativo. O registro não autoriza campanhas de marketing. Um pedido de interrupção bloqueia novas respostas e preserva o atendimento humano interno.</p><fieldset disabled={busy}><label>Contato<select required value={contactId} onChange={e=>{setContactId(e.target.value);const contact=contacts.find(c=>c.id===e.target.value);setMode(contact?.opted_out?'optout':contact?.consent?'consent':'unknown');setEvidence('');setMessage('');}}><option value="">Selecione o contato</option>{contacts.map(c=><option key={c.id} value={c.id}>{c.name}{c.opted_out?' · mensagens interrompidas':c.consent?' · consentimento registrado':' · consentimento pendente'}</option>)}</select></label><label>Preferência<select value={mode} onChange={e=>setMode(e.target.value as typeof mode)}><option value="unknown">Consentimento não confirmado</option><option value="consent">Autorizou atendimento administrativo</option><option value="optout">Pediu para interromper mensagens</option></select></label><label>Origem e data da preferência<input required minLength={2} maxLength={500} value={evidence} onChange={e=>setEvidence(e.target.value)} placeholder="Ex.: pedido recebido nesta conversa em 07/10/2026"/></label><Button disabled={!contactId||evidence.trim().length<2}>Registrar preferência</Button></fieldset>{error&&<p className="form-error" role="alert">{error}</p>}{message&&<p role="status">{message}</p>}</form></details>;
}
