'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {MessageCircle,ArrowUpRight,UserRound} from 'lucide-react';
import {Modal} from '@askadia/ui';
import type {InboxMessage} from '@askadia/contracts';
import {journeyApi} from '../lib/journey-api';
import s from './customer-history.module.css';
type History={contact:{name:string;phone_e164:string|null;email:string|null;created_at:string};opportunities:{id:string;stage:string;interest:string}[];thread:string|null;warning:string;hasMore:boolean;messages:InboxMessage[];metrics:{firstAvailableAt:string|null;firstResponseMs:number|null;averageResponseMs:number|null;responseCount:number;awaitingSince:string|null;lastInbound:InboxMessage|null;lastOutbound:InboxMessage|null};conversations:{id:string;triage_summary:string|null}[];notes:{id:string;body:string;created_at:string}[];stages:{id:string;stage:string;reason:string;created_at:string}[]};
const stages:Record<string,string>={new:'Novo',in_progress:'Em atendimento',qualified:'Qualificado',referred:'Encaminhado',scheduled:'Consulta agendada',attended:'Compareceu',enrolled:'Conversão confirmada',lost:'Perdido'};
const date=(v:string|null)=>v?new Date(v).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'}):'Não disponível';
const duration=(v:number|null)=>v===null?'Sem resposta':v<60000?'Menos de 1 min':v<3600000?Math.round(v/60000)+' min':(v/3600000).toFixed(1)+' h';
export function CustomerHistory({companyId,contactId,close}:{companyId:string;contactId:string;close:()=>void}){
 const [data,setData]=useState<History|null>(null),[error,setError]=useState('');
 useEffect(()=>{const c=new AbortController();setData(null);setError('');void journeyApi<History>('companies/'+companyId+'/crm/contacts/'+contactId+'/history',undefined,c.signal).then(d=>{if(!c.signal.aborted)setData(d);}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[companyId,contactId]);
 const chat=data?.thread?'/empresa/'+companyId+'/atendimento?thread='+encodeURIComponent(data.thread)+'&contactName='+encodeURIComponent(data.contact.name):null;
 return <Modal open className={s.modal} onOpenChange={v=>{if(!v)close();}} title="Ficha do lead" description="Contato, atendimento e histórico em um só lugar.">
 {error&&<p className={s.notice} role="alert">{error}</p>}{!data&&!error?<p className={s.empty} role="status">Consultando histórico…</p>:data&&<div className={s.body}>
 <header className={s.profile}><div className={s.avatar} aria-hidden="true">{/[\p{L}]/u.test(data.contact.name)?data.contact.name.split(/\s+/).slice(0,2).map(v=>v[0]).join('').toUpperCase():<UserRound size={26}/>}</div><div className={s.identity}><h2>{data.contact.name}</h2><div className={s.tags}>{data.thread&&<span className={s.channel}>WhatsApp</span>}{data.opportunities.map(o=><span key={o.id}>{stages[o.stage]??o.stage}</span>)}</div><div className={s.contact}><span>{data.contact.phone_e164||'Telefone não informado'}</span>{data.contact.email&&<span>{data.contact.email}</span>}</div></div></header>
 {chat?<Link className={s.chatButton} href={chat}><MessageCircle size={18}/>Abrir conversa no chat<ArrowUpRight size={17}/></Link>:<p className={s.empty}>Este contato ainda não tem uma conversa vinculada.</p>}
 {data.warning&&<p className={s.notice} role="status">{data.warning}</p>}
 <dl className={s.metrics}><div><dt>Primeiro contato disponível</dt><dd>{date(data.metrics.firstAvailableAt)}</dd><small>Histórico do WhatsApp</small></div><div><dt>Entrada no CRM</dt><dd>{date(data.contact.created_at)}</dd><small>Data do cadastro</small></div><div><dt>Primeira resposta</dt><dd>{duration(data.metrics.firstResponseMs)}</dd><small>Na amostra consultada</small></div><div><dt>Tempo médio de resposta</dt><dd>{duration(data.metrics.averageResponseMs)}</dd><small>{data.metrics.responseCount} resposta(s) na amostra</small></div></dl>
 <p className={s.help}>Indicadores calculados com até 50 mensagens recentes, incluindo respostas humanas e da IA. O histórico disponível pode não conter o primeiro contato original.</p>
 {data.metrics.awaitingSince&&<p className={s.notice}>Última mensagem sem resposta na amostra · {date(data.metrics.awaitingSince)}</p>}
 <section className={s.section}><h3>Últimas interações</h3><div className={s.messageGrid}>{[{label:'Cliente',message:data.metrics.lastInbound},{label:'Empresa',message:data.metrics.lastOutbound}].map(({label,message})=><article className={s.message} key={label}><header><strong>{label}</strong>{message?.time&&<time>{date(message.time)}</time>}</header><p>{message?.body??'Nenhuma mensagem disponível.'}</p></article>)}</div>{data.conversations.filter(c=>c.triage_summary).map(c=><div className={s.summary} key={c.id}><strong>Resumo do atendimento</strong><p>{c.triage_summary}</p></div>)}</section>
 {data.opportunities.some(o=>o.interest)&&<section className={s.section}><h3>Interesses registrados</h3>{data.opportunities.filter(o=>o.interest).map(o=><p className={s.summary} key={o.id}>{o.interest}</p>)}</section>}
 <details className={s.details}><summary>Mensagens recentes · {Math.min(20,data.messages.length)}</summary>{data.messages.slice(-20).map(m=><article key={m.id} className={s.timelineItem}><small>{m.fromMe?'Empresa':'Cliente'} · {date(m.time)}</small><p>{m.body}</p></article>)}{!data.messages.length&&<p className={s.empty}>Nenhuma mensagem disponível.</p>}{data.hasMore&&<p className={s.help}>Abra a conversa para consultar mais mensagens.</p>}</details>
 <section className={s.section}><h3>Histórico comercial</h3><div className={s.timeline}>{[...data.notes.map(n=>({...n,label:'Nota interna',text:n.body})),...data.stages.map(n=>({...n,label:stages[n.stage]??'Mudança de etapa',text:n.reason}))].sort((a,b)=>b.created_at.localeCompare(a.created_at)).map(n=><article className={s.timelineItem} key={n.id}><header><strong>{n.label}</strong><time>{date(n.created_at)}</time></header><p>{n.text}</p></article>)}</div>{!data.notes.length&&!data.stages.length&&<p className={s.empty}>As notas e mudanças de etapa aparecerão aqui.</p>}</section>
 </div>}</Modal>;
}
