'use client';
import { useCallback,useEffect,useState,type ChangeEvent } from 'react';
import { Download,Upload,FileText,ShieldCheck } from 'lucide-react';
import { Button } from '@askadia/ui';
import { draftImportSchema,exportedDraftsSchema,type DraftImport,type DraftImportResult,type EditorialDraft,type Company } from '@askadia/contracts';
import { readWorkspace,storageKey } from '../lib/workspace';
import { connectedApi } from '../lib/api-client';
export function DraftImportPanel({companyId,companyName}:{companyId:string;companyName:string}){
  const [payload,setPayload]=useState<DraftImport|null>(null),[sourceName,setSourceName]=useState(''),[localCompanies,setLocalCompanies]=useState<Company[]>([]);
  const [error,setError]=useState(''),[busy,setBusy]=useState(false),[confirmed,setConfirmed]=useState(false),[result,setResult]=useState<DraftImportResult|null>(null),[drafts,setDrafts]=useState<EditorialDraft[]|null>(null);
  const reload=useCallback(async(signal?:AbortSignal)=>{try{const r=await connectedApi<EditorialDraft[]>('companies/'+companyId+'/drafts',{signal});if(!signal?.aborted)setDrafts(r);}catch(e){if(!signal?.aborted)setError(e instanceof Error?e.message:'Não foi possível carregar rascunhos.');}},[companyId]);
  useEffect(()=>{const c=new AbortController();void reload(c.signal);return()=>c.abort();},[reload]);
  function prepare(input:unknown,name:string){const parsed=draftImportSchema.safeParse(input);if(!parsed.success)throw new Error('Arquivo inconsistente. Confira empresa, contatos vinculados, datas e limites: até 100 contatos, 100 oportunidades e 30 peças por lote.');setPayload(parsed.data);setSourceName(name);setConfirmed(false);setResult(null);setError('');}
  function loadLocal(id?:string){try{const state=readWorkspace(localStorage.getItem(storageKey));setLocalCompanies(state.companies);const company=state.companies.find(c=>c.id===id)??state.companies[0];if(!company)throw new Error('Não há rascunhos locais neste navegador. Você também pode escolher um arquivo exportado.');prepare({sourceCompanyId:company.id,contacts:state.contacts.filter(c=>c.companyId===company.id),opportunities:state.opportunities.filter(c=>c.companyId===company.id),contents:state.contents.filter(c=>c.companyId===company.id)},company.name);}catch(e){setError(e instanceof Error?e.message:'Não foi possível ler os rascunhos.');setPayload(null);}}
  async function loadFile(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;setPayload(null);setResult(null);setError('');try{if(file.size>262144)throw new Error('O arquivo deve ter até 256 KiB. Divida a exportação em lotes menores.');const parsed=exportedDraftsSchema.safeParse(JSON.parse(await file.text()));if(!parsed.success)throw new Error('Escolha um JSON exportado pela prévia local da MedSI.');prepare({sourceCompanyId:parsed.data.company.id,contacts:parsed.data.contacts,opportunities:parsed.data.opportunities,contents:parsed.data.contents},parsed.data.company.name);setLocalCompanies([]);}catch(e){setError(e instanceof Error?e.message:'Arquivo inválido.');}event.target.value='';}
  async function importNow(){if(!payload||!confirmed)return;setBusy(true);setError('');try{const r=await connectedApi<DraftImportResult>('companies/'+companyId+'/import',{method:'POST',body:payload});setResult(r);setPayload(null);setConfirmed(false);await reload();}catch(e){setError(e instanceof Error?e.message:'Importação não concluída.');}finally{setBusy(false);}}
  function exportDrafts(){if(!drafts)return;const url=URL.createObjectURL(new Blob([JSON.stringify({companyId,companyName,drafts},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='medsi-rascunhos-persistidos.json';a.click();URL.revokeObjectURL(url);}
  return <><div className="section-heading"><h2>Traga seus rascunhos para {companyName}</h2></div>
    <div className="info-note"><ShieldCheck size={18}/><p>Escolha a origem e confira o destino. Os dados locais serão preservados. Peças entram como rascunho e oportunidades voltam à etapa Novo para validação. Aprovações e conversões locais não são transferidas.</p></div>
    <section className="panel import-panel"><div className="import-actions"><Button variant="outline" onClick={()=>loadLocal()} disabled={busy}><FileText size={16}/>Ler deste navegador</Button><label className="button button-outline"><Upload size={16}/>Escolher JSON<input type="file" accept="application/json,.json" onChange={loadFile} disabled={busy} className="sr-only"/></label></div>
      {error&&<div className="error-banner" role="alert">{error}</div>}
      {localCompanies.length>1&&<label className="form">Empresa de origem<select value={payload?.sourceCompanyId??''} onChange={e=>loadLocal(e.target.value)} disabled={busy}>{localCompanies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>}
      {payload&&<div className="import-preview"><h3>{sourceName} → {companyName}</h3><p>{payload.contacts.length} contatos · {payload.opportunities.length} oportunidades · {payload.contents.length} peças</p><ul>{payload.contents.map(c=><li key={c.id}>{c.title} · {c.format} · entrará como rascunho</li>)}{payload.contacts.slice(0,10).map(c=><li key={c.id}>{c.name} · contato</li>)}</ul>{payload.contacts.length>10&&<p>Mais {payload.contacts.length-10} contatos neste lote.</p>}<label className="confirm-import"><input type="checkbox" checked={confirmed} disabled={busy} onChange={e=>setConfirmed(e.target.checked)}/>Confirmo que {companyName} é a empresa de destino destes dados.</label><Button onClick={importNow} disabled={!confirmed||busy}>{busy?'Importando…':'Confirmar importação'}</Button></div>}
      {result&&<div className="tenant-notice" role="status">Importação persistida: {result.contacts} contatos, {result.opportunities} oportunidades e {result.contents} peças. {result.skipped} registros já existentes foram preservados.</div>}
    </section>
    <div className="section-heading"><h2>Rascunhos persistidos</h2><Button variant="outline" disabled={!drafts?.length} onClick={exportDrafts}><Download size={15}/>Exportar peças</Button></div>
    {drafts===null?<div className="tenant-loading" role="status">{error?'Consulta indisponível.':'Carregando peças…'}</div>:!drafts.length?<section className="panel internal-empty"><h3>Nenhuma peça persistida para seu acesso.</h3><p>Após importar, suas peças aparecem aqui. Edição e produção conectadas serão adicionadas ao estúdio.</p></section>:<div className="tenant-company-grid">{drafts.map(d=><article className="panel tenant-company-card" key={d.id}><span className="tag">Rascunho · v{d.version}</span><h2>{d.title}</h2><p>{d.format}{d.planned_date?' · '+d.planned_date.split('-').reverse().join('/'):''}</p><p className="draft-caption">{d.caption||'Sem legenda'}</p></article>)}</div>}
  </>;
}
