'use client';
import {useCallback,useEffect,useState} from 'react';
import Link from 'next/link';
import {Button} from '@askadia/ui';
import {Check,ArrowRight,MousePointer2,LoaderCircle} from 'lucide-react';
import {stageReady,type OnboardingSnapshot,type LaunchRecommendations,type MarketingJourney,type RegionalReview} from '@askadia/contracts';
import {RegionalAudienceReview} from './regional-audience';
import {PreparationStatus} from './preparation-status';
import {StrategyWorkspace} from './strategy-workspace';
import {MarketingFacts} from './marketing-facts';
import {InstagramProfiles} from './instagram-profiles';
import {journeyApi} from '../lib/journey-api';
import styles from './guided-strategy.module.css';
export type {MarketingJourney} from '@askadia/contracts';
const titles=['Concorrentes e análise','Diagnóstico e planos','Publicações e datas','Relacionamento e vendas','Tráfego pago'];
const instructions=['Confira os perfis e os dados coletados. Depois, aprove a análise que orientará o diagnóstico.','Leia o diagnóstico e os planos macro, de médio e curto prazo. Peça ajustes ou aprove para continuar.','Revise os temas, formatos e datas. Cada peça ainda precisa de produção e revisão antes de publicar.','Confira as sugestões de atendimento e de campanhas para pacientes e novos clientes.','Revise as propostas de aquisição. A execução depende das integrações e dos recursos disponíveis no ambiente.'];
type PlanItem={id:string;date:string|null;idea:string;direction:string;format:string};
export function GuidedStrategy({companyId,data:initialData,write,approve,compact=false,onComplete}:{companyId:string;data:OnboardingSnapshot|null;write:boolean;approve:boolean;compact?:boolean;onComplete?:()=>void}){
 const [updatedProfile,setUpdatedProfile]=useState<OnboardingSnapshot|null>(null);const data=updatedProfile??initialData;
 useEffect(()=>setUpdatedProfile(null),[companyId,initialData]);
 const [journey,setJourney]=useState<MarketingJourney|null>(null),[selected,setSelected]=useState<number|null>(null),[error,setError]=useState(''),[loadError,setLoadError]=useState(''),[strategyEditing,setStrategyEditing]=useState(false),[busy,setBusy]=useState(false),[limitations,setLimitations]=useState('');const base='companies/'+companyId;
 const [regionalDirty,setRegionalDirty]=useState(false),[gapsAcknowledged,setGapsAcknowledged]=useState(false);
 const [pollDelay,setPollDelay]=useState(300000);
 const [posts,setPosts]=useState(8),[weekly,setWeekly]=useState(2);
 useEffect(()=>{if(journey?.planning){setPosts(journey.planning.postsPerMonth);setWeekly(journey.planning.maxPostsPerWeek);}},[journey?.planning?.postsPerMonth,journey?.planning?.maxPostsPerWeek]);
 const load=useCallback(async(signal?:AbortSignal)=>{const value=await journeyApi<MarketingJourney>(base+'/launch/journey',undefined,signal);if(!signal?.aborted){const regional=(value.stages[0]?.data as {regional?:RegionalReview}|null)?.regional;const working=[regional?.revision?regional.status:null,value.strategy?.status,value.preparation?.content?.status,value.preparation?.recommendations?.status].some(status=>status==='pending'||status==='running'||status==='generating');setPollDelay(working?15000:300000);setJourney(value);setLoadError('');}},[base]);
 useEffect(()=>{const c=new AbortController();let timer:ReturnType<typeof setTimeout>;let running=false;
  async function refresh(){if(running||c.signal.aborted)return;running=true;try{if(!document.hidden)await load(c.signal);}catch(e){if(!c.signal.aborted){setLoadError(e instanceof Error?e.message:'Não foi possível carregar as etapas.');setPollDelay(300000);}}finally{running=false;if(!c.signal.aborted)timer=setTimeout(()=>void refresh(),document.hidden?60000:pollDelay);}}
  function visible(){if(!document.hidden){clearTimeout(timer);void refresh();}}
  document.addEventListener('visibilitychange',visible);void refresh();return()=>{c.abort();clearTimeout(timer);document.removeEventListener('visibilitychange',visible);};
 },[load,pollDelay]);
 const current=journey?.stages.find(s=>!s.approved)?.stage??5;const active=Math.min(selected??current,current);const stage=journey?.stages.find(s=>s.stage===active);const previousApproved=journey?.stages.filter(s=>s.stage<active).every(s=>s.approved);
 const regional=(journey?.stages[0]?.data as {regional?:RegionalReview}|null)?.regional;
 const stageTitles=regional?['Público da região',...titles.slice(1)]:titles;
 const digitalProfiles=(journey?.stages[0]?.data as {digital?:{profiles:{username:string;snapshot:unknown}[]}}|null)?.digital?.profiles??[];
 const regionalGapList=regional?.data?([['IBGE',regional.data.ibge],['Facebook · público estimado',regional.data.facebook],['Google Trends',regional.data.trends],['Google Trends · em crescimento',regional.data.topics?.google],['Facebook · assuntos',regional.data.topics?.facebook],['X · assuntos recentes',regional.data.topics?.x],['Mapa e concorrentes',regional.data.map]] as [string,{state:string}|undefined][]).filter(([,s])=>s?.state!=='available').map(([label])=>label):[];
 regionalGapList.push(...digitalProfiles.filter(p=>!p.snapshot).map(p=>'Instagram @'+p.username));
 const ready=stageReady(stage,journey?.strategy);
 const canAccept=Boolean(journey?.confirmed&&journey.canApprove&&previousApproved&&ready&&!(active===1&&(regionalDirty||regionalGapList.length>0&&!gapsAcknowledged||regional?.data?.map&&!regional.data.map.selectionConfirmed))&&!stage?.approved&&!busy&&!loadError&&!(active===2&&(strategyEditing||data?.confirmedProfile?.version!==journey.profileVersion)));
 const progress=active>=4?journey?.preparation?.recommendations:journey?.preparation?.content;
 const failed=!ready&&['failed','stale'].includes(active===1&&regional?regional.status:progress?.status??'');
 const unavailable=!ready&&(active===1&&regional?journey?.regionalAvailable===false:journey?.preparation?.available===false);
 const waitingText=active===1&&regional&&regional.revision===0?'A pesquisa ainda não foi iniciada. Use o painel abaixo para iniciar ou tentar novamente.':active===1&&regional?'Estamos consultando as fontes do público regional para sua revisão.':active===2?'Estamos preparando o diagnóstico e os planos macro, de médio e curto prazo. A proposta aparecerá aqui automaticamente.':active===3?'Estamos organizando os temas e as datas a partir da estratégia aprovada.': 'Estamos preparando as sugestões de campanhas com base no plano aprovado. Elas aparecerão aqui automaticamente.';
 useEffect(()=>{setError('');setLimitations('');setGapsAcknowledged(false);},[active,stage?.basis]);
 async function savePlanning(){if(busy)return;setBusy(true);setError('');try{await journeyApi(base+'/launch/planning-preferences',{postsPerMonth:posts,maxPostsPerWeek:weekly});await load();}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar a frequência.');}finally{setBusy(false);}}
 async function resume(){if(busy)return;setBusy(true);setError('');try{await journeyApi(base+'/launch/resume',{});await load();}catch(e){setError(e instanceof Error?e.message:'Não foi possível retomar.');}finally{setBusy(false);}}
 async function traffic(mode:'skipped'|'planned'){if(busy||!stage||active!==5)return;setBusy(true);setError('');try{await journeyApi(base+'/launch/traffic-preference',{mode,basis:stage.basis});await load();}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar a escolha de tráfego.');}finally{setBusy(false);}}
 async function accept(){if(!canAccept||!stage)return;setBusy(true);setError('');try{await journeyApi(base+'/launch/approve',{stage:active,basis:stage.basis,limitations:active===1?[regionalGapList.length?'Reconheço as fontes indisponíveis nesta versão.':'',limitations.trim()].filter(Boolean).join(' '):'',...(active===1?{evidenceBasis:journey?.competitorReview?.basis}:{})});setSelected(null);await load();if(active===5){if(onComplete)onComplete();else window.location.assign('/empresa/'+companyId+'/preparacao');}}catch(e){setError(e instanceof Error?e.message:'Não foi possível aprovar.');await load().catch(()=>{});}finally{setBusy(false);}}
 return <section className={compact?`${styles.root} ${styles.compact}`:styles.root}><header><p className="page-eyebrow">ESTRATÉGIA GUIADA</p><h2>{compact?'Revise sua estratégia, etapa por etapa.':'Você decide. A MedSI executa o que foi aprovado.'}</h2><p>Cinco etapas para alinhar seu marketing. Cada proposta fica vinculada ao perfil e à versão que você revisou.</p></header>{(error||loadError)&&<p className="error-banner" role="alert">{error||loadError}</p>}
 {!journey&&!loadError&&<PreparationStatus title="Retomando sua estratégia" detail="Conferindo o plano confirmado e as etapas já salvas."/>}{loadError&&<Button disabled={busy} onClick={()=>{setBusy(true);void load().catch(e=>setLoadError(e instanceof Error?e.message:"Não foi possível carregar as etapas.")).finally(()=>setBusy(false));}}>{busy?"Tentando novamente…":"Tentar novamente"}</Button>}{journey&&!journey.confirmed&&<p>Primeiro, <Link href={'/empresa/'+companyId+'/onboarding'}>conclua o onboarding</Link>.</p>}
 {journey?.confirmed&&<><MarketingFacts companyId={companyId} key={journey.profileVersion} stage={active} write={write} onChanged={async next=>{setUpdatedProfile(next);setSelected(null);await load();}}/><ol className={styles.steps} aria-label="Etapas da estratégia">{stageTitles.map((title,i)=><li key={title}><button disabled={i+1>current} aria-current={active===i+1?'step':undefined} onClick={()=>setSelected(i+1)}><span>{journey.stages[i]?.approved?<Check size={17}/>:i+1}</span>{title}</button></li>)}</ol>
 <aside className={styles.guide} aria-live="polite">{ready?<MousePointer2 size={24}/>:<LoaderCircle size={24} className={!failed&&!unavailable&&!(active===1&&regional?.revision===0)?styles.spinner:undefined}/>}<div><strong>{stage?.status==='skipped'?'Tráfego pulado por enquanto':stage?.approved?'Etapa aprovada':ready?'Pronto para sua revisão':failed?'A preparação precisa ser retomada':unavailable?'Preparação indisponível no momento':'Preparando sua próxima etapa'} · etapa {active}</strong><p>{ready?(active===1&&regional?'Confira o endereço, os concorrentes e as evidências de compatibilidade antes de aprovar.':instructions[active-1]):unavailable?'A geração aguarda a configuração do servidor. Suas respostas e aprovações estão salvas. Use a ajuda para falar com nossa equipe.':failed?(active===1&&regional?regional.error:progress?.error):waitingText}</p>{ready&&<a href="#approve-stage">Ir para a aprovação desta etapa ↓</a>}{failed&&write&&!unavailable&&!(active===1&&regional)&&<Button disabled={busy} onClick={()=>void resume()}>Retomar preparação</Button>}</div></aside>
 {active===1&&regional&&<><RegionalAudienceReview companyId={companyId} key={regional.id+'_'+regional.revision} review={regional} onDirtyChange={setRegionalDirty} address={data?.state.facts.address?.value??undefined} available={journey.regionalAvailable===true} write={write} onChanged={load}/><InstagramProfiles companyId={companyId} onChanged={()=>load()}/><div className={styles.limitations}><h3>Revise a pesquisa da sua região</h3><p>Confirme os concorrentes pertinentes e as lacunas desta coleta. As pesquisas salvas continuam disponíveis para orientar a estratégia; ocultar os painéis não apaga os dados.</p>{regionalGapList.length>0&&<><p className="info-note">Fontes indisponíveis nesta coleta: <strong>{regionalGapList.join(', ')}</strong>.</p><label><input type="checkbox" checked={gapsAcknowledged} onChange={e=>setGapsAcknowledged(e.target.checked)}/> Revisei essas lacunas e quero continuar com a versão atual.</label></>}<details><summary>Adicionar uma observação (opcional)</summary><textarea value={limitations} onChange={e=>setLimitations(e.target.value)} maxLength={1000} placeholder="Ex.: o concorrente mais relevante fica fora do raio."/></details></div></>}
 {active===1&&!regional&&<><InstagramProfiles companyId={companyId} reviewWatches={journey.competitorReview?.watches} onChanged={()=>load()}/><div className={styles.limitations}><h3>Análise de concorrentes</h3><p>Compare seguidores, interações públicas e amostra de posts acima. O diagnóstico usará uma cópia desses dados com a data da coleta. Dados indisponíveis serão tratados como lacunas.</p><label>Se ainda faltam dados, registre a limitação antes de continuar<textarea value={limitations} onChange={e=>setLimitations(e.target.value)} maxLength={1000} placeholder="Ex.: o concorrente usa conta pessoal e suas métricas não estão disponíveis. Quero continuar com essa limitação registrada."/></label></div></>}
 {!ready&&active>1&&!failed&&!unavailable&&<PreparationStatus key={active} title={active===2?'Preparando diagnóstico e plano':active===3?'Organizando seu calendário':'Preparando propostas de campanhas'} detail={waitingText}/>}
 {active===2&&<>{journey.canApprove&&<section className={styles.panel}><h3>Quantidade e frequência do mês</h3><label>Publicações neste mês <input type="number" min={1} max={31} value={posts} onChange={e=>setPosts(Number(e.target.value))}/></label><label>Máximo por semana <input type="number" min={1} max={7} value={weekly} onChange={e=>setWeekly(Number(e.target.value))}/></label><p>Alterar exige gerar e revisar novamente o plano e as etapas seguintes.</p><Button variant="outline" disabled={busy} onClick={()=>void savePlanning()}>Salvar quantidade e frequência</Button></section>}{stage?.data&&(stage.data as {analysisCurrent?:boolean}).analysisCurrent===false&&<p className="info-note">A análise aprovada mudou. Use Pedir para refazer abaixo para atualizar o diagnóstico antes de aprovar.</p>}<StrategyWorkspace companyId={companyId} data={data} write={write} approve={approve} guided snapshot={journey.strategy??null} onRefresh={load} onEditingChange={setStrategyEditing}/></>}
 {active===3&&<section className={styles.panel}><h3>Seu calendário proposto</h3><p>O calendário usa os dias restantes do mês atual e a frequência escolhida. Estas são pautas e datas propostas. A produção de cada peça e sua aprovação final são etapas posteriores.</p>{Array.isArray(stage?.data)&&stage.data.length>0?<div className={styles.calendar}>{(stage.data as PlanItem[]).map(i=><article key={i.id}><small>{i.date?new Date(i.date+'T12:00:00').toLocaleDateString('pt-BR'):'Data pendente'} · {i.format}</small><h4>{i.idea}</h4><p>{i.direction}</p></article>)}</div>:<p role="status">Organizando os temas e as datas a partir da estratégia…</p>}<Link href={'/empresa/'+companyId+'/conteudo'}>Ajustar datas no calendário →</Link>{onComplete&&<p>Depois do ajuste, use Voltar à configuração para continuar por aqui.</p>}</section>}
 {active===4&&<section className={styles.panel}><h3>Campanhas de relacionamento e vendas</h3><p>As sugestões definem a direção. Para envio, a aprovação da campanha deve conter público elegível, texto e programação.</p>{stage?.data?<><SuggestionList title="Atendimento no WhatsApp" items={(stage.data as Pick<LaunchRecommendations,'whatsapp'|'messages'>).whatsapp}/><SuggestionList title="Campanhas de mensagens" items={(stage.data as Pick<LaunchRecommendations,'whatsapp'|'messages'>).messages}/></>:<p role="status">Preparando as sugestões com base no plano aprovado…</p>}</section>}
 {active===5&&<section className={styles.panel}><h3>Aquisição com tráfego pago · opcional</h3><p>A programação deverá respeitar o orçamento, público e criativos aprovados. Após a aprovação final, a execução depende das contas conectadas e da disponibilidade de saldo.</p>{stage?.status==='skipped'?<><p>Tráfego pulado por enquanto. Nenhuma campanha ou autorização de gasto foi criada por essa escolha.</p>{journey.canApprove&&<Button variant="outline" disabled={busy} onClick={()=>void traffic('planned')}>Retomar planejamento de tráfego</Button>}</>:<>{Array.isArray(stage?.data)?<SuggestionList title="Propostas de campanhas" items={stage.data as LaunchRecommendations['traffic']}/>:<p role="status">Preparando as sugestões de aquisição…</p>}{journey.canApprove&&previousApproved&&<Button variant="outline" disabled={busy} onClick={()=>void traffic('skipped')}>Pular por enquanto</Button>}</>}</section>}
 <section id="approve-stage" className={styles.approval}><div><strong>{stage?.approved?'Esta versão foi aprovada':ready?'Sua aprovação é o próximo passo':'A proposta ainda está em preparação'}</strong><p>{!ready?'A aprovação ficará disponível quando a proposta estiver pronta para você revisar.':active===3?'Você aprova ideias e datas agora. Cada criativo terá outra revisão antes de ser publicado.':active>=4?'Aprovação da direção proposta. Pendências de público, verba, criativo e conexão continuam visíveis na campanha antes de autorizar a execução.':'Leia a proposta e confira se está alinhada ao seu negócio.'}</p></div>{journey.canApprove&&<Button disabled={!canAccept} onClick={()=>void accept()}>{busy?'Aguarde…':!ready?'Aguardando proposta…':active===5?'Aprovar plano e preparar entregas':'Aprovar e continuar'}<ArrowRight size={17}/></Button>}{stage?.approved&&active<5&&<Button variant="outline" onClick={()=>setSelected(active+1)}>Ver próxima etapa</Button>}{journey.stages.every(s=>s.approved)&&(onComplete?<Button onClick={onComplete}>Entrar na MedSI<ArrowRight size={17}/></Button>:<Link className="button button-primary" href={'/empresa/'+companyId+'/preparacao'}>Acompanhar entregas</Link>)}</section></>}
 </section>;
}
function SuggestionList({title,items}:{title:string;items:LaunchRecommendations['traffic']}){return <section><h4>{title}</h4>{items?.map((s,i)=><article className={styles.suggestion} key={i}><h4>{s.title}</h4><p>{s.objective}</p><p><strong>Público:</strong> {s.audience}</p><ol>{s.steps.map((step,n)=><li key={n}>{step}</li>)}</ol>{s.message&&<blockquote>{s.message}</blockquote>}<p><strong>Como acompanhar:</strong> {s.successMetric}</p>{s.requirements.length>0&&<><strong>Pendências para executar</strong><ul>{s.requirements.map((r,n)=><li key={n}>{r}</li>)}</ul></>}</article>)}</section>;}
