'use client';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {createPortal} from 'react-dom';
import {BookOpen,Check,MessageCircle,Send,Ticket,ArrowUpRight} from 'lucide-react';
import {Modal} from '@askadia/ui';
import {searchSupport,supportArticles,supportProtocol,type SupportArticle,type SupportDetail} from '@askadia/contracts';
import {connectedApi} from '../lib/api-client';
import {SupportTickets} from './support-tickets';
import s from './help-chat.module.css';
type HelpMessage={role:'user'|'assistant';text:string;article?:SupportArticle;choices?:SupportArticle[]};
const welcome:HelpMessage={role:'assistant',text:'Olá! Sou a ajuda da MedSI. Conte o que você precisa e vou procurar uma orientação na nossa central de suporte.'};

export function HelpChat({companyId,aboveComposer=false}:{companyId?:string;aboveComposer?:boolean}){
 const [mounted,setMounted]=useState(false),[open,setOpen]=useState(false),[tab,setTab]=useState<'chat'|'new'|'tickets'>('chat'),[history,setHistory]=useState<HelpMessage[]>([welcome]),[question,setQuestion]=useState(''),[handoff,setHandoff]=useState(false),[whatsapp,setWhatsapp]=useState<string|null>(null),[contactError,setContactError]=useState(false),[subject,setSubject]=useState(''),[description,setDescription]=useState(''),[share,setShare]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[created,setCreated]=useState<SupportDetail|undefined>();
 const trigger=useRef<HTMLButtonElement>(null),chat=useRef<HTMLDivElement>(null),lock=useRef(false),request=useRef<{signature:string;id:string}|null>(null);
 useEffect(()=>{setMounted(true);},[]);
 useEffect(()=>{if(!open)return;const controller=new AbortController();setContactError(false);connectedApi<{whatsappUrl:string|null}>('support/config',{signal:controller.signal}).then(result=>{if(!controller.signal.aborted)setWhatsapp(result.whatsappUrl&&/^https:\/\/wa\.me\/[1-9]\d{10,14}$/.test(result.whatsappUrl)?result.whatsappUrl:null);}).catch(()=>{if(!controller.signal.aborted){setWhatsapp(null);setContactError(true);}});return()=>controller.abort();},[open]);
 useEffect(()=>{chat.current?.scrollTo({top:chat.current.scrollHeight,behavior:'smooth'});},[history,tab,open,handoff]);
 function toggle(value:boolean){setOpen(value);if(!value)requestAnimationFrame(()=>trigger.current?.focus());}
 function ask(event:FormEvent){event.preventDefault();const text=question.trim();if(!text)return;const found=searchSupport(text);setHistory(previous=>[...previous.slice(-29),{role:'user',text},{role:'assistant',text:found.kind==='answer'?found.articles[0]!.answer:found.kind==='suggestions'?'Encontrei estas orientações. Qual delas se parece com sua dúvida?':'Não encontrei uma orientação suficiente na nossa central para resolver isso. Você pode abrir um chamado ou falar com um especialista.',...(found.kind==='answer'?{article:found.articles[0]}:found.kind==='suggestions'?{choices:found.articles}:{})}]);setHandoff(found.kind==='handoff');setQuestion('');}
 function article(value:SupportArticle){setHistory(previous=>[...previous.slice(-29),{role:'assistant',text:value.answer,article:value}]);setHandoff(false);}
 function newTicket(){const last=history.slice().reverse().find(m=>m.role==='user')?.text??'';setSubject(last.slice(0,160));setDescription(last);setShare(false);setError('');setTab('new');}
 async function submit(event:FormEvent){event.preventDefault();if(lock.current)return;lock.current=true;setBusy(true);setError('');const payload={companyId:companyId??null,subject:subject.trim(),message:description.trim(),page:window.location.pathname.slice(0,160),transcript:share?history.slice(-8).map(m=>({role:m.role,text:m.text.slice(0,1000)})):[]};const signature=JSON.stringify(payload);if(request.current?.signature!==signature)request.current={signature,id:crypto.randomUUID()};try{const result=await connectedApi<SupportDetail>('support/tickets',{method:'POST',body:{...payload,requestId:request.current.id}});setCreated(result);setTab('tickets');request.current=null;}catch(e){setError(e instanceof Error?e.message:'Não foi possível abrir o chamado. Tente novamente ou use o WhatsApp.');}finally{lock.current=false;setBusy(false);}}
 const whatsappHref=whatsapp?whatsapp+'?text='+encodeURIComponent('Olá! Preciso de ajuda com a MedSI.'+(created?' Meu chamado é '+supportProtocol(created.ticket.number)+'.':'')):null;
 const escalation=<div className={s.escalation}><button type="button" className={s.primary} onClick={newTicket}><Ticket size={16}/>Abrir um chamado</button>{whatsappHref?<a href={whatsappHref} target="_blank" rel="noopener noreferrer"><MessageCircle size={16}/>Falar com um especialista<ArrowUpRight size={15}/></a>:<small>{contactError?'Não foi possível carregar o WhatsApp. Feche e abra a ajuda para tentar novamente.':'O WhatsApp do suporte ainda não está disponível.'}</small>}</div>;
 return <>{mounted&&createPortal(<button ref={trigger} type="button" className={aboveComposer?`${s.launcher} ${s.aboveComposer}`:s.launcher} onClick={()=>toggle(true)} aria-label="Abrir chat de ajuda" aria-haspopup="dialog" aria-expanded={open}><MessageCircle size={22}/><span>Ajuda</span></button>,document.body)}
  <Modal open={open} onOpenChange={toggle} title="Ajuda MedSI" description="Orientações da central de suporte e contato com nossa equipe." className={s.dialog}>
   <nav className={s.tabs} aria-label="Opções de ajuda"><button type="button" aria-current={tab==='chat'?'page':undefined} onClick={()=>setTab('chat')}>Conversar</button><button type="button" aria-current={tab==='tickets'?'page':undefined} disabled={busy} onClick={()=>setTab('tickets')}>Meus chamados</button><a href="/suporte" target="_blank" rel="noreferrer" aria-label="Abrir central de suporte"><BookOpen size={17}/></a></nav>
   {tab==='chat'&&<><div ref={chat} className={s.chat} role="log" aria-live="polite" aria-label="Conversa com a ajuda da MedSI">{history.map((item,i)=><article className={s.bubble} data-role={item.role} key={i}><small>{item.role==='user'?'Você':'Ajuda MedSI'}</small><p>{item.text}</p>{item.article&&<a href={'/suporte#'+item.article.id} target="_blank" rel="noreferrer"><BookOpen size={13}/>Fonte: {item.article.title}</a>}{item.choices&&<div className={s.choices}>{item.choices.map(item=><button type="button" key={item.id} onClick={()=>article(item)}>{item.title}</button>)}</div>}</article>)}
    {history.length===1&&<div className={s.choices}>{['checkout-bloqueado','etapas-estrategia','whatsapp-automacao'].map(id=>{const item=supportArticles.find(a=>a.id===id)!;return <button key={id} type="button" onClick={()=>article(item)}>{item.title}</button>;})}</div>}
    {history.length>1&&!handoff&&<div className={s.feedback}><span>Esta orientação ajudou?</span><button type="button" onClick={()=>{setHistory(h=>[...h,{role:'assistant',text:'Que bom! Se surgir outra dúvida, estou por aqui.'}]);}}><Check size={14}/>Sim</button><button type="button" onClick={()=>setHandoff(true)}>Ainda preciso de ajuda</button></div>}
    {handoff&&escalation}
   </div><form className={s.composer} onSubmit={ask}><label className={s.srOnly} htmlFor="help-question">Sua dúvida</label><input id="help-question" value={question} onChange={e=>setQuestion(e.target.value)} maxLength={1200} autoComplete="off" placeholder="Como podemos ajudar?"/><button type="submit" aria-label="Enviar dúvida" disabled={!question.trim()}><Send size={18}/></button></form><button type="button" className={s.humanLink} onClick={()=>setHandoff(true)}>Preciso falar com a equipe</button></>}
   {tab==='new'&&<form className={s.newTicket} onSubmit={submit}><h3>Conte o que aconteceu</h3><p>Seu chamado será salvo e a equipe responderá em “Meus chamados”.</p><label>Assunto<input value={subject} onChange={e=>setSubject(e.target.value)} minLength={5} maxLength={160} required disabled={busy}/></label><label>Como podemos ajudar?<textarea value={description} onChange={e=>setDescription(e.target.value)} minLength={10} maxLength={4000} rows={5} required disabled={busy} placeholder="Descreva o problema e o que você já tentou."/></label><label className={s.share}><input type="checkbox" checked={share} onChange={e=>setShare(e.target.checked)} disabled={busy}/>Incluir as últimas mensagens deste chat no chamado.</label>{share&&<details className={s.shared}><summary>Revisar conversa que será enviada</summary>{history.slice(-8).map((m,i)=><p key={i}>{m.role==='user'?'Você':'Ajuda MedSI'}: {m.text.slice(0,1000)}</p>)}</details>}<small>Não inclua senhas, tokens nem dados pessoais de pacientes.</small>{error&&<p role="alert" className={s.error}>{error}</p>}<button className={s.primary} type="submit" disabled={busy}>{busy?'Abrindo chamado…':'Enviar chamado'}<Ticket size={16}/></button>{whatsappHref&&<a href={whatsappHref} target="_blank" rel="noopener noreferrer">Prefiro falar no WhatsApp ↗</a>}</form>}
   {tab==='tickets'&&<div className={s.ticketArea}>{created&&<p className={s.success} role="status">Chamado {supportProtocol(created.ticket.number)} aberto. Acompanhe a resposta abaixo.</p>}<SupportTickets initialDetail={created}/><button type="button" className={s.humanLink} onClick={newTicket}>Abrir outro chamado</button>{whatsappHref&&<a className={s.humanLink} href={whatsappHref} target="_blank" rel="noopener noreferrer">Falar com um especialista no WhatsApp ↗</a>}</div>}
  </Modal>
 </>;
}
