'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {useSearchParams} from 'next/navigation';
import {ArrowLeft,Maximize2,Minimize2,MessageCircle,Paperclip,X,RefreshCw,Search,Send,Settings2,Sparkles,Zap} from 'lucide-react';
import {Button,Modal} from '@askadia/ui';
import {inboxLabels,type InboxBootstrap,type InboxMessage,type InboxThread,type QuickReply} from '@askadia/contracts';
import {journeyApi} from '../lib/journey-api';
import s from './inbox.module.css';
import {InboxMedia} from './inbox-media';
type Messages={messages:InboxMessage[];hasMore:boolean;mine:boolean;assigned:boolean};
const clock=(time:string|null)=>time?new Date(time).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'}):'';
export function InboxPanel({companyId,companyName}:{companyId:string;companyName:string}){
 const params=useSearchParams(),deepThread=params.get('thread'),deepName=params.get('contactName')?.slice(0,150),deepOpened=useRef(false);
 const base='companies/'+companyId+'/inbox';const [info,setInfo]=useState<(InboxBootstrap&{whatsappProvider?:string})|null>(null),[threads,setThreads]=useState<InboxThread[]>([]),[metaThreads,setMetaThreads]=useState<InboxThread[]>([]),[metaMore,setMetaMore]=useState(false),[metaError,setMetaError]=useState(''),[total,setTotal]=useState(0),[page,setPage]=useState(1),[search,setSearch]=useState(''),[filter,setFilter]=useState('all'),[selected,setSelected]=useState<InboxThread|null>(null),[history,setHistory]=useState<Messages|null>(null),[older,setOlder]=useState(1),[text,setText]=useState(''),[error,setError]=useState(''),[readError,setReadError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[full,setFull]=useState(false),[shortcuts,setShortcuts]=useState(false),[showReplies,setShowReplies]=useState(false);
 const [attachment,setAttachment]=useState<{base64:string;mimetype:string;fileName:string}|null>(null);
 const root=useRef<HTMLElement>(null),composer=useRef<HTMLTextAreaElement>(null),tail=useRef<HTMLDivElement>(null),lock=useRef(false),selection=useRef(''),alive=useRef(true),request=useRef<{id:string;text:string;thread:string}|null>(null);
 const loadInfo=useCallback(async(signal?:AbortSignal)=>{const d=await journeyApi<InboxBootstrap&{whatsappProvider?:string}>(base,undefined,signal);if(!signal?.aborted&&alive.current)setInfo(d);},[base]);
 const loadThreads=useCallback(async(signal?:AbortSignal)=>{const d=await journeyApi<{threads:InboxThread[];total:number}>(base+'/threads?page='+page+'&search='+encodeURIComponent(search),undefined,signal);if(!signal?.aborted&&alive.current){setThreads(d.threads);setTotal(d.total);setReadError('');}},[base,page,search]);
 useEffect(()=>{alive.current=true;const c=new AbortController();void loadInfo(c.signal).catch(e=>{if(!c.signal.aborted)setReadError(e.message);});return()=>{alive.current=false;c.abort();};},[loadInfo]);
 const connected=info?.connections.find(c=>c.channel==='whatsapp')?.connected;
 const officialWhatsApp=info?.whatsappProvider==='whatsapp_cloud';
 const metaSelected=selected?.channel==='instagram'||selected?.channel==='facebook';
 const messagePath=(id:string)=>base+(id.startsWith('meta.')?'/meta':'');
 const metaConnected=info?.connections.filter(c=>c.connected&&(c.channel==='instagram'||c.channel==='facebook')).map(c=>c.channel).join(',')??'';
 useEffect(()=>{const c=new AbortController();let running=false;setMetaThreads([]);setMetaError('');setMetaMore(false);const channels=metaConnected.split(',').filter(v=>v&&(filter==='all'||filter===v));if(!channels.length)return;const refresh=async()=>{if(running||document.hidden)return;running=true;const rows:InboxThread[]=[];const errors:string[]=[];let more=false;for(const channel of channels){try{const d=await journeyApi<{threads:InboxThread[];hasMore:boolean}>(base+'/meta/threads?channel='+channel+'&page='+page,undefined,c.signal);rows.push(...d.threads);more ||= d.hasMore;}catch(e){if(!c.signal.aborted)errors.push(channel+': '+(e instanceof Error?e.message:'Consulta indisponível'));}}if(!c.signal.aborted){setMetaThreads(rows);setMetaMore(more);setMetaError(errors.join(' · '));}running=false;};void refresh();const timer=setInterval(()=>void refresh(),30000);return()=>{c.abort();clearInterval(timer);};},[base,metaConnected,filter,page]);
 const visibleThreads=[...(filter==='all'||filter==='whatsapp'?threads:[]),...metaThreads].filter(t=>(filter==='all'||filter===t.channel)&&t.name.toLocaleLowerCase('pt-BR').includes(search.toLocaleLowerCase('pt-BR'))).sort((a,b)=>(b.time??'').localeCompare(a.time??''));
 useEffect(()=>{if(!connected)return;const c=new AbortController();let fetching=false;const refresh=async()=>{if(fetching||document.hidden)return;fetching=true;try{await loadThreads(c.signal);}catch(e){if(!c.signal.aborted)setReadError(e instanceof Error?e.message:'Falha ao consultar conversas.');}finally{fetching=false;}};const timer=setTimeout(()=>void refresh(),250);const interval=setInterval(()=>void refresh(),20000);return()=>{clearTimeout(timer);clearInterval(interval);c.abort();};},[connected,loadThreads]);
 useEffect(()=>{selection.current=selected?.id??'';setHistory(null);setOlder(1);setText('');setAttachment(null);setNotice('');request.current=null;if(!selected)return;const c=new AbortController();let fetching=false;const id=selected.id;const refresh=async()=>{if(fetching||document.hidden)return;fetching=true;try{const d=await journeyApi<Messages>(base+(id.startsWith('meta.')?'/meta':'')+'/messages?thread='+encodeURIComponent(id),undefined,c.signal);if(!c.signal.aborted&&selection.current===id){setReadError('');setHistory(prev=>({...d,messages:[...new Map([...(prev?.messages??[]),...d.messages].map(m=>[m.id,m])).values()].sort((a,b)=>(a.time??'').localeCompare(b.time??''))}));}}catch(e){if(!c.signal.aborted)setReadError(e instanceof Error?e.message:'Falha ao consultar mensagens.');}finally{fetching=false;}};void refresh();const interval=setInterval(()=>void refresh(),10000);return()=>{c.abort();clearInterval(interval);};},[base,selected]);
 useEffect(()=>{if(deepOpened.current||!deepThread||!connected)return;const known=threads.find(t=>t.id===deepThread);if(known){deepOpened.current=true;setSelected(known);}else {deepOpened.current=true;setSelected({id:deepThread,name:deepName||'Contato do CRM',channel:'whatsapp',preview:'',time:null,unread:0,group:false});}},[deepThread,deepName,threads,connected]);
 useEffect(()=>{tail.current?.scrollIntoView({block:'nearest'});},[selected?.id,history?.messages.at(-1)?.id]);
 useEffect(()=>{const change=()=>setFull(document.fullscreenElement===root.current);document.addEventListener('fullscreenchange',change);return()=>document.removeEventListener('fullscreenchange',change);},[]);
 async function act(run:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await run();}catch(e){if(alive.current)setError(e instanceof Error?e.message:'Não foi possível concluir.');}finally{lock.current=false;if(alive.current)setBusy(false);}}
 async function refresh(){setLoading(true);await act(async()=>{await loadInfo();await loadThreads();setNotice('Conexão e conversas atualizadas.');});setLoading(false);}
 async function takeover(){if(!selected)return;const id=selected.id;await act(async()=>{await journeyApi(messagePath(id)+'/takeover',{thread:id});if(selection.current===id)setHistory(v=>v?{...v,mine:true,assigned:true}:v);setNotice('Atendimento assumido. Respostas automáticas ficam bloqueadas nesta conversa.');});}
 async function send(){if(!selected||(!text.trim()&&!attachment)||!info?.canWrite)return;const id=selected.id,body=text.trim();if(attachment?.mimetype.startsWith('audio/')&&body){setError('Envie o áudio sem legenda. Você pode enviar o texto em uma mensagem separada.');return;}if(attachment&&body.length>3000){setError('A legenda aceita até 3.000 caracteres.');return;}const fingerprint=body+(attachment?'|'+attachment.fileName+'|'+attachment.base64:'');await act(async()=>{if(!request.current||request.current.text!==fingerprint||request.current.thread!==id)request.current={id:crypto.randomUUID(),text:fingerprint,thread:id};if(!history?.mine){await journeyApi(messagePath(id)+'/takeover',{thread:id});if(selection.current===id)setHistory(v=>v?{...v,mine:true,assigned:true}:v);}const r=await journeyApi<{state:string;message:string}>(messagePath(id)+(attachment?'/media-send':'/send'),attachment?{...attachment,thread:id,caption:body,requestId:request.current.id}:{thread:id,text:body,requestId:request.current.id});if(selection.current!==id)return;setNotice(r.message);if(r.state==='sent'){setText('');setAttachment(null);request.current=null;const h=await journeyApi<Messages>(messagePath(id)+'/messages?thread='+encodeURIComponent(id));if(selection.current===id)setHistory(h);}});}
 async function release(){if(!selected)return;const id=selected.id;await act(async()=>{await journeyApi(base+'/release',{thread:id});if(selection.current===id)setHistory(v=>v?{...v,mine:false,assigned:false}:v);setNotice('A IA poderá responder às próximas mensagens, se o envio automático deste canal estiver ativo.');});}
 async function suggest(){if(!selected)return;const id=selected.id;await act(async()=>{const r=await journeyApi<{text:string;handoff:boolean}>(base+'/suggest',{channel:selected.channel,thread:id});if(selection.current===id){setText(r.text);setNotice(r.handoff?'O fluxo indica encaminhamento humano. Revise a resposta antes de enviar.':'Sugestão pronta. Revise antes de enviar.');composer.current?.focus();}});}
 async function earlier(){if(!selected)return;const id=selected.id;await act(async()=>{const d=await journeyApi<Messages>(messagePath(id)+'/messages?thread='+encodeURIComponent(id)+'&page='+(older+1));if(selection.current===id){setHistory(prev=>({...d,messages:[...new Map([...d.messages,...(prev?.messages??[])].map(m=>[m.id,m])).values()].sort((a,b)=>(a.time??'').localeCompare(b.time??''))}));setOlder(v=>v+1);}});}
 async function attach(file:File){if(!selected)return;const id=selected.id;if(file.size>8*1024*1024){setError('O limite por arquivo é 8 MB.');return;}await act(async()=>{const base64=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]??'');reader.onerror=()=>reject(new Error('Não foi possível ler o arquivo.'));reader.readAsDataURL(file);});if(selection.current===id)setAttachment({base64,mimetype:file.type||({mp3:'audio/mpeg',ogg:'audio/ogg',m4a:'audio/mp4',wav:'audio/wav',pdf:'application/pdf',txt:'text/plain',csv:'text/csv'} as Record<string,string>)[file.name.split('.').at(-1)?.toLowerCase()??'']||'application/octet-stream',fileName:file.name.slice(0,150)});});}
 const channelSettings=info?.settings.find(c=>c.channel===selected?.channel);
 return <section ref={root} className={s.inbox} data-full={full} aria-label={'Caixa de entrada de '+companyName}>
  <header className={s.toolbar}><div><strong>Caixa de entrada</strong><small>{companyName} · {info?.connections.filter(c=>c.connected).map(c=>inboxLabels[c.channel]).join(' · ')||'Verifique os canais conectados'}</small></div><div className={s.tools}><Button size="small" variant="ghost" disabled={busy||loading} onClick={()=>void refresh()} aria-label="Atualizar conexão e conversas"><RefreshCw size={17}/></Button>{info?.canConfigure&&<Button size="small" variant="ghost" aria-label="Configurar atalhos rápidos" onClick={()=>{if(document.fullscreenElement)void document.exitFullscreen();setShortcuts(true);}}><Zap size={17}/></Button>}{info?.canConfigure&&<Link className={s.iconLink} href={'/empresa/'+companyId+'/configuracao-atendimento'} aria-label="Configuração de Atendimento"><Settings2 size={17}/></Link>}<Button size="small" variant="ghost" onClick={()=>void act(async()=>{if(document.fullscreenElement)await document.exitFullscreen();else await root.current?.requestFullscreen();})} aria-label={full?'Sair da tela cheia':'Abrir chat em tela cheia'}>{full?<Minimize2 size={17}/>:<Maximize2 size={17}/>}</Button></div></header>
  {(error||readError)&&<div className={s.error} role="alert">{error||readError}<button onClick={()=>{setError('');setReadError('');}} aria-label="Fechar aviso">×</button></div>}
  <div className={s.layout} data-selected={Boolean(selected)}><aside className={s.contacts}><label className={s.search}><Search size={16}/><input aria-label="Buscar contato ou conversa" value={search} placeholder="Buscar conversa" onChange={e=>{setSearch(e.target.value);setPage(1);}}/></label><div className={s.filters}>{['all','whatsapp','instagram','facebook','tiktok'].map(key=><button key={key} aria-pressed={filter===key} onClick={()=>{setFilter(key);setPage(1);}} >{key==='all'?'Todas':inboxLabels[key as keyof typeof inboxLabels]}</button>)}</div>
  <div className={s.contactList}>{!info&&!error&&<p className={s.empty}>Consultando canais…</p>}{metaError&&<p role="alert" className={s.empty}>{metaError}</p>}{!visibleThreads.length?<div className={s.empty}><MessageCircle size={28}/><p>{filter==='all'?'Nenhuma conversa disponível nesta página.':info?.connections.find(c=>c.channel===filter)?.connected?'Nenhuma conversa disponível na API. A Meta exige acesso avançado para conversas de pessoas fora dos papéis de teste do aplicativo.':info?.connections.find(c=>c.channel===filter)?.message}</p><Link href={'/empresa/'+companyId+'/integracoes'}>Ver integrações</Link></div>:visibleThreads.map(t=><button className={s.contact} key={t.id} aria-current={selected?.id===t.id?'true':undefined} onClick={()=>setSelected(t)}><span className={s.avatar}>{t.name.slice(0,2).toUpperCase()}</span><span className={s.contactText}><span className={s.contactTop}><strong>{t.name}</strong><time>{clock(t.time)}</time></span><span className={s.preview}>{t.preview}</span><span className={s.channel} data-channel={t.channel}>{inboxLabels[t.channel]}{t.group?' · Grupo':''}</span></span>{t.unread>0&&<span className={s.unread}>{t.unread>99?'99+':t.unread}</span>}</button>)}</div><footer className={s.pagination}><button disabled={page===1} onClick={()=>setPage(v=>v-1)}>Anterior</button><small>Página {page}</small><button disabled={!metaMore&&(!(filter==='all'||filter==='whatsapp')||page*60>=total)||page>=20} onClick={()=>setPage(v=>v+1)}>Próxima</button></footer></aside>
  <div className={s.chat}>{!selected?<div className={s.welcome}><span className={s.welcomeIcon}><MessageCircle size={38}/></span><h2>Conversas que aproximam.</h2><p>Selecione um contato para continuar o atendimento da {companyName}.</p><small>Cada empresa tem seus próprios canais, atalhos e assistente.</small></div>:<><header className={s.chatHeader}><Button className={s.back} size="small" variant="ghost" aria-label="Voltar às conversas" onClick={()=>setSelected(null)}><ArrowLeft size={18}/></Button><span className={s.avatar}>{selected.name.slice(0,2).toUpperCase()}</span><div className={s.contactText}><strong>{selected.name}</strong><small><span className={s.channel} data-channel={selected.channel}>{inboxLabels[selected.channel]}</span> · {history?.mine?'Você está atendendo':history?.assigned?'Com outro atendente':channelSettings?.automatic?'IA ativa':'Aguardando atendimento'}</small></div>{info?.canWrite&&!history?.mine&&!selected.group&&<Button size="small" disabled={busy} onClick={()=>void takeover()}>Assumir</Button>}{!metaSelected&&history?.assigned&&info?.canWrite&&channelSettings?.automatic&&<Button size="small" variant="outline" disabled={busy} onClick={()=>void release()}>Devolver à IA</Button>}</header>
  <div className={s.messages} role="log" aria-label="Histórico da conversa">{history?.hasMore&&<Button size="small" variant="outline" disabled={busy} onClick={()=>void earlier()}>Carregar mensagens anteriores</Button>}{!history?<p className={s.empty}>Carregando histórico…</p>:!history.messages.length?<p className={s.empty}>Sem mensagens disponíveis no canal.</p>:history.messages.map((m,i)=><div key={m.id}>{(i===0||m.time?.slice(0,10)!==history.messages[i-1]?.time?.slice(0,10))&&<div className={s.date}>{m.time?new Date(m.time).toLocaleDateString('pt-BR'):'Data não informada'}</div>}<article className={s.bubble} data-out={m.fromMe}><p>{m.body}</p><small>{clock(m.time)}{m.fromMe?' · '+(m.status==='READ'?'Lida':m.status==='DELIVERY_ACK'?'Entregue':'Enviada'):''}</small>{m.kind!=='text'&&!officialWhatsApp&&<InboxMedia key={selected.id+':'+m.id} base={base} thread={selected.id} messageId={m.id} kind={m.kind}/>}</article></div>)}<div ref={tail}/></div>
  <footer className={s.composer}>{notice&&<p role="status" className={s.notice}>{notice}</p>}{selected.group?<p className={s.notice}>Grupos estão disponíveis somente para leitura.</p>:!info?.canWrite?<p>Seu perfil permite apenas leitura.</p>:<><div className={s.composerTools}>{!metaSelected&&!officialWhatsApp&&<label className={s.attach}><Paperclip size={16}/><span>Anexar</span><input type="file" disabled={busy} aria-label="Anexar imagem, áudio ou documento" accept="image/jpeg,image/png,image/webp,image/gif,audio/mpeg,audio/ogg,audio/wav,audio/mp4,audio/webm,.pdf,.doc,.docx,.xls,.xlsx,.pptx,.txt,.csv" onChange={e=>{const file=e.target.files?.[0];if(file)void attach(file);e.target.value='';}}/></label>}<Button variant="ghost" size="small" disabled={busy} onClick={()=>setShowReplies(v=>!v)}><Zap size={15}/> Atalhos</Button>{!metaSelected&&channelSettings&&channelSettings.mode!=='human'&&<Button variant="ghost" size="small" disabled={busy||!history?.messages.length} onClick={()=>void suggest()}><Sparkles size={15}/> {channelSettings.mode==='ai'?'Sugerir com IA':'Aplicar fluxo'}</Button>}<small>{metaSelected?'Meta · resposta manual em até 24 h':channelSettings?.mode==='ai'?info.model+' · revisão humana':'Atendimento humano'}</small></div>{(showReplies||text.startsWith('/'))&&<div className={s.replies}>{(info.quickReplies.filter(q=>!text.startsWith('/')||q.shortcut.includes(text.slice(1)))).map(q=><button key={q.id} onClick={()=>{setText(q.body);setShowReplies(false);composer.current?.focus();}}><strong>/{q.shortcut}</strong> {q.title}</button>)}{!info.quickReplies.length&&<p>Nenhum atalho cadastrado.{info.canConfigure&&<button onClick={()=>setShortcuts(true)}>Configurar atalhos</button>}</p>}</div>}{attachment&&<div className={s.attachment}><Paperclip size={14}/><span>{attachment.fileName} · pronto para enviar</span><button aria-label="Remover anexo" disabled={busy} onClick={()=>setAttachment(null)}><X size={15}/></button></div>}<form className={s.composeRow} onSubmit={e=>{e.preventDefault();void send();}}><textarea ref={composer} aria-label="Mensagem para o contato" placeholder="Digite uma mensagem ou /atalho" value={text} disabled={busy} maxLength={metaSelected?1000:officialWhatsApp?4096:6000} rows={2} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)){e.preventDefault();void send();}}}/><Button type="submit" disabled={busy||(!text.trim()&&!attachment)} aria-label={history?.mine?"Enviar mensagem":"Assumir e enviar mensagem"} title={history?.mine?"Enviar":"Assumir e enviar"}><Send size={18}/>{!history?.mine&&<span>Assumir e enviar</span>}</Button></form><small className={s.hint}>Ctrl + Enter para enviar · sugestões e atalhos só são enviados ao clicar em Enviar.</small></>}</footer></>}
  </div></div><QuickReplies open={shortcuts} close={()=>setShortcuts(false)} replies={info?.quickReplies??[]} base={base} refresh={loadInfo}/>
 </section>;
}
function QuickReplies({open,close,replies,base,refresh}:{open:boolean;close:()=>void;replies:QuickReply[];base:string;refresh:()=>Promise<void>}){const [editing,setEditing]=useState<QuickReply|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');async function save(reply:QuickReply,remove=false){setBusy(true);setError('');try{await journeyApi(base+'/quick-replies',{...reply,remove});await refresh();setEditing(null);}catch(e){setError(e instanceof Error?e.message:'Falha ao salvar.');}finally{setBusy(false);}}return <Modal open={open} onOpenChange={v=>{if(!v)close();}} title="Atalhos rápidos" description="Respostas salvas somente para esta empresa. Use /atalho na conversa.">{error&&<p role="alert" className="form-error">{error}</p>}<div className={s.shortcutList}>{replies.map(q=><div key={q.id}><button onClick={()=>setEditing(q)}>/{q.shortcut} · {q.title}</button><Button size="small" variant="ghost" disabled={busy} onClick={()=>void save(q,true)}>Remover</Button></div>)}</div><form key={editing?.id??'new'} className="form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void save({id:editing?.id??crypto.randomUUID(),shortcut:String(f.get('shortcut')),title:String(f.get('title')),body:String(f.get('body'))});}}><fieldset disabled={busy}><label>Atalho (sem /)<input name="shortcut" defaultValue={editing?.shortcut} pattern="[a-z0-9_-]{1,30}" maxLength={30} required placeholder="boas_vindas"/></label><label>Título<input name="title" defaultValue={editing?.title} maxLength={80} required/></label><label>Resposta<textarea name="body" defaultValue={editing?.body} maxLength={3000} required rows={4}/></label><Button type="submit">{editing?'Salvar alteração':'Adicionar atalho'}</Button>{editing&&<Button type="button" variant="ghost" onClick={()=>setEditing(null)}>Novo atalho</Button>}</fieldset></form></Modal>;}
