'use client';
import Link from 'next/link';
import {useCallback,useEffect,useState} from 'react';
import {CheckCircle2,Clock3,LoaderCircle,TriangleAlert} from 'lucide-react';
import {Button} from '@askadia/ui';
import type {LaunchSnapshot} from '@askadia/contracts';
import {journeyApi} from '../lib/journey-api';
import styles from './preparation.module.css';
const statuses:Record<string,string>={scheduled:'Próximas semanas programadas',pending:'Na fila',running:'Preparando',completed:'Pronto para revisar',failed:'Precisa de atenção',stale:'Perfil ou versão alterada'};
export function LaunchPreparation({companyId}:{companyId:string}){
 const [data,setData]=useState<LaunchSnapshot|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const base='companies/'+companyId+'/launch';
 const load=useCallback(async(signal?:AbortSignal)=>{const next=await journeyApi<LaunchSnapshot>(base,undefined,signal);if(!signal?.aborted){setData(next);setError('');}},[base]);
 useEffect(()=>{const c=new AbortController();let timer:ReturnType<typeof setTimeout>;async function refresh(){try{await load(c.signal);}catch(e){if(!c.signal.aborted)setError(e instanceof Error?e.message:'Não foi possível consultar a preparação.');}finally{if(!c.signal.aborted)timer=setTimeout(()=>void refresh(),8000);}}void refresh();return()=>{c.abort();clearTimeout(timer);};},[load]);
 async function resume(){if(busy)return;setBusy(true);try{await journeyApi(base+'/resume',{});await load();}catch(e){setError(e instanceof Error?e.message:'Não foi possível retomar.');}finally{setBusy(false);}}
 const content=data?.content;const recommendations=data?.jobs.find(j=>j.kind==='recommendations');const site=data?.jobs.find(j=>j.kind==='site');
 const steps=[{title:'Estratégia e publicações',description:data?.proposalOnly?'Pautas e datas salvas para revisão. A produção de textos e artes ainda não está disponível neste ambiente.':'Plano de marketing, calendário, textos e artes. Vídeos recebem roteiro para gravação.',status:data?.contentAvailable?(content?.stage==='scheduled'?'scheduled':content?.status):undefined,notice:content?.error,available:data?.contentAvailable,href:'conteudo'},{title:'Site da empresa',description:'Uma página com sua identidade, serviços, fotos e contato.',status:site?.status,notice:site?.error,available:data?.siteAvailable??data?.available,href:'site'},{title:'Campanhas e atendimento',description:'Sugestões para WhatsApp, mensagens e tráfego pago com requisitos e métricas.',status:recommendations?.status,notice:recommendations?.error,available:data?.available,href:'#sugestoes'}];
 const done=steps.filter(s=>s.available&&['completed','scheduled'].includes(s.status??'')).length;
 return <section className={styles.root}><header className={styles.hero}><span className={styles.eyebrow}>SEU MARKETING COMEÇA AQUI</span><h2>{data?.confirmed&&!data.approved?'Seu plano aguarda aprovação.':data?.proposalOnly?'Sua estratégia e propostas estão salvas.':done===3?'Entregas disponíveis para revisão.':'Estamos preparando suas entregas.'}</h2><p>{data?.proposalOnly?'Revise o calendário e as recomendações abaixo. Produção de peças e site ainda estão indisponíveis neste ambiente; nenhuma publicação, mensagem ou campanha foi ativada.':'Transformamos a conversa em um plano, conteúdo, site e sugestões de aquisição. Você pode sair desta tela e voltar: o trabalho continua no servidor.'}</p><p role="status" aria-live="polite">{data?done+' de 3 frentes concluídas · perfil versão '+data.profileVersion:'Consultando a preparação…'}</p></header>
 {error&&<p role="alert" className="error-banner">{error}</p>}{data&&!data.confirmed&&<p className="info-note">Confirme o perfil para preparar a versão atual. <Link href={'/empresa/'+companyId+'/onboarding'}>Voltar à conversa</Link></p>}
 {data?.confirmed&&!data.approved&&<p className="info-note">Revise e aprove as cinco etapas para liberar a produção. <Link href={'/empresa/'+companyId+'/estrategia'}>Continuar na estratégia →</Link></p>}
 <div className={styles.grid}>{steps.map(s=>{const Icon=s.status==='completed'?CheckCircle2:s.status==='running'?LoaderCircle:['failed','stale'].includes(s.status??'')?TriangleAlert:Clock3;return <article className={styles.card} key={s.title}><Icon size={26}/><span className={styles.state}>{!data?'Consultando':!s.available?'Indisponível neste ambiente':statuses[s.status??'']??'Aguardando confirmação'}</span><h3>{s.title}</h3><p>{s.description}</p>{s.notice&&<p className={styles.notice}>{s.notice}</p>}{(s.available||s.href==='conteudo')&&<Link href={s.href.startsWith('#')?s.href:'/empresa/'+companyId+'/'+s.href}>Ver entrega →</Link>}</article>;})}</div>
 <div className={styles.footer}><p>As entregas são rascunhos. Publicação, envio de mensagens, ativação de atendimento e investimento passam pelas autorizações da empresa.</p>{data?.canEdit&&data.confirmed&&<Button disabled={busy||!data.available} variant="outline" onClick={()=>void resume()}>{busy?'Retomando…':'Retomar etapas pendentes'}</Button>}<Link href={'/empresa/'+companyId+'/integracoes'}>Conferir conexões</Link></div>
 <section id="sugestoes" className={styles.recommendations}><h2>Próximas ações sugeridas pela IA</h2>{recommendations?.output?<><p>{recommendations.output.summary}</p>{([['whatsapp','Atendimento pelo WhatsApp'],['messages','Campanhas de mensagens'],['traffic','Campanhas de tráfego']] as const).map(([key,label])=><section key={key}><h3>{label}</h3>{recommendations.output![key].map((s,i)=><article className={styles.suggestion} key={i}><h4>{s.title}</h4><p>{s.objective}</p><p><strong>Público:</strong> {s.audience}</p><ol>{s.steps.map((step,n)=><li key={n}>{step}</li>)}</ol>{s.message&&<blockquote>{s.message}</blockquote>}<p><strong>Como medir:</strong> {s.successMetric}</p>{s.requirements.length>0&&<><strong>Antes de ativar</strong><ul>{s.requirements.map((r,n)=><li key={n}>{r}</li>)}</ul></>}</article>)}</section>)}{recommendations.output.unknowns.length>0&&<aside><h3>Informações a completar</h3><ul>{recommendations.output.unknowns.map((s,i)=><li key={i}>{s}</li>)}</ul></aside>}</>:<p>As sugestões aparecerão aqui quando esta etapa terminar.</p>}</section>
 </section>;
}
