'use client';
import {useEffect,useState} from 'react';
import {Button} from '@askadia/ui';
import {journeyApi} from '../lib/journey-api';
import styles from './campaigns.module.css';
type Status={integration:{active:boolean;lastReceivedAt:string|null}|null;endpoint:string};
export function ManagementIntegration({companyId,owner}:{companyId:string;owner:boolean}){
 const [data,setData]=useState<Status|null>(null),[key,setKey]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');const base='companies/'+companyId+'/management';
 useEffect(()=>{const c=new AbortController();journeyApi<Status>(base,undefined,c.signal).then(d=>{if(!c.signal.aborted)setData(d);}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[base]);
 async function change(revoke:boolean){if(busy)return;setBusy(true);setError('');setKey(null);try{const result=await journeyApi<{key:string|null}>(base+'/key',{revoke});setKey(result.key);setData(await journeyApi<Status>(base));}catch(e){setError(e instanceof Error?e.message:'Não foi possível alterar a integração.');}finally{setBusy(false);}}
 return <section className={styles.card}><h2>Sistema de gestão da clínica</h2><p>Contatos autorizados e datas administrativas podem apoiar o relacionamento. Não importe prontuários, exames ou diagnósticos. Cada integração pertence somente a esta empresa.</p>{error&&<p role="alert" className="form-error">{error}</p>}
 <article className={styles.proposal}><h3>API do sistema de gestão</h3><p>{data?.integration?.active?data.integration.lastReceivedAt?'Último lote recebido: '+new Date(data.integration.lastReceivedAt).toLocaleString('pt-BR'):'Chave criada · aguardando o primeiro lote de dados':'Ainda não conectada'}</p><p>Seu sistema ou um integrador pode enviar lotes no contrato da MedSI. Sistemas com APIs diferentes precisam de um adaptador; cadastrar uma URL não faz essa tradução automaticamente.</p><code style={{overflowWrap:'anywhere'}}>{data?.endpoint??'Carregando endereço…'}</code><details><summary>Contrato para o integrador</summary><p>POST com Authorization: Bearer SUA_CHAVE e Content-Type: application/json. Até 500 pacientes por lote. Cada lote tem um eventId UUID único e observedAt com data/hora/fuso dos dados. Eventos repetidos não são aplicados duas vezes.</p><pre style={{whiteSpace:'pre-wrap',fontSize:12}}>{JSON.stringify({eventId:'UUID_DO_LOTE',observedAt:'DATA_HORA_ISO_COM_FUSO',students:[{externalId:'ID_NO_SISTEMA',name:'NOME_DO_CONTATO',phone:'+5511999999999',birthday:null,lastAttendance:null,status:'active',consent:false,tag:''}]},null,2)}</pre><p>birthday: AAAA-MM-DD ou null; lastAttendance: data/hora ISO com fuso ou null. consent deve refletir a autorização real para mensagens. status: active ou inactive. Os dados precisam ser atuais; lotes com mais de 24 horas são recusados. IDs e telefones não podem identificar pacientes diferentes.</p></details>{owner&&<div className={styles.actions}><Button disabled={busy||!data} onClick={()=>void change(false)}>{data?.integration?.active?'Substituir chave de integração':'Gerar chave de integração'}</Button>{data?.integration?.active&&<Button variant="outline" disabled={busy} onClick={()=>void change(true)}>Revogar chave</Button>}</div>}{data?.integration?.active&&owner&&<p>Substituir a chave interrompe o acesso da chave anterior. Atualize-a também no sistema de origem.</p>}{key&&<div role="status"><p>Chave criada. Copie agora e guarde no servidor do integrador; ela não será exibida novamente.</p><textarea readOnly aria-label="Chave de integração criada" rows={2} value={key} style={{width:'100%'}}/><Button variant="outline" onClick={()=>setKey(null)}>Ocultar chave</Button></div>}</article>
 <article className={styles.proposal}><h3>Agenda e sistemas da clínica</h3><span className="tag">Conector específico sob homologação</span><p>A API recebe contatos autorizados. A sincronização de agenda, confirmação de consultas e integração com prontuários não estão implementadas. A equipe confirma os agendamentos no sistema que já utiliza.</p></article>
 </section>;
}
