'use client';
import {useEffect,useState} from 'react';
import {Button} from '@askadia/ui';
import {labels,type FactInput,type OnboardingSnapshot,type ProfileKey} from '@askadia/contracts';
import {journeyApi} from '../lib/journey-api';
const stageKeys:Record<number,ProfileKey[]>={1:['objective','audience','channels','brand'],2:['structure','hours','offers','video'],3:['video','brand'],4:['sales','hours'],5:['budget','objective']};
export function MarketingFacts({companyId,stage,write,onChanged}:{companyId:string;stage:number;write:boolean;onChanged:(snapshot:OnboardingSnapshot)=>void|Promise<void>}){
 const [snapshot,setSnapshot]=useState<OnboardingSnapshot|null>(null),[values,setValues]=useState<Partial<Record<ProfileKey,FactInput>>>({}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const keys=stageKeys[stage]??stageKeys[1]!;
 useEffect(()=>{const c=new AbortController();setSnapshot(null);setError('');void journeyApi<OnboardingSnapshot>('companies/'+companyId+'/marketing-facts',undefined,c.signal).then(value=>{if(c.signal.aborted)return;setSnapshot(value);setValues(Object.fromEntries(Object.entries(value.state.facts).map(([key,fact])=>[key,{value:fact.value,status:fact.status}])));}).catch(e=>{if(!c.signal.aborted)setError(e instanceof Error?e.message:'Não foi possível carregar o perfil.');});return()=>c.abort();},[companyId]);
 async function save(){if(!snapshot||busy)return;setBusy(true);setError('');setNotice('');try{const facts=Object.fromEntries(keys.filter(k=>{const value=values[k],prior=snapshot.state.facts[k];return value&&JSON.stringify({value:prior?.value??null,status:prior?.status??'deferred'})!==JSON.stringify(value);}).map(k=>[k,values[k]]));if(!Object.keys(facts).length){setNotice('Nenhuma alteração para salvar.');return;}const next=await journeyApi<OnboardingSnapshot>('companies/'+companyId+'/marketing-facts',{requestId:crypto.randomUUID(),revision:snapshot.state.revision,facts});setSnapshot(next);setNotice('Fatos confirmados. As propostas precisam de nova revisão para esta versão.');await onChanged(next);}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar.');}finally{setBusy(false);}}
 return <details className="panel"><summary>Informações para esta etapa</summary><p>Informe os fatos aprovados pela clínica. Você pode marcar o que ainda não sabe e continuar depois. Não inclua dados de pacientes.</p>{stage===5&&<p>O orçamento serve para planejar. Nenhuma campanha ou autorização de gasto será criada.</p>}{error&&<p className="form-error" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{!snapshot&&!error&&<p role="status">Carregando fatos salvos…</p>}{snapshot&&<fieldset disabled={!write||busy} className="form">{keys.map(key=><label key={key}>{labels[key]}<select value={values[key]?.status??'deferred'} onChange={e=>setValues({...values,[key]:{value:e.target.value==='provided'?values[key]?.value??'':null,status:e.target.value as FactInput['status']}})}><option value="provided">Informar e confirmar</option><option value="deferred">Informar depois</option><option value="unknown">Ainda não sei</option></select>{values[key]?.status==='provided'&&<textarea rows={3} maxLength={6000} value={values[key]?.value??''} onChange={e=>setValues({...values,[key]:{value:e.target.value,status:'provided'}})} placeholder={key==='brand'?'Cores, estilo, tom e materiais autorizados':key==='channels'?'URLs públicos HTTPS, Instagram e contato administrativo':undefined}/>}</label>)}<Button disabled={busy||!write||snapshot.state.confirmed_revision!==snapshot.state.revision} onClick={()=>void save()}>{busy?'Salvando…':'Confirmar e salvar estas informações'}</Button>{snapshot.state.confirmed_revision!==snapshot.state.revision&&<p>Confirme primeiro as alterações pendentes do cadastro.</p>}</fieldset>}</details>;
}
