'use client';
import {useCallback,useEffect,useState} from 'react';
import {Button} from '@askadia/ui';
import {journeyApi} from '../lib/journey-api';
type Status={configured:boolean;connected:boolean;state:string;automaticAvailable:boolean};
export function OfficialWhatsAppConnection({companyId,canConnect,onChange}:{companyId:string;canConnect:boolean;onChange:()=>Promise<void>}){
 const base='companies/'+companyId+'/whatsapp-cloud';const [status,setStatus]=useState<Status|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 const load=useCallback(async(signal?:AbortSignal)=>{const data=await journeyApi<Status>(base+'/status',undefined,signal);if(!signal?.aborted)setStatus(data);},[base]);
 useEffect(()=>{const controller=new AbortController();void load(controller.signal).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[load]);
 async function act(action:'connect'|'disconnect'){setBusy(true);setError('');setMessage('');try{const response=await journeyApi<{message?:string}>(base+'/'+action,{});setMessage(response.message??'Conexão oficial encerrada.');await load();await onChange();}catch(e){setError(e instanceof Error?e.message:'Não foi possível concluir a conexão oficial.');}finally{setBusy(false);}}
 return <section><h3>WhatsApp oficial · Meta Cloud API</h3><p role="status">{!status?'Consultando configuração…':status.connected?'Conectado ao número oficial desta empresa.':status.state==='pending'?'Número verificado. Aguardando a primeira mensagem recebida pelo webhook oficial.':'Conexão oficial pendente.'}</p><p>O responsável configura o aplicativo Meta, a conta WhatsApp Business, o número verificado e o webhook no servidor. As credenciais pertencem a esta empresa e são guardadas no cofre.</p>{status&&!status.configured&&<p>Peça à equipe responsável a configuração segura desta empresa. Depois volte aqui para verificar o número. Nenhuma chave é solicitada nesta tela.</p>}{status?.connected&&<p>Abra a Caixa de entrada para assumir e responder a conversas recebidas nas últimas 24 horas. {status.automaticAvailable?'O processamento automático está disponível e depende de regras e horários revisados, consentimento e ausência de atendimento humano.':'O processamento automático está pausado ou aguarda configuração do servidor.'} Envio de arquivos ainda aguarda homologação neste canal.</p>}{error&&<p className="form-error" role="alert">{error}</p>}{message&&<p role="status">{message}</p>}{canConnect&&<div className="row"><Button disabled={busy||!status?.configured} onClick={()=>void act('connect')}>{busy?'Verificando…':'Verificar e vincular número oficial'}</Button><Button variant="outline" disabled={busy} onClick={()=>void load().catch(e=>setError(e.message))}>Atualizar estado</Button>{status?.state!=='unconfigured'&&<Button variant="ghost" disabled={busy} onClick={()=>void act('disconnect')}>Desconectar</Button>}</div>}</section>;
}
