'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {BarChart3,Users,MapPin,TrendingUp,RefreshCw,ArrowUpRight,Send,Globe,Info,Building2} from 'lucide-react';
import {Button} from '@askadia/ui';
import {distanceMeters,type BusinessOverview,type MarketSnapshot,type Metric} from '@askadia/contracts';
import {journeyApi} from '../lib/journey-api';
import {readApiResponse} from '../lib/response';
import {PlacesMap} from './places-map';
import {TrendsEmbed} from './trends-embed';
import {LoadState} from './load-state';
import s from './overview-bi.module.css';
const number=(value:number|null|undefined,digits=0)=>value===null||value===undefined?'—':value.toLocaleString('pt-BR',{maximumFractionDigits:digits});
const timestamp=(value:string|null|undefined)=>value?new Date(value).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo',dateStyle:'short',timeStyle:'short'})+' · Brasília':'Ainda não consultado';
type Finance={metrics:Metric[];permissions:{finance:boolean};limitations:string[];sources:unknown[]};
function Empty({children}:{children:React.ReactNode}){return <div className={s.empty}><BarChart3 size={25}/><p>{children}</p></div>;}
function Stat({label,value,detail,icon}:{label:string;value:string;detail:string;icon:React.ReactNode}){return <article className={s.stat}><div>{label}{icon}</div><strong>{value}</strong><small>{detail}</small></article>;}
function Bars({rows,max}:{rows:{label:string;value:number}[];max?:number}){const ceiling=max??Math.max(...rows.map(r=>r.value),1);return <ol className={s.bars}>{rows.map((r,i)=><li key={r.label}><span>{String(i+1).padStart(2,'0')}</span><div><div><strong>{r.label}</strong><b>{number(r.value,1)}</b></div><div className={s.track}><i style={{width:(r.value/ceiling*100)+'%'}}/></div></div></li>)}</ol>;}
export function OverviewBi({companyId,canResearch,confirmed}:{companyId:string;canResearch:boolean;confirmed:boolean}){
 const [days,setDays]=useState(30),[attempt,setAttempt]=useState(0),[data,setData]=useState<BusinessOverview|null>(null),[finance,setFinance]=useState<Finance|null>(null),[error,setError]=useState(''),[financeError,setFinanceError]=useState(''),[loading,setLoading]=useState(true);
 const [radius,setRadius]=useState(3000),[market,setMarket]=useState<MarketSnapshot|null>(null),[marketError,setMarketError]=useState(''),[researching,setResearching]=useState(false),[selected,setSelected]=useState<string[]>([]);
 const researchRequest=useRef<AbortController|null>(null);const base='/empresa/'+companyId;
 useEffect(()=>{const c=new AbortController();setLoading(true);setData(null);setFinance(null);setError('');setFinanceError('');void journeyApi<BusinessOverview>('companies/'+companyId+'/overview?days='+days,undefined,c.signal).then(async value=>{if(c.signal.aborted)return;setData(value);setLoading(false);try{const params=new URLSearchParams({companyId,start:value.start,end:value.end,timezone:value.timezone,section:'overview'});const response=await fetch('/api/dashboard?'+params,{signal:c.signal,cache:'no-store'});const snapshot=await readApiResponse<Finance>(response);if(!c.signal.aborted)setFinance(snapshot);}catch{if(!c.signal.aborted)setFinanceError('Dados de mídia e finanças indisponíveis neste momento.');}}).catch(e=>{if(!c.signal.aborted){setError(e.message);setLoading(false);}});return()=>c.abort();},[companyId,days,attempt]);
 useEffect(()=>{researchRequest.current?.abort();const c=new AbortController();researchRequest.current=c;setMarket(null);setSelected([]);setMarketError('');setResearching(true);void journeyApi<MarketSnapshot>('companies/'+companyId+'/market?radius='+radius,undefined,c.signal).then(async value=>{if(!value.collectedAt&&canResearch&&confirmed)value=await journeyApi<MarketSnapshot>('companies/'+companyId+'/market',{radius},c.signal);if(!c.signal.aborted)setMarket(value);}).catch(e=>{if(!c.signal.aborted)setMarketError(e.message);}).finally(()=>{if(!c.signal.aborted)setResearching(false);});return()=>c.abort();},[companyId,radius,canResearch,confirmed]);
 async function refreshMarket(){researchRequest.current?.abort();const c=new AbortController();researchRequest.current=c;setResearching(true);setMarketError('');try{const value=await journeyApi<MarketSnapshot>('companies/'+companyId+'/market',{radius},c.signal);if(!c.signal.aborted){setMarket(value);setSelected([]);}}catch(e){if(!c.signal.aborted)setMarketError(e instanceof Error?e.message:'Pesquisa indisponível.');}finally{if(!c.signal.aborted)setResearching(false);}}
 const municipality=market?.demographics.data;const search=market?.competitors.search;const selectedPlace=search?.places.find(p=>p.id===selected[0]);const crm=data?.crm;const campaign=data?.campaigns;const totalOpportunities=crm?.stages.reduce((n,s)=>n+s.count,0)??0;
 return <div className={s.dashboard}>
  <div className={s.toolbar}><div><span className={s.eyebrow}>PAINEL DO NEGÓCIO</span><h2>O que acontece na sua clínica.</h2><p>Operação, oportunidades e contexto para decidir o próximo passo.</p></div><div className={s.controls}><label>Período<select value={days} onChange={e=>setDays(Number(e.target.value))}><option value={7}>Últimos 7 dias</option><option value={30}>Últimos 30 dias</option><option value={90}>Últimos 90 dias</option></select></label><Button variant="outline" size="small" disabled={loading} onClick={()=>setAttempt(x=>x+1)}><RefreshCw size={15}/>Atualizar BI</Button></div></div>
  {error?<LoadState error={error} retry={()=>setAttempt(x=>x+1)}/>:loading?<LoadState label="Consultando os indicadores da empresa…"/>:<>
   <div className={s.stats}><Stat label="Contatos no CRM" value={number(crm?.totalContacts)} detail={crm?'Base atual cadastrada':'Sem acesso ou consulta indisponível'} icon={<Users size={18}/>}/><Stat label="Novos cadastros" value={number(crm?.newContacts)} detail={'Criados no CRM · últimos '+days+' dias'} icon={<TrendingUp size={18}/>}/><Stat label="Campanhas ativas" value={number(campaign?.active)} detail="Campanhas de mensagens · agora" icon={<Send size={18}/>}/><Stat label="Mensagens enviadas" value={number(campaign?.sent)} detail={'Campanhas · últimos '+days+' dias'+(campaign?.uncertain?' · '+campaign.uncertain+' sem confirmação':'')} icon={<Send size={18}/>}/></div>
   {data?.failures.length? <p className={s.notice}>Consulta parcial: {data.failures.join(', ')}. Os campos indisponíveis aparecem como “—”.</p>:null}
   <div className={s.twoColumns}><section className={s.panel}><div className={s.heading}><div><span className={s.eyebrow}>AQUISIÇÃO</span><h3>Novos contatos por dia</h3></div><Link href={base+'/crm'}>Abrir CRM <ArrowUpRight size={15}/></Link></div>{crm?<><div className={s.chart} role="img" aria-label={'Cadastros diários no CRM. Total: '+crm.newContacts}><div className={s.chartBars}>{crm.daily.map(d=><div key={d.date} title={d.date+': '+d.count+' cadastros'}><i style={{height:Math.max(2,d.count/Math.max(...crm.daily.map(p=>p.count),1)*100)+'%',opacity:d.count?1:0.18}}/></div>)}</div></div><div className={s.axis}><span>{data?.start.split('-').reverse().join('/')}</span><span>{data?.end.split('-').reverse().join('/')}</span></div><details className={s.dataTable}><summary>Ver dados por dia</summary><table><thead><tr><th>Data</th><th>Cadastros</th></tr></thead><tbody>{crm.daily.map(d=><tr key={d.date}><td>{d.date.split('-').reverse().join('/')}</td><td>{d.count}</td></tr>)}</tbody></table></details><p className={s.note}>Fonte: CRM da empresa · {data?.timezone}. Importações contam na data de cadastro, não como primeiro contato.</p></>:<Empty>Sem acesso ao CRM ou sem consulta disponível.</Empty>}</section>
   <section className={s.panel}><div className={s.heading}><div><span className={s.eyebrow}>RELACIONAMENTO</span><h3>Oportunidades por etapa</h3></div><b>{crm?number(totalOpportunities):'—'}</b></div>{crm?<><Bars rows={crm.stages.map(stage=>({label:stage.label,value:stage.count}))}/><p className={s.note}>Distribuição atual de toda a base. Etapas não representam conversão histórica nem pagamento confirmado.</p></>:<Empty>Os indicadores comerciais exigem acesso ao CRM.</Empty>}</section></div>
   <section className={s.panel}><div className={s.heading}><div><span className={s.eyebrow}>INVESTIMENTO E RETORNO</span><h3>Resultados com origem.</h3></div></div>{finance?<><div className={s.financeGrid}>{finance.metrics.filter(m=>['media','revenue','cac','roas','roi','customers'].includes(m.id)).map(m=><article key={m.id}><small>{m.label}</small><strong>{m.value===null?'—':m.unit==='BRL'?m.value.toLocaleString('pt-BR',{style:'currency',currency:'BRL'}):number(m.value,2)+(m.unit==='percent'?'%':m.unit==='multiple'?'x':'')}</strong><span>{m.value===null?'Sem base suficiente':m.state==='available'?'Dados disponíveis':'Cobertura parcial'}</span><details><summary>Fonte e cálculo</summary><p>{m.source}</p><p>{m.formula}</p><p>{m.reason}</p></details></article>)}</div><p className={s.note}>Período selecionado · receitas e custos informados nas fontes do BI. Contatos e oportunidades não substituem clientes pagantes.</p></>:<Empty>{financeError||'Conferindo fontes financeiras…'}</Empty>}</section>
  </>}
  <section className={s.regionHeader}><div><span className={s.eyebrow}>INTELIGÊNCIA DA REGIÃO</span><h2>Conheça o entorno da sua clínica.</h2><p>População do município, estabelecimentos próximos e demanda de pesquisa.</p></div><div className={s.controls}><label>Raio de concorrentes<select value={radius} disabled={researching} onChange={e=>setRadius(Number(e.target.value))}><option value={1000}>1 km</option><option value={3000}>3 km</option><option value={5000}>5 km</option><option value={10000}>10 km</option></select></label><Button size="small" variant="outline" disabled={researching||!canResearch||!confirmed} onClick={()=>void refreshMarket()}><RefreshCw size={15}/>{researching?'Consultando…':'Atualizar região'}</Button></div></section>
  {!confirmed&&<p className={s.notice}>Confirme o perfil e a localização da clínica no <Link href={base+'/onboarding'}>onboarding</Link> para iniciar a análise regional.</p>}{marketError&&<LoadState error={marketError} retry={canResearch?()=>void refreshMarket():undefined}/>}
  <div className={s.stats}><Stat label="População do município" value={number(municipality?.population)} detail={municipality?municipality.municipality+' · Censo '+municipality.year:'IBGE · aguardando consulta'} icon={<Users size={18}/>}/><Stat label="Densidade demográfica" value={municipality?.density!=null?number(municipality.density,2)+' hab/km²':'—'} detail={municipality?'Média municipal · Censo '+municipality.year:'IBGE · sem base disponível'} icon={<Globe size={18}/>}/><Stat label="Locais encontrados" value={number(market?.competitors.count)} detail={'Google Maps · '+radius/1000+' km · amostra parcial'} icon={<MapPin size={18}/>}/><Stat label="Páginas no Facebook" value={number(market?.facebook.count)} detail={'Com coordenadas no raio · fonte separada'} icon={<Building2 size={18}/>}/></div>
  {municipality?<p className={s.source}><a href={municipality.sourceUrl} target="_blank" rel="noreferrer">IBGE · tabela 4714 <ArrowUpRight size={13}/></a>Área municipal: {number(municipality.areaKm2,2)} km². {market?.demographics.message}</p>:<p className={s.note}>{market?.demographics.message}</p>}
  <div className={s.regionalGrid}>
   <section className={s.panel}><div className={s.heading}><div><span className={s.eyebrow}>GOOGLE TRENDS</span><h3>{market?.trends.rows.length?'Top 20 · pesquisas relacionadas':'Pesquisas da região'}</h3></div><TrendingUp size={21}/></div><p className={s.note}>{market?.trends.region??'Região a confirmar'} · {market?.trends.period??'Últimos 3 meses'} · “{market?.trends.query??'clínica'}”</p>{market?.trends.rows.length?<><Bars rows={market.trends.rows.map(r=>({label:r.term,value:r.interest}))} max={100}/><p className={s.note}>{market.trends.rows.length} resultados fornecidos. Interesse relativo 0–100; não é quantidade de pesquisas.</p></>:market?.trends.geo?<p className={s.note}>Pesquisas relacionadas a clínicas, na visualização oficial do Google.</p>:<Empty>{researching?'Consultando a disponibilidade de tendências…':market?.trends.message??'Atualize a análise regional para conferir a disponibilidade.'}</Empty>}<p className={s.note}>{market?.trends.rows.length?market.trends.message:'O recorte disponível é estadual, separado do raio do mapa. Não representa as 20 buscas de todo o município.'}</p>{market?.trends.geo&&!market.trends.rows.length&&<TrendsEmbed geo={market.trends.geo} query={market.trends.query}/>}<div className={s.links}><a href={market?.trends.sourceUrl??'https://trends.google.com/trends/'} target="_blank" rel="noreferrer">Ver no Google Trends <ArrowUpRight size={14}/></a></div></section>
   <section className={s.panel}><div className={s.heading}><div><span className={s.eyebrow}>MAPA DE CONCORRENTES</span><h3>Seu mercado por perto.</h3></div><span className={s.badge}>{radius/1000} km</span></div>{search?<><PlacesMap search={search} selected={selected} onSelect={id=>setSelected([id])} disabled={false}/>{selectedPlace&&<div className={s.selected}><strong>{selectedPlace.name}</strong><p>{selectedPlace.address}</p><a href={selectedPlace.url} target="_blank" rel="noreferrer">Ver no Google Maps <ArrowUpRight size={13}/></a></div>}<ol className={s.places}>{search.places.map((p,i)=><li key={p.id} data-selected={selected.includes(p.id)}><button onClick={()=>setSelected([p.id])}><span>{i+1}</span><div><strong>{p.name}</strong><small>{p.address}</small></div><b>{search.center&&p.latitude!==null&&p.longitude!==null?number(distanceMeters(search.center,{latitude:p.latitude,longitude:p.longitude})/1000,1)+' km':''}</b></button>{p.attributions.map(a=><small key={a.uri}><a href={a.uri} target="_blank" rel="noreferrer">{a.displayName}</a></small>)}</li>)}</ol></>:<Empty>{researching?'Buscando estabelecimentos ao redor…':market?.competitors.message??'Aguardando pesquisa da região.'}</Empty>}<p className={s.note}>{search?market?.competitors.message:''}{market?.competitors.limited?' O limite de 20 resultados foi atingido; podem existir outros locais.':''}</p><Link href={base+'/onboarding'} className={s.subtleLink}>Revisar localização da empresa <ArrowUpRight size={13}/></Link></section>
  </div>
  <section className={s.panel}><div className={s.heading}><div><span className={s.eyebrow}>FONTE COMPLEMENTAR</span><h3>Concorrentes encontrados no Facebook</h3></div><Link href={base+'/integracoes'}>Ver conexão <ArrowUpRight size={15}/></Link></div><p>{market?.facebook.message??'Conecte a Página e atualize a região para conferir o acesso à pesquisa.'}</p>{Boolean(market?.facebook.places.length)&&<div className={s.facebookList}>{market!.facebook.places.map(p=><a key={p.id} href={p.url} target="_blank" rel="noreferrer"><strong>{p.name}</strong><small>{number(p.distance/1000,1)} km <ArrowUpRight size={13}/></small></a>)}</div>}</section>
  <p className={s.source}><Info size={14}/>Consulta regional: {timestamp(market?.collectedAt)}. Fontes têm coberturas diferentes. Dados demográficos não são em tempo real.</p>
 </div>;
}

