import Link from 'next/link';
import {ArrowRight,Check,Gift,ShieldCheck} from 'lucide-react';
import {commercePlans,commerceFeatures,assistedImplementation,installmentAmounts,type CommercePlanId} from '@askadia/contracts';
import s from './purchase.module.css';
export const brl=(cents:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',minimumFractionDigits:cents%100?2:0,maximumFractionDigits:2}).format(cents/100);
export function InstallmentNote({total,count}:{total:number;count:number}){const amounts=installmentAmounts(total,count);return amounts.last===amounts.regular?null:<small className={s.installmentNote}>{count-1} parcelas de {brl(amounts.regular)} e a última de {brl(amounts.last)}. Total exato: {brl(total)}.</small>;}
export function AssistedImplementation(){return <aside className={s.assisted}><span className={s.giftIcon}><Gift size={25}/></span><div><span className={s.offerLabel}>BRINDE PARA OS {assistedImplementation.giftLimit} PRIMEIROS CLIENTES</span><h3>Implementação Assistida</h3><p>Um início acompanhado para colocar o marketing da sua empresa em movimento.</p></div><div className={s.giftPrice}><s>{brl(assistedImplementation.priceCents)}</s><strong>De presente</strong></div></aside>;}
export function PricingCards({onSelect,busy=false,unavailable=false,compact=false,previewPlan='askadia_semiannual',integralPayment=false}:{compact?:boolean;previewPlan?:CommercePlanId;integralPayment?:boolean;onSelect?:(id:CommercePlanId)=>void;busy?:boolean;unavailable?:boolean}){
 return <><div className={compact?`${s.plans} ${s.compactPlans}`:s.plans}>{commercePlans.map(p=><article key={p.id} data-preview={p.id===previewPlan} className={p.commitmentMonths===6?s.annual:s.plan}>
  <div className={s.planTop}><span>{p.name}</span>{p.commitmentMonths===6&&<small>Economize {brl(commercePlans[0].totalCents*6-p.totalCents)}</small>}</div><h2>{p.commitmentMonths===6&&<small>{integralPayment?'Pagamento integral de':'Em até 6x no cartão de'}</small>}{brl(integralPayment?p.totalCents:p.installmentCents)}{p.commitmentMonths===1&&<small>/mês</small>}</h2>
  <p>{p.commitmentMonths===6?'Contrato semestral · total de '+brl(p.totalCents):'Assinatura mensal recorrente'}</p>{p.commitmentMonths===6&&!integralPayment&&<InstallmentNote total={p.totalCents} count={p.installments}/>}<p className={s.planDescription}>{p.description}</p>{compact&&<p className={s.compactIncluded}><Check size={14}/>Todos os recursos incluídos</p>}<ul><li><Check size={17}/>Todas as funcionalidades</li><li><Check size={17}/>Estratégia, conteúdo e site com IA</li><li><Check size={17}/>Campanhas, atendimento e CRM</li><li><Check size={17}/>Você aprova antes da execução</li></ul>
  {onSelect?<button className={s.primary} disabled={busy||unavailable} onClick={()=>onSelect(p.id)}>{busy?'Preparando…':'Escolher '+p.name.toLowerCase()}<ArrowRight size={18}/></button>:<Link className={s.primary} href="/login?modo=cadastro">Começar grátis<ArrowRight size={18}/></Link>}<small className={s.perCompany}>Valor por empresa criada no workspace</small>
 </article>)}</div><AssistedImplementation/></>;
}
export function PricingFeatures(){return <section className={s.features}><div className={s.sectionTitle}><span>TUDO CONECTADO AO SEU NEGÓCIO</span><h2>Menos tarefas soltas.<br/>Mais direção para crescer.</h2><p>Os mesmos recursos nos dois planos. Escolha a forma de pagamento que combina com a sua empresa.</p></div><div className={s.featureGrid}>{commerceFeatures.map(([title,description],i)=><article key={title}><span>{String(i+1).padStart(2,'0')}</span><h3>{title}</h3><p>{description}</p></article>)}</div><p className={s.disclosure}><ShieldCheck size={20}/>A verba de anúncios e os custos dos provedores conectados são separados da assinatura. Recursos dependem das integrações e permissões disponíveis. Uso de IA sujeito aos limites da conta; nenhum plano promete uso ilimitado.</p></section>;}
