'use client';
import {AsaasBillingPanel} from './asaas-billing-panel';
import {HelpChat} from './help-chat';
import Link from 'next/link';
import {useCallback,useEffect,useRef,useState} from 'react';
import {ArrowRight,ArrowLeft,ShieldCheck,FlaskConical} from 'lucide-react';
import {commercePlans,type Checkout,type CommercePlanId,type OnboardingSnapshot,type PurchaseState} from '@askadia/contracts';
import {BrandMark,BrandWordmark} from './brand';
import {OnboardingChat} from './onboarding-chat';
import {GuidedStrategy} from './guided-strategy';
import {PricingCards,InstallmentNote,brl} from './pricing';
import {journeyApi} from '../lib/journey-api';
import s from './purchase.module.css';
type Screen='loading'|'travel'|'welcome'|'interview'|'unlock'|'plans'|'checkout'|'billing'|'strategy';
export function PurchaseJourney({companyId,clientName}:{companyId?:string;clientName:string}){
 const [screen,setScreen]=useState<Screen>(companyId?'loading':'travel'),[purchase,setPurchase]=useState<PurchaseState|null>(null),[profile,setProfile]=useState<OnboardingSnapshot|null>(null),[checkout,setCheckout]=useState<Checkout|null>(null),[accepted,setAccepted]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[outcome,setOutcome]=useState('');
 const [previewPlan,setPreviewPlan]=useState<CommercePlanId>('askadia_semiannual');
 const page=useRef<HTMLElement>(null);
 useEffect(()=>{window.scrollTo({top:0,behavior:'auto'});const heading=page.current?.querySelector('h1');if(heading){heading.setAttribute('tabindex','-1');heading.focus({preventScroll:true});}},[screen]);
 const lock=useRef(false),beginId=useRef<string|null>(null),checkoutRequest=useRef<{id:string;plan:CommercePlanId;installments:number}|null>(null);const base='companies/'+companyId;
 const resume=useCallback(async(signal?:AbortSignal)=>{if(!companyId)return;const [state,data]=await Promise.all([journeyApi<PurchaseState>(base+'/purchase',undefined,signal),journeyApi<OnboardingSnapshot>(base,undefined,signal)]);if(signal?.aborted)return;setPurchase(state);setProfile(data);if(!state.onboardingComplete)setScreen('interview');else if(state.aiAllowed)setScreen('strategy');else if(state.asaasSandboxEnabled&&state.canPurchase)setScreen('billing');else if(state.latestCheckout?.status==='pending'&&Date.parse(state.latestCheckout.expires_at)>Date.now()){setCheckout(state.latestCheckout);setScreen('checkout');}else setScreen('unlock');},[companyId,base]);
 useEffect(()=>{if(!companyId)return;const c=new AbortController();void resume(c.signal).catch(e=>{if(!c.signal.aborted)setError(e instanceof Error?e.message:'Não foi possível retomar seu cadastro.');});return()=>c.abort();},[companyId,resume]);
 useEffect(()=>{if(screen!=='travel')return;const t=setTimeout(()=>setScreen('welcome'),2800);return()=>clearTimeout(t);},[screen]);
 async function begin(){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{beginId.current??=crypto.randomUUID();const value=await journeyApi<{companyId:string}>('companies',{requestId:beginId.current});window.location.assign('/comecar?empresa='+value.companyId);}catch(e){setError(e instanceof Error?e.message:'Não foi possível começar.');}finally{lock.current=false;setBusy(false);}}
 async function choose(plan:CommercePlanId,installments=plan==='askadia_semiannual'?6:1){if(lock.current||!companyId)return;if(purchase?.asaasSandboxEnabled){setPreviewPlan(plan);setScreen('billing');return;}lock.current=true;setBusy(true);setError('');setOutcome('');try{if(checkoutRequest.current?.plan!==plan||checkoutRequest.current.installments!==installments)checkoutRequest.current={id:crypto.randomUUID(),plan,installments};const value=await journeyApi<Checkout>(base+'/purchase/checkout',{requestId:checkoutRequest.current.id,planId:plan,installments});setCheckout(value);setAccepted(false);setScreen('checkout');}catch(e){setError(e instanceof Error?e.message:'Não foi possível selecionar o plano.');}finally{lock.current=false;setBusy(false);}}
 async function confirm(result:'approved'|'declined'|'cancelled'){if(lock.current||!checkout)return;lock.current=true;setBusy(true);setError('');try{await journeyApi(base+'/purchase/checkout/confirm',{checkoutId:checkout.id,outcome:result,accepted});checkoutRequest.current=null;if(result==='approved'){await resume();}else{setCheckout(null);setOutcome(result==='declined'?'Pagamento de teste recusado. Nenhuma cobrança ocorreu e a IA continua bloqueada. Você pode tentar novamente.':'Checkout cancelado. Seu onboarding continua salvo.');setScreen('plans');}}catch(e){setError(e instanceof Error?e.message:'Não foi possível confirmar. Tente novamente: a solicitação não será duplicada.');}finally{lock.current=false;setBusy(false);}}
 async function finish(){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{const finished=await journeyApi<{nextPath?:string}>(base+'/purchase/finish',{});window.location.assign(finished.nextPath==='/empresa/'+companyId+'/preparacao'?finished.nextPath:'/empresa/'+companyId);}catch(e){setError(e instanceof Error?e.message:'Conclua as aprovações para entrar.');}finally{lock.current=false;setBusy(false);}}
 const dark=['travel','welcome','unlock'].includes(screen);const companyName=profile?.state.facts.name?.value??'Sua empresa';
 return <main ref={page} className={`${s.journeyShell} ${screen==='interview'?s.chatShell:screen==='plans'?s.plansShell:dark?s.dark:s.shell}`}>{screen!=='interview'&&<header className={s.header}><Link href="/" aria-label="MedSI, início"><BrandWordmark/></Link><div className={s.headerActions}><HelpChat key={companyId??'account'} companyId={companyId}/><Link href="/entrada">Minha conta</Link></div></header>}{dark&&<div className={s.space} aria-hidden="true"><div className={s.stars}/><div className={s.ring}/><div className={s.ring}/><div className={s.ring}/></div>}
 {error&&screen!=='plans'&&<div className={s.interview}><div className={s.error} role="alert">{error}{screen==='loading'&&<button className={s.textButton} onClick={()=>{setError('');void resume().catch(e=>setError(e.message));}}>Tentar novamente</button>}</div></div>}
 {screen==='loading'&&<div className={s.loading} role="status"><div className={s.symbol}><BrandMark/></div>Retomando seu próximo passo…</div>}
 {screen==='travel'&&<section className={s.center}><div className={s.symbol}><BrandMark/></div><span className={s.badge}>UMA NOVA ÓRBITA PARA SEU NEGÓCIO</span><h1>Vamos mais longe.<br/><em>Juntos.</em></h1><p>Seu próximo capítulo começa com uma conversa.</p><button className={s.textButton} onClick={()=>setScreen('welcome')}>Pular animação <ArrowRight size={16}/></button></section>}
 {screen==='welcome'&&<section className={s.center}><div className={s.symbol}><BrandMark/></div><span className={s.badge}>CONVERSA QUE VIRA AÇÃO</span><h1>Boas-vindas à MedSI,<br/><em>{clientName}.</em></h1><p>Serei seu novo assistente de marketing. Tenho algumas perguntas para conhecer sua empresa e preparar seu espaço. Podemos começar?</p><button className={s.primary} disabled={busy} onClick={()=>void begin()}>{busy?'Abrindo sua conversa…':'Sim, vamos começar'}<ArrowRight size={18}/></button><small>Cadastro e conversa gratuitos. Depois você escolhe um plano.<br/>A IA só começa após a confirmação.</small></section>}
 {['plans','checkout','billing','strategy'].includes(screen)&&<nav className={s.progress} aria-label="Progresso do cadastro"><span aria-current={screen==='interview'?'step':undefined}>{screen==='interview'?<strong>01 · Sua empresa</strong>:'01 · Sua empresa'}</span><i/><span aria-current={screen==='plans'||screen==='checkout'||screen==='billing'?'step':undefined}>{screen==='plans'||screen==='checkout'||screen==='billing'?<strong>02 · Seu plano</strong>:'02 · Seu plano'}</span><i/><span aria-current={screen==='strategy'?'step':undefined}>{screen==='strategy'?<strong>03 · Sua estratégia</strong>:'03 · Sua estratégia'}</span></nav>}
 {screen==='interview'&&companyId&&<section className={s.chatInterview}><OnboardingChat immersive companyId={companyId} onExit={purchase?.onboardingComplete?()=>setScreen(purchase.aiAllowed?'strategy':'unlock'):undefined} readOnly={!purchase?.canWrite} onConfirmed={data=>{setProfile(data);setPurchase(p=>p?{...p,onboardingComplete:true}:p);setScreen(purchase?.aiAllowed?'strategy':'plans');}}/></section>}
 {screen==='unlock'&&<section className={s.center}><div className={s.symbol}><BrandMark/></div><span className={s.badge}>PRONTOS PARA O PRÓXIMO PASSO</span><h1>{companyName} tem potencial.<br/><em>Vamos dar direção?</em></h1><p>Seu briefing está salvo. Para criar e ver sua estratégia completa, escolha um plano. Depois, vamos revisar juntos cada etapa.</p>{purchase?.canPurchase?<button className={s.primary} onClick={()=>setScreen('plans')}>Escolher meu plano<ArrowRight size={18}/></button>:<p>O responsável pela conta precisa confirmar o plano.</p>}<small>Checkout de teste · sem cobrança real</small>{purchase?.canWrite&&<button className={s.textButton} onClick={()=>setScreen('interview')}>Revisar minhas respostas</button>}</section>}
 {screen==='plans'&&<section className={s.planScreen} aria-label="Escolha do plano">
  <header className={s.planHeading}><div><h1>Escolha seu plano.</h1><p>Todos os recursos. Você aprova cada ação.</p></div><span className={s.badge} title={companyName}>{companyName}</span></header>
  {(error||outcome)&&<div className={s.planFeedback} role={error?'alert':'status'}><p>{error||outcome}</p><button type="button" onClick={()=>{setError('');setOutcome('');}} aria-label="Fechar aviso">×</button></div>}
  <div className={s.planTabs} role="group" aria-label="Comparar planos">{commercePlans.map(plan=><button key={plan.id} type="button" aria-pressed={previewPlan===plan.id} disabled={busy} onClick={()=>setPreviewPlan(plan.id)}>{plan.name}</button>)}</div>
  <PricingCards compact integralPayment={purchase?.asaasSandboxEnabled} previewPlan={previewPlan} onSelect={id=>void choose(id)} busy={busy} unavailable={!(purchase?.testCheckoutEnabled||purchase?.asaasSandboxEnabled)||!purchase.canPurchase}/>
  <footer className={s.planFooter}><p><ShieldCheck size={15}/><span>{purchase?.asaasSandboxEnabled?'Asaas sandbox · pagamento confirmado pelo provedor.':purchase?.testCheckoutEnabled?'Teste sem cobrança · IA após confirmação.':'Contratação disponível em breve · suas respostas estão salvas.'}<small>Por empresa · anúncios e provedores à parte.</small></span></p><Link href="/planos" target="_blank" rel="noreferrer">Ver todos os recursos ↗</Link></footer>
 </section>}
 {screen==='billing'&&companyId&&<section className={s.checkout}><button type="button" className={s.textButton} onClick={()=>setScreen('plans')}><ArrowLeft size={16}/>Ver planos</button><AsaasBillingPanel companyId={companyId} plan={previewPlan} onUpdated={state=>{if(state.subscription?.status==='active'&&state.subscription.provider_confirmed)void resume().catch(()=>setError('Consulte novamente para retomar a jornada.'));}}/></section>}
 {screen==='checkout'&&checkout&&<section className={s.checkout}><button className={s.textButton} disabled={busy} onClick={()=>{checkoutRequest.current=null;setScreen('plans');setAccepted(false);}}><ArrowLeft size={16}/>Trocar plano</button><h1>Confirme sua escolha.</h1><div className={s.checkoutGrid}><aside className={s.summary}><small>RESUMO DA ESCOLHA</small><h2>{companyName}</h2><p>MedSI {commercePlans.find(p=>p.id===checkout.plan_id)?.name??'Anual (anterior)'} · Todos os recursos</p><dl><div><dt>{checkout.plan_id==='askadia_monthly'?'Mensalidade recorrente':checkout.installments===1?'Pagamento à vista':checkout.installments+' parcelas de'}</dt><dd><strong>{brl(checkout.installment_cents)}</strong></dd></div><div><dt>{checkout.plan_id==='askadia_monthly'?'Total por mês':checkout.plan_id==='askadia_semiannual'?'Total em 6 meses':'Total em 12 meses'}</dt><dd>{brl(checkout.total_cents)}</dd></div><div><dt>Contratação</dt><dd>Por empresa</dd></div><div><dt>Cobrança neste teste</dt><dd>R$ 0</dd></div></dl><InstallmentNote total={checkout.total_cents} count={checkout.installments}/>{checkout.plan_id==='askadia_semiannual'&&<label className={s.installmentsLabel}>Parcelamento no cartão<select aria-label="Parcelamento no cartão" value={checkout.installments} disabled={busy} onChange={e=>void choose('askadia_semiannual',Number(e.target.value))}>{[1,2,3,4,5,6].map(n=><option key={n} value={n}>{n===1?'À vista':n+'x de'} {brl(Math.floor(checkout.total_cents/n))}</option>)}</select></label>}</aside><div className={s.checkoutForm}><span className={s.testNotice}><FlaskConical size={17}/>Ambiente de teste</span><h2>Seu plano está quase pronto.</h2><p>Simule a aprovação sem cartão ou cobrança. O teste libera sete dias de acesso à IA para esta empresa.</p><label><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)} disabled={busy}/>Conferi o plano {checkout.plan_id==='askadia_monthly'?'mensal recorrente de '+brl(checkout.total_cents):(checkout.plan_id==='askadia_semiannual'?'semestral':'anual anterior')+' em '+checkout.installments+' parcela(s), total de '+brl(checkout.total_cents)} por empresa e entendo que esta é uma simulação, sem cobrança.</label><button className={s.primary} disabled={busy||!accepted} onClick={()=>void confirm('approved')}>{busy?'Confirmando…':'Simular pagamento aprovado'}<ArrowRight size={18}/></button><div className={s.testActions}><button className={s.textButton} disabled={busy} onClick={()=>void confirm('declined')}>Testar recusa</button><button className={s.textButton} disabled={busy} onClick={()=>void confirm('cancelled')}>Cancelar</button></div></div></div></section>}
 {screen==='strategy'&&companyId&&<section className={s.strategy}><div className={s.strategyIntro}>{purchase?.accessMode==='test'&&<span>{purchase.asaasSandboxEnabled?'Plano confirmado no sandbox · sem dinheiro real':'Plano ativado em simulação · sem cobrança'}</span>}Revise e aprove cada etapa. A geração pode levar alguns minutos.</div><GuidedStrategy compact companyId={companyId} data={profile} write={purchase?.canWrite??false} approve={profile?.capabilities.actions.includes('strategy.approve')??false} onComplete={()=>void finish()}/>{busy&&<p role="status">Abrindo seu espaço…</p>}</section>}
 </main>;
}
