'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {Button} from '@askadia/ui';
import type {CalendarItem,CreativeAsset} from '@askadia/contracts';
import {journeyApi} from '../lib/journey-api';
type Video={id:string;item_id:string;revision:number;name:string};
type Publication={id:string;item_id:string;revision:number;status:string;desired:string;error:string|null;remote:{mediaId?:string;containerId?:string};snapshot:{instagramId:string;pageId:string;caption:string;scheduledAt:string;format:string;media:{creativeId:string;preparedId:string|null;mime:string;frame:number}[]}};
type Snapshot={items:Publication[];enabled:boolean;account:{instagramId:string|null;name:string;pageId:string;ready:boolean}|null};
const states:Record<string,string>={draft:'Aguardando aprovação específica',approved:'Agendada e autorizada',processing:'Mídia em processamento na Meta',published:'Publicada na conta aprovada',paused:'Pausada',cancelled:'Cancelada',stale:'Versão ou autorização mudou',blocked:'Bloqueada — revise o erro',reconciling:'Resultado incerto — aguardando conferência'};
export function SocialPublications({companyId,item,assets,videos,write,approve}:{companyId:string;item:CalendarItem;assets:CreativeAsset[];videos:Video[];write:boolean;approve:boolean}){
 const [data,setData]=useState<Snapshot|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[accepted,setAccepted]=useState(false),[editing,setEditing]=useState(false),[caption,setCaption]=useState([item.details?.caption,item.details?.cta,item.details?.hashtags.join(' ')].filter(Boolean).join('\n\n')),[scheduled,setScheduled]=useState((item.planned_date??new Date(Date.now()+86400000).toISOString().slice(0,10))+'T10:00');const lock=useRef(false);
 const path='companies/'+companyId+'/social-publications';
 const load=useCallback(async(signal?:AbortSignal)=>{const snapshot=await journeyApi<Snapshot>('companies/'+companyId+'/social-publications',undefined,signal);if(!signal?.aborted)setData(snapshot);},[companyId]);
 useEffect(()=>{const c=new AbortController();void load(c.signal).catch(e=>{if(!c.signal.aborted)setError(e instanceof Error?e.message:'Não foi possível consultar publicações.');});return()=>c.abort();},[load]);
 const publication=data?.items.find(p=>p.item_id===item.id&&p.snapshot.media.some(m=>assets.some(a=>a.id===m.creativeId&&a.revision===item.revision)||videos.some(v=>v.id===m.creativeId&&v.revision===item.revision)));
 const monitoring=publication&&['approved','processing','reconciling'].includes(publication.status);
 useEffect(()=>{if(!monitoring)return;const c=new AbortController(),timer=setInterval(()=>void load(c.signal).catch(()=>{}),15000);return()=>{c.abort();clearInterval(timer);};},[load,monitoring]);
 async function action(suffix:string,body:unknown){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await journeyApi(path+suffix,body);setAccepted(false);setEditing(false);await load();}catch(e){setError(e instanceof Error?e.message:'Não foi possível concluir.');}finally{lock.current=false;setBusy(false);}}
 const creative=item.format==='video'?videos.find(v=>v.revision===item.revision)?.id:assets.find(a=>a.revision===item.revision&&a.frame===0)?.id;
 return <section aria-label="Publicação no Instagram" style={{padding:'1rem',marginTop:'1rem',border:'1px solid #d5dce2',borderRadius:12}}><h5>Publicar no Instagram</h5>{error&&<p role="alert">{error}</p>}{!data?<p>Consultando conta e publicações…</p>:<>
 {!data.account?.ready&&<p>Conecte uma conta profissional e autorize publicação em <Link href={'/empresa/'+companyId+'/integracoes'}>Integrações</Link>.</p>}
 {!publication?<><p>A aprovação da peça final permite preparar a publicação. A autorização de publicar será revisada separadamente.</p><form className="form" onSubmit={e=>{e.preventDefault();if(creative)void action('',{id:crypto.randomUUID(),itemId:item.id,creativeId:creative,caption,scheduledAt:new Date(scheduled).toISOString()});}}><label>Legenda final<textarea rows={5} value={caption} maxLength={2200} onChange={e=>setCaption(e.target.value)} required/></label><small>{caption.length}/2200 caracteres</small><label>Data e horário da publicação (fuso do seu navegador)<input type="datetime-local" value={scheduled} onChange={e=>setScheduled(e.target.value)} required/></label><Button disabled={busy||!write||!creative||item.status!=='approved'||!data.account?.ready||caption.length>2200||!caption.trim()}>Preparar publicação para revisar</Button><p>As artes serão preparadas como JPEGs privados para Instagram. Vídeos MP4 serão enviados como Reels. Nenhuma publicação ocorre nesta etapa.</p></form></>:<>
 <p><strong>{states[publication.status]??publication.status}</strong></p><p>Conta Instagram: {publication.snapshot.instagramId} · {publication.snapshot.format==='carousel'?'Carrossel':publication.snapshot.format==='reels'?'Reel':'Imagem'} · {new Date(publication.snapshot.scheduledAt).toLocaleString('pt-BR')}</p><p style={{whiteSpace:'pre-wrap'}}>{publication.snapshot.caption}</p><div style={{display:'flex',gap:12,flexWrap:'wrap'}}>{publication.snapshot.media.filter(m=>m.mime==='image/jpeg').map(m=><a key={m.creativeId} href={m.preparedId?'/api/onboarding/'+path+'/media/'+m.preparedId:'/api/onboarding/companies/'+companyId+'/creatives/'+m.creativeId} target="_blank" rel="noreferrer"><img alt={'JPEG preparado para publicar — slide '+(m.frame+1)} src={m.preparedId?'/api/onboarding/'+path+'/media/'+m.preparedId:'/api/onboarding/companies/'+companyId+'/creatives/'+m.creativeId} style={{width:180,maxHeight:220,objectFit:'contain'}}/></a>)}</div>
 {publication.error&&<p role="alert">{publication.error}</p>}{publication.remote.mediaId&&<p>ID confirmado pela Meta: {publication.remote.mediaId}</p>}
 {write&&['draft','approved','paused','blocked'].includes(publication.status)&&!publication.remote.containerId&&<>{!editing?<Button variant="outline" disabled={busy} onClick={()=>{setCaption(publication.snapshot.caption);const date=new Date(publication.snapshot.scheduledAt);setScheduled(new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16));setEditing(true);}}>Editar legenda e horário</Button>:<form className="form" onSubmit={e=>{e.preventDefault();void action('/'+publication.id+'/edit',{revision:publication.revision,caption,scheduledAt:new Date(scheduled).toISOString()});}}><label>Legenda revisada<textarea rows={5} maxLength={2200} required value={caption} onChange={e=>setCaption(e.target.value)}/></label><label>Novo horário (fuso do navegador)<input type="datetime-local" required value={scheduled} onChange={e=>setScheduled(e.target.value)}/></label><Button disabled={busy}>Salvar nova versão para aprovação</Button><Button type="button" variant="ghost" disabled={busy} onClick={()=>setEditing(false)}>Cancelar edição</Button></form>}</>}
 {publication.status==='draft'&&<><label style={{display:'block',margin:'1rem 0'}}><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/> Revisei a conta, a legenda, as mídias e o horário. Autorizo esta publicação e o acesso temporário da Meta às mídias privadas por até 10 minutos.</label><Button disabled={busy||editing||!approve||!accepted||!data.enabled} onClick={()=>void action('/'+publication.id+'/approve',{revision:publication.revision,allowTemporaryProviderAssetAccess:true})}>Autorizar esta publicação</Button>{!data.enabled&&<p>A execução oficial do Instagram ainda não foi habilitada neste ambiente.</p>}</>}
 {approve&&!['published','cancelled','stale'].includes(publication.status)&&<div style={{display:'flex',gap:8,marginTop:12}}><Button variant="outline" disabled={busy} onClick={()=>void action('/'+publication.id+'/control',{revision:publication.revision,action:'pause'})}>Pausar</Button><Button variant="outline" disabled={busy} onClick={()=>void action('/'+publication.id+'/control',{revision:publication.revision,action:'revoke'})}>Revogar autorização</Button><Button variant="ghost" disabled={busy} onClick={()=>void action('/'+publication.id+'/control',{revision:publication.revision,action:'cancel'})}>Cancelar publicação</Button></div>}
 {publication.status==='reconciling'&&<p>Confira a conta no Instagram. O sistema não reenviará uma operação incerta. Uma revogação não consegue desfazer uma publicação já aceita pela Meta.</p>}
 </>}
 </>}</section>;
}
