'use client';
import {useCallback,useEffect,useState} from 'react';
import {Button} from '@askadia/ui';
import type {VisualJob} from '@askadia/contracts';
import {journeyApi} from '../lib/journey-api';
import s from './visual-studio.module.css';
type Data={jobs:VisualJob[];available:boolean;canEdit:boolean};
const labels={pending:'Na fila',running:'Criando imagem',completed:'Pronto para revisar',failed:'Precisa de atenção',stale:'Versão alterada'};
export function VisualStudio({companyId,materials=[],planId,campaignIndex,onApply,disabled=false}:{companyId:string;materials?:{id:string;name:string}[];planId?:string;campaignIndex?:number;onApply?:(id:string,sourceId:string|null)=>void;disabled?:boolean}){
 const [data,setData]=useState<Data|null>(null),[source,setSource]=useState(''),[instructions,setInstructions]=useState(''),[ratio,setRatio]=useState<'16:9'|'4:5'|'1:1'|'9:16'>(planId?'4:5':'16:9'),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const kind=planId?'campaign_creative':'site_image',base='companies/'+companyId+'/visual-jobs';
 const load=useCallback(async(signal?:AbortSignal)=>{const result=await journeyApi<Data>(base,undefined,signal);if(!signal?.aborted)setData(result);},[base]);
 useEffect(()=>{const c=new AbortController();let timer:ReturnType<typeof setTimeout>;async function refresh(){try{await load(c.signal);if(!c.signal.aborted)setError(current=>current.startsWith('Não foi possível carregar')?'':current);}catch(e){if(!c.signal.aborted)setError(e instanceof Error?e.message:'Não foi possível carregar as imagens.');}finally{if(!c.signal.aborted)timer=setTimeout(()=>void refresh(),10000);}}void refresh();return()=>{c.abort();clearTimeout(timer);};},[load]);
 async function generate(){if(busy)return;setBusy(true);setError('');try{await journeyApi(base,{id:crypto.randomUUID(),kind,sourceId:planId?null:source,planId:planId??null,campaignIndex:campaignIndex??null,instructions,ratio,references:planId?materials.slice(0,5).map(m=>m.id):[]});await load();}catch(e){setError(e instanceof Error?e.message:'Não foi possível solicitar a imagem.');}finally{setBusy(false);}}
 const jobs=data?.jobs.filter(j=>j.kind===kind&&(!planId||j.plan_id===planId&&j.campaign_index===campaignIndex)).slice(0,8)??[];
 return <section className={s.root}><h3>{planId?'Criativos desta campanha':'Editar fotos com IA'}</h3><p>{planId?'As peças são rascunhos para revisão. Cada variação fica vinculada a esta campanha.':'Escolha uma foto e descreva o ajuste. O original é preservado; você decide quando usar a nova versão no rascunho.'}</p>{error&&<p role="alert" className="error-banner">{error}</p>}{data&&!data.available&&<p role="status">A geração de imagens ainda não está disponível.</p>}
 {data?.canEdit&&<form className="form" onSubmit={e=>{e.preventDefault();void generate();}}>{!planId&&<label>Foto original<select required value={source} disabled={busy||disabled} onChange={e=>setSource(e.target.value)}><option value="">Selecione a foto</option>{materials.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label>}<label>{planId?'Orientação para a variação (opcional)':'O que deseja ajustar?'}<textarea required={!planId} minLength={planId?0:5} maxLength={2000} rows={2} value={instructions} onChange={e=>setInstructions(e.target.value)} placeholder={planId?'Ex.: destaque a consulta confirmada e simplifique a composição.':'Ex.: melhore a iluminação e enquadre para a capa, preservando o espaço real.'}/></label><label>Formato<select value={ratio} onChange={e=>setRatio(e.target.value as typeof ratio)}><option value="16:9">Horizontal · 16:9</option><option value="4:5">Feed · 4:5</option><option value="1:1">Quadrado · 1:1</option><option value="9:16">Stories · 9:16</option></select></label><Button disabled={busy||disabled||!data.available||(!planId&&(!source||instructions.trim().length<5))}>{busy?'Solicitando…':planId?'Criar variação com IA':'Criar versão editada'}</Button></form>}
 <div className={s.grid}>{jobs.map(job=><article key={job.id}><span className="tag">{labels[job.status]} · {job.ratio}</span>{job.result_attachment_id&&<><img src={'/api/onboarding/companies/'+companyId+'/attachments/'+job.result_attachment_id} alt={planId?'Criativo da campanha para aprovação':'Nova versão da foto para revisão'} loading="lazy"/><div className={s.actions}><a href={'/api/onboarding/companies/'+companyId+'/attachments/'+job.result_attachment_id} download>Baixar imagem</a>{onApply&&<Button disabled={disabled||job.status!=='completed'} variant="outline" onClick={()=>onApply(job.result_attachment_id!,job.source_attachment_id)}>Usar no rascunho</Button>}</div></>}{job.instructions&&<p>{job.instructions}</p>}{job.error&&<p role="status">{job.error}</p>}</article>)}</div>{data&&!jobs.length&&<p>Nenhuma imagem criada nesta etapa.</p>}</section>;
}
