import {randomUUID,createHmac} from 'node:crypto';
import {BadRequestException,Body,Controller,ForbiddenException,Get,Param,Post,Query,Req,UseGuards} from '@nestjs/common';
import {z} from 'zod';
import {dateInZone,shiftDay,utcStartOfDay,marketQuerySchema,distanceMeters,type MarketSnapshot,type BusinessOverview,type OnboardingSnapshot} from '@askadia/contracts';
import {AuthGuard,type AuthRequest} from '../identity/auth';
import {result} from '../identity/service';
import {metaContext,metaGraph} from '../inbox/meta';
import {GoogleLocalAdapter,IbgeAdapter,SerpApiTrendsAdapter} from './market-providers';
const stages=[['new','Novo'],['in_progress','Em atendimento'],['qualified','Qualificado'],['referred','Encaminhado'],['scheduled','Consulta agendada'],['attended','Compareceu'],['enrolled','Conversão confirmada'],['lost','Perdido']];
const cache=new Map<string,{expires:number;value:MarketSnapshot}>();
const running=new Map<string,Promise<MarketSnapshot>>();
function parse<T>(schema:z.ZodType<T>,value:unknown){const r=schema.safeParse(value);if(!r.success)throw new BadRequestException('Confira os filtros da análise.');return r.data;}
export async function authorizeOverview(r:AuthRequest,id:string,write=false){parse(z.uuid(),id);const c=result<{actions:string[]}>(await r.actor.client.rpc('company_capabilities',{p_company_id:id}));if(!c.actions.includes(write?'marketing.write':'marketing.read'))throw new ForbiddenException('Seu perfil não permite consultar ou atualizar esta análise.');return c;}
function emptyMarket(id:string,version:number,radius:number):MarketSnapshot{return {companyId:id,profileVersion:version,collectedAt:null,radius,demographics:{state:'pending',data:null,message:'Atualize a análise para consultar o município no IBGE.'},competitors:{state:'pending',search:null,count:null,limited:false,message:'Atualize a pesquisa da região.'},facebook:{state:'pending',count:null,places:[],message:'A pesquisa de páginas depende de uma conta conectada e acesso permitido pela Meta.'},trends:{state:'unconfigured',rows:[],region:null,geo:null,query:'clínica',period:'Últimos 3 meses',sourceUrl:'https://trends.google.com/trends/explore?date=today%203-m&q=clínica&geo=BR',collectedAt:null,message:'Ranking consolidado pendente de provedor. Consulte abaixo a visualização oficial do Google Trends.'}};}
@Controller('onboarding')
@UseGuards(AuthGuard)
export class OverviewController{
 @Get('companies/:id/overview') async overview(@Req() r:AuthRequest,@Param('id') id:string,@Query() query:unknown):Promise<BusinessOverview>{
  const cap=await authorizeOverview(r,id);const {days}=parse(z.object({days:z.coerce.number().pipe(z.union([z.literal(7),z.literal(30),z.literal(90)])).default(30)}).strict(),query);
  const company=result<{timezone:string}>(await r.actor.client.from('companies').select('timezone').eq('id',id).single());const timezone=company.timezone||'America/Sao_Paulo';const end=dateInZone(new Date(),timezone);const dates=Array.from({length:days},(_,i)=>new Date(Date.parse(end+'T12:00:00Z')-(days-1-i)*86400000).toISOString().slice(0,10));const start=dates[0]!;const since=utcStartOfDay(start,timezone),until=utcStartOfDay(shiftDay(end,1),timezone);
  const out:BusinessOverview={companyId:id,generatedAt:new Date().toISOString(),days,start,end,timezone,crm:null,campaigns:null,failures:[]};
  if(!cap.actions.includes('crm.read'))return out;
  const count=async(table:string,filters:Record<string,string>={})=>{let q=r.actor.client.from(table).select('id',{count:'exact',head:true}).eq('company_id',id);for(const [k,v] of Object.entries(filters))q=q.eq(k,v);const value=await q;result(value);if(value.count===null)throw new Error('COUNT_UNAVAILABLE');return value.count;};
  const crm=async()=>{
   // Paged dates only; no personal fields and no silent 1,000-record truncation.
   const contacts:{created_at:string}[]=[];let offset=0;
   for(;;){const page=result<{created_at:string}[]>(await r.actor.client.from('contacts').select('created_at').eq('company_id',id).gte('created_at',since).lt('created_at',until).order('created_at').order('id').range(offset,offset+999));contacts.push(...page);if(page.length<1000)break;offset+=1000;if(offset>=100000)throw new Error('REPORT_TOO_LARGE');}
   const daily=dates.map(date=>({date,count:0}));for(const contact of contacts){const day=daily.find(d=>d.date===dateInZone(new Date(contact.created_at),timezone));if(day)day.count++;}
   const [totalContacts,stageCounts]=await Promise.all([count('contacts'),Promise.all(stages.map(async([key,label])=>({key:key!,label:label!,count:await count('opportunities',{stage:key!})})))]);return {totalContacts,newContacts:daily.reduce((n,d)=>n+d.count,0),daily,stages:stageCounts};
  };
  const campaigns=async()=>{const delivery=async(state:string)=>{const q=await r.actor.client.from('message_campaign_deliveries').select('id',{count:'exact',head:true}).eq('company_id',id).eq('state',state).gte('updated_at',since).lt('updated_at',until);result(q);if(q.count===null)throw new Error('COUNT_UNAVAILABLE');return q.count;};const [active,sent,uncertain,students]=await Promise.all([count('message_campaigns',{status:'active'}),delivery('sent'),delivery('uncertain'),count('campaign_students',{status:'active'})]);return {active,sent,uncertain,students};};
  const reads=await Promise.allSettled([crm(),campaigns()]);if(reads[0].status==='fulfilled')out.crm=reads[0].value;else out.failures.push('CRM');if(reads[1].status==='fulfilled')out.campaigns=reads[1].value;else out.failures.push('Campanhas');return out;
 }
 private async context(r:AuthRequest,id:string,query:unknown,write=false){await authorizeOverview(r,id,write);const {radius}=parse(marketQuerySchema,query);const profile=result<OnboardingSnapshot>(await r.actor.client.rpc('company_onboarding_read',{p_company_id:id}));const version=profile.confirmedProfile?.version??0;return {radius,profile,key:[id,version,profile.state.revision,radius].join(':'),version};}
 @Get('companies/:id/market') async market(@Req() r:AuthRequest,@Param('id') id:string,@Query() query:unknown){const c=await this.context(r,id,query);const cached=cache.get(c.key);return cached&&cached.expires>Date.now()?cached.value:emptyMarket(id,c.version,c.radius);}
 @Post('companies/:id/market') async refresh(@Req() r:AuthRequest,@Param('id') id:string,@Body() body:unknown){
  const c=await this.context(r,id,body,true);if(!c.profile.confirmedProfile)throw new BadRequestException('Confirme o perfil da empresa antes de pesquisar a região.');
  const cached=cache.get(c.key);if(cached&&Date.now()-Date.parse(cached.value.collectedAt!)<300000)return cached.value;
  const active=running.get(c.key);if(active){const value=await active;const latest=await this.context(r,id,body);if(latest.key!==c.key)throw new BadRequestException('O perfil mudou. Atualize a análise.');return value;}
  const job=this.collect(r,id,c).finally(()=>running.delete(c.key));running.set(c.key,job);return job;
 }
 private async collect(r:AuthRequest,id:string,c:Awaited<ReturnType<OverviewController['context']>>){
  const requestId=randomUUID();const reserved=result<boolean>(await r.actor.client.rpc('reserve_onboarding_provider',{p_company_id:id,p_request_id:requestId,p_kind:'places'}));if(!reserved)throw new BadRequestException('Limite diário de pesquisas atingido. Tente novamente depois.');
  let completed=false;
  try{
  const out=emptyMarket(id,c.version,c.radius);const facts=c.profile.confirmedProfile!.facts;const cityText=facts.city?.value?.trim()??'';let city=cityText,uf='';const match=cityText.match(/^(.+?)\s*(?:[-,/]\s*|\s)([A-Z]{2})(?:\s|$)/);if(match){city=match[1]!.trim();uf=match[2]!;}
  let center:{latitude:number;longitude:number}|null=null;const placeId=facts.placeId?.value;
  const google=process.env.GOOGLE_PLACES_SERVER_KEY?new GoogleLocalAdapter(process.env.GOOGLE_PLACES_SERVER_KEY):null;
  if(google&&placeId){try{const location=await google.location(placeId);center=location.center;if(location.city)city=location.city;if(location.uf)uf=location.uf;}catch{out.competitors={...out.competitors,state:'unavailable',message:'Não foi possível localizar o endereço confirmado no Google. Revise o perfil e tente atualizar.'};}}
  else out.competitors={...out.competitors,state:google?'pending':'unconfigured',message:google?'Selecione a localização da clínica no onboarding para pesquisar pelo raio.':'Pesquisa do Google Places ainda não configurada.'};
  const demographics=async()=>{try{const ibge=new IbgeAdapter();const town=await ibge.municipality(city,uf);if(!town){out.demographics={state:'pending',data:null,message:'Município não identificado com segurança. Informe cidade e UF no perfil.'};return;}const data=await ibge.demographics(String(town.id),uf);out.demographics={state:'available',data,message:'Densidade média do município no Censo. Não representa a população dentro do raio.'};}catch{out.demographics={state:'unavailable',data:null,message:'IBGE indisponível nesta consulta. Atualize novamente mais tarde.'};}};
  const competitors=async()=>{if(!center||!google||!placeId)return;try{const nearby=await google.competitors(center,c.radius,placeId);out.competitors={state:'available',count:nearby.places.length,limited:nearby.limited,message:'Clínicas e consultórios encontrados pelo Google. Amostra parcial, não um censo de concorrentes.',search:{status:'available',places:nearby.places,radius:c.radius,center,message:'Google Maps · locais encontrados no raio.',...(process.env.GOOGLE_MAPS_BROWSER_KEY?{mapKey:process.env.GOOGLE_MAPS_BROWSER_KEY}:{})}};}catch{out.competitors={...out.competitors,state:'unavailable',message:'A pesquisa de estabelecimentos falhou. Confira a integração Google Places.'};}};
  const facebook=async()=>{if(!center){out.facebook.message='Confirme a localização da clínica para filtrar páginas por distância.';return;}try{const context=await metaContext(r,id,'marketing.read');if(!context.userToken||!process.env.META_APP_SECRET)throw new Error('MISSING_USER_TOKEN');type Page={id:string;name:string;location?:{latitude:number;longitude:number}};const response=await metaGraph<{data:Page[]}>('pages/search',context.userToken,{q:'clínica '+city,fields:'id,name,location,link',limit:'100',appsecret_proof:createHmac('sha256',process.env.META_APP_SECRET).update(context.userToken).digest('hex')});const origin=center;const seen=new Set<string>();const pages=response.data.flatMap(p=>{if(typeof p.name!=='string'||!/^\d+$/.test(p.id)||seen.has(p.id)||p.id===context.page||!p.location||!Number.isFinite(p.location.latitude)||!Number.isFinite(p.location.longitude))return [];seen.add(p.id);const distance=distanceMeters(origin,p.location);return distance<=c.radius?[{id:p.id,name:p.name,url:'https://www.facebook.com/'+p.id,distance:Math.round(distance)}]:[];});out.facebook={state:'available',places:pages,count:pages.length,message:'Páginas encontradas com coordenadas no raio. Cobertura parcial; podem repetir locais do Google. As contagens não são somadas.'};}catch{out.facebook={state:'unavailable',places:[],count:null,message:'A pesquisa de páginas não foi autorizada ou está indisponível. Conectar a Página não garante acesso à análise de concorrentes pela Meta.'};}};
  const trends=async()=>{if(!/^[A-Z]{2}$/.test(uf)){out.trends.message='Confirme município e UF para definir o recorte regional das pesquisas.';return;}const geo='BR-'+uf;out.trends={...out.trends,geo,region:'Estado '+uf,sourceUrl:'https://trends.google.com/trends/explore?'+new URLSearchParams({geo,date:'today 3-m',q:'clínica',hl:'pt-BR'})};if(!process.env.SERPAPI_API_KEY)return;try{const rows=await new SerpApiTrendsAdapter(process.env.SERPAPI_API_KEY).related(geo,'clínica');out.trends={...out.trends,state:'available',rows,collectedAt:new Date().toISOString(),message:'Google Trends via SerpApi · principais buscas relacionadas a “clínica” no estado. Interesse relativo 0–100, não volume absoluto nem ranking de todas as buscas.'};}catch{out.trends={...out.trends,state:'unavailable',message:'Não foi possível obter pesquisas relacionadas neste recorte. Não ampliamos a região silenciosamente.'};}};
  await Promise.all([demographics(),competitors(),facebook(),trends()]);
  // Revocation and profile edits during external requests must invalidate the response/cache.
  const latest=await this.context(r,id,{radius:c.radius});if(latest.key!==c.key)throw new BadRequestException('O perfil mudou. Atualize a análise.');
  out.collectedAt=new Date().toISOString();completed=true;
  if(cache.size>=200)cache.delete(cache.keys().next().value!);cache.set(c.key,{expires:Date.now()+6*3600000,value:out});return out;
  }finally{await r.actor.client.rpc('finish_onboarding_provider',{p_company_id:id,p_request_id:requestId,p_kind:'places',p_outcome:completed?'completed':'failed'});}
 }
}

