import Link from 'next/link';
import {ArrowRight,LifeBuoy,Mail,MessageCircle} from 'lucide-react';
import {MarketingShell,marketingMetadata,signupHref} from '../../components/marketing-site';
import {PublicContactForm} from '../../components/public-contact-form';
import {publicContact} from '../../lib/public-contact';
import s from '../home.module.css';
export const dynamic='force-dynamic';
export const metadata=marketingMetadata('Contato','Fale sobre os desafios da sua clínica, conheça as soluções da MedSI ou encontre ajuda para usar a plataforma.','/contato');
export default function Contact(){const contact=publicContact();return <MarketingShell><section className={s.pageHero}><span className={s.eyebrow}>VAMOS CONVERSAR</span><h1>Qual é o próximo passo da sua clínica?</h1><p>Conheça a MedSI, tire suas dúvidas ou encontre o caminho para resolver uma dificuldade no sistema.</p></section><section className={s.contentNarrow}><div className={s.infoGrid}><article className={s.infoCard}><MessageCircle size={28}/><h2>Conhecer a solução</h2><p>Conte sobre a sua clínica e o que gostaria de organizar: conteúdo, atendimento, relacionamento ou presença digital.</p>{contact.whatsapp||contact.salesEmail?<PublicContactForm email={contact.salesEmail} whatsapp={contact.whatsapp}/>:<><p className={s.note}>Os canais de atendimento comercial estão em preparação. Você já pode criar seu acesso e conhecer a plataforma.</p><Link className={s.primary} href={signupHref}>Criar meu acesso <ArrowRight size={17}/></Link></>}{contact.salesEmail&&<p><a className={s.textLink} href={'mailto:'+contact.salesEmail}><Mail size={17}/>{contact.salesEmail}</a></p>}</article><article className={s.infoCard}><LifeBuoy size={28}/><h2>Já usa a MedSI?</h2><p>Encontre orientações sobre acesso, onboarding, conteúdo, WhatsApp e site. Se precisar de ajuda, reúna o nome da empresa, a tela e o que aconteceu.</p><Link className={s.secondary} href="/suporte">Acessar central de suporte <ArrowRight size={17}/></Link><div className={s.supportLinks}><Link href="/suporte#acesso">Acesso à minha conta <ArrowRight size={15}/></Link><Link href="/suporte#conteudo-ajuda">Estratégia e publicações <ArrowRight size={15}/></Link><Link href="/suporte#conexoes-ajuda">WhatsApp e integrações <ArrowRight size={15}/></Link></div></article></div></section></MarketingShell>;}
